### ISSUE TITLE
add binary files?

### ISSUE THREAD

**Issue by m4b** [bytecodealliance/wasmtime#1]
I wanted to test native code generation, but unless I missed something, only textual wasm files are supplied, but the tools require binary wasm modules.

Is there an easy way to generate binary from text versions in the repo, or do I need another tool?

**Comment by sunfishcode** [comment]
Currently that needs another tool, such as wat2wasm from [wabt](https://github.com/WebAssembly/wabt).

Also, as a caveat, wasm2obj isn't in a very useful state at the moment, but I'm happy to help if there are specific things you're interested in doing with it.

**Comment by m4b** [comment]
I see.

I just wanted to try out codegen with faerie and look at binaries it was producing, see if they’re linking correctly, etc., if they’re runnable, etc. 

P.S. should have working mach backend pretty soon, maybe this weekend.

**Comment by m4b** [comment]
Ok, so I got wabt and ran `wasm2obj` on `call.wat`, and I get this error:

```
thread 'main' panicked at 'relocations not supported yet', lib/obj/src/emit_module.rs:25:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: wasmstandalone_obj::emit_module::emit_module
             at lib/obj/src/emit_module.rs:25
   7: wasm2obj::handle_module
             at src/wasm2obj.rs:104
   8: wasm2obj::main
             at src/wasm2obj.rs:71
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  11: main
  12: __libc_start_main
  13: _start
```

which means the relocations are empty.

So, at this stage I would like to get this working, so I can:

1. test what your requirements might look like for faerie
2. what your object output flow is like
3. investigate random corner cases
4. incorporate platform differences in a unified manner (or try)
5. and finally, reflect this in an updated API

Is there a "quick and dirty way" to get relocations working on the wasm2obj pipeline, or is this a significant amount of work?

**Comment by alexcrichton** [comment]
I believe tooling now uniformly supports text/binary formats and toolkits like wabt can be used to convert between them (or `wat` if it's a test in this repo), so I'm going to close this.
