### ISSUE TITLE
test test_run_hello_example has been running for over 60 seconds

### ISSUE THREAD

**Issue by davnav** [bytecodealliance/wasmtime#1005]
Not sure this is a known defect or my system configuration issue.!

cargo test -v -p wasmtime-c-api
failing with below message!

running 7 tests
test test_run_hello_example ... test test_run_hello_example has been running for over 60 seconds
test test_run_callback_example ... test test_run_callback_example has been running for over 60 seconds
test test_run_global_example ... test test_run_global_example has been running for over 60 seconds
test test_run_memory_example ... test test_run_memory_example has been running for over 60 seconds
test test_run_callback_example ... FAILED
test test_run_hello_example ... FAILED
test test_run_global_example ... FAILED
test test_run_memory_example ... FAILED
test test_run_start_example ... FAILED
test test_run_reflect_example ... FAILED
test test_run_trap_example ... FAILED

failures:

---- test_run_callback_example stdout ----
thread 'test_run_callback_example' panicked at 'failed to execute the C example 'callback':     Blocking waiting fo
r file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
   Compiling libc v0.2.67

**Comment by alexcrichton** [comment]
Thanks for the report! It's expected that tests will be pretty slow in debug mode or on smaller systems, this test for example is calling Cargo recursively to build more code.

It looks like the error here may be cut off though? Would you be able to gist the full error message? It may also benefit from setting `RUST_BACKTRACE=1`

**Comment by davnav** [comment]
**Below are full messages when I use RUST_BACKTRACE=1**


running 7 tests
test test_run_hello_example ... FAILED
test test_run_callback_example ... FAILED
test test_run_memory_example ... FAILED
test test_run_global_example ... FAILED
test test_run_trap_example ... FAILED
test test_run_start_example ... FAILED
test test_run_reflect_example ... FAILED

failures:

---- test_run_hello_example stdout ----
thread 'test_run_hello_example' panicked at 'failed to execute the C example 'hello':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/hello-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_hello_example
             at crates/c-api/tests/wasm-c-examples.rs:31
  16: wasm_c_examples::test_run_hello_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:30
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_callback_example stdout ----
thread 'test_run_callback_example' panicked at 'failed to execute the C example 'callback':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/callback-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_callback_example
             at crates/c-api/tests/wasm-c-examples.rs:92
  16: wasm_c_examples::test_run_callback_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:91
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_memory_example stdout ----
thread 'test_run_memory_example' panicked at 'failed to execute the C example 'memory':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/memory-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_memory_example
             at crates/c-api/tests/wasm-c-examples.rs:52
  16: wasm_c_examples::test_run_memory_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:51
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_global_example stdout ----
thread 'test_run_global_example' panicked at 'failed to execute the C example 'global':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/global-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_global_example
             at crates/c-api/tests/wasm-c-examples.rs:73
  16: wasm_c_examples::test_run_global_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:72
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_trap_example stdout ----
thread 'test_run_trap_example' panicked at 'failed to execute the C example 'trap':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/trap-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_trap_example
             at crates/c-api/tests/wasm-c-examples.rs:169
  16: wasm_c_examples::test_run_trap_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:168
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_start_example stdout ----
thread 'test_run_start_example' panicked at 'failed to execute the C example 'start':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/start-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_start_example
             at crates/c-api/tests/wasm-c-examples.rs:147
  16: wasm_c_examples::test_run_start_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:146
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_run_reflect_example stdout ----
thread 'test_run_reflect_example' panicked at 'failed to execute the C example 'reflect':     Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
/usr/bin/ld: cannot find -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wasm-c-api/out/example/reflect-c] Error 1
', crates/c-api/tests/wasm-c-examples.rs:15:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/io/mod.rs:1428
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: rust_begin_unwind
             at src/libstd/panicking.rs:378
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  14: wasm_c_examples::run_c_example
             at crates/c-api/tests/wasm-c-examples.rs:15
  15: wasm_c_examples::test_run_reflect_example
             at crates/c-api/tests/wasm-c-examples.rs:117
  16: wasm_c_examples::test_run_reflect_example::{{closure}}
             at crates/c-api/tests/wasm-c-examples.rs:116
  17: core::ops::function::FnOnce::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libcore/ops/function.rs:232
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/liballoc/boxed.rs:1017
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/436494b8f8008b600d64b3951f63c2bb0ea81673/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_run_callback_example
    test_run_global_example
    test_run_hello_example
    test_run_memory_example
    test_run_reflect_example
    test_run_start_example
    test_run_trap_example

test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by yurydelendik** [comment]
@davnav what is your system configuration? do you have any developers/build tools installed?

**Comment by yurydelendik** [comment]
FWIW on CI the tests are run via `cargo test --package wasmtime-c-api -- --nocapture --test-threads 1`

**Comment by davnav** [comment]
> @davnav what is your system configuration? do you have any developers/build tools installed?
I am using Ubuntu linux.

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 61
Model name:            Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
Stepping:              4
CPU MHz:               2977.593
CPU max MHz:           3000.0000
CPU min MHz:           500.0000
BogoMIPS:              4788.85
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt dtherm ida arat pln pts

**Comment by davnav** [comment]
> FWIW on CI the tests are run via `cargo test --package wasmtime-c-api -- --nocapture --test-threads 1`

test cases getting failed for above command also..

**Comment by alexcrichton** [comment]
@davnav the error in https://github.com/bytecodealliance/wasmtime/issues/1005#issuecomment-592147116 is because your development environment isn't configured to build C++ programs, which the test suite currently requires.

This isn't really a bug with wasmtime per se but is perhaps a bug with our documentation in how to set up a developer environment! Can you try installing the `g++` package and see if it fixes the issue for you?

**Comment by davnav** [comment]
I do have g++ installed. Still getting the error.


ii  clang                                       1:3.8-33ubuntu3.1                                                   amd64        C, C++ and Objective-C compiler (LLVM based)
ii  clang-3.8                                   1:3.8-2ubuntu4                                                      amd64        C, C++ and Objective-C compiler (LLVM based)
ii  g++                                         4:5.3.1-1ubuntu1                                                    amd64        GNU C++ compiler
ii  g++-4.8                                     4.8.5-4ubuntu2                                                      amd64        GNU C++ compiler
ii  g++-5                                       5.4.0-6ubuntu1~16.04.12                                             amd64        GNU C++ compiler
ii  gcc                                         4:5.3.1-1ubuntu1                                                    amd64        GNU C compiler
ii  gcc-4.8                                     4.8.5-4ubuntu2                                                      amd64        GNU C compiler
ii  gcc-4.9                                     4.9.3-13ubuntu2                                                     amd64        GNU C compiler
ii  gcc-5                                       5.4.0-6ubuntu1~16.04.12                                             amd64        GNU C compiler
ii  gcc-m68hc1x                                 1:3.3.6+3.1+dfsg-3ubuntu1                                           amd64        GNU C compiler for the Motorola 68HC11/12 processors
ii  gccgo                                       4:6-20160210-1ubuntu1                                               amd64        Go compiler, based on the GCC backend
ii  gccgo-6                                     6.0.1-0ubuntu1                                                      amd64        GNU Go compiler
ii  golang                                      2:1.6-1ubuntu4

**Comment by alexcrichton** [comment]
Sorry, to be clear, the error you're getting @davnav is this:

```
/usr/bin/ld: cannot find -lstdc++
```

The linker is saying that it cannot find `libstdc++.a`. I don't know what package on your system would provide that file, but it's something I think you'll need to figure out locally. You'll need to execute commands like this to test whether you've succeeded or not:

```sh
$ echo 'int main() {}' > foo.cpp
$ g++ foo.cpp -lstdc++
```

**Comment by eminence** [comment]
On Ubuntu I believe the package name is `libstdc++-6-dev`, so @davnav you should try running:

    apt install libstdc++-6-dev

If this doesn't work, please let us know exactly what version of ubuntu you are running (the output of `lsb_release -d` should say)

**Comment by davnav** [comment]
> On Ubuntu I believe the package name is `libstdc++-6-dev`, so @davnav you should try running:
> 
> ```
> apt install libstdc++-6-dev
> ```
> 
> If this doesn't work, please let us know exactly what version of ubuntu you are running (the output of `lsb_release -d` should say)

I am using 	**Ubuntu 16.04.3 LTS.**


But **apt install libstdc++-6-dev** could not locate package

**Comment by eminence** [comment]
Ok try this then:

    apt install libstdc++-4.8-dev

**Comment by davnav** [comment]
> Ok try this then:
> 
> ```
> apt install libstdc++-4.8-dev
> ```

**tried .. looks like its already installed**.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++-4.8-dev is already the newest version (4.8.5-4ubuntu2).
libstdc++-4.8-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  gir1.2-javascriptcoregtk-3.0 gir1.2-webkit-3.0 gyp
  libjs-inherits libjs-node-uuid libuv1 libuv1-dev
  node-abbrev node-ansi node-ansi-color-table
  node-archy node-block-stream node-combined-stream
  node-cookie-jar node-delayed-stream
  node-forever-agent node-form-data node-fstream
  node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits
  node-ini node-json-stringify-safe node-lockfile
  node-lru-cache node-mime node-minimatch node-mkdirp
  node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once
  node-osenv node-qs node-read node-read-package-json
  node-request node-retry node-rimraf node-semver
  node-sha node-sigmund node-slide node-tar
  node-tunnel-agent node-underscore node-which
  update-notifier-common
Use 'sudo apt autoremove' to remove them.

**Comment by eminence** [comment]
Ok, here's my last suggestion:  Can you install the `clang` package?   This should bring in `clang-3.8` which automatically brings in `libstdc++-5-dev`.   Can you also make sure the `make` package is installed.

(With these packages installed, I'm able to run these tests in a ubuntu 16.04 docker container)

**Comment by alexcrichton** [comment]
I'm gonna go ahead and close this since I believe it's an unrelated local configuration problem unrelated to wasmtime, but if that turns out to not be the case feel free to let me know!
