### ISSUE TITLE
Fuzz various functions in cranelift

### ISSUE THREAD

**Issue by anholt** [bytecodealliance/wasmtime#1026]
I've wanted to play with a fuzzing tool for a long time, so I brought up [cargo-fuzz on cretonne](https://github.com/anholt/cretonne/commits/fuzz).  I think this could be a useful complement to the test suite, but I want to do the following before generating a PR:

- Hook up a few more fuzzers.
- Debug at least one fuzzing failure.
- Document the debugging workflow for it -- the commit has some info, but the ASan backtrace is pretty useless.  How do I get gdb at the point of failure?
- Figure out if there's any useful integration to be done with the test suite.

**Comment by bjorn3** [comment]
Wasmtime and regalloc.rs are now being fuzzed. Should this be closed?

**Comment by fitzgen** [comment]
Yeah we have a fairly extensive suite of `cargo fuzz` targets running in oss-fuzz. While improvements to those are always appreciated, it looks like this issue isn't tracking any particular missing thing anymore.
