### ISSUE TITLE
Better handling of literals in Ast substitution/copy and semantic checking

### ISSUE THREAD

**Issue by d1m0** [bytecodealliance/wasmtime#1027]
Rationale: icmp,load,store all have an enumerable immediate field, base on whose value we may want to do something different in the semantics. As a result, we'd like to be able to match a different transform to a concrete piece of rtl, depending on the value of some of the immediate fields. To enable this we need several things:

   0. A base class for all Literals - current (Enumerator, ConstantInt) and future (FlagSet)
   1. Support substitutions Var->Literal, Literal->Var (requires changes to {Ast, Def,Rtl}.{copy, substitution}
   2. Change verify_semantics() to enumerate all concrete values of enumerable immediates on top of enumerating all concrete typings.

**Comment by bjorn3** [comment]
The new backend framework doesn't use legalizations as much as the old backend.
