### ISSUE TITLE
Test instruction encoding against another toolchain

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasmtime#1034]
I have encountered at least one bug related to instruction encodings that was pretty tricky to isolate, but easy enough to fix, https://github.com/Cretonne/cretonne/issues/211

It would be helpful to have a test suite that compared Cretonne's encodings against another toolchain (probably llvm, though gcc could work too). The meta-language could add a way to specify how to translate an instruction into assembly language text, and the encoding of the instruction could be compared against the output of another assembler. The domain size for each instruction is small enough that this could probably be an exhaustive test.

**Comment by bjorn3** [comment]
Why did you close this? I don't think this is implemented yet.

**Comment by cfallin** [comment]
I guess @pchickey is cleaning up old issues generally... while it's true we don't test encodings specifically against other toolchains, I think we have equivalent-or-better coverage via differential fuzzing against other engines (V8, wasmi, spec interpreter). So IMHO at least I could potentially call this issue "obsolete", though others feel free to weigh in as well.

**Comment by bjorn3** [comment]
Differential fuzzing only covers the subsets of clif ir used by wasm. It doesn't cover large parts used by cg_clif.
