### ISSUE TITLE
Consider alternative methods for writing binary data

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#1035]
Currently, binemit has its own [CodeSink](https://docs.rs/cretonne-codegen/0.5.0/cretonne_codegen/binemit/trait.CodeSink.html) trait for writing binary data. It isn't entirely satisfying, in part because it's an unsafe interface -- it doesn't perform bounds checking on the underlying data. While we can provide relatively safe interfaces to protect users from misusing the API, it's harder to be absolutely certain that the number of bytes `compile` says a function needs is the number of bytes `emit_to_memory` actually writes for that function.

One option would be to provide a safe checked version of `MemoryCodeSink`. However, it's also worth considering evaluating available crates that provide low-level byte buffer writing functionality, including:
 - https://crates.io/crates/bytevec
 - https://crates.io/crates/bytebuffer
 - https://crates.io/crates/scroll

**Comment by bjorn3** [comment]
The `CodeSink` trait is now gone. `MachBufferFinalized` contains all information in the form of `SmallVec`'s which the user can access as slices. As such I think this issue can be closed.

**Comment by cfallin** [comment]
Yep, this is no longer an issue -- thanks!
