### ISSUE TITLE
Example combining wasm + simplejit

### ISSUE THREAD

**Issue by kazimuth** [bytecodealliance/wasmtime#1042]
I'd like to use CraneLift as a JIT backend for a standalone WebAssembly embedding. However, from browsing the documentation I'm not sure how to do this, or even if it's fully possible yet. An example showing how to use cranelift_wasm and cranelift_simplejit together would be really helpful.

**Comment by bjorn3** [comment]
I think Wasmtime has subsumed this issue. Especially now that it supports no_std.
