### ISSUE TITLE
Use callee-saved registers across calls

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#1043]
Currently, cranelift [spills all registers across calls](https://github.com/CraneStation/cranelift/blob/master/lib/codegen/src/regalloc/spilling.rs#L264), without regard to whether they're callee-saved.

However the nice thing about callee-saved registers is that they're saved across calls ;-), and Cranelift indeed [supports the callee side of this](https://github.com/CraneStation/cranelift/blob/master/lib/codegen/src/isa/x86/abi.rs#L192).

At a high level, the steps here are:
 - Generalize x86's `callee_saved_gprs` into `callee_saved_regs` and make it not specific to GPRs (this appears needed for saving XMM registers on windows_fastcall too). 
 - Refactor this `callee_saved_regs` from being a private function to being a function in the `TargetIsa` trait, so that we can access the `callee_saved_gprs` from other places in the code.
 - Make the code mentioned above in spilling.rs consult the `TargetIsa`'s `callee_saved_regs` set and skip spilling registers in the callee-saved set.

**Comment by bjorn3** [comment]
This is fixed with the new backends, right?

**Comment by cfallin** [comment]
Indeed; I think we can go ahead and close this since we've addressed the issue (no longer need to track it); even if the new backend is not yet the default for the codegen crate or in wasmtime, it will be soon enough.

**Comment by krh** [comment]
Is there an option to force spilling of callee save registers?

**Comment by cfallin** [comment]
Not exactly as such; we have ongoing work to add ABIs that behave this way, but switching the ABI specified for a callee implies much bigger changes than just forced-spills.

Could you say more about *why* you want this in particular? Knowing the end goal might help us understand better what to recommend. E.g., if you're trying to call a function that actually *does* conform to an ABI with no callee-saves, the right answer is "add support for that different ABI". If you want registers on the stack for... debugging, or observability, or something like that, then we can talk about that in more detail.

**Comment by cfallin** [comment]
Ah! Indeed, I didn't connect the two threads as being related, sorry :-)

**Comment by krh** [comment]
Hehe, sorry for spamming this old bug, it came up search.
