### ISSUE TITLE
Use `//` for line comments?

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#1046]
Cranelift's clif files (example [here](https://github.com/CraneStation/cranelift/blob/master/filetests/parser/branch.clif)) currently use `;` for line comments. This is somewhat common in assembler languages, and LLVM IR, but it's not always immediately obvious for people from other backgrounds.

Using `//` would follow Cranelift's syntax for types `v0: i32`, `-> i32`, and so on in taking syntactic queues from Rust where it makes sense to do so. (Related: should we change `function` to `fn`? That doesn't feel as important because `function` is more self-explanatory there, but it's worth considering.)

`//` is two characters rather than `;`'s one, but my intuition is that little things we can do to make IR dumps easier to approach for people not already familiar with them will end up being valuable in a variety of contexts, more so than absolute conciseness.

**Comment by cfallin** [comment]
I'm doing some issue gardening, and this has been open for ~3.5 years without much happening; given that we have gotten along well enough with our current CLIF comment character (`;`) in the meantime I think I will go ahead and close this. If anyone wants to make a renewed effort/argument for alternative CLIF syntax please feel free though!
