### ISSUE TITLE
Coloring: Don't leave regmove/regspill/regfill behind

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#1049]
The regmove/regspill/regfill instructions are special. They're emitted by the coloring pass to temporarily override the assigned registers (`func.locations`) for values. This is surprising, and it means that very late passes which run after register allocation can't just look at `func.locations` and have to use `RegDiversions` and walk the IR in order to know what registers are assigned to what values.

They also currently require special casing to work around [this issue](https://github.com/CraneStation/cranelift/issues/420).

It would be nice to find a way to either avoid using regfill/regspill/regfill, or to rewrite them once coloring is done, so that `func.locations` is left up to date.

**Comment by bjorn3** [comment]
These don't exist for the new backend framework anymore.

**Comment by cfallin** [comment]
Addressed with regalloc.rs in new backends.
