### ISSUE TITLE
Rename "Heap"?

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#1060]
"Heap" is a pretty generic term, but Cranelift's `Heap` is a very specific construct. What if we renamed Cranelift's "Heap" to "LinearMemory", since it's essentially a WebAssembly linear memory with a few more knobs exposed?

And perhaps we could shorten it to "linearmem" in some places, so that `heap_addr` would be `linearmem_addr`. Or maybe `linmem_addr`? Or maybe `linear_addr`?

**Comment by cfallin** [comment]
This issue has been open for 3.5 years without any movement and it seems by now calling our heaps `heap` has been baked into our mental models and the code, so a proposal to rename a basic entity would need a fairly strong argument. In the absence of compelling reasons, avoiding confusing name-changes in our public APIs/IR concepts is probably the right call. So I'll go ahead and close this, but others please speak up if you feel strongly about renaming still.
