### ISSUE TITLE
Map to DWARF register numbers

### ISSUE THREAD

**Issue by philipc** [bytecodealliance/wasmtime#1078]
We need a way to map cranelift registers to DWARF registers.

I think this should be part of `RegInfo`. LLVM stores this map as an array of register pairs, and performs lookups using `lower_bound`. I'm not sure if cranelift should do the same, or use an array indexed by `RegUnit`.

Should we wait until after `RegInfo` generation is converted from python before doing this?

**Comment by bjorn3** [comment]
Both the old and new backend framework now provide a method on `TargetIsa` to do this.
