### ISSUE TITLE
Pooled entity set implementation in cranelift-entity

### ISSUE THREAD

**Issue by hansihe** [bytecodealliance/wasmtime#1079]
I am using cranelift-entity in one of my projects. I wrote a pooled EntitySet based on EntityList and ListPool. It is similar to EntitySet, except that it used pooled allocation, and has some extra functionality. Is this something you would be interested in having in cranelift-entity?

It is still unfinished, and I am adding functions to it as I need them, but I still think it is relatively useful.

https://github.com/eirproject/eir/blob/master/util/src/pooled_entity_set.rs

**Comment by cfallin** [comment]
I'm doing some issue gardening and came across this old issue. The link above is dead now, but if you have something you might want to contribute to `cranelift-entity`, please feel free to open a PR! I will go ahead and close this in the meantime.

**Comment by bjorn3** [comment]
The new url is https://github.com/eirproject/eir/blob/a615a9d41563f2632a0e51bcdb99fba673b380cc/util/libeir_util_datastructures/src/pooled_entity_set.rs
