### ISSUE TITLE
Add bswap instruction

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1092]
There is an x86 instruction for this.

**Comment by 11evan** [comment]
Here's an attempt at adding Bswap: https://github.com/bytecodealliance/wasmtime/pull/5147

Also tested with a toy program on both x86_64 and aarch64

It's my first contribution to this project, any and all feedback welcome
Who should I tag for reviewing this?

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/pull/5147 mostly implemented this, but bswap.i128 is still missing. cc @jameysharp

**Comment by bjorn3** [comment]
This is now fully implemented.
