### ISSUE TITLE
iadd_cout and family not legalized for i8 and i16

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1099]
https://github.com/CraneStation/cranelift/blob/2b1cfea1634c58d22b880eb082c748350041c3f0/cranelift-codegen/meta/src/shared/legalize.rs#L465-L515

They are put in the `expand` group, which doesn't run for `i8` and `i16`.

**Comment by cfallin** [comment]
This is I think subsumed by the more general issue of needing to properly support bool carry flag outputs (#2860), so I will close in favor of that.
