### ISSUE TITLE
iadd_cout and isub_bout wrong for signed values

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1100]
https://github.com/CraneStation/cranelift/blob/2b1cfea1634c58d22b880eb082c748350041c3f0/cranelift-codegen/meta/src/shared/legalize.rs#L465-L477

They should do a signed comparison for signed integers.

Edit: when `y` is negative, the condition should be inverted too.

**Comment by cfallin** [comment]
Closing in favor of #2860 as we need to implement the carry/borrow-out-as-flag in general (we no longer use the old legalizations).
