### ISSUE TITLE
Correctly align stack when vector is passed on stack

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1107]
Section "3.2.2 The Stack Frame" of https://software.intel.com/sites/default/files/article/402129/mpx-linux64-abi.pdf

> The end of the input argument area shall be aligned on a 16 (32 or 64, if __m256or __m512ispassed on stack) byte boundary.

**Comment by cfallin** [comment]
I believe we correctly implement this part of the x64 ABI now.
