### ISSUE TITLE
How do I negate a bool?

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/wasmtime#1110]
I'm trying to compile this simple C program:

```c
int main() {
    return !1;
}
```

I'll spare you the parsing, what my program does after implicit casts is:

- create a literal using `let val = builder.ins().iconst(types::I32, 1);`, where `builder` is a `FunctionBuilder`
- cast 1 to `B1` using `let val = builder.ins().icmp_imm(condcodes::IntCC::NotEqual, val, 0);`
- negate the `B1` using `let val = builder.ins().bnot(val);`
- extend the `B1` to `I32` using `builder.ins().bint(types::I32, val)`

This gives me a verifier error: `VerifierError { location: inst2, message: "v2 is a real GPR value defined by a ghost instruction" }`.

What, if anything, am I doing wrong? I see that `rustc_codegen_cranelift` [extends the bool to an I32](https://github.com/bjorn3/rustc_codegen_cranelift/blob/master/src/base.rs#L291), do I need to do that?

**Comment by cfallin** [comment]
This is an old issue and I believe we have proper support for the above now; feel free to open more issues as needed if there are still holes in bool support!
