### ISSUE TITLE
Rename RegDiversion::at_ebb to something better.

### ISSUE THREAD

**Issue by nbp** [bytecodealliance/wasmtime#1115]
This issue was raised by @sstangl on https://github.com/CraneStation/cranelift/pull/883/files#r314880861 , and to avoid delaying the work on Basic Blocks any longer until we can decide on a better naming I am opening this issue.

The current naming `at_ebb` was chosen to be similar to the cursor function named `at_top` which move the instruction cursor to the top of a basic block.

Is there any other proposal, which carry the meaning that we reset the `RegDiversions` set to the one recorded during the coloring phase?

**Comment by bjorn3** [comment]
The new backend framework uses a different register allocator that doesn't use `RegDiversion`.
