### ISSUE TITLE
Add padding between code and constant pool

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1120]
`cranelift-simplejit` and `faerie` already align functions to 16 bytes. Adding enough padding before the constant pool of a function would make the constant pool aligned to 16 bytes too. That would make it possible to use `movaps` instead of `movups` for `vconst`.

https://github.com/CraneStation/cranelift/blob/624d5675a485e74dc73d75f21707f1343621d2b9/cranelift-codegen/meta/src/isa/x86/encodings.rs#L1831-L1835

**Comment by cfallin** [comment]
VCodeConstants properly handle alignment now; closing issue.
