### ISSUE TITLE
[wasm] Revert the custom section validation loosening from #898

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1121]
[This comment](https://github.com/CraneStation/cranelift/pull/898#issuecomment-521992171) hasn't been answered to, and I don't think there are good reasons to loosen validation, and we'd need to implement it later again. Was there actually any good reasons to do so?

cc @alexcrichton @sunfishcode

**Comment by alexcrichton** [comment]
I believe that this is no longer as applicable as it once was, so I'm going to close this.
