### ISSUE TITLE
Add SIMD encodings for older SSE releases

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1122]
As @bnjbvr mentioned in https://github.com/CraneStation/cranelift/pull/943#discussion_r322831206, some cranelift users may not have the most recent SSE versions (e.g. SSE4.1). In these cases, we may need to provide alternate encodings or legalizations in order to implement certain SIMD instructions.

**Comment by cfallin** [comment]
This is subsumed by #3810 I think: we should support Wasm-SIMD on x86-64 with SSE2 (the minimum required architecturally on x86-64) as well as with the more recent extensions. Closing in favor of #3810.
