### ISSUE TITLE
cranelift-wasm: translate wasm spec test suite to cranelift IR and run it through the verifier

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#1128]
Actually running the spec test suite requires an embedder, but even if we just translate it to cranelift ir and verify what we produce, we should get useful tests out of it. This would have helped me catch some bugs with my multi-value wasm PR, that I only later ended up finding out about when working on the wasmtime integration.

**Comment by cfallin** [comment]
This issue was created when the Wasmtime repository was separate from Cranelift; now that they are merged and we get test coverage of the Wasm spec test suite on every Cranelift PR, I think we can probably consider this issue "fixed".
