### ISSUE TITLE
Use variable-length encodings for REX encodings

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1130]
Variable-length encodings (introduced to support the proper machine code for loads/stores which memory operand is in a given register on x86) could allow removing the need to have both the REX vs non-REX encodings.

This would have a few benefits:

- reduce the number of encodings in the legalizer interpreter, making it faster
- allow some encodings to accept REX registers, when they couldn't before (at least regmove is affected by this issue)
- reduce the number of methods in PerCpuModeEncodings

**Comment by bjorn3** [comment]
The new backend framework emits a REX prefix only when it is necessary.
