### ISSUE TITLE
Verify immediate and value types at the time they are bound to instructions

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1135]
In bytecodealliance/cranelift#1012 I noticed that that when we bind a type or immediate to an instruction (e.g. `.bind(I32)`), we don't verify that they are valid. I believe this happens at some later time but it would be more comprehensible to the user if the error was thrown closer to where they wrote the `bind` code. 

Secondly, I did not see that the order of value types and immediates is checked, so the `bind` calls could be mixed in some nonsensical order (to the user) that ends up working correctly during codegen. This could be fixed by storing all of the bound parameters together in a single vector instead of separate vectors for value types and immediates.

**Comment by bjorn3** [comment]
The new backend framework doesn't use legalizations as much as the old backend framework anymore.
