### ISSUE TITLE
Use meta for IR instruction pattern matching

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1137]
The meta language is powerful enough to handle the problem of transforming one instruction into a sequence of other instructions using simple declarations. It could also solve the reverse problem of pattern-matching several instructions into one, which could help implementing instruction selection / pipehole optimizations using meta declarations.

**Comment by bjorn3** [comment]
We have peepmatic now, which is roughtly this, right?

**Comment by cfallin** [comment]
Yes, though there are open questions around how to integrate it or use a Peepmatic-like scheme for instruction lowering in the new backends, so I think we should leave this open to track.

**Comment by akirilov-arm** [comment]
And I guess we are now discussing this in bytecodealliance/rfcs#15?

**Comment by bnjbvr** [comment]
Yep.
