### ISSUE TITLE
Figure out a better type during `bitcast` of a scalar to a vector

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1140]
As noted in https://github.com/CraneStation/cranelift/pull/1120#discussion_r335156013, when moving a scalar value (`I32` or `I64`) to a vector register in x86, the destination must be a a `I64x2` due to typing restrictions that ensure vectors have more than one lane. This may be rather confusing when looking at CLIF IR because the intent of that move (using the `bitcast` instruction) is to zero out the upper bits and only load the lower bits using the scalar value--it's more a `I128x1` than anything else.

There are several options here, some of which are:
 - leave as-is with `I64x2` and remove the TODO comment
 - change the typing restrictions to allow `I128x1`
 - use a different CLIF instruction altogether
 - etc.

**Comment by cfallin** [comment]
Is this still a relevant issue with the new backends @abrown?

**Comment by abrown** [comment]
Nope, closing.
