### ISSUE TITLE
Integrate clippy checking in CI build

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1144]
Please try to describe precisely what you would like to do in Cranelift and/or
expect from it. You can answer the questions below if they're relevant and
delete this text before submitting. Thanks for opening an issue!

- What is the feature or code improvement you would like to do in Cranelift?
After merging bytecodealliance/cranelift#1169 (and seeing bytecodealliance/cranelift#1168), it occurred to me that we should output clippy warnings as a part of `test-all.sh`. I'm not sure we should fail the build (though this could be an option) but this would make non-clippy-approved additions more visible.

- What is the value of adding this in Cranelift?
It should result in cleaner, more standard code in the long run.

- Do you have an implementation plan, and/or ideas for data structures or
  algorithms to use?
Add `cargo clippy` to `test-all.sh` and ensure `clippy` is installed for Azure pipelines.

- Have you considered alternative implementations? If so, how are they better
  or worse than your proposal?
No.

**Comment by marmistrz** [comment]
I think it would be nice to have selected checks enforced on the CI. 

For instance, I frequently encounter the "unnecessary name repetition" lint failing in the codebase and I think it would be a good idea. On the other hand, this should be definitely a whitelist of curated checks and not a wholesale inclusion of clippy.

Is there any reason why we have to use clippy check from actions-rs and not just manually install it with `rustup` and execute `cargo clippy` inside the CI?

**Comment by bjorn3** [comment]
The actions-rs version shows annotations on pull requests for all warnings and errors, while just using `cargo clippy` requires you to visit the build log.

**Comment by alexcrichton** [comment]
Clippy is currently checked on CI although most lints are turned off. It's intended that we'll enable clippy lints on a case-by-case basis and watch them in CI.
