### ISSUE TITLE
Wasm br_table spec running forever

### ISSUE THREAD

**Issue by bjfish** [bytecodealliance/wasmtime#1153]
The `br_table.wast` spec appears to run forever when the `jump_tables_enabled` flag is set to false.  This may be a regression in recent versions like `0.49.0` as this was not observed in `0.44.0`.

- What are the steps to reproduce the issue? 
I used wasmtime at commit `a2479df32932b2481ae576a9b07a55081288b20c` to run the spectests.
   1. Add `flag_builder.set("jump_tables_enabled", "false").unwrap();` to `wast_testsuites.rs` in wasmtime.
  2. Run `cargo test br_table` in wasmtime.
  3. The test appears to run forever.

- What do you expect to happen? 
  The spectest should run to completion. 
- What does actually happen?
  The spectest appears to run forever.
- Which Cranelift version / commit hash / branch are you using?
`0.50.0`
- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)
rustc 1.39.0 (4560ea788 2019-11-04)
macOS Catalina

**Comment by cfallin** [comment]
This is an old bug from the time of the old x86 backend and I believe should be resolved now; closing.
