### ISSUE TITLE
Support VEX and EVEX encodings

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1154]
- What is the feature or code improvement you would like to do in Cranelift?

Add VEX and EVEX encoding mechanisms for x86 code generation.

- What is the value of adding this in Cranelift?

Certain Wasm SIMD operations (e.g. [convert, trunc](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#conversions)) only can be lowered with VEX and EVEX encodings. Many VEX and EVEX encodings are only available in later SIMD feature sets (e.g. AVX-512); adding the ability to use VEX and EVEX encodings does not preclude legalizations for x86 CPUs without later SIMD feature sets, but that is a separate issue.

- Do you have an implementation plan, and/or ideas for data structures or algorithms to use?

I think the relevant thing here is that it may impact how we go about resolving bytecodealliance/wasmtime#1141.

- Have you considered alternative implementations? If so, how are they better or worse than your proposal?

Not having the ability to use VEX and EVEX encodings would force cranelift to use multi-instruction legalizations instead of optimal instructions during instruction selection.

**Comment by bjorn3** [comment]
I believe this is handled with the new framework backend.

**Comment by abrown** [comment]
It should be handled but I don't think it is yet... at least not that I know of. I haven't ported the VEX/EVEX encoding stuff over from the old backend.

**Comment by cfallin** [comment]
This is all covered now in the current `x64` backend, and we have VEX encodings for many vector instructions -- closing now!
