### ISSUE TITLE
undefined reference to `__cranelift_probestack'

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/wasmtime#1159]
- What are the steps to reproduce the issue? Can you include a CLIF test case,
  ideally reduced with the `bugpoint` clif-util command?

```clif
function u0:0() -> i32 system_v {
    ss0 = explicit_slot 10000
    ss1 = explicit_slot 10000

ebb0:
    v0 = iconst.i32 0
    return v0
}
```

- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?

I expect this to compile and return 0. Instead I get a linker error:
```/usr/local/bin/ld: /tmp/.tmpK629Dc: in function `main':
intcode.c:(.text.main+0xc): undefined reference to `__cranelift_probestack'```

- Which Cranelift version / commit hash / branch are you using?

Cranelift 0.49.0

- If relevant, can you include some extra information about your environment?
x86_64 Linux, Ubuntu 18.04 LTS, linking using GNU ld 2.32. I am using cranelift-faerie to emit object files.

**Comment by cfallin** [comment]
This is an old issue that I think is "working as expected" (one needs to provide an external stack-probe function), so I will go ahead and close.
