### ISSUE TITLE
Move documentation from readthedocs.io to docs.rs

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1160]
#### What is the feature or code improvement you would like to do in Cranelift?

Figure out what to do with https://cranelift.readthedocs.io. At some point (can't remember where), I saw a discussion about moving the documentation to https://docs.rs exclusively. I think this would be a good idea in order to keep documentation up to date, since https://cranelift.readthedocs.io seems to have some gaps.

#### What is the value of adding this in Cranelift?

Documentation should be complete and ideally in one place.

#### Do you have an implementation plan, and/or ideas for data structures or algorithms to use?

I believe we would have to distribute the contents of the `docs` directory to Rust files such as `cranelift-umbrella/src/lib.rs` (and remove the `sphinx` documentation in `README.md`). Also, as noted in bytecodealliance/cranelift#1264, it occurred to me that perhaps we would also like to update the docs badge to something like:

```
[![Documentation Status](https://docs.rs/cranelift/badge.svg)](https://docs.rs/cranelift)
````
[![Documentation Status](https://docs.rs/cranelift/badge.svg)](https://docs.rs/cranelift)

**Comment by sunfishcode** [comment]
We've completely migrated off of the readthedocs site now. The content has been migrated to markdown source files in Cranelift's [docs directory](https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/docs/index.md), and documentation of the instructions is now on docs.rs as [part of the API documentation](https://docs.rs/cranelift-codegen/0.60.0/cranelift_codegen/ir/trait.InstBuilder.html).
