### ISSUE TITLE
test failure in cranelift-bforest and cranelift-entity with: no global memory allocator found but one is required; link to std 

### ISSUE THREAD

**Issue by stefson** [bytecodealliance/wasmtime#1165]
I've run the tests via: 
```
cargo build -j12
cargo test --all -j12
```

here's the full log: [test-failure.zip](https://github.com/bytecodealliance/cranelift/files/3987977/test-failure.zip)

I wonder if this is related to https://github.com/bytecodealliance/cranelift/pull/1262

**Comment by cfallin** [comment]
This is an old bug and appears related to `no_std` support, which we don't support; I will go ahead and close this.
