### ISSUE TITLE
Determine cause of crash with inferred-REX brz/brnz

### ISSUE THREAD

**Issue by sstangl** [bytecodealliance/wasmtime#1166]
Reported in https://github.com/bytecodealliance/cranelift/issues/1305 and fixed (by partially reverting a patch in https://github.com/bytecodealliance/cranelift/pull/1308), it appears that when `brz` and `brnz` are emitted with runtime-inferred `REX` prefixes (and therefore don't have constant instruction size), the code can jump into the middle of nowhere.

https://github.com/bytecodealliance/cranelift/pull/1308 changed `brz` and `brnz` back to using separate encodings for REX and non-REX to prevent crashes in the meantime. This issue is to find the cause and fix it.

STR are in https://github.com/bytecodealliance/cranelift/issues/1305 but I was not able to reproduce it locally.

**Comment by bjorn3** [comment]
This is a bug with the old x86 backend.
