### ISSUE TITLE
Windows (Fastcall) calling convention: Callee-saved XMM (FP) registers are not actually saved

### ISSUE THREAD

**Issue by hrydgard** [bytecodealliance/wasmtime#1177]
We're having issues, only on Windows, with floating point variables becoming corrupt across calls into Cranelift from Wasmer.

The following function `callee_saved_gprs` in the codegen is supposed to return a list of the callee-saved registers:

https://github.com/bytecodealliance/cranelift/blob/23e9bdb2d99fb8f554793cb87f1578cc543c355f/cranelift-codegen/src/isa/x86/abi.rs#L370

However, it, nor its callers, seem to concern themselves with saving the floating point callee-saved registers (with gprs in its name, that kind makes sense). Quoth https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019#callercallee-saved-registers:

> The registers RBX, RBP, RDI, RSI, RSP, R12, R13, R14, R15, and XMM6-15 are considered nonvolatile and must be saved and restored by a function that uses them.

`callee_saved_gprs` only lists RBX, RBP, RDI, RSI, RSP, R12, R13, R14, R15, ignoring XMM6-15.

I believe this may be the cause of our troubles, it definitely looks wrong. What do you think?

(If the reserved stack spaced for this would be prohibitive and code is generated assuming no callee saved registers, things could still work internally as they do now, but you'd still need to save XMM6-15 on entering Cranelift and restore them when exiting Cranelift).

**Comment by hrydgard** [comment]
What happens now to the PR that was going to fix this,  https://github.com/bytecodealliance/cranelift/pull/1378 , now that cranelift has moved into wasmtime? That surely also needs to be moved?

**Comment by alexcrichton** [comment]
@hrydgard I [posted instructions](https://github.com/bytecodealliance/cranelift/pull/902#issuecomment-592778184) of how to move PRs, and it requires author intervention. I didn't post on that PR b/c I didn't want to spam the same authors on PRs more than once, or at least I tried!

**Comment by hrydgard** [comment]
Okay! Just want to make sure it doesn't fall through the cracks of the move, it's a super critical fix.

**Comment by peterhuene** [comment]
I believe this has been resolved since March of 2020, but this probably fell through the cracks during the cranelift repo migration; therefore I'm closing this issue now.
