### ISSUE TITLE
Don't build the meta crate with optimizations with Rustc 1.41+

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1180]
See https://github.com/bytecodealliance/wasmtime/commit/8affec0896334925f6b6ee714b7d3a85782ab7ee. With Rustc 1.41+, it's possible to disable optimizations for build-time-only crates, so we should do this. This should reduce build time for optimized and release builds.

**Comment by csmoe** [comment]
@bnjbvr cranelift was moved into wasmtime, so this issue can be closed?

**Comment by alexcrichton** [comment]
Indeed this should be taken care of now!

**Comment by bnjbvr** [comment]
@alexcrichton Where is this done? I would have expected changes to build settings to appear in cranelift-codegen Cargo.toml file, or the cranelift-codegen-meta Cargo.toml file? I might be missing something here. The goal of this issue was to make the build crate (meta crate) with no optimizations all the time for all the embedders, not only in the context of "cranelift being used in wasmtime", which might be a different story.

**Comment by bjorn3** [comment]
This is done in the workspace `Cargo.toml`:

https://github.com/bytecodealliance/wasmtime/blob/f7c2a58d236bf23819139930bf1e469a47e08140/Cargo.toml#L60-L61

**Comment by bnjbvr** [comment]
Ok, so I'll reopen: my intent was to do this in Cranelift's cargo files, so this benefits all the Cranelift users.

**Comment by alexcrichton** [comment]
Oh sorry so yes, to clarify, this is done in the workspace Cargo.toml which now applies to cranelift as well. @bnjbvr what you're asking for, I believe, is not a feature that Cargo supports at this time. There's no way for a crate to say "build me without optimizations all the time". This'd have to be something that would be in the documentation for cranelift users, if anything. Something like "if you feel like cranelift's build is slow try putting this in Cargo.toml"

**Comment by bnjbvr** [comment]
Ah, I was a bit too optimistic :) Thanks, we can make this a documentation issue then.

**Comment by jameysharp** [comment]
Good point, @bjorn3. If I'm understanding this issue correctly, I think we can close it.
