### ISSUE TITLE
Allow parsing of hexadecimal immediates

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1182]
#### Feature

The types `i16`, `i32`, and `i64` currently cannot be parsed from a hexadecimal integer; `i8` can by using the `match_uimm8` function in `parser.rs` but `match_imm16`, `match_imm32`, and `match_imm64` do not allow this.

#### Benefit

At times we are forced to use strange negative numbers to represent values more naturally expressed with a hexadecimal number; e.g. when preparing a value for checking overflow semantics in a 16-bit vector lane, it is more convenient to use `0xffff` than `-32768`.

#### Implementation

- Add hexadecimal parsing to  `match_imm16`, `match_imm32`, and `match_imm64` (see `match_uimm8`)
- Modify tests using strange negative numbers (e.g. like [this comment](https://github.com/bytecodealliance/cranelift/pull/1371#discussion_r382664691)), replacing these with the more clear hexadecimal syntax

#### Alternatives

We could leave this as is; it makes sense that the `match_imm*` functions are concerned primarily with parsing signed integers. However, adding hexadecimal parsing would not break anything as long as we include checks that the number has no more bits than necessary (e.g. a hex number parsed to an `Imm64` should have no more than 64 bits).

**Comment by darinmorrison** [comment]
I'd like to try implementing this. Can you assign me?

**Comment by abrown** [comment]
I'm on [Zulip](https://bytecodealliance.zulipchat.com) if you run into issues!
