### ISSUE TITLE
SIMD testsuite tests failing with speed optimization.

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime#1186]
See bytecodealliance/wasmtime#988 which is enabling speed optimizations by default in the Rust and C APIs for Wasmtime.

This caused failures in the SIMD testsuite tests as noted in that PR.

To reproduce, comment out the FIXME lines in `tests/wast_testsuites.rs` that are disabling optimizations when testing with SIMD enabled.

**Comment by bjorn3** [comment]
The assignment got lost when transfering this issue to wasmtime.
