### ISSUE TITLE
Improve bitselect codegen with knowledge of operand origin

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1187]
#### Feature

As discussed in https://github.com/WebAssembly/simd/issues/192, the Wasm SIMD `bitselect` instruction could be lowered to one of the x86 `BLEND*` family of instructions instead using 3-4 instructions.

#### Benefit

Potentially faster code, smaller code size.

#### Implementation

If we know that the `bitselect` control mask value comes from a comparison instruction then, for each lane, all of the bits will be either 0s or 1s. This allows us to use a `BLEND*` instruction on x86, since the ISA has no bit-level selection like ARM's `VBSL`.

#### Alternatives

https://github.com/WebAssembly/simd/issues/192 also proposed making this type of information explicit in the Wasm SIMD spec by having comparisons return a mask type that would allow following instructions to make the optimization above without looking up the control mask origin and through function calls. Unfortunately, this is not likely to happen soon--["a lot of work"](https://github.com/WebAssembly/simd/issues/192#issuecomment-589869555).

**Comment by teapotd** [comment]
I'll look into this.
