### ISSUE TITLE
The wasm-rust.md example with interface types does not work.

### ISSUE THREAD

**Issue by tiptop96** [bytecodealliance/wasmtime#1210]
https://github.com/bytecodealliance/wasmtime/blob/master/docs/wasm-rust.md#webassembly-interface-types

Problem number one is that it will not work with a higher version than`wasm-bindgen = "=0.2.55"`. Currently it is set to `wasm-bindgen = "0.2.54"` which will install a higher minor version than 55. This has been discussed, see: https://github.com/bytecodealliance/wasmtime-demos/issues/13#issuecomment-571258694

The second is that the `wasmtime` command requires the `--enable-multi-value` flag when using interface types (maybee this is just specific to the way the `wasm-bindgen` proc-macro works?). Or we get this.
```sh
$ wasmtime --invoke greet target/wasm32-wasi/release/wasm_greeting.wasm "Wooo!"
Error: failed to run main module `target/wasm32-wasi/release/wasm_greeting.wasm`

Caused by:
    invalid result arity: func type returns multiple values (at offset 43)
```
I have a PR ready to fix these, unless anyone has anything to add?

**Comment by tiptop96** [comment]
@alexcrichton I can't assign you but I think you'd be the best person too look at this, being the author of the linked comment.

**Comment by alexcrichton** [comment]
Thanks for the report!

Unfortunately at this time the demos of interface types are broken and we haven't gotten around to discussing how best to update documentation and update the state of the world. There's [some discussion on Zulip though](https://bytecodealliance.zulipchat.com/#narrow/stream/217126-wasmtime/topic/What.20do.20to.20about.20our.20Interface.20Types.20support.3F) if you're curious to jump in!

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!
