### ISSUE TITLE
Missing define/undef of 'own' symbol for wasmtime.h

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#1215]
#define own
and
#undef own

are missing for new wasmtime.h.

Both wasi.h and wasm.h define own properly.

**Comment by rene-fonseca** [comment]
Also, there is an extra , - that breaks build.

https://github.com/bytecodealliance/wasmtime/blob/master/crates/c-api/include/wasmtime.h#L58

bool wasmtime_wat2wasm(
    wasm_engine_t *engine,
    const wasm_byte_vec_t *wat,
    own wasm_byte_vec_t *ret,
    own wasm_byte_vec_t *error_message, // <<< REMOVE ,
);

**Comment by rene-fonseca** [comment]
@alexcrichton FYI

**Comment by rene-fonseca** [comment]
And then I like:
#include <wasm.h>
changed to:
#include "wasm.h"

This will allow headers to work regardless of the include search path. wasi.h already uses #include "wasm.h" as desired.

See note in https://github.com/bytecodealliance/wasmtime/pull/1211

**Comment by rene-fonseca** [comment]
FYI This was tested with clang.

**Comment by rene-fonseca** [comment]
Maybe *error_message* should use wasm_name_t instead of wasm_byte_vec_t for consistency.

**Comment by rene-fonseca** [comment]
API confirmed to work with https://github.com/bytecodealliance/wasmtime/blob/master/tests/wat/rs2wasm-add-func.wat .

**Comment by alexcrichton** [comment]
I believe this was fixed in https://github.com/bytecodealliance/wasmtime/pull/1286, and we're not verifying the header file is usable on CI!

**Comment by rene-fonseca** [comment]
Yes, fixed now.

**Comment by rene-fonseca** [comment]
Oh I still like the #include <wasm.h> changed though - see above.

**Comment by alexcrichton** [comment]
Can you open a separate issue? It's hard to dig through the comments of an unrelated issue to see what needs fixing.

**Comment by rene-fonseca** [comment]
Opened https://github.com/bytecodealliance/wasmtime/issues/1313
