### ISSUE TITLE
Master branch seems to have lost a dependency

### ISSUE THREAD

**Issue by icefoxen** [bytecodealliance/wasmtime#1229]
Per the docs here: https://bytecodealliance.github.io/wasmtime/contributing-building.html , you should be able to build wasmtime with just `cargo build`.  When I try, on Rust stable (1.41), I get:

```
error: failed to read `~/src/wasmtime/crates/wasi-common/wig/WASI/tools/witx/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I actually can't find `witx` at all, though there's plenty of code references to it, and it's published on `crates.io`.  The culprit seems to be the `witx` dependency in `crates/wasi-common/wig/Cargo.toml`, but changing that to use the crates.io version of `witx` causes other things to break.

In fact, trying to build from source using the 0.12 release archive also breaks with the same problem.  Not sure what to say about that!  The 0.11 source release seems to have an issue building as well:

```
   Compiling wasi-common v0.11.0 (~/src/wasmtime-0.11.0/crates/wasi-common)
error: proc macro panicked
  --> crates/wasi-common/src/host.rs:12:1
   |
12 | witx_host_types!("snapshot" "wasi_snapshot_preview1");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: error opening file /home/icefox/tmp/wasmtime-0.11.0/crates/wasi-common/wig/WASI/phases/snapshot/witx/wasi_snapshot_preview1.witx: IO error with file "/home/icefox/tmp/wasmtime-0.11.0/crates/wasi-common/wig/WASI/phases/snapshot/witx/w
```

**Comment by abrown** [comment]
Is it a git submodule issue? Any change after running `git submodule init && git submodule update`?

**Comment by tschneidereit** [comment]
Indeed, initializing submodules was missing from the build instructions. I created #1258 to address that.
