### ISSUE TITLE
cranelift-codegen fails to compile without x86 support

### ISSUE THREAD

**Issue by iximeow** [bytecodealliance/wasmtime#1240]
- What are the steps to reproduce the issue?
  - Build `cranelift-codegen` targeting only one architecture (as an example, clone https://github.com/iximeow/cautious-pancake and build it)
- What do you expect to happen?
  - Compilation should succeed.
- What does actually happen?
  - Compilation does not succeed.
- Which Cranelift version / commit hash / branch are you using?
  - `3179dcf` (`master`)
- If relevant, can you include some extra information about your environment?
  - n/a - reproducible anywhere Cargo runs.

This was first mentioned by @stefson in [this comment](https://github.com/bytecodealliance/cranelift/pull/1174#issuecomment-595205081).

I agree with @bjorn3's assessment [in reply](https://github.com/bytecodealliance/cranelift/pull/1174#issuecomment-595217112). Since TLS access assumes a C ABI, would it make sense to just add `is_call` as an attribute to these opcodes? Edit: this depends on other questions like, can `TlsGetAddr` be hoisted [in LICM](https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/codegen/src/licm.rs#L139-L141)? Eligible for [DCE](https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/codegen/src/dce.rs#L14-L15)? And interaction with the verifier?  Given that it [includes a call](https://github.com/bytecodealliance/cranelift/pull/1174/files#diff-868c004db6bfd05b9f83082219c3389fR3296-R3299) I think this might be the right way to go about it. And since the call takes an argument [in rdi](https://github.com/bytecodealliance/cranelift/pull/1174/files#diff-868c004db6bfd05b9f83082219c3389fR3285-R3290), if there needs to be a signature for verifier reasons, it looks like we can synthesize one of the form `(rdi) -> rax`?

A wider concern: does anyone have ideas on how we'd build Cranelift under these different, more specific, feature flag combinations? I was surprised to learn `cargo build --no-default-features --features std` didn't work to show this, but that seems to be a consequence of [this issue](https://github.com/rust-lang/cargo/issues/4753). It seems appropriate to have some test crates that build under feature flag combinations we want to support, so issues like this get caught in CI. It would raise build times a bit, but I'm not sure how much. Does that sound acceptable?

**Comment by bnjbvr** [comment]
This is now biting us in Spidermonkey too, where we only build the relevant backends, so this is high priority for us.

We could add supplementary builds with disabled features in automation, to make sure they don't get broken anymore.

**Comment by bjorn3** [comment]
I initially tried adding `is_call`, but that requires `analyze_call` to return a valid `CallInfo`. As the instructions in question are not normal calls and don't have a `Signature`, it is not possible to return a valid `CallInfo`.

> can TlsGetAddr be hoisted in LICM? Eligible for DCE?

Yes and yes, I think.

> And since the call takes an argument in rdi, if there needs to be a signature for verifier reasons, it looks like we can synthesize one of the form (rdi) -> rax?

How would that signature get assigned to the instruction? It is not possible to lower the instructions to libcalls, as they require a very specific combination of x86 instructions for the linker to handle it correctly.

>  was surprised to learn cargo build --no-default-features --features std didn't work to show this, but that seems to be a consequence of this issue.

During compilation the build script detects the current architecture and automatically enables support for it. (at least if there are no archs enabled through feature flags)

**Comment by bnjbvr** [comment]
So my current thinking is the following: since this can't be emulated properly with a call, maybe the proper way here is to add a new accessor on the opcode? I've got a wip patch that does this, with a new property called "clobbers_all_regs", and which is tested during register allocation in place of the opcode comparisons. I thought about other names, like "emulates_call", but this seems to be the most explicit, at the very least.

**Comment by bjorn3** [comment]
> I've got a wip patch that does this, with a new property called "clobbers_all_regs"

:+1:

**Comment by bjorn3** [comment]
Was actually working on the same, but named it `clobbers_all` :)
