### ISSUE TITLE
wasm_config_delete not exported for wasmtime C-API

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#1256]
wasm_config_delete declared in wasm.h via WASM_DECLARE_OWN(config) is not available as exported symbol in wasmtime library. Seen for macOS.

**Comment by peterhuene** [comment]
Note: config ownership is expected to be transferred in `wasm_engine_new_with_config`, so `wasm_config_delete` should only be called in the case of creating an unused config and wanting to free it.
