### ISSUE TITLE
[cranelift] Simplify SSABuilder with basic block

### ISSUE THREAD

**Issue by Y-Nak** [bytecodealliance/wasmtime#1259]
#### Feature
Current implementation of `SSABuilder` has redundant fields and depends on redundant  function/struct in order to work with `EBB`.
We no longer need them and can simplify `SSABuilder` when assuming all blocks are `BasicBlock`.

#### Benefit
Readability and (small) performance improvement.

#### Implementation 
Remove extra fields and functions related to `EBB` from `frontend/src/ssa.rs` and `frontend/src/frontend.rs`.

**Comment by Y-Nak** [comment]
Draft proposal: https://github.com/Y-Nak/wasmtime/tree/simplify-ssa-builder

**Comment by bnjbvr** [comment]
Thanks for opening an issue. We identified this simplification opportunity too with @eqrion, so it's definitely something we had in mind. Maybe @eqrion or I could do a proper review for this, if you wanted to submit a PR?

**Comment by Y-Nak** [comment]
Thanks for responding back. I'll submit a PR.
