### ISSUE TITLE
A way to stop WASM instance when execution hangs

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#1268]
#### Feature

Would it be possible to add a way to send a trap or similar to the WASM instance from any caller at any time from API to force a currently running instance to terminate nicely. It is kind of like sending a POSIX abort/interrupt signal().

#### Benefit

Allow WASM instance to be aborted nicely when it would otherwise run in infinite loop. When to abort, is then fully controllable from caller.

#### Implementation

Allow special trap to be sent from external caller thread which would be injected into a given running thread or all threads of the WASM instance. Which any return will trigger a trap within a given time or execution cycles.

#### Alternatives

Not sure what else could be done. There is no guarantee that an import is called from the WASM instance to hook for arbitrary modules.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe this is covered by https://github.com/bytecodealliance/wasmtime/issues/860, or that's at least where we've been consolidating these sorts of feature requests, so I'm going to close this in favor of that.

**Comment by rene-fonseca** [comment]
Thanks.
