### ISSUE TITLE
Filling out missing Introductory Documentation

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#1272]
I'd like to use this issue as a tracking issue for filling out gaps in `wasmtime`'s introductory documentation. This includes [our book](https://github.com/bytecodealliance/wasmtime/tree/master/docs) ([rendered](https://bytecodealliance.github.io/wasmtime/)), API documentation ([rendered](https://bytecodealliance.github.io/wasmtime/api/wasmtime/)), and [examples](https://github.com/bytecodealliance/wasmtime/tree/master/crates/api/examples). (or anything else others can think of as well!)

Below I'm gonna fill out a bunch of checkmarks and checkboxes for what is currently missing *at this time*. If you'd like to help in and document things, please feel free to do so! If you leave a comment on this issue along with what you'd like to help fill in, we'll edit your name into the description here to know that it's claimed. Any and all help here is greatly appreciated!

## Book Documentation

As a precursor I'll say that this is organized largely page-by-page in the book. The current organization of the book was an initial proposal from awhile ago and thinking back on it some of it may be a little redundant. Please feel free to also discuss the layout of the book and what documentation would best go where!

* [x] [Step-by-step tutorial to create and run hello-world.wasm](https://bytecodealliance.github.io/wasmtime/tutorial.html). This is intended to be a gentle introduction to running code with wasmtime, originating from nothing and ending using the `wasmtime` CLI to execute a Rust-generated WebAssembly file - @noculture 
* [ ] [List of example programs compiled to WebAssembly](https://bytecodealliance.github.io/wasmtime/examples.html). We'll want to include some listings of a few "hello world" wasm modules as well as some more complicated ones like Rust projects with Cargo dependencies (e.g. a markdown parser)
* [x] [Documenation of using wasm from Python](https://bytecodealliance.github.io/wasmtime/lang-python.html) - @jjsullivan5196 
* [x] [Documentation of using wasm from .NET](https://bytecodealliance.github.io/wasmtime/lang-dotnet.html)
* [x] [Documentation of using wasm from Rust](https://bytecodealliance.github.io/wasmtime/lang-rust.html) (not necessarily detailed embedder docs, but more of how you might use wasmtime at a high level to plug into a larger application)
* [x] [Documentation of using wasm from bash](https://bytecodealliance.github.io/wasmtime/lang-bash.html) (aka examples of using the CLI)
* [x] [Writing WebAssembly from C/C++](https://bytecodealliance.github.io/wasmtime/wasm-c.html)
* [x] [Writing WebAssembly, markdown example](https://bytecodealliance.github.io/wasmtime/wasm-markdown.html) - @humancalico
* [x] [Embedding wasmtime overview](https://bytecodealliance.github.io/wasmtime/embed.html)
* [x] [Embedding wasmtime in Rust](https://bytecodealliance.github.io/wasmtime/embed-rust.html) - currently has docs but feels a bit light on content
* [x] [Embedding wasmtime in C/C++](https://bytecodealliance.github.io/wasmtime/embed-c.html)
* [x] Embedding wasmtime in .NET - probably want a page on this?
* [ ] [What stability means in wasmtime](https://bytecodealliance.github.io/wasmtime/stability.html) - probably want to talk about what our version scheme is, what's stable, what's not, etc.
* [x] [Release process](https://bytecodealliance.github.io/wasmtime/stability-release.html) - documenting a release cadence, when releases happen, policies for releases, where releases are announced, etc.
* [x] [Platform support](https://bytecodealliance.github.io/wasmtime/stability-platform-support.html) - currently contains a lot of introductory documentation, feels pretty light though and like it could be better tied together.
* [x] [Security policy](https://bytecodealliance.github.io/wasmtime/security.html)
* [x] [Disclosure policy](https://bytecodealliance.github.io/wasmtime/security-disclosure.html)
* [x] [Sandboxing](https://bytecodealliance.github.io/wasmtime/security-sandboxing.html) - @sunfishcode 
* [ ] [Governance](https://bytecodealliance.github.io/wasmtime/contributing-governance.html)

## API Documentation

* [x] The [crate documentation](https://bytecodealliance.github.io/wasmtime/api/wasmtime/) feels lacking and could use a broad example to introduce the crate.
* [x] The [`Module` type](https://bytecodealliance.github.io/wasmtime/api/wasmtime/struct.Module.html) should have at least one example somewhere.
* [x] The [`Instance` type](https://bytecodealliance.github.io/wasmtime/api/wasmtime/struct.Instance.html) should have at least one example.
* [x] The [`Store` type](https://bytecodealliance.github.io/wasmtime/api/wasmtime/struct.Store.html) needs more documentation about what it is, although this is somewhat up for debate in other issues as well.
* [x] The [`Memory` type](https://bytecodealliance.github.io/wasmtime/api/wasmtime/struct.Memory.html) needs examples of safe usage, and double-checks on wording about unsafe usage.
* [x] The [`Func` type](https://bytecodealliance.github.io/wasmtime/api/wasmtime/struct.Func.html) could use an example on the `get` family of methods.
* [x] Types which correspond to the [wasm specification](https://webassembly.github.io/spec/core/index.html) should link there where possible.

## Examples

I think we want an overhaul of how our examples work. Here's my proposal for what we need to do:

* [x] Move Rust examples to a top-level `examples` directory - @alexcrichton 
* [x] Move C examples to the top-level `examples` directory too - @alexcrichton 
* [x] Every example has a comment at the top of the file of how to build and run it - @alexcrichton 
  * Rust is typically `cargo run --example foo`
  * C is `gcc examples/foo.c -I crates/c-api/include -o foo && ./foo` (ish)
* [x] Wasm files are never checked in for examples - @alexcrichton 
  * Either wasm is written inline as a `*.wat` string
  * Or example is structured as `examples/name/main.rs` with a corresponding `examples/name/wasm/Cargo.toml` which is a Rust project compiled to wasm. (or `examples/name/wasm.c` if we want to show off a C-compiled wasm example)
* [x] Every example is available in both Rust and C - @alexcrichton 
  * For `examples/foo.rs` we have a corresponding `examples/foo.c`
  * For `examples/foo/main.rs` we have a corresponding `examples/foo/main.c`
* [ ] Example showing how to link in the WASI functions
* [ ] Example of reading a string from a wasm module 
* [ ] Example of a string processor, for example a markdown renderer
* [x] All examples are compiled and run on CI, regardless of language, on our three main platforms. - @alexcrichton

**Comment by noculture** [comment]
I could take a stab at this: "Step-by-step tutorial to create and run hello-world.wasm"

**Comment by alexcrichton** [comment]
I'm working on a number of the examples bullets, mostly around organizing them and bringing C on par with Rust. Also CI!

**Comment by sunfishcode** [comment]
I'll write some content for the Sandboxing section.

**Comment by jjsullivan5196** [comment]
I can work on getting the python examples illustrated in the documentation. I think the demo video on the wasmtime home page is pretty comprehensive, so I'll probably just add some more details for project setup with things like pipenv and the like https://youtu.be/Qn_4F3foB3Q

**Comment by alexcrichton** [comment]
@jjsullivan5196 sounds great to me! I do think we should still at least document what we have which should work well for integers and such, but  yeah the exact video won't work any more because strings are no longer supported.

**Comment by humancalico** [comment]
@alexcrichton I'll write the markdown parser for the book

**Comment by Hyperion101010** [comment]
Hi there Shivam here. I can try on working "Documentation of using wasm from Rust" @alexcrichton .

**Comment by ilikepi63** [comment]
@alexcrichton The list above doesn't seem to be updated with the examples that have been submitted. Is there anything that anyone can begin working on at the moment?

**Comment by alexcrichton** [comment]
Ah thanks for the ping but I think that this is largely done now and this is pretty old now so I'm going to go ahead and close this.
