### ISSUE TITLE
spawn

### ISSUE THREAD

**Issue by willemneal** [bytecodealliance/wasmtime#129]
Since there  is no fork/exec, is invoking another program up to the runtime?

Is there a convention for doing it such as creating a special file?

**Comment by sunfishcode** [comment]
There is not yet a convention for doing this. It's something we'd like to add though!

**Comment by bjorn3** [comment]
Should this be moved to https://github.com/webassembly/wasi?

**Comment by sunfishcode** [comment]
The original question is answered; if someone wants to discuss this further, opening an issue in the WASI repository would be a good starting point!
