### ISSUE TITLE
Canonicalize NaNs when fuzzing

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#1332]
In `Config::new` in `crates/api/src/runtime.rs`, we should conditionally enable the `canonicalize_nans` cranelift option when we're being built for fuzzing:

```rust
#[cfg(fuzzing)]
flags.set("enable_nan_canonicalization", "true").unwrap();
```

This should make execution during fuzzing that much more deterministic.

**Comment by teapotd** [comment]
Hello, I'd like to work on this.
