### ISSUE TITLE
How to use polyfill.js in webpack entry file?

### ISSUE THREAD

**Issue by alanpoon** [bytecodealliance/wasmtime#135]
How to use polyfill.js in webpack entry file such that the modules function defined in the polyfill can be found my subsequent wasm?

Here is my sample entry file.
https://gist.github.com/alanpoon/0da16e04fbccf29c0846c8c32324c622

**Comment by sunfishcode** [comment]
I'm unfortunately not familiar enough with webpack to know how to answer this myself.

**Comment by bjorn3** [comment]
This was about the polyfill at https://wasi.dev/polyfill/index.html, right? It is now gone.
