### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by willemneal** [bytecodealliance/wasmtime#139]
How are signals handled by the runtime?

If my program were to be in an infinite loop, how does it handle signals?  Is the runtime responsible for interrupting the running wasm program to check if it has received any signals?

**Comment by sunfishcode** [comment]
Wasmtime doesn't yet have a way to handle signals. It's something we're planning to add though -- Cranelift has support for injecting an interrupt check in loops which we plan to hook up as an option, and we plan to have the runtime be able to interrupt programs with signals too.
