### ISSUE TITLE
Cranelift: implement bmask instruction

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1429]
There is currently neither an encoding, nor a legalization for this instruction.

**Comment by bjorn3** [comment]
I think it should be used by `translate_vector_icmp` and `translate_vector_fcmp` after an encoding is added.

**Comment by bjorn3** [comment]
According to the docs the instruction would for every lane return an all ones integer for a true bool and an all zeros integer for a false bool. Eg `bmask.i8x2` on `[false, true]` would return `[0x00, 0xff]`.

`translate_vector_{icmp,fcmp}` currently assume that `icmp` and `fcmp` on vectors represent the resulting bool using all zeros / all ones. Otherwise the `raw_bitcast` would fail. This is not guaranteed anywhere and for non vectors this assumption is wrong. Using eg `bmask.i8x16` to convert a `b8x16` instead of using `raw_bitcast.i8x16` would avoid making this assumption.

**Comment by abrown** [comment]
As I understand it, on x86 and [ARM](https://github.com/v8/v8/blob/master/src/compiler/backend/arm64/code-generator-arm64.cc#L2057-L2066) the output of vector `icmp` and `fcmp` is another vector with lanes of all zeroes or all ones. Are you suggesting using `bmask.i8x16` in 
`translate_vector_{icmp,fcmp}` to make things look more type-correct but actually encode it as a noop on those platforms?

**Comment by bjorn3** [comment]
Yes

**Comment by cfallin** [comment]
Closing this in favor of #3205, which encompasses the general topic of our vector-bool representation.
