### ISSUE TITLE
__WASI_RIGHT_PATH_OPEN when calling __wasi_path_open

### ISSUE THREAD

**Issue by willemneal** [bytecodealliance/wasmtime#143]
I'm confused, if calling `__wasi_path_open`, should you always pass this flag?  Where do you get the initial permission to open a file?

**Comment by sunfishcode** [comment]
You need `__WASI_RIGHT_PATH_OPEN` on the directory handle passed to `path_open`. The rights you pass into `path_open` are the rights you're requesting on the newly opened file descriptor.

**Comment by willemneal** [comment]
So you will always have the right for any pre-openned directories?

**Comment by bjorn3** [comment]
As the rights system has been removed from Wasmtime and doesn't exist at all in wasip2 can this be closed?
