### ISSUE TITLE
Maximum multi value limit count

### ISSUE THREAD

**Issue by Alphapage** [bytecodealliance/wasmtime#1447]
Hello,

I tried the multi value example which is a great feature.
But is there a maximum number of value or any limit count ?

Thank you in advance for your answers.

**Comment by alexcrichton** [comment]
This is [currently defined by wasmparser](https://github.com/bytecodealliance/wasmparser/blob/75dc45ad26270ad77b7153a990c61e6be64397e5/src/limits.rs#L30) and the number of results looks to be 1000 max
