### ISSUE TITLE
Add a new method Linker::get_export(module,name).

### ISSUE THREAD

**Issue by aleksmelnikov** [bytecodealliance/wasmtime#1454]
#### Feature

I would like to change my code from:
```
    let module1 = Module::from_file(&store, "a.wasm")?;
    let instance1 = linker.instantiate(&module1)?;
    linker.instance("env", &instance1)?;
    let run = instance1.get_export("funca").and_then(|e| e.func()).unwrap();
    let run = run.get0::<()>()?;
    run()?;
```
to:
```
    let module1 = Module::from_file(&store, "a.wasm")?;
    let instance1 = linker.instantiate(&module1)?;
    linker.instance("env", &instance1)?;
    let run = linker.get_export("env","funca").and_then(|e| e.func()).unwrap();
    let run = run.get0::<()>()?;
    run()?;
```

#### Benefit

Get exports from one source (Linker).

#### Implementation

Add a new method Linker::get_export(module,name).

#### Alternatives

Please, see the existing solution above.

**Comment by alexcrichton** [comment]
Oh one thing I forgot about when originally thinking about this was that you can actually define the same name multiple times for different types. That would make this API a bit more complicated and we might have to solve it via one of two methods:

* Remove this feature from `Linker`. I'm not honestly sure how useful it is anyway.
* Change `Linker::get_export` to something like `Linker::get_func::<(i32, i32), (i32,)>(...)` where you specify types as input.

I think I'd honestly lean towards removing the ability to define the same name twice in the linker under different types. That feels overly complicated and not really necessary for most practical use cases.

**Comment by aleksmelnikov** [comment]
Basically, I wouldn't want that changing API will decrease functionality. It seems to me `Linker` stores function signatures (types). Right? So, theoretically can get a right function.

**Comment by alexcrichton** [comment]
It's possible, yeah, but we actually [wanted behavior like this](https://github.com/bytecodealliance/wasmtime/pull/1391#discussion_r397436128) in `Linker` before, and I don't really have strong reasons for the complications of allowing one definition per type, so I'd personally be fine at least removing the support.

**Comment by aleksmelnikov** [comment]
@alexcrichton , I think should be relied on your experience.

**Comment by alexcrichton** [comment]
I've made a proposal for an API in https://github.com/bytecodealliance/wasmtime/pull/1480

**Comment by aleksmelnikov** [comment]
@alexcrichton , very interesting improvements. Сan't wait to try to work with them. Thank you!
