### ISSUE TITLE
Cranelift: Build failure during testing caused by unnecessary braces

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#1458]
Thanks for opening a bug report! Please answer the questions below
if they're relevant and delete this text before submitting.

- What are the steps to reproduce the issue? Can you include a CLIF test case,
  ideally reduced with the `bugpoint` clif-util command?
- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?
- Which Cranelift version / commit hash / branch are you using?
- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)

Hi .. I am seeing test failures in the pr here: https://github.com/bytecodealliance/wasmtime/pull/819 but the failure is unrelated to the patch. Specifically it is failing to a warning about an unnecessary brace around an assignment in some code in cranelift:

![image](https://user-images.githubusercontent.com/45402135/78208125-72c9e700-7458-11ea-9aeb-54f33b0808fd.png)

When I run this on my target machine I see no such error so I can't reproduce. Furthermore it is unclear why the error for each line number is being printed out twice. Perhaps this is some testing configuration issue.

**Comment by jlb6740** [comment]
> 

Oh ... or perhaps there is a regression in nightly?

**Comment by bjorn3** [comment]
Nightly introduced a new lint. On CI `-Dwarnings` is passed, so the lint is set to deny instead of warn. Using `-Dwarnings` is excempt from the stability guarantees as otherwise it would be impossible to introduce new lints.

**Comment by bnjbvr** [comment]
Fixed by #1459, thanks for the patch!
