### ISSUE TITLE
clif-util: don't require a target when only doing wasm->clif translation (the -t flag)

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#1473]
Translating wasm into clif should not require a target, but right now it does:

```
$ cargo run -- wasm -tp ~/scratch/two-plus-five.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `/home/fitzgen/wasmtime/target/debug/clif-util wasm -tp /home/fitzgen/scratch/two-plus-five.wasm`
Error: the wasm command requires an explicit isa.
```

When the `-t` flag is passed, and therefore we are only doing wasm to clif translation, we should not require a `--target` flag.

**Comment by bjorn3** [comment]
The target is necessary to get the pointer size for things like reference types.

**Comment by abrown** [comment]
I think it would be nice to have a sane default here: if `--target` is not passed, try to use the host's native target. I've run into this several times in the past and it's annoying.

**Comment by alexcrichton** [comment]
The wasm subcommand has been removed from clif-util, so closing now.
