### ISSUE TITLE
Trap symbolication doesn't work after `Module` is dropped

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#1479]
Currently in the `wasmtime` crate a `Module` will [dynamically register](https://github.com/bytecodealliance/wasmtime/blob/1a2ecccbebb7e0aab8b292874c75734c5d058728/crates/api/src/instance.rs#L135) its unwinding information in [a global](https://github.com/bytecodealliance/wasmtime/blob/1a2ecccbebb7e0aab8b292874c75734c5d058728/crates/api/src/frame_info.rs#L14) which is unregistered [when a module is dropped](https://github.com/bytecodealliance/wasmtime/blob/1a2ecccbebb7e0aab8b292874c75734c5d058728/crates/api/src/frame_info.rs#L120-L126). This global is [used when inspecting a native backtrace](https://github.com/bytecodealliance/wasmtime/blob/1a2ecccbebb7e0aab8b292874c75734c5d058728/crates/api/src/trap.rs#L63-L65) to figure out which frames are wasm frames and which frames are native frames.

Unfortunately though instances and their exports can still be usable after a `Module` is dropped. For example you can continue to use a `Func` after the `Instance` and `Module` are dropped. This means, though, that traps aren't properly symbolicated and resolved to wasm modules after the `Module` is dropped though.

To fix this I think we'll need to tie the trap info registration to the `wasmtime_runtime::InstanceHandle` somehow rather than the `Module`.

**Comment by sunfishcode** [comment]
It doesn't seem safe to use a `Func` after its associated `Instance` has been dropped in general -- its `vmctx` parameter would dangle and any reference to memories, tables, or even imports would be unsafe. In what context does this come up?

**Comment by alexcrichton** [comment]
This program shows the error:

```rust
use wasmtime::*;

fn main() -> anyhow::Result<()> {
    let store = Store::default();
    let module = Module::new(&store, r#"(func (export "foo") unreachable)"#)?;
    let instance = Instance::new(&module, &[])?;
    let func = instance.exports()[0].func().unwrap().clone();

    println!("asserting before we drop modules");
    assert_trap(func.call(&[]).unwrap_err().downcast()?);
    drop((instance, module));

    println!("asserting after drop");
    assert_trap(func.call(&[]).unwrap_err().downcast()?);
    Ok(())
}

fn assert_trap(t: Trap) {
    assert_eq!(t.trace().len(), 1);
    assert_eq!(t.trace()[0].func_index(), 0);
}
```

the first assertion there passes but the second fails.

We keep an [`InstanceHandle` inside of `Func`](https://github.com/bytecodealliance/wasmtime/blob/1a2ecccbebb7e0aab8b292874c75734c5d058728/crates/api/src/func.rs#L139) which keeps the actual underlying instance alive even after you drop the `Instance` which keeps it at least memory safe.
