### ISSUE TITLE
Exposing functions from Rust to WASM

### ISSUE THREAD

**Issue by XBagon** [bytecodealliance/wasmtime#148]
I'm having a hard time figuring out how I would be able to expose a function to the VM, so I can call it from the wasm code. I found stuff like Imports and looked a bit into the code, ending up trying to write my own `Resolver`, but then failed to do it cause I'm really not sure how to create an `Export::Function` and then link it to a Rust function. The documentation is kinda confusing and the tutorials seem only to cover direct usage as a binary. I would appreciate help very much!

**Comment by sunfishcode** [comment]
Indeed this is something we are planning to support well, but it isn't very advanced yet. The best example we have right now is the WASI implementation in wasmtime-wasi/src/syscalls.rs.

**Comment by alexcrichton** [comment]
With the `wasmtime` crate this is now done with the `Func` API, and we're continuing to improve it over time as well!
