### ISSUE TITLE
Cranelift: express x86 callee-save FPR correctly

### ISSUE THREAD

**Issue by iximeow** [bytecodealliance/wasmtime#1497]
In `isa/x86/abi.rs`, callee-save FPRs are represented as `F64`. In the only ABI we currently support with callee-save FPRs, we preserve xmm registers, which should be written more specifically as `F64x2` or some other equivalently-sized type. `F64` gets correct codegen out at the moment, but some optimization that tries to be clever about only preserving the low 64 bits of a callee-save register might break this in the future. It also would make the code less surprising by removing a point of confusion for the reader :)

See [here](https://github.com/bytecodealliance/wasmtime/blob/4cca5100858cb7aa4bec9f68e80d3c309ae1007e/cranelift/codegen/src/isa/x86/abi.rs#L624-L626), [here](https://github.com/bytecodealliance/wasmtime/blob/4cca5100858cb7aa4bec9f68e80d3c309ae1007e/cranelift/codegen/src/isa/x86/abi.rs#L913), and [here](https://github.com/bytecodealliance/wasmtime/blob/4cca5100858cb7aa4bec9f68e80d3c309ae1007e/cranelift/codegen/src/isa/x86/abi.rs#L1038-L1040).

This was done at the time because of a missing `fstDisp8` encoding allowing a REX prefix. Such an encoding might have been added in the intervening time, so hopefully this is a very simple change.

**Comment by samrat** [comment]
Hello! I would like to take a stab at this issue. I'm fairly new to the codebase though, so I'll probably need to spend some time familiarizing myself with how codegen works in Cranelift.
