### ISSUE TITLE
Cranelift: clean up generated callee-save FPR code

### ISSUE THREAD

**Issue by iximeow** [bytecodealliance/wasmtime#1498]
In `isa/x86/abi.rs` we have to save callee-preserved FPRs for some calling conventions. We save these to the stack and reload them before exiting, but at the moment the Cranelift IR operations `stack_load` and `stack_store` are not directly encodable. In other parts of a function, `stack_load` and `stack_store` would be legalized and then optimized into the assembly we'd like (`movdqa [rsp + offset], xmm*`), but prologue/epilogue addition happen after both legalization and register allocation.

When `stack_load` and `stack_store` can be directly encoded, we can switch to those, remove an explicit `stack_address`, and simplify x86 callee-preserved FPR machinery. #1198 adds these encodings.

For more, see [this comment](https://github.com/bytecodealliance/wasmtime/blob/4cca5100858cb7aa4bec9f68e80d3c309ae1007e/cranelift/codegen/src/isa/x86/abi.rs#L899-L902) and [this comment](https://github.com/bytecodealliance/wasmtime/blob/4cca5100858cb7aa4bec9f68e80d3c309ae1007e/cranelift/codegen/src/isa/x86/abi.rs#L1024-L1028).

**Comment by bjorn3** [comment]
I think this is fixed with the new backend framework.
