### ISSUE TITLE
Wasm file traps with wasmtime

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#150]
[rustc_binary-wasmtime-149-repro.wasm.zip](https://github.com/CraneStation/wasmtime/files/3183851/rustc_binary-wasmtime-149-repro.wasm.zip) Edit: expected this issue to be number 149

This needs a nightly compiler, the `miri` component installed, the `x86_64-unknown-linux-gnu` target installed and having ran `cargo miri setup`. `MIRI_SYSROOT` refers to the path `cargo miri setup` eventually emits.

```
$ echo 'fn main() { println!("Hello world!"); }' > example.rs
$ wasmtime -g --dir . --dir $MIRI_SYSROOT rustc_binary.wasm -- example.rs --sysroot $MIRI_SYSROOT -Zcodegen-backend=metadata_only --target x86_64-unknown-linux-gnu
[...]
[2019-05-15T17:52:51Z INFO  rustc_mir::interpret::step] // bb1
[2019-05-15T17:52:51Z INFO  rustc_mir::interpret::step] StorageDead(_5)
[2019-05-15T17:52:51Z INFO  rustc_mir::interpret::step] _0 = const std::vec::SpecExtend::spec_extend(move _3, move _4) -> bb2
error while processing main module ../../target/wasm32-wasi/release/rustc_binary.wasm: Instantiation error: Trap occurred while invoking start function: wasm trap at 0x7fbd698e38df
```

When using wasmer with the `singlepass` backend it doesn't trap. (You need to build the `fix/wasi_path_filestat_get` branch of wasmer to fix a wasi compat problem)

**Comment by yurydelendik** [comment]
@bjorn3 I tried to reproduce the issue to see if #63 will help to troubleshot the issue. I'm getting the different crash:

```
...
[2019-07-12T18:52:44Z INFO  rustc_metadata::creader] resolving crate `extern crate std as std`
[2019-07-12T18:52:44Z INFO  rustc_metadata::creader] falling back to a load
filesearch: FileSearch { sysroot: "/home/yury/.cache/miri/HOST", triple: "x86_64-unknown-linux-gnu", search_paths: [], tlib_path: SearchPath { kind: All, dir: "/home/yury/.cache/miri/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib", files: ["/home/yury/.cache/miri/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib/&\x9Ag\u{4}IV\u{0}\u{0}\u{5}\u{0}\u{0}\u{0}IV\u{0}\u{0}\x98\xFE\xBF\u{f}\u{0}\u{0}\u{0}\u{0}\xFF\xFF\xFF\u{f}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}", "/home/yury/.cache/miri/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib/&\x9Ag\u{4}IV\u{0}\u{0}\u{5}\u{0}\u{0}\u{0}IV\u{0}\u{0}\x98\xFE\xBF\u{f}\u{0}\u{0}\u{0}\u{0}\xFF\xFF\xFF\u{f}\u{0}\u{0}", "/home/yury/.cache/miri/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib/&\x9Ag\u{4}IV\u{0}\u{0}\u{5}\u{0}", "/home/yury/.cache/miri/HOST/lib/rus
...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed

error while processing main module rustc_binary.wasm: Instantiation error: Trap occurred while invoking start function: wasm trap at 0x7f2563fa11c5
```

Can you perhaps create a new version of rustc_binary?

**Comment by bjorn3** [comment]
There seems to be corruption:

The path `/home/yury/.cache/miri/HOST/lib/rustlib/x86_64-unknown-linux-gnu/lib/&\x9Ag\u{4}IV\u{0}\u{0}\u{5}\u{0}\u{0}\u{0}IV\u{0}\u{0}\x98\xFE\xBF\u{f}\u{0}\u{0}\u{0}\u{0}\xFF\xFF\xFF\u{f}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}` should not contain random bytes.

**Comment by alexcrichton** [comment]
I've run across this issue and it's pretty old at this point and we've had a lot of changes in the meantime. I've tried reproducing this but so much has changed I'm getting lots of various kinds of errors. In any case today I can't quite see any form of corruption still around, so I'm going to close. If this crops up again we can certainly reopen though!

**Comment by bjorn3** [comment]
I rebuilt `rustc_binary.wasm` yesterday. It worked perfectly.
