### ISSUE TITLE
Cranelift: imax/imin ghost value

### ISSUE THREAD

**Issue by RobinTD** [bytecodealliance/wasmtime#1505]
Using cranelift 0.62, the following results in this error message:" v5 is a ghost value used by a real [Op1ret#c3] instruction".

```
function u0:82(i64) -> i64 system_v {
block0(v0: i64):
    v1 = load.i64 notrap aligned v0
    v2 = load.i64 notrap aligned v0+8
    v3 = iconst.i64 1
    v4 = iconst.i64 2
    v5 = imax v3, v4
    return v5
}
```

**Comment by bjorn3** [comment]
`imax` is only implemented for 128bit vectors with 8, 16 or 32bit lanes:

https://github.com/bytecodealliance/wasmtime/blob/428449133943213f2edc58ec161efcbb23d0eebd/cranelift/codegen/meta/src/isa/x86/legalize.rs#L634-L635

It makes sense to me to implement it for non-vectors too.

> v5 is a ghost value used by a real [Op1ret#c3] instruction

A ghost value is a value which is the output of an instruction without encoding, so this says that the `imax` which has `v5` as output doesn't have an encoding.

**Comment by RobinTD** [comment]
Thanks. `fmin`/`fmax` works for scalars, so making it work for integer scalars too would be less surprising.

**Comment by cfallin** [comment]
Closing in favor of #3370.
