### ISSUE TITLE
Cranelift ARM64 / AArch64 backend: support debug info

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#1523]
We need to propagate debug information through the new compilation pipeline in order to support several use-cases. For example, `wasmtime` needs this information to build a map from machine-code offsets to wasm bytecode offsets. Other use-cases may want to e.g. emit DWARF debug info in an AOT-compiled object output file.

Issue raised by @alexcrichton in the wasmtime context

cc @julian-seward1, @bnjbvr

**Comment by bnjbvr** [comment]
This seems sensible to do, at least for debug information. This was also required for Spidermonkey before using the regular sinks (see also #1453), so there's also the possibility here to add new sinks abstractions to handle this (if it is for every single instruction, this might be high overhead, though).

**Comment by repi** [comment]
Is this still an issue that one can't get debug info in the aarch64 backend (but works with x64 backend)?

**Comment by cfallin** [comment]
@repi I'm actually working on this as we speak :-)

There is partial unwind-info generation; this is (IIRC) enough for libunwind to traverse frames on the stack. But there's no DWARF info at the level that would (e.g.) map Wasm locals to registers/stack slots.

(It's a little tricky as it requires tracing the values through lowering and regalloc but there's a solution that *should* work involving marker instructions and a little post-lowering analysis.)

**Comment by cfallin** [comment]
(To be clear, the debuginfo stuff I'm working on is for both `MachInst` backends, not just aarch64.)

**Comment by repi** [comment]
Ah I see, thanks for the clarification! For our own use cases stack traces was the most critical, but general DWARF debug info will be great.

**Comment by akirilov-arm** [comment]
@cfallin What is the status of this issue? Unwinding works now, but what about some of the other functionality you mention (e.g. map Wasm locals to registers/stack slots)? I suppose the latter would not be implemented in AArch64-specific code anyway, so we should probably rephrase the issue a bit.

**Comment by bjorn3** [comment]
> I suppose the latter would not be implemented in AArch64-specific code anyway

All debuginfo generation requires code in the backend for the respective architecture to keep the mapping between the clif level input and the machine code level output for the respective debuginfo constructs. At least for value debuginfo the backend part is already implemented for AArch64 though I think.

**Comment by cfallin** [comment]
The general debuginfo support -- passing the correspondences through to the codegen and then computing the metadata -- works for new backends generally, as I had built that out and tested it on x86-64. However, IIRC, there are some x86-isms in the DWARF support code in the debug crate and so it probably needs a bit more work to fully connect the dots on aarch64. I don't have time to look into this at the moment, but would be happy to review PRs if someone else does.

**Comment by akirilov-arm** [comment]
I just noticed that some of the issues had been mentioned in issue #2856.

**Comment by cfallin** [comment]
I'm doing some issue gardening and I will go ahead and close this in favor of #2856, which subsumes this (the issue is really that some of the DWARF-handling is x86-specific).
