### ISSUE TITLE
Support MinGW as a wasmtime target

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#1535]
It looks like Go at least [only supports MinGW as a toolchain to link with](https://github.com/bytecodealliance/wasmtime-go/issues/3), but wasmtiem does not currently have MinGW support. If we'd like to support Windows support for Wasmtime in Go I think we'll need to add a MinGW target as well as CI/releases for it.

**Comment by tschneidereit** [comment]
Do you know how complicated that would be initially—and how much of a maintenance burden it'd be on an ongoing basis? If neither is a concern, this makes sense to me. Otherwise, I think we should let the be driven by use cases.

**Comment by tschneidereit** [comment]
Ah, I now see the wasmtime-go issue. I guess the question is how many people will want to run Go programs on Windows, which I don't have a good handle on.

**Comment by alexcrichton** [comment]
Oh sorry I should have clarified, but I definitely agree that we should let use cases and difficulty of implementation guide this in terms of priorities. I don't think it's clear how motivated this is right now (I don't know how often it'd be wanted on Go for Windows). I suspect this would be relatively difficult because of stack unwinding, but I might give this a go later today and see if it "trivially works" or "trivially doesn't work". Basically I think it's probably worth a little bit of effort to see how much effort it would take for us to support this.

**Comment by tschneidereit** [comment]
That makes a lot of sense to me, yes. Thank you for the clarification!

**Comment by alexcrichton** [comment]
Turns out that with https://github.com/bytecodealliance/wasmtime/pull/1490 all tests pass. I think there's probably some difference in how big the stack is when a segfault comes in which causes issues today, but once https://github.com/bytecodealliance/wasmtime/pull/1490 lands I can look into adding this to CI. Don't think it'll be too too hard!
