### ISSUE TITLE
problems building js-polyfill

### ISSUE THREAD

**Issue by jrandall** [bytecodealliance/wasmtime#154]
I get an error when I try to build the browser polyfill:
```
~/checkouts/wasmtime/wasmtime-wasi/js-polyfill$ ./build.sh 
error: Linking globals named 'rwlock_init': symbol multiply defined!
shared:ERROR: Failed to run llvm optimizations: 
```

I am using emscripten 1.38.31:
```
~/checkouts/wasmtime/wasmtime-wasi/js-polyfill$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.31 (commit 040e49ad1e084ab4c464a9ca098c49b8c7085ffe)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 ```

What version(s) of emscripten are known to work to build the polyfill?

**Comment by sunfishcode** [comment]
We're in the process of moving the WASI implementation from C to Rust, and the polyfill build script doesn't yet support Rust. We'll eventually fix that, but in the meantime I created a [polyfill branch](https://github.com/CraneStation/wasmtime/tree/polyfill/) to preserve the full C version, which should build with any reasonably recent version of Emscripten.

**Comment by jrandall** [comment]
Thanks! Is there a polyfill for the Rust-based implementation, and it just doesn't have a build script? Happy to `cargo build` something instead if that works.

**Comment by sunfishcode** [comment]
The plan is to port [the support code](https://github.com/CraneStation/wasmtime/tree/polyfill/wasmtime-wasi/js-polyfill) over to [wasi-common](https://github.com/CraneStation/wasi-common), which is written in Rust, and compile that with wasm32-unknown-emscripten. It'll need more work than just a `cargo build` to wire everything up, but in theory shouldn't be too crazy.

**Comment by bjorn3** [comment]
I think this can be closed now as the polyfill at https://wasi.dev/polyfill/index.html is gone.
