### ISSUE TITLE
What's the relationship/differences between wasm-c-api and wasi-sdk

### ISSUE THREAD

**Issue by leonwanghui** [bytecodealliance/wasmtime#1554]
Hi all, recently I'm going to develop a C/C++ app that can be built in WASM module, then adopted in `wasmtime` environment.

When I look through the [WebAssembly](https://github.com/webAssembly/) repository, there are two projects (`wasm-c-api` and `wasi-sdk`) listed. When I found wasmtime is relied to `wasm-c-api` to support WASM format, I have several questions listed below:
* What's the difference between wasm-c-api and wasi-sdk?
* Why wasmtime is relied on wasm-c-api rather than wasi-sdk to support WASI standard directly?
* Can wasmtime support the wasm-based app compiled with wasi-sdk?

Maybe I have some misunderstanding between these two projects, would be appreciated if anyone could offer some suggestion.

**Comment by bjorn3** [comment]
`wasi-sdk` is for programs that are compiled to wasm. `wasm-c-api` is for native programs to embed a wasm runtime.

**Comment by leonwanghui** [comment]
> Can wasmtime support the wasm-based app compiled with wasi-sdk?

@bjorn3 Thanks for clarification. Does that mean I can use wasmtime to run wasm compled with wasi-sdk? Is there some version compatible constraints on them?

**Comment by bjorn3** [comment]
> Does that mean I can use wasmtime to run wasm compiled with wasi-sdk?

Yes

> Is there some version compatible constraints on them?

As far as I know wasmtime supports all currently existing versions of WASI. In fact wasmtime is kind of the playground to implement new WASI api's.

**Comment by leonwanghui** [comment]
@bjorn3 Thanks a lot! I'll have a try recently : )
