### ISSUE TITLE
Cranelift `test_run` command doesn't print skipped tests

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#1558]
Extracting an issue from [this comment](https://github.com/bytecodealliance/wasmtime/pull/1526#discussion_r409827301), cc @abrown on this.

Currently cranelift tests will be skipped if they're executing code but the host platform can't execute the code (e.g. AArch64 on x86_64), but nothing is printed currently about this.

**Comment by abrown** [comment]
Note to self: take a look at this after #1517.
