### ISSUE TITLE
Possible backends

### ISSUE THREAD

**Issue by pepyakin** [bytecodealliance/wasmtime#156]
Now having the lightbeam backend being added, I am curious on what is the scope of this project. Will it be beneficial to add, say, `wasmi` backend (for ensuring correctness) or `llvm` for highly optimized builds?

**Comment by sunfishcode** [comment]
Yes, interpreters and additional compiling backends are in scope.

I haven't looked at what a wasmi backend in particular might look like yet, and it's likely that wasmtime-runtime will need some changes to support this, but that's one of the places we're interested in heading.

**Comment by ethanfrey** [comment]
Any update here?

I'm investigating switching to wasmtime as our wasm backend, and the cranelift AOT and light beam JIT pairs looks good. I did see a comment in the README about supporting interpreters and that would be nice for some situations, if we could swap that out so easily.

However, looking into the compiler strategies, it seems an enum of cranelift or light beam.

Am I correct that there is no wasm interpreter that works with wasmtime? And is there any tracking issue (besides this) with any plans? I would also be interested in wasmi support

**Comment by sunfishcode** [comment]
Yes, you're correct. I don't think we have a separate tracking issue, though I do know there are a lot of people are interested in interpreter support.

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14). I think we're still interested in new backends but they'll need to go through the RFC process, so I'm going to close this.
