### ISSUE TITLE
Don't set warnings as errors in Rust nightly builds in CI

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1588]
... because then it means that you can get a new compilation failure unrelated to a PR, just because you compiled on a day where a new warning had been introduced in Rust-nightly.

For instance: https://github.com/bytecodealliance/wasmtime/pull/1578/checks?check_run_id=614733207 which I can't locally reproduce, even after upgrading to latest Rustc nightly (i suspect this is because i'm using RLS and all, and so it skipped updating as there was a missing rustup component).

cc @alexcrichton

**Comment by tschneidereit** [comment]
I think this makes sense, yes. We should probably still keep warn-as-error for beta and release builds, meaning we would still get breakage unrelated to changes, but much more rarely.

If we don't have warn-as-error anywhere, I fear we'll quickly see a lot of warnings creep up, making it harder to discern things that should really be addressed from those we don't care about.

**Comment by alexcrichton** [comment]
[sounds good to me](https://github.com/bytecodealliance/wasmtime/pull/1589)!
