### ISSUE TITLE
Cranelift-wasm: tests fail on a clean checkout of `master`

### ISSUE THREAD

**Issue by cdisselkoen** [bytecodealliance/wasmtime#1595]
On a clean git checkout of wasmtime `master`, I'm getting test failures when running `cargo test` in the `cranelift/wasm` directory.  At a minimum, I'm getting failures in the tests `use_name_section`, `use_fallthrough_return`, and `testsuite`.  All three failures appear to be due to lacking support for riscv64, causing failures in the `unwrap`s on [this line](https://github.com/bytecodealliance/wasmtime/blob/6cd92f91328b538076f8d724ee2a205edf5b70fc/cranelift/wasm/tests/wasm_testsuite.rs#L60) or [this line](https://github.com/bytecodealliance/wasmtime/blob/6cd92f91328b538076f8d724ee2a205edf5b70fc/cranelift/wasm/tests/wasm_testsuite.rs#L94).

Am I doing something wrong / missing a step?  Do some crate features need to be enabled in order for tests to pass?  I got the same results with plain `cargo test` and with `cargo test --all-features`.

<details>
<summary>Detailed test output:</summary>

```
> cargo test --all-features
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running /usr/local/home/cdisselk/wasmtime/target/debug/deps/cranelift_wasm-42dfb56b7188030c

running 3 tests
test func_translator::tests::small2 ... ok
test func_translator::tests::small1 ... ok
test func_translator::tests::infloop ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /usr/local/home/cdisselk/wasmtime/target/debug/deps/wasm_testsuite-7a98d34c19ece58b

running 3 tests
test use_name_section ... FAILED
test use_fallthrough_return ... FAILED
test testsuite ... FAILED

failures:

---- use_name_section stdout ----
thread 'use_name_section' panicked at 'called `Result::unwrap()` on an `Err` value: SupportDisabled', cranelift/wasm/tests/wasm_testsuite.rs:60:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- use_fallthrough_return stdout ----
thread 'use_fallthrough_return' panicked at 'called `Result::unwrap()` on an `Err` value: SupportDisabled', cranelift/wasm/tests/wasm_testsuite.rs:94:15

---- testsuite stdout ----
=== ../wasmtests/arith.wat ===
thread 'testsuite' panicked at 'called `Result::unwrap()` on an `Err` value: SupportDisabled', cranelift/wasm/tests/wasm_testsuite.rs:94:15


failures:
    testsuite
    use_fallthrough_return
    use_name_section

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test wasm_testsuite'
```
</details>

Tested on both macOS and Linux, on x86_64, with Rust 1.43.0.  Wasmtime commit `6cd92f913`.

**Comment by bnjbvr** [comment]
Thanks for opening an issue! I suspect that when run in automation, we run it from an higher-up directory, which will select the feature that enables codegen support for all the architectures. So if tested independently, it might not work; but tested with the rest of Cranelift, it should work fine. Probably the fix is to enable the riscv codegen backend for testing.
