### ISSUE TITLE
Implement real jump tables

### ISSUE THREAD

**Issue by pepyakin** [bytecodealliance/wasmtime#16]
There is this panic

https://github.com/CraneStation/wasmtime/blob/c5f0cd7d5e350afe4dd2d18e8efc009ad7f1eae3/lib/environ/src/compilation.rs#L66-L73

what is this about? I've tried to use a simple `br_table` with a few arms and it seems to work fine.

**Comment by sunfishcode** [comment]
br_table is currently implemented by lowering it into a bunch of conditional branches. #453 is working on implementing it with an actual jump table.

**Comment by pepyakin** [comment]
Cool, thanks for the info! So then we need to implement relocating jump tables after they land in cranelift: https://github.com/CraneStation/cranelift/pull/453.

I will update this issue and https://github.com/CraneStation/wasmtime/issues/14

**Comment by pepyakin** [comment]
I believe this is implemented.
