### ISSUE TITLE
Is there any networking example?

### ISSUE THREAD

**Issue by jjeffcaii** [bytecodealliance/wasmtime#1602]
Hi~
I want to do some networking program in WASI, but I don't know how to get start.
Is there any networking examples? (eg: TCP connect/listen)

Thanks!

**Comment by kubkon** [comment]
Hi! Since networking has not yet been fully fleshed our by the WASI Community Group, it’s currently not supported by WASI or Wasmtime. Have a look [here] to learn more about what’s currently supported the WASI spec.

[here]: https://github.com/webassembly/wasi

**Comment by jjeffcaii** [comment]
Thanks!
