### ISSUE TITLE
Execute wasm file in NodeJS

### ISSUE THREAD

**Issue by Gregoirevda** [bytecodealliance/wasmtime#161]
I'd like to expand the tutorial on how to run the wasm file in NodeJS after running it with wasmtime.

Normally you can simply run `WebAssembly.instantiate(buf)`, but here the demo.c contains arguments input.txt and output.txt.
The WebAssembly requires a `wasi_unstable` object and within that a `fd_prestat_get` function, but I don't know how it should look like...

`index.js`
```js
const fs = require('fs');
const buf = fs.readFileSync('./demo.wasm');

(async () => {
  const res = await WebAssembly.instantiate(buf, {wasi_unstable: {fd_prestat_get: () => {}}});

  console.log(res.instance);
})();
```

**Comment by bjorn3** [comment]
https://github.com/devsnek/node-wasi may be what you want.

**Comment by Gregoirevda** [comment]
Thanks @bjorn3 

I managed to run the wasm package, but get into the first error defined in the `demo.c` file 
`usage: (null) <from> <to>`

You know how to pass params to wasm main function?

```js
const WASI = require('wasi');
const fs = require('fs');

const buf = fs.readFileSync('./demo.wasm');

const wasi = new WASI({
  // preopenDirectories: { '.': '.' },
});

(async () => {
  let res = await WebAssembly.instantiate(buf, {
    wasi_unstable: wasi.exports
  });
  wasi.setMemory(res.instance.exports.memory);

  res.instance.exports._start("./input.txt", "output.txt");
})()
```

**Comment by bjorn3** [comment]
https://github.com/devsnek/node-wasi/blob/68902020ce28210ab1fc12dfaec090ef82c44263/index.js#L507

It seems like you can use `new WASI({ args: ["arg1", "arg2"] })` to pass args.

**Comment by Gregoirevda** [comment]
It's overriding the 1st arg, so I tried passing the wasm executable path and the 2 other args
`args: ["fullpath/demo.wasm", "input.txt", "output.txt"]`

but getting
```
TypeError: wasm function signature contains illegal type
    at openat (wasm-function[24]:318)
    at open (wasm-function[26]:114)
    at main (wasm-function[15]:209)
    at _start (wasm-function[14]:405)
    at /wasi/index.js:19:24
```

Line 19 `res.instance.exports._start()`

**Comment by devsnek** [comment]
@Gregoirevda you'll need to run it with `node --experimental-wasm-bigint`

**Comment by Gregoirevda** [comment]
I managed to make it work with path.resolve

```
js
const WASI = require('wasi');
const fs = require('fs');
const path = require('path');

const buf = fs.readFileSync('./demo.wasm');

const wasi = new WASI({
  preopenDirectories: { '.': '.' },
  args: [path.resolve(__dirname, "test.wasm"), path.resolve(__dirname, 'test.txt'), path.resolve(__dirname, 'output.txt')]
});

(async () => {
  let res = await WebAssembly.instantiate(buf, {
    wasi_unstable: wasi.exports
  });

  wasi.setMemory(res.instance.exports.memory);
  res.instance.exports._start();
})()
```

I'm getting the next error `error opening input /Users/gvanderauw001/dev/workshop/wasi/test.txt: Capabilities insufficient`

Is there a way to give capability with WASI like
`wasmtime --dir=. --dir=/tmp demo.wasm test.txt /tmp/somewhere.txt`?

**Comment by bjorn3** [comment]
> Is there a way to give capability with WASI like
> `wasmtime --dir=. --dir=/tmp demo.wasm test.txt /tmp/somewhere.txt?`

That's what `preopenDirectories` does: `preopenDirectories: { '.': '.', '/tmp': '/tmp' },`

**Comment by Gregoirevda** [comment]
@bjorn3 both input.txt and output.txt are in the same folder. I tried passing `.`, `./`, `{__dirname}` without success...

**Comment by Gregoirevda** [comment]
What are key:value used for?

**Comment by devsnek** [comment]
`pathForWasi: realPath`

e.g. if you wanted to expose `./project/sandbox` as `/` to wasi you would do `'/': './project/sandbox'`

**Comment by Gregoirevda** [comment]
Same error with stdio

**Comment by bjorn3** [comment]
I think this can be closed. It isn't related to Cranelift or Wasmtime.
