### ISSUE TITLE
Cranelift aarch64: support reference types

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#1617]
This will imply some work in `regalloc.rs` to tell where spilled ref-typed values might be, and some integration in the new backend.

cc @julian-seward1 @cfallin

**Comment by bjorn3** [comment]
> This will imply some work in regalloc.rs to tell where spilled ref-typed values might be

Also for refs stored in registers, right?

**Comment by bnjbvr** [comment]
> Also for refs stored in registers, right?

Eventually yes, but we don't require it in the short term at least in Spidermonkey, which scans the stack only at times where everything has been spilled onto the stack. (I wonder if that was accidentally working with the old regalloc, because it would inefficiently spill callee-preserved registers across a call...)

**Comment by julian-seward1** [comment]
Sure; this will require tracking which `VirtualRange`s are ref-typed, or something like that.  It might turn into a whole barrel of fun once we take into account copy coalescing, too.

**Comment by bjorn3** [comment]
It would be nice to immediately do the more general version of tracking which `Value` is stored where. That is necessary to implement debuginfo for locals.

**Comment by cfallin** [comment]
Closing now, given that #1852 and subsequent bugfixes have landed; #1886 will track the wasmtime-specific work (which seems mainly to involve getting the right debug-info bits in place for the stack walk to work).
