### ISSUE TITLE
Support Emscripten

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasmtime#1641]
#### Feature

It would be nice if **wasmtime** add support applications that compiled with _Emscripten Toolchain_

#### Benefit

It would be possible to run application compiled with _Emscripten_

#### Alternatives

There are other run-time that support _WASI_, but it also supports _Emscripten_ like https://github.com/wasmerio/wasmer

**Comment by tschneidereit** [comment]
We explicitly decided not to support the Emscripten ABI in Wasmtime. The [WASI announcement post](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/) contains an explanation of the important differences, and in particular the safety guarantees that WASI runtimes can make.

The most important reason for not also supporting the Emscripten ABI is that as soon as a runtime also supports an ABI that doesn't make those guarantees, you can no longer trust any content executed by that runtime in the same way.

I'll close this issue, and hope this explanation makes sense!

**Comment by redradist** [comment]
@tschneidereit It would be possible to add ability to run Emscripten Application only if user run with special flag:
```
wasmtime app.wasm --emscripten
```
And by default application works safely ...

**Comment by tschneidereit** [comment]
That'd be a theoretical option, but a) it'd amount to a global switch making everything insecure, which we don't think is a good idea, and b) the ABI has other issues, as described in the post I linked to, so it's not just the security issue that made us decide not to support it.
