### ISSUE TITLE
Binfmt and argument passing

### ISSUE THREAD

**Issue by ghost** [bytecodealliance/wasmtime#1655]
I registered wasmtime to binfmt by adding config file to /etc/binfmt.d

*/etc/binfmt.d/wasmtime.conf*
`:wasm32-wasi:M::\x00asm:\xff\xff\xff\xff:/usr/local/bin/wasmtime:`

But i can see there are some problems, for example with passing arguments.

For example

`./app.wasm --help` opens Wasmtime's help, not the command ones.

But `./app.wasm -- --help` works fine.

I did an workaround:

```bash
#!/bin/bash
/usr/local/lib/wasmtime $1 -- ${*:2}
```
but it isn't an elegant solution.

Some possibility to create an official binfmt?

**Comment by sunfishcode** [comment]
One of the things that make this tricky is that Wasmtime currently needs --dir and/or --mapdir flags to pass in pre-opened directories to allow the program to access files. So even if we had a binfmt entry which added `--`, it wouldn't handle directory permissions unless we set up preconfigured directories to grant, but that's even less elegant, and goes against the spirit of WASI. We have plans to make the command-line easier to use which will address this, and then we'll be able to address the `--` issue at the same time.

**Comment by alexcrichton** [comment]
I'm going to close this since I don't think there's anything actionable for Wasmtime to implement for now. With features like the typed main proposal and such this may become more viable over time, but otherwise using Wasmtime for binfmt support is unlikely to be the best idea.
