### ISSUE TITLE
Can't mutate state from Funcs passed as wasm imports

### ISSUE THREAD

**Issue by J0eCool** [bytecodealliance/wasmtime#1678]
Trying to build a graphical application using the wasmtime Rust API, using the [sdl2 crate](https://docs.rs/sdl2/0.34.0/sdl2/), I run in to the issue that SDL's drawing methods take a mutable reference to the screen, and using those from a closure passed to `Func::wrap` gives me the error

> error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnMut`

#### Feature

Let the closure argument to `Func::wrap` derive from `FnMut` instead of `Fn`

#### Benefit

This should allow embedder applications more freedom to build wasm modules that interact with the outside world in stateful ways

**Comment by alexcrichton** [comment]
Thanks for the report! This is required for safety when using wasm modules, however, so it's not something that we can fix. Host functions can be called recursively if they, for example, reenter wasm and then get called again.

You can get mutation through interior mutability in Rust, however, for example through `RefCell` or `Cell`.
