### ISSUE TITLE
Increase maximum alignment for data objects

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#1691]
#### Feature

Currently an `u8` is used to represent the alignment. This means that the biggest power of two that fits in the alignment specifier is 128 bytes. I propose to use at least an `u16` for alignment.

#### Benefit

A rustc test depends on 256 byte alignment. There is also code that requires much bigger alignments like 4096 bytes or even bigger.

#### Implementation

Replace `u8` with `u16` to specify alignment in `cranelift-module`.

#### Alternatives

None

**Comment by julian-seward1** [comment]
Could you leave it as `u8` and reinterpret it to be log2 of the required alignment?  That would restrict the expressable alignments to powers of 2 ; is that a problem?

**Comment by bjorn3** [comment]
That would also work. I don't think any object file format supports non power of 2 alignments anyway.
