### ISSUE TITLE
Implement custom [de]serialization for `IntegerInterner`

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#1705]
Right now we use `derive(Serialize, Deserialize)` but this results in some unnecessary data being [de]serialized: the `map` member.

Instead, if we implement [de]serialization by hand, we can serialize the interned integers in order of their id and then recreate the `map` member on the fly during deserialization. This is what we do for the `PathInterner`, for example.

This would result in smaller serialized automata generated by peepmatic.

**Comment by declanvk** [comment]
@fitzgen 

Hello, I was interested in `peepmatic` and I saw this category of issues, so I thought I would attempt some of the easier ones.

I have a PR for this issue (#1944). If more PRs in this area would be welcome/un-welcome, please let me know.

**Comment by fitzgen** [comment]
Hi @declanvk! Glad to hear of your interest. Yes, more PRs are very welcome, thanks :)
