### ISSUE TITLE
wasi-common: cannot use file handles for `WasiCtxBuilder::std[in|out|err]`

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime#1735]
It appears that #1561 regressed `WasiCtxBuilder::stdin`, `WasiCtxBuilder::stdout`, and `WasiCtxBuilder::stderr` because it is [using `OsOther`](https://github.com/bytecodealliance/wasmtime/blob/master/crates/wasi-common/src/ctx.rs#L372) which will error with [invalid argument](https://github.com/bytecodealliance/wasmtime/blob/master/crates/wasi-common/src/sys/unix/osother.rs#L17) when given a file handle.

cc @kubkon.

This caused a [CI failure in the .NET implementation](https://github.com/bytecodealliance/wasmtime-dotnet/runs/694789903?check_suite_focus=true) that I hadn't had time to look into the last few days.

Unfortunately, there's a test coverage hole in Wasmtime CI where only a pipe handle was used for these functions, which is why the regression wasn't caught (`OsOther` works fine for pipes).

**Comment by kubkon** [comment]
Oh shoot, it seems that my refactoring regressed a lot more than expected, sorry about that! I’ll have a look ASAP and also will try figure out an additional test. Thanks for the report @peterhuene!

**Comment by kubkon** [comment]
Just out of curiosity, would #1600 fix this issue for you?

**Comment by peterhuene** [comment]
From a quick glance, I don't think it would, as the .NET API goes through the WASI C API, which [remains using `OsOther`](https://github.com/bytecodealliance/wasmtime/pull/1600/files#diff-f031dfa47983d0510bdad12a13d636e9R253-R267).

I was thinking of a more specific fix to where we currently handle `PendingEntry::OsHandle` to support either a file handle or an other handle, ala https://github.com/peterhuene/wasmtime/commit/21b0d6e27ccf5d19eee43f921f7898e960f005a0.  It does incur an extra stat to see what type of handle it is, though.

**Comment by peterhuene** [comment]
Breaking change to the Rust API aside, I think if we changed those to `OsFile`, your approach would work.  Th C API is only accepting paths to files.

**Comment by kubkon** [comment]
Since #1600 landed, I’m closing this one. Feel free to reopen it though if you feel it’s not been fully fixed @peterhuene!
