### ISSUE TITLE
Cranelift: AND/OR expressions for ISA predicates

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#1766]
#### Feature

Add the ability to link `SettingPredicateNumber`s with AND and OR.

#### Benefit

When passing around `SettingPredicateNumber`s (i.e. the identifiers for CPU features), I do not see a way to create an OR expression for various CPU features. This functionality is available for `InstructionPredicationNode`s (which are used in, e.g., `EncodingBuilder::inst_predicate`), but not for `SettingPredicateNumber`s (which are used in, e.g., `EncodingBuilder::isa_predicate`). Since some encodings are present under more than one CPU feature, it would be good to be able to express this.

#### Implementation

Unsure, but:
 - perhaps there is a way to unify the `inst_` and `isa_` predicates?

#### Alternatives

I don't yet see any.

**Comment by abrown** [comment]
cc: @bnjbvr, @iximeow, @sunfishcode

**Comment by abrown** [comment]
Needed in order to add correct predicates for [`VPMULLQ`](https://github.com/bytecodealliance/wasmtime/blob/4ec16fa057774dcd0d82dce05f8160689f0fe050/cranelift/codegen/meta/src/isa/x86/encodings.rs#L2091) eventually [`VCVTTUDQ2PS`](https://github.com/bytecodealliance/wasmtime/pull/1765/commits/7baedd9d65437b495a56a5d19239b4f0c0da06ba#diff-fe2a612bc8d9beb9107cd41f353e61d5R1878)

**Comment by bnjbvr** [comment]
It's a bit hidden, but I think you can already do this: does something like this work for your use case? https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/codegen/meta/src/isa/x86/settings.rs#L54

**Comment by bjorn3** [comment]
I don't think this is necessary anymore for the new backend framework.
