### ISSUE TITLE
update

### ISSUE THREAD

**Issue by flipchan** [bytecodealliance/wasmtime#1806]
Please update bumpalo since version less then 3.2.1 is unstable 

https://github.com/bytecodealliance/wasmtime/blob/a76639c6fb65b3c8427a9f382443fe3b56fd17d1/cranelift/peepmatic/crates/runtime/Cargo.toml

Links:
https://rust.firosolutions.com/paste/e4Q9jYY3eHoSxVUlpIc2Mmzj9RvhwxZ9SGngoQLR4
https://rustsec.org/advisories/RUSTSEC-2020-0006.html

**Comment by bjorn3** [comment]
`bumpalo 3.2.1` is semver compatible with the required `bumpalo 3.2.0`, so just updating the `Cargo.lock` of the user of Cranelift will be enough to use `bumpalo 3.2.1` or later. The `Cargo.lock` of Wasmtime already specifies `bumpalo 3.4.0`.

**Comment by alexcrichton** [comment]
Thanks for the reported, but as @bjorn3 mentioned we should be covered here. Projects using wasmtime will pull in the latest bumpalo and we're already using a fixed version too.

**Comment by flipchan** [comment]
awesome
