### ISSUE TITLE
No support for unsigned types in external functions

### ISSUE THREAD

**Issue by olonho** [bytecodealliance/wasmtime#1829]
When using `Linker.func` with function with signature `fn(u64, u64) -> i32` get this error

the trait wasmtime::func::IntoFunc&lt;_, _&gt; is not implemented for fn(u64, u64) -> i32 

It is important to use unsigned types in external functions in many cases.

**Comment by alexcrichton** [comment]
I think this was added pretty recently in https://github.com/bytecodealliance/wasmtime/pull/1808, mind trying that out and seeing if that works for you?

**Comment by alexcrichton** [comment]
I believe this has since been added so closing.
