### ISSUE TITLE
provide a download

### ISSUE THREAD

**Issue by Horcrux7** [bytecodealliance/wasmtime#187]
Please provide a download of Wasmtime. A download of a nightly build would be nice. Ideally for different platforms.

**Comment by tschneidereit** [comment]
We now have [downloads](https://github.com/CraneStation/wasmtime/releases) automatically deployed to github for every new commit to the `master` branch.

**Comment by sunfishcode** [comment]
We should add a link to the README.md pointing people to the download site.

**Comment by alexcrichton** [comment]
The readme now points to wasmtime.dev which has the install script, so I think we're good to go!
