### ISSUE TITLE
Cranelift: doesn't compile in nightly because of staticvec

### ISSUE THREAD

**Issue by pventuzelo** [bytecodealliance/wasmtime#1877]
Build is broken using  latest nightly due to staticvec. A new version of staticvec have been release.
see https://github.com/slightlyoutofphase/staticvec/issues/37 for more info.

**Comment by bjorn3** [comment]
Cranelift doesn't depend on `staticvec`, only Lightbeam does: https://github.com/bytecodealliance/wasmtime/blob/60d55a3483165c0b31503edebab5ce8c0294990c/Cargo.lock#L1102-L1119

**Comment by slightlyoutofphase** [comment]
I opened [a pull request](https://github.com/bytecodealliance/wasmtime/pull/1878) to update lightbeam's dependency to 0.10, which fixes this problem. 

Sorry this has happened though... I honestly did not see it coming / expect it at all. The language functionality I was using in 0.9 that got broken had been working flawlessly for months, and to me seemed like an entirely safe bet.

**Comment by pventuzelo** [comment]
Thanks @slightlyoutofphase

**Comment by slightlyoutofphase** [comment]
No problem!

**Comment by alexcrichton** [comment]
I believe this has now been addressed, so closing.
