### ISSUE TITLE
wasmtime: support reference types on aarch64

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#1886]
I think this should mostly Just Work after https://github.com/bytecodealliance/wasmtime/issues/1617 lands, but we also need to remove these `cfg`s (and make sure the tests pass, ofc):

* https://github.com/bytecodealliance/wasmtime/blob/647d2b423131c533af57e59e98928ca5d1f6887e/build.rs#L214-L216

* https://github.com/bytecodealliance/wasmtime/blob/647d2b423131c533af57e59e98928ca5d1f6887e/tests/all/main.rs#L22-L24

**Comment by cfallin** [comment]
For tracking purposes: the initial support for the ref values and opcodes themselves is in the WIP PR #1852, and @julian-seward1 and I are working out the safepoints story from the regalloc.rs and isel sides respectively. We should have at least an initial version done in the next few weeks.

We're pushing things forward for the SpiderMonkey use-case and planning to test there, so I'll be interested to see how we interface with `wasmtime`'s new reftypes support you've been building. The stackmaps interface will likely need a bit of finessing but I'm happy to work that out once we get there.

**Comment by fitzgen** [comment]
Thanks for the update @cfallin!

FYI we now have `test stackmaps` support in filetests now too, so that should hopefully make testing in-tree a little easier for you:

* https://github.com/bytecodealliance/wasmtime/blob/master/cranelift/filetests/src/test_stackmaps.rs
* https://github.com/bytecodealliance/wasmtime/tree/master/cranelift/filetests/filetests/stackmaps

The stack maps interfaces definitely need a little finessing (one example off the top of my head would be to have "semantic" methods rather than just exposing the inner bit map directly and expecting callers to figure out how to interpret that; also I suspect we can do better than iterating over every word in the frame and have an iterator over only the live refs instead).

As long as everything remains SP-relative, then I think Wasmtime should be fine (getting SP portably and reliably is *much* easier than getting the CFA with libunwind).

**Comment by cfallin** [comment]
Fixed by #2410.
