### ISSUE TITLE
Unable to disable default features in Wasmtime dependencies

### ISSUE THREAD

**Issue by mbestavros** [bytecodealliance/wasmtime#189]
I am interested in building Wasmtime against a Cranelift with all architectures disabled except for the target architecture.

From my research, it seems that the way to accomplish this would be to [re-export](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) the desired architecture feature in Wasmtime's `cargo.toml`:

`riscv = ["cranelift-codegen/riscv"]`

(For reference, the feature belongs to `cranelift-codegen`, whose features can be found in [its `cargo.toml` file](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/Cargo.toml).)

However, `cranelift-codegen`'s [default configuration](https://github.com/CraneStation/cranelift/blob/0a5961c9fe2d74621807924768882a7485d1c80b/cranelift-codegen/Cargo.toml#L32) enables all architectures to begin with, so in order to re-apply only the desired one, I would need to disable the default features in Cranelift and then enable only the desired one by re-exporting the feature, as outlined above.

The Rust-official method to accomplish this is to use the `--no-default-features` flag, as outlined [here](https://doc.rust-lang.org/cargo/reference/manifest.html#usage-in-end-products). However, as I discovered today, [the Wasmtime repository is set up as a workspace](https://github.com/CraneStation/wasmtime/blob/6b7ebfdddc28bfd1664a81038a84a3669efca200/Cargo.toml#L47) (rather than a package), and [the flag is non-functional on workspaces](https://github.com/rust-lang/cargo/issues/4753) -- it only works on packages.

`cranelift-codegen` is not a workspace by itself, so I also tried using the inline `default-features = false` option (example of that [here](https://github.com/camallo/dkregistry-rs/pull/96/files)); however, that didn't seem to work either.

Given this seems to be an upstream issue, I was wondering if there would be any guidance around this at all.

**Comment by alexcrichton** [comment]
One important thing to note as well here is that Cargo unions dependencies for crates, and by default all dependency edges enable the `default` feature. That means to disable a default feature then every single crate depending on another must disable the `default` feature. I think that may be why inline `default-features = false` didn't work perhaps?

FWIW this practically means that heavily depended on crates (those with a good number of incoming dependency edges) are very difficult to disable default features. If that's the case it may best to not actually enable any architectures by default in cranelift-codegen and instead allow top-level projects to specify. (and perhaps having a feature for `all-architectures` or something like that).

I think overall there's two possible solutions here:

* Leave all architectures enabled by `default`, but all crates depending on `cranelift-codegen` (and transitively) need to disable default features and then reexport the feature necessary to enable each architecture. 
* Instead remove the `default` feature from `cranelift-codegen` and replace it with a non-default "enable everything" feature, and then require crates to enable at least one feature to enable a backend.

**Comment by npmccallum** [comment]
@alexcrichton There might be a third option. My intuition tells me that it is not a good one, but I can't put my finger on why. Maybe you could clarify this.

We could write a `build.rs` which detects whether or not any architecture features are manually defined. If some are defined, the `build.rs` would do nothing. If none are defined, it could manually enable default options.

**Comment by alexcrichton** [comment]
Ah unfortunately I don't think that would be possible because `build.rs` would presumably be written in `cranelift-codegen` but doesn't have access to the `Cargo.toml` of all files depending on `cranelift-codegen`. A `build.rs` file knows that features are activated, but it doesn't know how features are activated.

**Comment by mbestavros** [comment]
Option 2 seems like the ideal way forward (from our point of view, at least); it would definitely simplify things for us. I think it also fits better with Rust's idea that "features should be additive".

**Comment by chaozju** [comment]
@mbestavros 
Does this mean Wasmtime is available for riscv-cross-compiling? THX

**Comment by bjorn3** [comment]
While Cranelift has basic risc-v support, it is nowhere near complete enough to be usable with Wasmtime.

**Comment by bjorn3** [comment]
This has been fixed by https://github.com/bytecodealliance/cranelift/pull/853, right?

**Comment by cfallin** [comment]
I believe so; and the crate and feature structure has changed so much in the past five years anyway that any current problems can have new issues filed.
