### ISSUE TITLE
wasm2obj: exported function names

### ISSUE THREAD

**Issue by cdisselkoen** [bytecodealliance/wasmtime#1940]
Not sure if this is a bug, my own user error, or just a not-implemented-yet.

I have the following minimal Wasm example (hello.wat):
```wasm
(module
  (func (export "helloFunc") (result i32) (i32.const 42))
)
```

`wasm2obj` seems to not respect the declared export function name:
```bash
(Linux)
> wasmtime wasm2obj hello.wat hello.o
> nm hello.o
0000000000000000 D _vmcontext_init
0000000000000000 T _wasm_function_0
```

```bash
(macOS)
> wasmtime wasm2obj hello.wat hello.o
> nm hello.o
000000000000000e D __vmcontext_init
0000000000000000 T __wasm_function_0
```

Instead of `_wasm_function_0`, I was expecting `helloFunc`.

This behavior is still the same with the following `hello.wat` declaring the export a different way:
```wasm
(module
  (func (result i32) (i32.const 42))
  (export "helloFunc" (func 0))
)
```

I've tested this on Wasmtime `master` as of this writing, which is commit c91a9313b.  As shown above, I observed this behavior on both Linux and macOS.

**Comment by abrown** [comment]
@yurydelendik?

**Comment by cdisselkoen** [comment]
Not knowing what I'm doing, my first attempt to fix this (https://github.com/PLSysSec/wasmtime-blade/commit/7494c43099831d581f78909cc5ad13bbf62ec39f) failed to make any difference in my testing.

**Comment by yurydelendik** [comment]
> Not sure if this is a bug, my own user error, or just a not-implemented-yet.

There is no specification in which form wasm2obj shall produce its output. Currently, wasmtime just packages machine code into object file containers, and adds unique symbols (such as "_wasmtime_0") to mark starts of the functions. AFAIK wasm2obj is used only by developers to troubleshot internals of wasmtime and no intent to be used by end user.

**Comment by cdisselkoen** [comment]
Sure, that sounds reasonable.  In that case I can close this issue as it sounds like it's out of scope?

I think Lucet will probably be the tool I'm looking for, even for simple examples (non-WASI code, no external calls).

**Comment by yurydelendik** [comment]
> In that case I can close this issue as it sounds like it's out of scope?

Yes. Also you may just re-purpose this issue as feature request -- I expect we change the behavior of wasm2obj to be more user friendly.

**Comment by cdisselkoen** [comment]
Ok, I will leave this as-is then and let maintainers choose whether to close or edit to a feature request.

**Comment by bjorn3** [comment]
Wasm2obj has been deleted in favor of `wasmtime compile`, so this can be closed I think.

**Comment by akirilov-arm** [comment]
Yes, but `wasmtime compile` could be similarly affected - @alexcrichton, any opinion?

**Comment by alexcrichton** [comment]
The format of the ELF with `wasmtime compile` isn't a public implementation detail so it's not intended to be consumed elsewhere, so because it's purely an implementation detail I'm gonna close this. Eventually we'll want a public-facing object-file format, but this will almost surely be addressed in such an implementation.
