### ISSUE TITLE
Can't debug on macOS Catalina (LLDB)

### ISSUE THREAD

**Issue by hardfist** [bytecodealliance/wasmtime#1953]
I following the instruction in this article https://hacks.mozilla.org/2019/09/debugging-webassembly-outside-of-the-browser/,
it works fine for gdb on macos and lldb on linux, but it does not works well for lldb on macos
I try the following ways, but all failed, 
* codesign lldb
* build lldb using  `-DLLDB_USE_SYSTEM_DEBUGSERVER=ON`
can someone give me an example on how to debug on macOS using lldb

**Comment by yurydelendik** [comment]
> it works fine for gdb on macos and lldb on linux
> can someone give me an example on how to debug on macOS using lldb

The only difference between linux and macos is default state of "plugin.jit-loader.gdb.enable" settings. You can add `settings set plugin.jit-loader.gdb.enable on` to ".lldbinit" or beginning of the lldb session. This setting was added in lldb version 9. Other than that, linux and macosx behavior shall be almost identical.

**Comment by hardfist** [comment]
> > it works fine for gdb on macos and lldb on linux
> > can someone give me an example on how to debug on macOS using lldb
> 
> The only difference between linux and macos is default state of "plugin.jit-loader.gdb.enable" settings. You can add `settings set plugin.jit-loader.gdb.enable on` to ".lldbinit" or beginning of the lldb session. This setting was added in lldb version 9 (see e.g. brew's one). Other than that, linux and macosx behavior shall be almost identical.

Thank you, It works now, but it seems not working in vscode when using `https://github.com/vadimcn/vscode-lldb` plugin

**Comment by hardfist** [comment]
oh, after setup `initCommands` , it works now

**Comment by yurydelendik** [comment]
Closing as resolved
