### ISSUE TITLE
Relocation of memory.grow and memory.size

### ISSUE THREAD

**Issue by mrowqa** [bytecodealliance/wasmtime#199]
As we discussed with @sunfishcode, after merging https://github.com/CraneStation/wasmtime/pull/194 there's probably no need for `{Imported,}Memory32{Grow,Size}` in [RelocationTarget](https://github.com/CraneStation/wasmtime/blob/c80508c8a9aba77a490f4f513c6ec32520acc904/wasmtime-environ/src/compilation.rs#L110-L126), or at least the tests pass. However, there are is an idea for having a command line setting which allows user to choose between fast startup using cache and less relocations, or better performance paying extra time for compilation and relocation. The mentioned code hasn't been deleted and it's just a tracking issue.

**Comment by kubkon** [comment]
Oooh I do like the idea of having a command line argument which would allow the user to choose between a fast startup but poorer performance, and better performance but slower startup. So a definite +1 for that from me :-)

**Comment by pepyakin** [comment]
I wonder if this requires dedicated flags or it could be generalized as, bikeshedingly, `--fast-start`/`--more-performace`.

**Comment by alexcrichton** [comment]
Thes relocations ended up getting removed in https://github.com/bytecodealliance/wasmtime/pull/949 and we can always make a new issue if the current relocation strategy is too slow for some use cases!
