### ISSUE TITLE
wasm2obj: Implement memory initializers

### ISSUE THREAD

**Issue by m4b** [bytecodealliance/wasmtime#2]
of the test files, only call does not have memory initializer. I'd like to see it implemented, or at least stubbed out, so I can examine the object files produced.

```
RUST_BACKTRACE=1 cargo run --bin wasm2obj -- memory.wasm -o memory.o
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/wasm2obj memory.wasm -o memory.o`
%wasm_0x0(0): relocs: []
 error: FIXME: implement data initializers
```

How much work would it be to implement this, or at least add stubs so it doesn't stop the entire binary emission process?

**Comment by sunfishcode** [comment]
I just pushed a patch which writes wasm data initializers into faerie data sections. Wasm data initializers have some special semantics that involve more than just prepopulating the contents of a .data section, but if you're just testing object file writing, you don't need to worry about that for now.

**Comment by m4b** [comment]
Awesome, got it! Yup, I'm just examining the object files and primarily grepping them / gdb disass, and eventually will try to link.

**Comment by m4b** [comment]
Wowwwww this is so cool ! How many translators does cretonne have ?

And yes I’m definitely doing PIC and function sections  (afaics function sections is only applicable to ELF and not mach-o)

At some point could make it do non PIC but I dunno if it’s worth the effort as it’s becoming niche. And also need to get other than X86 relocations working :laughing:

**Comment by sunfishcode** [comment]
The wasm ones and the llvm2cretonne prototype are the most complete frontends at the moment. There are a few others that have started, but aren't usable yet.

And yeah, PIC and function sections are definitely the way to go for now.

**Comment by m4b** [comment]
Re zero relocation, i would have to investigate but my guess is your compiler was very clever and added a relative relocation to the locally defined function so as to avoid routing a callq through the plt table, _OR_ it’s just a bug in faerie ;)

Unfortunately I suspect it’ll be difficult for me to get the llvm-sys crate working, I always have llvm lib linking difficulties on my computer... hopefully will be fine, will try tonight !

**Comment by akirilov-arm** [comment]
@alexcrichton Since you removed `wasm2obj` in PR #3301, I suppose this is no longer relevant :smile:?

**Comment by alexcrichton** [comment]
Indeed!
