### ISSUE TITLE
C API: creating a module should require an engine, not a store

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#2025]
We made changes to the Rust API so that creating a module requires an engine, not a store. However, we didn't propagate this change out to the C API (nor the python API and I assume not to the go or .NET APIs either).

We should do this. It might require using non-standard `wasmtime.h` functions, unless we convince upstream to make this change as well.

**Comment by yurydelendik** [comment]
> We made changes to the Rust API so that creating a module requires an engine, not a store.

Yeah, the reason was `HostRef`. Now since it is gone we can change signature of `wasmtime_module_new`.
