### ISSUE TITLE
wiggle: lifetime not applied to field

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#2053]
While talking to @kubkon about an issue with #2050, we found that the lifetime of the `Tensor` struct was not being propagated downwards to the field correctly. On #2050's branch and using `cd crates/wasi-common && cargo expand wasi`:

```
9014   │         pub type TensorData<'a> = wiggle::GuestPtr<'a, [u8]>;
9015   │         pub struct Tensor<'a> {
9016   │             pub dimensions: TensorDimensions,
9017   │             pub type_: TensorType,
9018   │             pub data: TensorData,
9019   │         }
``` 

It looks like it should generate instead `pub data: TensorData<'a>` and `pub data: TensorDimensions<'a>`.

**Comment by abrown** [comment]
cc: @kubkon, @pchickey, @sunfishcode

**Comment by kubkon** [comment]
An update here. I've fixed the lifetime issue, but the problem remains with marshalling the memory in and out. Take this bit of `witx` for example:

```
(typename $struct_of_array
    (struct
       (field $arr $some_bytes)))

(module $something
    (@interface func (export "summm")
        (param $a_struct $struct_of_array)
        (result $error $errno))
```

The shims we generate for the interface function will look like:

```rust
fn summm(ctx: &WasiCtx, memory: &dym wiggle::GuestMemory, a_struct_ptr: i32) -> i32 { // ... }
```

The trick here is being able to extract the pointer and length of the array from the struct pointer which we currently don't support in `wiggle`. I'm wondering if we should though. @pchickey thoughts?
