### ISSUE TITLE
machinst x64: bint.i8 not implemented for b1 inputs

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2121]
```
target x86_64

function u0:0(i8) -> i8 system_v {
                                block0(v0: i8):
                                    v1 -> v0
@0001                               v2 = icmp_imm.i8 eq v1, 0
@0001                               v3 = bint.i8 v2
@0003                               return v3
}
```

```
thread 'rustc' panicked at 'internal error: entered unreachable code: unexpected extension kind from types::B1 to types::I8', /home/bjorn/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/8cfff26/cranelift/codegen/src/isa/x64/lower.rs:813:22
```

**Comment by bnjbvr** [comment]
Not sure what the cranelift semantics expect here: should we sign-extend the value in the lowest bit to all the bits? If not, this would just require another arm in this match, `(1, 8) => None`.

**Comment by bjorn3** [comment]
It should zero-extend. `bint` maps to `false` to 0 and `true` to 1. `bmask` maps `false` to all 0s and `true` to all 1s.

**Comment by bjorn3** [comment]
I am currently working on this and other instructions unimplemented by the new x86_64 backend, but implemented by the AArch64 backend.
