### ISSUE TITLE
CI breaks on staticvec compile for lightbeam

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#2183]
CI fails in nightly due to a failure while compiling StaticVec. However when I build with nightly 1.48 2020-08-28 local I do not get this failure and have no problems building. The CI is using nightly 1.48 from 2020-09-01. 
Staticvec is at it's latest version of v10.2 so nothing to update there. Anyone with pointers here? 

https://github.com/bytecodealliance/wasmtime/pull/2180/checks?check_run_id=1062989787
https://github.com/bytecodealliance/wasmtime/pull/2180

**Comment by pchickey** [comment]
Fixed by #2182
