### ISSUE TITLE
Looking up an exported function by name in CAPI

### ISSUE THREAD

**Issue by jovanivanovic** [bytecodealliance/wasmtime#2196]
Hello, I've been going through the C Hello World embed and I've seen that in order to get an exported function from wasm, you get it by an index:
```c
wasm_extern_vec_t externs;
wasm_instance_exports(instance, &externs);
assert(externs.size == 1);
wasm_func_t *run = wasm_extern_as_func(externs.data[0]);
```

Is there a possibility that I can lookup the function using it's name, `run` for example?

**Comment by alexcrichton** [comment]
Currently this can't be directly done with one function, but you can match up the list returned by `wasm_module_exports` with the list returned by `wasm_instance_exports` to get the name of each item.

**Comment by jovanivanovic** [comment]
@alexcrichton Thanks for the answer. Would it be possible for you to write an example on the matter please?
