### ISSUE TITLE
Performance decrease when functions have same name

### ISSUE THREAD

**Issue by Rochet2** [bytecodealliance/wasmtime#2213]
- What are the steps to reproduce the issue?
Link a 1000 modules together with the following code inside them by using a Linker.
```C
__attribute__((used))
int hello(int i) {
    return i;
}
```
Then measure the time it takes to call `instance.get_func(&function_name)` for each instance's hello function.
Then create 1000 modules with the same code, except the hello functions in each module has an increasing integer in its name.
The time measurements should differ.

In our tests when all modules are having the same hello function name, the average time for a single fetch is
`0.0010949896000000006` seconds
and when the function names are different (have different number at the end of them) the measured time is
`0.000036767999999999476` seconds

The difference is quite significant and the only change we tested was to change the function names in the modules.

- What do you expect to happen? What does actually happen? Does it panic, and if so, with which assertion?
We would expect the time to fetch a function to be similar regardless of function naming.

- Which Wasmtime version / commit hash / branch are you using?
0.19

- If relevant, can you include some extra information about your environment? (Rust version, operating system, architecture...)
Ubuntu 18.04.5 LTS 64-bit
rustc 1.44.0 (49cae5576 2020-06-01)
16GB RAM, i5-7200 @2.5GHz*4

**Comment by alexcrichton** [comment]
Thanks for the report, and this does indeed seem a little bizarre! Would you be able to share some code of how you're using the `wasmtime` crate, and ideally what wasm blobs you're using?

**Comment by Rochet2** [comment]
Thanks for your response. Closing the issue as new tests show that the measurement was likely simply flawed.
The original measuring code is not available, but attempts to replicate the issue based on code used at the time the issue was created or based on the issue description yields the expected correct result.
