### ISSUE TITLE
Support RISC-V target in new backend framework

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#2217]
As mentioned in a reddit discussion [here](https://www.reddit.com/r/rust/comments/iwumjn/a_new_backend_for_cranelift_part_1_instruction/g64hdlq/), we don't yet have a tracking issue for this.

We should implement a backend in the MachInst framework for RISC-V 32- and/or 64-bit platforms. It seems we had the very start of this in the old backend framework (cranelift/codegen/src/isa/riscv/) but it appears fairly skeletal.

**Comment by laizy** [comment]
Is there any progress on this?

**Comment by dunxen** [comment]
I'd love to try but fear I don't have the required domain knowledge here :)

**Comment by yuyang-ok** [comment]
@dunxen  are you working on risc-v already?

**Comment by dunxen** [comment]
> @dunxen  are you working on risc-v already?

Hey sorry, I've been away for some time.
Unfortunately, I am not. I'm still learning about the ISA.

**Comment by yuyang-ok** [comment]
> I'd love to try but fear I don't have the required domain knowledge here :)

same!!

**Comment by dunxen** [comment]
> > I'd love to try but fear I don't have the required domain knowledge here :)
> 
> 
> 
> same!!

I'd love to work on it but can't give an ETA at all. I'll check closer to the end of the month.

**Comment by a1phyr** [comment]
I think this issue can be closed now :tada:

**Comment by sanxiyn** [comment]
For the record, #4271 merged RISC-V backend.

**Comment by jameysharp** [comment]
Yes, this is done. Hooray!
