### ISSUE TITLE
Add define_anonymous_data function to cranelift-module

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2220]
#### Feature

Add a method to cranelift-module that defines a data object without creating a new symbol.

#### Benefit

Avoiding symbols for anonymous data objects improves linker times.

#### Implementation

For `cranelift-simplejit` symbol names are unused for everything except for imports and exports already. For `cranelift-object` the data object could be added to the right section and then the section id and offset could be stored to generate the right relocations in the future.

#### Alternatives

Using `Linkage::Local` requires you to generate an unique name and has a negative impact on compilation times.

**Comment by pchickey** [comment]
Seems reasonable to me
