### ISSUE TITLE
Problems with the C API header

### ISSUE THREAD

**Issue by DagAgren** [bytecodealliance/wasmtime#2253]
Using the latest macOS release (https://github.com/bytecodealliance/wasmtime/releases/download/v0.20.0/wasmtime-v0.20.0-x86_64-macos-c-api.tar.xz):

Some of the function defines, like `WASM_API_EXTERN own wasm_config_t* wasm_config_new();` are not quite correct, and should use `(void)` for the arguments. `()` works, but defines a function with undeclared arguments, rather than with no arguments. Xcode, at least, will by default warn on this:

    .../wasm.h:121:51: This function declaration is not a prototype

**Comment by alexcrichton** [comment]
Thanks for the report! This isn't actually a header which we define in this repository, it's located upstream at https://github.com/WebAssembly/wasm-c-api, so that's where the fix will need to land first for us to pull it in.

**Comment by DagAgren** [comment]
Submitted https://github.com/WebAssembly/wasm-c-api/issues/154.

**Comment by Hywan** [comment]
I've fixed it for you, https://github.com/WebAssembly/wasm-c-api/pull/160 :-).

**Comment by bjorn3** [comment]
https://github.com/WebAssembly/wasm-c-api/pull/160 has been merged.
