### ISSUE TITLE
Restrict memory usage

### ISSUE THREAD

**Issue by mleonhard** [bytecodealliance/wasmtime#2273]
I wish to use wasmtime in a server to run small untrusted code blocks.  I need to limit the maximum memory consumed by each running block to 5MB.  I looked through the docs and found no way to restrict how much memory the VM can allocate.  There seems to be a built-in limit of 4GB.  See #1872 .

Let's support or document how to restrict memory usage.

**Comment by bjorn3** [comment]
For imported memory you can set the limit when creating the memory. For exported memory you could parse the module and check that the memory limit is at most 5MB.

**Comment by alexcrichton** [comment]
You can control memory via a number of different means. Application-level configuration happens through the [`Config`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Config.html) type. For example you can use [`static_memory_maximum_size`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Config.html#method.static_memory_maximum_size), [`static_memory_guard_size`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Config.html#method.static_memory_guard_size), and [`dynamic_memory_guard_size`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Config.html#method.dynamic_memory_guard_size) to tweak how wasmtime allocates memory. The smallest VM reservations will come with a static max size of 0 and a dynamic guard of zero, but code will not perform as well at runtime.

You can further configure the [`with_host_memory`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Config.html#method.with_host_memory) method which means that your application is bringing its own memory allocation strategy, where you can limit even the size of locally defined memories in a wasm module.

And as @bjorn3 mentioned if you're creating the memory itself then you can specify the maximum size at runtime.

**Comment by mleonhard** [comment]
Thank you both for your quick replies.

Is there a way to use `static_memory_maximum_size`, `static_memory_guard_size`, and `dynamic_memory_guard_size` to restrict the VM from allocating more memory?  Could I set the static_memory_guard_size to 4GB - 5MB?  I suppose this could work on a platform with a wide-enough memory address space.

To use `wasmtime::Config::with_host_memory`, I must implement [wasmtime::MemoryCreator](https://docs.rs/wasmtime/0.20.0/wasmtime/trait.MemoryCreator.html).  The MemoryCreator is configured on the `Engine` which contains many VMs.  [`InstanceHandle::new`](https://github.com/bytecodealliance/wasmtime/blob/e88d74903102266a18e97489557760b9be67f782/crates/runtime/src/instance.rs#L853) calls [`instance::create_memories`](https://github.com/bytecodealliance/wasmtime/blob/e88d74903102266a18e97489557760b9be67f782/crates/runtime/src/instance.rs#L1358) calls `MemoryCreator::new_memory` and does not pass any data about which VM (`Store` or `Instance`) the memory is for.  How could I use the engine-specific struct to decide if a particular VM has reached its allocation limit?

I looked at how to check the size of memories in a module.  I'm not familiar with WASM memories.  Are all module-allocated memories exported?  Would this work?
1. Call [`wasmtime::Module::exports`](https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Module.html#method.exports)
2. Iterate through the result and examine `ExternType::Memory` entries
3. Error if there is a missing `Limits::max` value
4. Sum up the `Limits::max` values and error if they go over the limit

[`wasmparser::Parser`](https://docs.rs/wasmparser/0.63.0/wasmparser/struct.Parser.html) can parse the [Memory entries](https://docs.rs/wasmparser/0.63.0/wasmparser/enum.MemoryType.html).  There is a `shared` flag.  I suppose `shared=true` means the memory is exported.  So some WASM binaries might have `shared=false` memories, which would not appear in the list of exports.  So I cannot use `wasmtime::Module::exports` to count total memory usage.  `wasmparser::Parser` should work.  I think this might be the solution.

Does WASM define any way for a module to make new Memory objects at runtime?

**Comment by mleonhard** [comment]
An article that describes how WASM memories work:
https://depth-first.com/articles/2019/10/16/compiling-c-to-webassembly-and-running-it-without-emscripten/

**Comment by alexcrichton** [comment]
@mleonhard I'd recommend reading the documentation about dynamic/static memories. Unfortunately there is no "disallow more than 5MB per instance" switch in Wasmtime, and this is something that will require work to be done at this time. The `MemoryCreator` trait allows a custom implementation which you can embed with specifics related to your application. You can track growth and allocation to disallow or arbitrarily "fail" growth beyond a certain point.

For wasm memories in general, I'd recommend reading up on documentation in the wasm spec or in various posts online. Wasm modules can define or import a memory. Memories always state a minimum size and optionally have a maximum size. You would probably want to validate in your application that the minimum size isn't too big.

**Comment by mleonhard** [comment]
I found the answer: Code in a Wasm VM cannot make new Memory objects.  See [WebAssembly 1.1 Memories](https://webassembly.github.io/spec/core/syntax/modules.html#syntax-mem).  Every Wasm binary can define exactly one Memory object with a specified initial size and an optional max size.  Code inside the VM can use [memory instructions](https://webassembly.github.io/spec/core/syntax/instructions.html#memory-instructions) to grow a Memory region, up to its max size.

Code in a Wasm VM could import and call a function that makes a new Memory object or does anything.  By default, a wasmtime VM does not provide any importable functions to code inside the VM.  Call [`wasmtime_wasi::Wasi::new`](https://docs.rs/wasmtime-wasi/0.20.0/wasmtime_wasi/struct.Wasi.html#method.new) to make WASI functions importable. See example [Embedding in Rust - WASI](https://bytecodealliance.github.io/wasmtime/examples-rust-wasi.html).

To check the max memory usage of a program running inside a wasmtime VM, [parse](https://crates.io/crates/wasmparser) the binary and check the max size of the single `Memory` entry.

To set the memory usage limit of a program running inside a wasmtime VM, modify the binary to set the max size value of the `Memory` entry.  The [object crate](https://crates.io/crates/object) has an API and an [example](https://github.com/gimli-rs/object/blob/master/examples/objcopy.rs) that could be adapted to modify Wasm binaries, but it won't be pretty.

I also found [WASM Micro Runtime](https://github.com/bytecodealliance/wasm-micro-runtime) which provides a simple way to limit memory.  But it [has no Rust bindings](https://github.com/bytecodealliance/wasm-micro-runtime/issues/230).

**Comment by mleonhard** [comment]
https://crates.io/crates/parity-wasm looks like a very clean library for modifying Wasm binaries to set memory max size.

**Comment by alexcrichton** [comment]
In addition to the resources already mentioned I believe that the current `ResourceLimiter` trait is another avenue to limiting memory of modules, so I'm going to close this.

**Comment by huntc** [comment]
For completeness, another suggestion cited here: https://users.rust-lang.org/t/how-to-set-max-memory-limit-in-wasm/64725/10

The flags can also be declared in a .cargo/config.toml file so that a regular `cargo build --target=wasm32-wasi` command can be used:

```toml
[target.wasm32-wasi]
rustflags = ["-Clink-args=--initial-memory=2621440 --max-memory=2621440"]
```
