### ISSUE TITLE
JIT Profiling Support

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#229]
Hi .. I'd like to ask for input on JIT profiling support of wasmtime ... specifically the gaps that exists, current code that should be leveraged, and a good implementation direction for sharing code paths. Personally, I would like to see support in both perf and vtune. Currently there do not appear to be any wasmtime patches that specifically targeting profiling support, but there are patches scattered in related projects that may be leveraged in support of such an effort. Specifically @yurydelendik has some patches as discussed here wasmtime/pull/53 that potentially may be levered to help create a mapping information that can be used either by vtune directly or by vtune and perf indirectly. Also, there is the perf map support here cranelift/pull/571 which I hope to try soon. 

I have started implementing support for a hook for vtune for at least seeing the jitted assembly, and I will continue that soon focusing on getting proper mappings. I think for perf support it may make sense to start with a generating a simple map file and developing instructions for leveraging that. Ultimately though, I'd hope it would be possible to share as much code as possible as part of a comprehensive solution for that covers both profiling tools.

**Comment by yurydelendik** [comment]
@ jlb6740 is there a way for vtune to attach/use GDB JIT interface to capture "dynamic" images?

**Comment by jlb6740** [comment]
Hi @yurydelendik, I am not familiar with the GDB JIT interface ... are you referring to this: https://sourceware.org/gdb/onlinedocs/gdb/JIT-Interface.html? VTune's interface is based in jitprofiling.h as described here: https://software.intel.com/en-us/vtune-amplifier-help-jit-profiling-api . Is the gdb interface the same that lldb uses? If so then perhaps this is potential direction where it would make sense to look into mapping the two interfaces.

**Comment by yurydelendik** [comment]
>  are you referring to this: https://sourceware.org/gdb/onlinedocs/gdb/JIT-Interface.html?

Correct

> Is the gdb interface the same that lldb uses?

yes, lldb implements GDB's JIT interface

> VTune's interface is based in jitprofiling.h 

Thanks for link. Looks like it is possible to generate jitprofiling.h info from DWARF.

**Comment by jlb6740** [comment]
"Thanks for link. Looks like it is possible to generate jitprofiling.h info from DWARF."

I believe it can use this dwarf to help generate call stack information. I am looking to get more details though to see how dwarf embedded in the custom section can be leveraged. The jitprofiling.h still looks like it needs to be populated with hooks before wasm code is executed but after it is loaded into memory.  

Are there particular files in wasmtime I can source to find the implementation for the GDB-JIT interface?

**Comment by bjorn3** [comment]
wasmtime-runtime/src/jit_int.rs
