### ISSUE TITLE
Cranelift: Support stack probes without external function call

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2299]
#### Feature

LLVM has support for performing the stack probes directly in the function prologue instead of calling an external function. (see https://github.com/rust-lang/rust/pull/77885 for using this in Rust)

#### Benefit

This can be faster due to being able to unroll the stack probe loop. It also avoids having to provide an external stack probe function. This makes it possible to enable stack probing in cg_clif. (https://github.com/bjorn3/rustc_codegen_cranelift/issues/661)

#### Implementation

This should only be implemented for the machinst backends. It should probably be added to either the `gen_prologue` implementation or `gen_prologue` caller.

#### Alternatives

Keep using an external stack probe function with the associated drawbacks.

**Comment by bjorn3** [comment]
Neither AArch64, nor s390x has support for this yet.

**Comment by afonso360** [comment]
Right, should we reopen this or open issues against both backends?

**Comment by bjorn3** [comment]
Opened #4846 and #4847.
