### ISSUE TITLE
wasmtime fails to compile on armv7 with: error[E0308]: mismatched types    --> crates/runtime/src/traphandlers.rs:156:52

### ISSUE THREAD

**Issue by stefson** [bytecodealliance/wasmtime#2315]
I checked out latest git, compiled it with rust-1.45.2 and got this error: 

```
error[E0308]: mismatched types
   --> crates/runtime/src/traphandlers.rs:156:52
    |
156 |         unsafe fn get_pc(cx: *mut libc::c_void) -> *const u8 {
    |                   ------                           ^^^^^^^^^ expected *-ptr, found `()`
    |                   |
    |                   implicitly returns `()` as its body has no tail or `return` expression
    |
    = note: expected raw pointer `*const u8`
                 found unit type `()`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `wasmtime-runtime`.
```

there's also another error, which is expected as armv7 isn't fully implemented yet: 

```
error: unsupported platform
   --> crates/runtime/src/traphandlers.rs:174:21
    |
174 |                     compile_error!("unsupported platform");
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

verbose error log: [verbose-error.zip](https://github.com/bytecodealliance/wasmtime/files/5432974/verbose-error.zip)

**Comment by stefson** [comment]
I'm doing this test compile every once in a while to stop the code base from decaying further, making it even more difficult to work on it in the future and maybe implement full armv7 support. Sadly, I'm unable to fix this on my own as I don't speak that much rust, but I can offter to test any provided patch.

**Comment by alexcrichton** [comment]
Lots has changed in the interim since this issue was opened, and at this time Wasmtime does not support armv7 as there is no Cranelift backend for that target. Tracking that is probably best done by https://github.com/bytecodealliance/wasmtime/issues/1173
