### ISSUE TITLE
Serialized wasmtime modules are extremely large

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime#2318]
I'm using custom module serialization based caching in [YoWASP](https://yowasp.org), primarily to be able to show a message during cold startup (which can take many minutes on slow machines), but also to avoid applying zstd compression that noticeably increases warm startup latency. 

The problem is that the cached modules are extremely large—so large that it causes a near-pathological amount of disk I/O. (On Windows VMs, due to the I/O, warm startup actually becomes slower compared to wasmtime's own caching. On bare metal Windows on SSDs it still gets faster.)

On Linux, [yosys.wasm](https://github.com/bytecodealliance/wasmtime/files/5436001/yosys.wasm.zip) (21M wasm file) results in a 290M serialized module, an increase of ~14×. On Windows, for some reason, that very same file results in a ~580M serialized module, an increase of ~28×. The native Yosys binary for x86_64 is 17M; even once you account for libc and libstdc++, it really should not take over half a gigabyte of space.

I'm filing this issue on request of @alexcrichton [here](https://github.com/bytecodealliance/wasmtime-py/pull/43#issuecomment-716211943).

**Comment by whitequark** [comment]
Oh and the script that runs it is [here](https://github.com/YoWASP/yosys/blob/develop/pypi/yowasp_yosys/__init__.py). It's extremely simple but maybe I forgot something important.

**Comment by alexcrichton** [comment]
The cache entry size is effectively the bincode-coded size of [this structure](https://github.com/bytecodealliance/wasmtime/blob/fc1cedb2ff43e4b31bcc8f99ef069d5a2d189899/crates/jit/src/instantiate.rs#L53-L73), which I believe is roughly analagous to the in-memory size of that structure. Adding some simple instrumentation I was able to get the encoded byte size of each of the fields:

```
module:                  152817        
obj:                   56236896        
funcs:                242146780        
  funcs(traps):                24182940
  funcs(address_map):         217774640
  funcs(stack_maps):             189216
data_initializers:      2880584        
unwind_info:            4611040        
total:                306028126        
```

clearly `funcs` is the massive field (too much so), and the worst offenders are the `traps` and `address_maps` maps. Neither of these maps really justifies taking up so much space, and longer-term we need to have a more serious refactoring to probably encode these entirely different in a much more compact fashion. The consumer, however, relies on random-access right now (or at least the ability to do a binary search), so it won't be immediately trivial to restructure these data structures. In the meantime https://github.com/bytecodealliance/wasmtime/pull/2321 should be a band-aid for now to make it a bit more reasonable (although still pretty unreasonable).

I've yet to investigate the Windows discrepancy here, that's quite worrisome too!

**Comment by alexcrichton** [comment]
Oh and after that PR, the breakdown looks like:

```
module:                  152817        
obj:                   56236896        
funcs:                 97596780        
  funcs(traps):                24182940
  funcs(address_map):          73224640
  funcs(stack_maps):             189216
data_initializers:      2880584        
unwind_info:            4611040        
total:                161478126        
```

**Comment by alexcrichton** [comment]
Ok I've got one more linked improvement as well as https://github.com/bytecodealliance/wasmtime/pull/2326 which should account for the discrepancy on Windows.

**Comment by alexcrichton** [comment]
With current master plus https://github.com/bytecodealliance/wasmtime/pull/2324 the cache entry size of the original wasm module is down to 97MB, and the cache entry sizes should be roughly the same on Linux and Windows. @whitequark  for your use cases is that still too large? It's still pretty large  having a >4x size increase, but further changes may require more invasive tweaks than the low hanging fruit picked off so far.

**Comment by whitequark** [comment]
> for your use cases is that still too large?

Seems excellent to me. Any chance you can do a point release of wasmtime-py with the updated interpreter? I have to test on a fairly heterogenous set of machines so it'd be much easier if I didn't have to distribute patched wheels as well.

**Comment by alexcrichton** [comment]
Sure! I'll wait until #2324 is in and then I'll do a release of wasmtime

**Comment by fitzgen** [comment]
I don't know how easy `bincode` is to extend, but all the address-keyed func data could probably compress really well if we used deltas instead of absolute values combined with a variable length integer encoding (e.g. LEB128).

**Comment by fitzgen** [comment]
(and we ensured they were sorted)

**Comment by alexcrichton** [comment]
@fitzgen turns out bincode [has an option for just that](https://github.com/bytecodealliance/wasmtime/pull/2322)!

**Comment by alexcrichton** [comment]
Ok wasmtime-py 0.21.0 is now published @whitequark if you'd be able to test it out

**Comment by whitequark** [comment]
I'll take a look over the next few days!

**Comment by whitequark** [comment]
Were there any breaking changes? It's a bit unfortunate that I'll have to rebuild all the packages as that makes it a bit harder to get other people to compare several different versions.

**Comment by whitequark** [comment]
I've rebuilt yowasp-yosys and yowasp-nextpnr-ice40 with wasmtime 0.21.0 on my Linux machine.
  * Yosys: 291M→94M cache file size improvement, ~2x warm startup latency improvement (wow!!);
  * nextpnr-ice40: 23M→6.9M cache file size improvement, warm startup latency changes within noise threshold.

**Comment by alexcrichton** [comment]
Right now our release process for wasmtime is just "major bump everything", and we're then trying to keep the external packages like wasmtime-py and wasmtime-go in sync with the main repo. We should probably allocate space to have minor version bumps of everything as well though...

Glad to hear the results as well!

**Comment by whitequark** [comment]
Ah ok if it's in sync with the main repo then it might actually be pretty handy. I wasn't sure exactly how it worked.

**Comment by whitequark** [comment]
@alexcrichton I've tried running yowasp-yosys and yowasp-nextpnr-ice40 on the cheapest and slowest laptop I found nearby, and it's only something like 2× slower on both cold and warm startup than my XPS 13. I have no idea how you managed to achieve that, and I'm quite impressed. As far as I'm concerned this is enough performance.

**Comment by alexcrichton** [comment]
Nice! Thanks again for the report and helping to investigate!
