### ISSUE TITLE
Minimum Rust badge seems incorrect

### ISSUE THREAD

**Issue by Voultapher** [bytecodealliance/wasmtime#2377]
Just tried building the cranelift tests with `cd cranelift && cargo test --all` using Rust 1.44 and it failed building one of the dependencies because it wanted to use this https://github.com/alexcrichton/proc-macro2/pull/228. After upgrading to 1.47 everything works as expected. The top level README has a Rust 1.37+ badge. Either that is wrong or misleading.

Edit: Actually I need nightly to build and run the tests. I suggest we put that in the relevant README.

**Comment by alexcrichton** [comment]
Ah yes I think that's a mistake, sorry about that! A PR would be welcome to clarify and update this!

**Comment by Voultapher** [comment]
This issue hasn't seen activity in long time so I'm closing it.
