### ISSUE TITLE
Implement IntoFunc for Func

### ISSUE THREAD

**Issue by softprops** [bytecodealliance/wasmtime#2380]
#### Feature

I've been struggling with a way to decompose chains of `linker.func` that delegate to closures into chains of  `linker.func` that delegate to methods

from

```rust
linker.func("module", "foo", closure)?
 .linker.func("module", "bar", closure)?
```

into

```rust
linker.func("module", "foo", foo(&store))?
 .linker.func("module", "bar", bar(&store))?
```

My best guess way to do that would be to decompose into methods that returned `impl IntoFunc` but its type signature proved cumbersome to make that work.

My next thought was that I could just return `Func` objects from method but then realized `Func` doesn't implement `InfoFunc`

```rust
fn foo(store: &Store) -> Func {
  Func::wrap(...)
}

fn bar(store: &Store) -> Func {
   Func::wrap(...)
}
```

This seems trivial to add but I'm not sure what the type arguments for `IntoFunc` would look like

```rust
impl IntoFunc<?,?> for Func {
    fn into_func(self, store: &Store) -> Func {
       self
   }
}
```

#### Benefit

A slightly more flexible linker api.

#### Implementation

An open question above was what to fill in for type parameters

```rust
impl IntoFunc<?,?> for Func {
    fn into_func(self, store: &Store) -> Func {
       self
   }
}
```

#### Alternatives

I could have a muting api which roughly implements what I started out with 

```rust

fn with_foo(linker: mut Linker, store: &Store) -> Result<Linker, ...> {
  linker.func("module", "foo", closure)
}

fn with_bar(linker: mut Linker, store: &Store) -> Result<Linker, ...> {
  linker.func("module", "foo", closure)
}

with_foo(linker, store)?
  .with_bar(linker, store)?
```

This has the workaround-for-an-api feel to it.

**Comment by alexcrichton** [comment]
Would [`Linker::define`](https://docs.rs/wasmtime/0.21.0/wasmtime/struct.Linker.html#method.define) work for you in this case?

Otherwise we could probably add something like `IntoFunc<(), ()>` for `Func` perhaps?

**Comment by softprops** [comment]
ohhh nice. I could try that. since there's and into impl for Func => Extern that might tick the box for me.

**Comment by softprops** [comment]
also thanks for the extremely fast feedback

**Comment by softprops** [comment]
`Linker::define` seems to work so I'm going to close this issue. Thanks again @alexcrichton for such an amazing project
