### ISSUE TITLE
Port unwind tests to new x64 backend

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#2415]
In #2411, we discovered that unwind tests for the `x86` backend are running even when the new `x64` backend is enabled, resulting in test failures (due to the mismatch of implementation internals). In that PR, we disabled the old tests on the new configuration; but before we remove the old backend entirely, we need to preserve the test coverage by porting the tests over. This should largely be mechanical, with just some updates to the expected unwind info if the prologues/epilogues differ slightly.

**Comment by alexcrichton** [comment]
I think all unwinding bits and pieces for the new backend are now in place, so I figure this can be closed.
