### ISSUE TITLE
Implement full debug-info support in new x64 backend

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#2416]
We need to add support for generating `ValueLabelRange`s to the `machinst` framework and (at least) the `x64` backend before we can remove the `x86` backend (#1936, #2079).

This requires tracking the correspondence from CLIF `Value`s to VCode `Reg`s (pre- and post-regalloc) and `SpillSlot`s. We will need to either:
- extend the returned info from regalloc.rs somewhat in order to provde the pre-to-post-regalloc mapping, or
- stash this pre-to-post-regalloc mapping on our side inside the `map_regs()` callback, possibly only for `Reg`s that correspond to `ValueLabel`s

**Comment by bjorn3** [comment]
I think this is done.

**Comment by cfallin** [comment]
Indeed, completed recently, forgot to close!
