### ISSUE TITLE
Roadmap of wasmtime

### ISSUE THREAD

**Issue by daubaris** [bytecodealliance/wasmtime#2435]
#### Feature
Adding a roadmap of wasmtime.

#### Benefit
I think most of the users and yet-to-be users would be interested in seeing what is the future of the project. Similarly, a roadmap could potentially reveal if the project is focused on achieving some specific major goals, such as specific platform support. Moreover, a clear list, for example, for a release could attract more contributors as it would be clear what needs to be done.

At the present moment, it is certainly vague what needs to be improved (besides checking issues), what new features could be developed (besides new proposals) and what are the overall goals.

#### Implementation
It could be added as a new document to the existing `docs` folder.

**Comment by michaelvoronov** [comment]
Heavily +1, we are especially interested in interface types MVP implementation in Wasmtime. There are some proposals (like module linking and let from function reference) that should be supported first, and module linking has the nice tracking issue with all neccessary information, but absence of global roadmap doesn't allow us to make a long-term plans.

**Comment by cfallin** [comment]
Hi all: it doesn't directly address the *wasmtime* planning (w.r.t. Wasm feature support and other runtime efforts), but I've put up an RFC just now with a proposed roadmap for Cranelift in 2021 (bytecodealliance/rfcs#8), which may be relevant for planning purposes as wasmtime relies on and benefits from Cranelift improvements (and Cranelift lives in this repo) :-)

**Comment by sunfishcode** [comment]
[The recent 1-year-update blog post](https://bytecodealliance.org/articles/1-year-update) lays out a roadmap for a lot of the things that we'll be focusing on in Wasmtime.

**Comment by alexcrichton** [comment]
This is a pretty old issue at this point so I'm going to close this. In general this is mostly a topic for the bytecodealliance at large and the RFCs repository as well. At this time I do not believe there is an official roadmap for Wasmtime itself, and adding one is best done through an RFC rather than an issue here.
