### ISSUE TITLE
[CLI] How to link multiple wasm's with command line?

### ISSUE THREAD

**Issue by Horki** [bytecodealliance/wasmtime#2438]
**Example 1**
I have written a gcd unit tests into `gcd.wast`

```
(module
  ;; Do I need this header?
  (import "gcd" "gcd" (func $gcd (param i32) (param i32) (result i32)))
)

(assert_return (invoke "gcd" (i32.const 27) (i32.const 6)) (i32.const 3))
(assert_return (invoke "gcd" (i32.const 6) (i32.const 27)) (i32.const 3))

```

And I want to run wast file from CLI, with importing wat file.

`wasmtime --import gcd.wat wast gcd.wast`

**Example 2**
Linking example

How can I do this?
`wasmtime --import examples/linking2.wat run examples/linking1.wat`

**Comment by alexcrichton** [comment]
I think you might be looking for the `--preload` CLI option? That allows loading modules under specific names I think for this use case

**Comment by Horki** [comment]
Hi @alexcrichton , `--preload` currently only works with `run` command, but it's missing in `wast` command

Meaning `example2` is working;
```
# Example 2 ! Works
$ wasmtime run --preload linking2=examples/linking2.wat examples/linking1.wat --invoke run

# Not working for wast command
$ wasmtime wast --preload gcd=examples/gcd.wat gcd.wast
> Found argument '--preload' which wasn't expected, or isn't valid in this context
```

What would be the proper way to `preload` while using wast for unit testing?

**Comment by alexcrichton** [comment]
Ah sorry I missed that! I believe that the `wast` command doesn't have support for this yet but it probably wouldn't be too hard to do so!

**Comment by Horki** [comment]
@alexcrichton 

Ok, I've got it, no need for `preload` in my case

`gcd.wast`

```
(assert_return (invoke "gcd" (i32.const 27) (i32.const 6)) (i32.const 3))
(assert_return (invoke "gcd" (i32.const 6) (i32.const 27)) (i32.const 3))
```

```
# This will run
$ wasmtime wast examples/gcd.wat gcd.wast
```

As in  https://github.com/bytecodealliance/wasmtime/blob/ac0ee271b16891883d0e6d40697bc0885f66c058/src/commands/wast.rs#L44-L48
