### ISSUE TITLE
Cranelift: ensure we are using SSE 4.1+ when we can, when enabled

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#2467]
I know this isn't part of the PR, but it is curious that these are implemented as lib calls instead of using `ROUNDSD` and `ROUNDSS`--@bnjbvr, do you know why this is? I wonder if there is some NaN handling there that we should also be doing for the packed version...

_Originally posted by @abrown in https://github.com/bytecodealliance/wasmtime/pull/2457#discussion_r534339371_

**Comment by alexcrichton** [comment]
I believe that this has since been handled, so closing.
