### ISSUE TITLE
fuzzing: Make the `TableOps` test case generator use wasm-encoder instead of concatenating WAT strings

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#2499]
https://github.com/bytecodealliance/wasmtime/blob/main/crates/fuzzing/src/generators/table_ops.rs

Similar to https://github.com/bytecodealliance/wasmtime/issues/2498. We can improve our fuzzing throughput by generating Wasm binaries directly via [`wasm-encoder`](docs.rs/wasm-encoder/) builders rather than concatenating WAT strings and then translating those into Wasm binaries.

If you want to work on this issue, leave a comment, and let me know whatever questions you have!

Info for getting up and running with contributing: https://docs.wasmtime.dev/contributing.html

**Comment by dhaynespls** [comment]
Hey @fitzgen so it's a rainy night so I got cozy and took a first pass on this issue. I'm still new to Rust and have zero background on wasm but I saw your tweet and this seemed like a nicely sized issue to take on. There are a few parts not working yet, marked with `TODO`s and I'm also open to nits about style and whatnot but overall the transition to `wasm_encoder` was super smooth!

**Comment by fitzgen** [comment]
Great! Looks like Alex has reviewed your PR and given you some good feedback. Let me know if anything isn't clear or anything like that!
