### ISSUE TITLE
Docs for cranelift-codegen are not published in docs.rs

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#2500]
As discussed [here](https://bytecodealliance.zulipchat.com/#narrow/stream/217117-cranelift/topic/docs.2Ers), the `cranelift-codegen` crate only has docs for version `0.66`, not `0.67` and `0.68` which are the more recently-published versions. The docs.rs logs are not available to determine why this failed.

**Comment by abrown** [comment]
Also, the Cranelift documentation pages themselves could use a review; some of the information is outdated (e.g., [here](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/docs/ir.md))

**Comment by cfallin** [comment]
docs.rs currently has docs published from Cranelift v0.83 (the most recent release); closing issue.
