### ISSUE TITLE
v8x16.shuffle optimizations needed

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasmtime#2531]
I translated the IDCT [SSE code](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/simd/x86_64/jidctint-sse2.asm) into Wasm. The algorithm uses lots of various `punpckxxxx` instructions, though WebAssembly has v8x16.shuffle. The [v8 lowers](https://github.com/v8/v8/blob/dc712da548c7fb433caed56af9a021d964952728/src/compiler/backend/x64/instruction-selector-x64.cc#L3297) into native SSE2 equivalents by matching immediate argument. I cannot find if we do it for any of the cranelift backends.

STR:
1. Use test case at https://github.com/yurydelendik/zbar-wasm/raw/0083a9a48c8c06e5555424d85f71ce5a4b560145/zbar_jpeg/test.wasm
2. Run `time wasmtime run --enable-simd test.wasm --invoke test500`

Observe the time; it is about 15 sec here. Node runs test.wasm (`_initialize` + `test500`) in about 11 sec here.

It is expected that wasmtime/cranelift will improve the performance by using specialized SSE2 instructions by 40-50%.

**Comment by abrown** [comment]
I agree; perhaps this benchmark could be adapted for sightglass?

**Comment by yurydelendik** [comment]
> perhaps this benchmark could be adapted for sightglass?

Not familiar with the sightglass. Can you sketch what needs to be done?

**Comment by abrown** [comment]
[Here](https://github.com/bytecodealliance/sightglass/blob/main/docs/next.md) is a high-level document describing the basic idea and [here is an example](https://github.com/bytecodealliance/sightglass/tree/main/benchmarks-next/shootout-ackermann).

**Comment by alexcrichton** [comment]
Can confirm that all these shuffles are now implemented, even on aarch64 too. All `i8x16.shuffle` instructions present in the above module are compiled to single-instruction lowerings on both x86_64 and aarch64. In that case I'm going to close this.
