### ISSUE TITLE
Debugging of Hand-Written WASM

### ISSUE THREAD

**Issue by Dakror** [bytecodealliance/wasmtime#2542]
#### Feature

As i understand the documentation, wasmtime offers debugging support using DWARF data embedded in wasm binaries.
However this cannot be used when writing / generating raw Webassembly or converting it via wat2wasm. It would therefore be a great feature to add wat-source-level debugging (much like the early Chrome DevTools debugging) to atleast look at the text representation.

#### Benefit

This would aid in debugging of immediate wasm code, where a high source representation is unavailable

#### Implementation

When using a wat2wasm parser or when generating an IR by yourself, you'd need to track the binary locations of your expressions to emit DWARF yourself

#### Alternatives

I've also opened this issue over at binaryen, since this is what I'm using to generate raw WASM (via their C-API). However I think that this feature is generator independent and would best be implemented at the runtime.

**Comment by yurydelendik** [comment]
FWIW, `-g` generates DWARF info that uses wasm bytecode offset for source locations. See https://github.com/bytecodealliance/wasmtime/blob/main/tests/all/debug/simulate.rs 

That's what Chrome and Firefox DevTools do, UI do the rest of the WAT magic.

**Comment by yurydelendik** [comment]
> When using a wat2wasm parser or when generating an IR by yourself, you'd need to track the binary locations of your expressions to emit DWARF yourself

Looks like this is request for the wat2wasm tool(s) and not for wasmtime.

**Comment by Dakror** [comment]
> FWIW, `-g` generates DWARF info that uses wasm bytecode offset for source locations. See https://github.com/bytecodealliance/wasmtime/blob/main/tests/all/debug/simulate.rs
> 
> That's what Chrome and Firefox DevTools do, UI do the rest of the WAT magic.

Where am i to specify `-g`? When compiling wasmtime from source? I don't quite understand. I'm using the Wasm C api + the wasmtime specific functions to embed wasmtime right now.

**Comment by Dakror** [comment]
I've found that this is actually working and my tools werent properly set up. So the only thing that remains is the need for a UI / lookup for the code section offset into WAT code.
