### ISSUE TITLE
Remove imported_memory_XXX/memory_XXX builtin environment functions

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasmtime#2561]
Continuation of https://github.com/bytecodealliance/wasmtime/pull/2556#discussion_r554016039

> Due to the relative cost of [imported_memory_XXX and memory_XXX builtin environment] functions, could the distinction between local/imported memories be removed to halve the number of intrinsics added?

It is related to https://github.com/bytecodealliance/wasmtime/blob/5de5bf15650ec603e12f8d1183cac19794813a5e/crates/environ/src/builtin.rs#L6-L47 and newly defined in #2556 .

> .... we did it awhile ago for a few reference types intrinsics but haven't gotten around to fixing things generally.

**Comment by rgrmrts** [comment]
Hi @yurydelendik, if no one is taking a look at this issue I'd love to take a stab at it. Any tips on how to start would be greatly appreciated (Rust noob)!

Also, @alexcrichton, I read https://github.com/bytecodealliance/wasmtime/pull/2556#discussion_r554016039 and was wondering if you had a PR for the similar work you mentioned in the comment that I might be able to use as a reference?

**Comment by alexcrichton** [comment]
Ah unfortunately the work I mentioned was buried in the review of a different PR so I don't think there's a diff to look at. I think this would be great to fix, however! It'll touch both the code generator and wasmtime runtime, however, so you'll need to update this in a few locations.

**Comment by rgrmrts** [comment]
Sounds like a fun task :) I'll dig in in earnest over the weekend. Cheers!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/bytecodealliance/wasmtime/pull/3023
