### ISSUE TITLE
Cargo build is not working (or I'm wrong)

### ISSUE THREAD

**Issue by adsick** [bytecodealliance/wasmtime#2572]
```[adsick@panda Rust]$ git clone https://github.com/bytecodealliance/wasmtime.git```
```[adsick@panda Rust]$ cd wasmtime/```

```[adsick@panda wasmtime]$ pwd
/home/adsick/Rust/wasmtime
```

```[adsick@panda wasmtime]$ cargo build
error: failed to read `/home/adsick/Rust/wasmtime/crates/wasi-common/WASI/tools/witx/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by bjorn3** [comment]
You need to run `git submodule update --init` to checkout all submodules.

**Comment by adsick** [comment]
Yeah, that's the case, thank you)
I'm such a silly...
