### ISSUE TITLE
How to define extern func with referenced mutable arguments?

### ISSUE THREAD

**Issue by clearloop** [bytecodealliance/wasmtime#2578]
## Desc

Here I'm trying to define the `HostFuncType<T>` below as extern functions in `wasmtime`, but I don't know how to handle the `&mut T`

```rust
pub type HostFuncType<T> = fn(&mut T, &[Value]) -> Result<ReturnValue, HostError>;
```

It might be possible using `ExternRef<Arc<RefCell<T>>>` instead of doing something like this, but if there is any solution can pass the `&mut T` without breaking the arguments of the `HostFuncType<T>`?

**Comment by alexcrichton** [comment]
Thanks for the report! Can you clarify what you're trying to do, however? Host functions are generally defined with the [`Func`](https://docs.rs/wasmtime/0.21.0/wasmtime/struct.Func.html) type, which should have a number of examples on it as well. Are you unsure on how to create a `Func`, though?

**Comment by clearloop** [comment]
Thanks for your relying @alexcrichton ~

> Thanks for the report! Can you clarify what you're trying to do, however? Host functions are generally defined with the [`Func`](https://docs.rs/wasmtime/0.21.0/wasmtime/struct.Func.html) type, which should have a number of examples on it as well. Are you unsure on how to create a `Func`, though?

Yep,  I'm trying to implement a `Func` like:

```rust
fn my_host_func<T>(state: &mut T, args: &[val]) {}

fn main() -> Result<()> {
    // ...
  
    let my_extern_host_func = Func::wrap(&store, |state: &mut T, args: &[Val]| {
        my_host_func(state, args);
    });

    let instance = Instance::new(&store, &module, &[my_extern_host_func.into()])?;
    
    //...

    Ok(())
}
```

**Comment by alexcrichton** [comment]
When using `&[Val]` you'll want to use `Func::new`, and `state: &mut T` can't be given to you from wasm, so it can't be a parameter in the closure passed to `Func::wrap`. What you can do, however, is close over the `state` in the closure you provide to `Func::wrap`. If you need mutable access you'll need to use something like `RefCell` to account for the possibility that your closure is invoked recursively.

**Comment by clearloop** [comment]
> When using `&[Val]` you'll want to use `Func::new`, and `state: &mut T` can't be given to you from wasm, so it can't be a parameter in the closure passed to `Func::wrap`. What you can do, however, is close over the `state` in the closure you provide to `Func::wrap`. If you need mutable access you'll need to use something like `RefCell` to account for the possibility that your closure is invoked recursively.

Thanks! 

At least I'm certain about I can't pass `state` as a parameter now, I'll try to move `state` into the closure, afraid of not using `state` as a parameter, functions implemented in wasm could not recognize the signature of the host functions.

I'll do more practice and close this issue as I implement it.

Ref to https://github.com/bytecodealliance/wasmtime/issues/1678

**Comment by clearloop** [comment]
Is there any example of making a function with `&[Val]` as parameters into a `Func`?

**Comment by alexcrichton** [comment]
In tthis case `HostFuncTypeA` will need to take `&RefCell<T>`, not a by-value version.

**Comment by clearloop** [comment]
> In tthis case `HostFuncTypeA` will need to take `&RefCell<T>`, not a by-value version.

```
error[E0621]: explicit lifetime required in the type of `state`
  --> primitives/sandbox/src/imp/wasmtime/util.rs:93:2
   |
66 |     state: &RefCell<T>,
   |            ----------- help: add explicit lifetime `'static` to the type of `state`: `&'static RefCell<T>`
...
93 |     Func::new(store, wasmtime_sig(sig), func)
   |     ^^^^^^^^^ lifetime `'static` required

error: aborting due to previous error
```

If use `&RefCell`, it will require `'static`, I'm not sure if this situation is possible, not sure about if I have to add `'static` to `T`.

**Comment by clearloop** [comment]
Just got an example following #2491, https://github.com/chifflier/suricata/blob/295091c2e6598e84519d92b87dbe24d31c5fd070/rust/src/wasm/runtime_util.rs, but using `Func::wrap()`

**Comment by clearloop** [comment]
Closing this because I'm certain about the problem in my implementation is not a wasmtime problem now.
