### ISSUE TITLE
Release v0.22.1 to crates.io

### ISSUE THREAD

**Issue by apopiak** [bytecodealliance/wasmtime#2605]
v0.22.1 was released [here on github](https://github.com/bytecodealliance/wasmtime/releases/tag/v0.22.1)
but is missing [on crates.io](https://crates.io/crates/wasmtime)

**Comment by alexcrichton** [comment]
Thanks for the report! 0.22.1 just updated the lock file, however, so we won't be publishing to crates.io since that isn't necessary (it just affected the binary artifacts)
