### ISSUE TITLE
bench-api: configure the bench API using a struct

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#2619]
After discussing https://github.com/bytecodealliance/wasmtime/pull/2612, @fitzgen and I agreed that the best way to configure the bench-api shared library for running benchmarks is with a configuration `struct`. This has advantages such as:
 - the bench-api signatures explicitly indicate what is required for running a benchmark (e.g. working directory, where to capture stdout, what wasi modules are enabled, etc.)
 - we will avoid thrash on the bench-api signatures and confine this type of configuration change to the configuration `struct` (still an API change, but not as drastic)

One additional thought is to version the configuration `struct` in some way (first field is a `usize`?) to verify that both sightglass and the bench-api shared library are operating on the same understanding of how to configure the benchmark.

**Comment by abrown** [comment]
Another way of doing this would be to use environment variables to communicate from sightglass to the bench-api shared library, but this seems more prone to error.

**Comment by fitzgen** [comment]
Fixed in #2937
