### ISSUE TITLE
CNCF SIG-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [bytecodealliance/wasmtime#2628]
Hello wasmtime team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I think it would be great for you to present/discuss wasmtime at one of our meetings. For example, discuss things such as general architecture, use cases, current state of the project, etc. I think the community would greatly benefit from it.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by alexcrichton** [comment]
This is a pretty old issue at this point and I believe the event has since passed, so I'm going to close this.

**Comment by raravena80** [comment]
@alexcrichton it didn't happen yet. Can the wasmtime make it happen? Thx!

**Comment by alexcrichton** [comment]
Personally I feel this is best left to individuals rather than an open issue on the project. If you're interested in getting discussions/presentations I might recommend a Zulip thread for this rather than an issue report on GitHub.

**Comment by raravena80** [comment]
ok, thanks!
