### ISSUE TITLE
Cranelift: miscompilation for shl.i128 with zero shift amount

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2679]
### Steps to Reproduce

* Codegen `1u128 << 0` using `ishl.i128`

### Expected Results

The resulting value is 1.

### Actual Results

The resulting value is 0x10000000000000001.

### Versions and Environment

Cranelift version or commit: 98d3e6823f700aace38631c05f3afab3c5b07c76

Operating system: N/A

Architecture: x86_64

### Extra Info

This only happens for a zero shift amount. Any other amount is fine.

**Comment by bjorn3** [comment]
This is responsible for the miscompilation of https://github.com/bjorn3/rustc_codegen_cranelift/issues/1143.

**Comment by cfallin** [comment]
Closed with #2682.
