### ISSUE TITLE
Suggested upgrade path for 0.22 => 0.23 for WasiCtxBuilder::new()

### ISSUE THREAD

**Issue by softprops** [bytecodealliance/wasmtime#2691]
I'm in the process of upgrading both wasmtime and wasmtime-wasi  from 0.22 this was pretty straight forward except that I noticed `WasiCtxBuilder::new()` was removed. I'd previously used this to construct a new Wasi instance as follows

```rust
 let wasi = Wasi::new(
            &store,
            WasiCtxBuilder::new()
                .inherit_stdout()
                .inherit_stderr()
                .build()?,
        );
```

It's unclear what the upgrade path is. There wasn't an explicit callout in the [release notes](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0230)

I'm also noticing the docs hosted on docs.rs seem to stop publishing at [0.21](https://docs.rs/wasmtime-wasi/0.21.0/wasmtime_wasi/struct.WasiCtxBuilder.html#method.new)

**Comment by softprops** [comment]
for anyone else that hits this upgrade bump. You'll want to use a new provider crate https://crates.io/crates/wasi-cap-std-sync

The upgrade path is just

```diff
++ use wasi_cap_std_sync::WasiCtxBuilder;
-- use wasmtime_wasi::WasiCtxBuilder;
```

**Comment by sunfishcode** [comment]
Thanks for pointing this out! I've now fixed https://github.com/bytecodealliance/wasmtime/pull/2694 to add this to the RELEASES.md document.
