### ISSUE TITLE
peepmatic: rewrite type checking to use traditional unification

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#2695]
I originally punted on implementing this by hand and just gave all the type constraints to Z3, which was easy and is usually fast, but occasionally Z3 gets confused and hangs. Also the fuzzers have discovered inputs where Z3 hangs, which leads to noise in our fuzzing results.

We should rewrite Peepmatic's type checking to use the traditional approach to unifying type constraints via union-find.

**Comment by fitzgen** [comment]
When we do this, we should re-introduce the fuzz targets removed in https://github.com/bytecodealliance/wasmtime/pull/2696

**Comment by lqd** [comment]
@fitzgen this was probably fixed by mistake automatically by github because of the "when we fix" this issue text in that PR ? :)

**Comment by fitzgen** [comment]
Ah yes, thanks for the heads up!

**Comment by fitzgen** [comment]
Peepmatic was removed in https://github.com/bytecodealliance/wasmtime/pull/3543
