### ISSUE TITLE
x64: Test popcnt instruction with popcnt feature enabled

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2720]
https://github.com/bytecodealliance/wasmtime/blob/267d4a8bdbe46929afe9c33b20da4422087a631d/cranelift/filetests/filetests/isa/x64/popcnt.clif#L5

The x64 backend already supports it: https://github.com/bytecodealliance/wasmtime/blob/508f8fa5a921240ff2d25fd2eb859366c87834a3/cranelift/codegen/src/isa/x64/lower.rs#L2619

**Comment by AlexanderEkdahl** [comment]
I was browsing the feature tracker after reading the very interesting blog posts by cfallin. From what I understand this was implemented as part of https://github.com/bytecodealliance/wasmtime/commit/2275519cb19cacf3361a34fbcc9cb81f35f5ec1d? Or am I missing something?

**Comment by bjorn3** [comment]
Missed that test. The comment can be simply removed then.
