### ISSUE TITLE
Cranelift: Readthedocs.io is broken https://cranelift.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by mikedlr** [bytecodealliance/wasmtime#2725]
Thanks for filing an issue! Please fill out the TODOs below.

### `.clif` Test Case

N.A. this is documentation

### Steps to Reproduce

* First: go to https://cranelift.readthedocs.io/en/latest/
* Then: note lack of documentation
* Then: note lack of link to new documentation location

### Expected Results

https://cranelift.readthedocs.io/en/latest/ should contain either documentation or a link to where the documentation is now.

### Actual Results

> Welcome to Read the Docs
> 
> This is an autogenerated index file.
> 
> Please create an index.rst or README.rst file with your own content under the root (or /docs) directory in your repository.

### Versions and Environment

Cranelift version or commit: 797d2e2b (version at bottom of page)
 
Operating system: Chromium?  That count? 

Architecture: Semi-Traditional English

### Extra Info

All the best - thanks for doing FOSS software

**Comment by bjorn3** [comment]
It probably broke with the merge of Cranelift into the Wasmtime repo. You can find most of the docs at https://github.com/bytecodealliance/wasmtime/tree/main/cranelift/docs. The instruction docs can be found at https://docs.rs/cranelift-codegen/*/cranelift_codegen/ir/trait.InstBuilder.html.

**Comment by bnjbvr** [comment]
It would probably require access to the Readthedocs.io settings to configure a new repository where their CI would pull the code from, and put a small page

**Comment by sunfishcode** [comment]
As discussed on zulip, I've now removed the old readthedocs.io site, which we migrated off of in https://github.com/bytecodealliance/wasmtime/issues/1160.

**Comment by bnjbvr** [comment]
Thanks Dan! Search engines should catch up in a couple days.
