### ISSUE TITLE
Why is there no path_filestat_set_size in the WASI API?

### ISSUE THREAD

**Issue by marmistrz** [bytecodealliance/wasmtime#273]
To quote the spec:
```
__WASI_RIGHT_PATH_FILESTAT_SET_SIZE

The right to change a file's size (there is no __wasi_path_filestat_set_size()).

If __WASI_RIGHT_PATH_OPEN is set, includes the right to invoke __wasi_path_open() with __WASI_O_TRUNC.
```
Is there any reason why `path_filestat_set_size` is not present in the WASI API, when there's a corresponding right defined and both `path_filestat_get` and `path_filestat_set_times` are present? Currently the right is only used in `path_open`.

**Comment by sunfishcode** [comment]
I think such a function could be added if there's a use for it.

POSIX and popular POSIX-like platforms have no `truncateat` function, and applications can do `path_open` followed by `fd_filestat_set_size` to set the size.

**Comment by marmistrz** [comment]
Sounds fair enough. How about mentioning this rationale in the API docs? Can we just do it my a PR or do we need a more complicated procedure for that?

**Comment by sunfishcode** [comment]
If you'd like to submit a PR for this, that'd be great! The place to do it is now the [WASI repo](https://github.com/WebAssembly/WASI).

**Comment by bjorn3** [comment]
Is there value in keeping this open? https://github.com/WebAssembly/WASI/pull/180 has been merged.
