### ISSUE TITLE
Support OS page granularity of lazy memory initialization w/ uffd+pooling

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#2795]
Right now, when using the pooling instance allocator with the uffd feature, we always copy data segments into linear memory with a granularity of a wasm page. We should also support the granularity of an OS page.

(Motivation: for wizened modules that pointer chase through the heap, bringing in whole wasm pages is effectively pulling in a bunch of unrelated stuff.)

cc @peterhuene @alexcrichton

**Comment by alexcrichton** [comment]
uffd has since been removed, so I'm going to close this
