### ISSUE TITLE
Cranelift: Rework or remove the CodeSink interface for machinst backends

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2824]
The old backends used the `CodeSink` to emit instruction bytes and relocations as they were being generated. The machinst backends store everything in a `MachBuffer` before finally emitting the compiled code one byte at a time to the `CodeSink`. Unlike a plain `memcpy` this is not easily vectorizable. In addition there are a lot of branches to check if the current instruction has a relocation, can trap or is a call site.

I propose that either the `CodeSink` interface is removed in favor of giving the embedder direct access to the `MachBufferFinalized` or the `CodeSink` interface will get a `put_bytes` function that allows copying all bytes at the same time in combination with explicit offsets for the `reloc_external`, `trap` and `add_call_site` methods.

**Comment by cfallin** [comment]
Yes, agreed, this would be great!

We're somewhat constrained until we eventually remove the old backend infrastructure (which is on my TODO list but not my very highest priority at the moment). Once that happens, I think we'll want to look over the codegen-crate interfaces generally to see if there are any other possible efficiency improvements like this one.
