### ISSUE TITLE
Bugpoint: Try removing SourceLoc's

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/wasmtime#2827]
#### Feature

When using bugpoint to reduce clif ir turn something like

```
function u0:0() system_v {
                                block0:
@000c                               v0 = iconst.i32 0
@000c                               trap user0
}
```

into

```
function u0:0() system_v {
block0:
    v0 = iconst.i32 0
    trap user0
}
```

#### Benefit

Makes the reduced clif ir a bit easier to read.

**Comment by zleyyij** [comment]
I'm going to attempt this issue, absolutely no promises. I'll try to keep this updated if I give up.

**Comment by bjorn3** [comment]
If you haven't found it yet, I think a good place to implement this would be right after https://github.com/bytecodealliance/wasmtime/blob/81efaa738419c6e2078e4ad6d14df1e1461d415f/cranelift/src/bugpoint.rs#L841 (likely in a separate function called there) It really only needs to be done once and reverted if it no longer crashes.

**Comment by yerke** [comment]
Since https://github.com/bytecodealliance/wasmtime/pull/8883 was merged, should this issue be closed?
