### ISSUE TITLE
Importing dynamic dependencies?

### ISSUE THREAD

**Issue by vitiral** [bytecodealliance/wasmtime#284]
The web assembly docs say the following on [dynamic linking](https://webassembly.org/docs/dynamic-linking/)

> Since the manner in which modules are loaded and instantiated is defined by the host environment (e.g., the JavaScript API), dynamic linking requires use of host-specific functionality to link two modules. At a minimum, the host environment must provide a way to dynamically instantiate modules while connecting exports to imports.

Do you know of any plans for how WASI (and in particular wasmtime) handles these actions? I would expect that you would be able to pass dependencies via cmdline args (or a mapping file of some kind), although there might be other implementations which are preferred.

**Comment by sunfishcode** [comment]
Part of the story is [still being worked out at the standards level](https://github.com/WebAssembly/design/issues/1286).

Wasmtime doesn't expose this functionality at the command-line right now, though it does offer you a fair amount of flexibility at the crate API level, though it's also fairly low-level right now. We are working on developing a better abstraction around Libraries, which will join [Commands and Reactors](https://github.com/WebAssembly/design/issues/1286) as a third flavor of WebAssembly module, though the concepts are still evolving.

**Comment by vitiral** [comment]
thanks for the summary and your awesome work on this.

**Comment by alexcrichton** [comment]
I'm going to close this since the `wasmtime` API crate should support this.
