### ISSUE TITLE
Add testing back for the old backend on Windows in CI?

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#2844]
Thanks to a collaborative debugging session with @alexcrichton, we've identified what the issue was with my test case failing on Windows: it was a combination of using the old-backend (before the type-confusion bug had been fixed) and Windows, following #2806 that broke unwind information generation on windows old-backend (I'll send a PR for this).

So the real question is, should we re-add the CI on Windows for support of the old-backend?

- If the plan is to remove the old-backend before the next release, that means that it won't be available later, so there's not a real point in maintaining it.
- If the plan is to remove the old-backend *after* the next release, then it'd be nice to not break it in the future, and in this case it would be worthwhile adding it back in CI, in my opinion.

**Comment by cfallin** [comment]
@bnjbvr thanks for bringing this up, and I think it would be a good idea to do so!

The plan, FWIW, is definitely to take it slow with the removal of the old backend: I will (at some point, after at least one more release) write up an RFC to propose removing it, and we'll want to seek out any folks who are still depending on it (and possibly hold off until we can e.g. make sure the migration path to the new backend works for everyone). For now, the old backend is definitely still supported, even if it is not evolving further.

**Comment by akirilov-arm** [comment]
Obsoleted by #3009?

**Comment by cfallin** [comment]
Indeed!
