### ISSUE TITLE
[Question] Is wasmtime suitable to be used in a production environment?

### ISSUE THREAD

**Issue by NutshellySima** [bytecodealliance/wasmtime#2867]
I'm developing a plugin system for a database system in production to run untrusted user code as UDF similar to the one mentioned in [1].

I noticed that compared to Google's V8 js engine mentioned in the above-mentioned paper, wasmtime has a focus to be used in the environment outside of a browser. Thus, I'm more interested in embedding wasmtime than V8 in my application.

I noticed that there does not seem to be well-known industrial usage of wasmtime (compared to V8's use in Chromium and Cloudflare edge workers), but it seems to have experienced a fair amount of fuzzing[2], so I am wondering is wasmtime considered production-ready in the aspect of both reliability and performance?

As a newbie of Rust, I'm also quite worried about the vast dependencies of wasmtime and the possibility of a supply chain attack.

Thanks.

[1] Tian Zhang, Dong Xie, Feifei Li, and Ryan Stutsman. 2019. Narrowing the Gap Between Serverless and its State with Storage Functions. In ACM Symposium on Cloud Computing (SoCC ’19) (https://www.cs.utah.edu/~lifeifei/papers/shredder.pdf)
[2] https://bytecodealliance.org/articles/1-year-update

**Comment by alexcrichton** [comment]
This is a pretty old issue at this point, and for anyone still wondering the answer is "yes"
