### ISSUE TITLE
C API: incorrect documentation of wasm_module_serialize/wasm_module_deserialize

### ISSUE THREAD

**Issue by TerrorJack** [bytecodealliance/wasmtime#2894]
According to https://github.com/bytecodealliance/wasmtime/blob/main/crates/c-api/include/doc-wasm.h#L1500, `wasm_module_serialize`/`wasm_module_deserialize` are unimplemented, but that's not the case. Of course, users should favor `wasmtime_module_serialize`/`wasmtime_module_deserialize` when possible, but this is still a minor bug in documentation.

**Comment by alexcrichton** [comment]
Thanks for the report! I'll look to update this documentation in https://github.com/bytecodealliance/wasmtime/pull/2897 as I touch a whole bunch of other docs too.

**Comment by alexcrichton** [comment]
I think this was fixed in #2897
