### ISSUE TITLE
Tests for cranelift-wasm use wat files located outside the crate

### ISSUE THREAD

**Issue by olivierlemasle** [bytecodealliance/wasmtime#2910]
`cranelift-wasm`'s [tests](https://github.com/bytecodealliance/wasmtime/blob/7ef3ae2/cranelift/wasm/tests/wasm_testsuite.rs) use [wat files](https://github.com/bytecodealliance/wasmtime/tree/7ef3ae2903dcad960e17cee4b197f60805f95a07/cranelift/wasmtests) which are located outside the crate (in directory `../wasmtests`).

This causes test failures when the tests are executed outside wasmtime's repository, which is the case when packaging cranelift's crates (I'm currently in the process of packaging wasmtime & cranelift for Fedora).

Which option do you prefer?

1. Moving `wasmtests` in the crate `cranelift-wasm`.
   :heavy_plus_sign: That's the cleanest/easiest way to make the tests autonomous
   :heavy_minus_sign: The crate's size grows from 340 KB to 2.2 MB.
2. Making `wasmtests` an independent crate, published on crates.io, and adding it to `cranelift-wasm`'s dev-dependencies.
   :heavy_plus_sign: Crates that depend on `cranelift-wasm` do not have to fetch the test files.
   :heavy_minus_sign: We need to publish a crate with (wat) data only and no Rust...
3. Skip the tests if `../wasmtests` do not exist
   :heavy_plus_sign: No change in the packaging
   :heavy_minus_sign: The tests will not be executed outside the git repo

/cc @cfallin because you expressed interest on this Fedora packaging

**Comment by cfallin** [comment]
@olivierlemasle thanks for pointing this out!

I think I would favor Option 1 as the most canonical and the cleanest. Aside from the growth in size, it doesn't require us to publish a data-only crate, and it doesn't create a weird non-deterministic testing dependence on the filesystem outside the crate's root. We could eventually opt to split the tests out as a separate piece of infrastructure, however packaging them as part of the crate now doesn't prevent us from doing that later.

So: I'd be happy to review a PR that just moves the directory and alters the path in the testsuite driver. Thanks!

**Comment by abrown** [comment]
Fedora packaging would be nice; what repository this will be in, etc.?

**Comment by olivierlemasle** [comment]
@abrown It will be included in the main Fedora repository, starting with Fedora 34 normally. But there's still a long way to go. Here is my status: https://olem.fedorapeople.org/wasmtime/
