### ISSUE TITLE
aarch64 tests no longer running on CI

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#2938]
As of https://github.com/bytecodealliance/wasmtime/pull/2936 all our tests do is print out QEMU's version and then exit. Apparently if you have `QEMU_VERSION` set in the environment then qemu just exits out early. Who knew!

Wanted to open an issue for this so we don't forget, but I'm currently testing some other CI changes and hope to post a fix soon.

**Comment by cfallin** [comment]
That is quite the qemu feature. Thanks for noticing this!
