### ISSUE TITLE
Is there a way to free memory allocated with the `MemoryCreator` interface?

### ISSUE THREAD

**Issue by athei** [bytecodealliance/wasmtime#2995]
I don't see any possibility to de-allocate memory that was created using the `MemoryCreator` / `LinearMemory` interface. Shouldn't it be freed when the `Store` is dropped?

I am asking because I implemented `MemoryCreator` in order to make use of a low level macOS feature (purgable memory). In order to do so I need to allocate the 6GB virtual space as two consecutive memory mappings. I run out of virtual space to do so pretty quickly to fit those next to each other (rust runs tests all run in the same process). Or at least  the mach kernel sees no way to fit them next to each other once enough tests were run.

**Comment by alexcrichton** [comment]
I believe for your type that implements `LinearMemory` if you implement `Drop` that should be a hook to deallocate memory? Nothing will get dropped until the `Store` is dropped, but otherwise we should still run the destructors of all memories when the store is dropped.

**Comment by athei** [comment]
> I believe for your type that implements LinearMemory if you implement Drop that should be a hook to deallocate memory? 

Now I feel stupid. I will test that.

**Comment by athei** [comment]
Yes that did work. The `Drop` implementation is called. Thanks a lot.
