### ISSUE TITLE
Missing documentation for some "features"

### ISSUE THREAD

**Issue by davxy** [bytecodealliance/wasmtime#3036]
Hi there,

looks like some feature flags are not documented [here](https://docs.rs/wasmtime/0.28.0/wasmtime/#crate-features). 

In particular I'm interested in the "fiber" feature. What it is supposed to do exactly? 

Thanks for your awesome work.

**Comment by bjorn3** [comment]
I can't find a fiber feature declared in `Cargo.toml`.

**Comment by davxy** [comment]
Sorry, my fault. "wasm-time" fiber is a package required by the async feature.
