### ISSUE TITLE
Add memory limit per `Store`

### ISSUE THREAD

**Issue by bkolobara** [bytecodealliance/wasmtime#3040]
Is it possible to add a memory limit to a `Store`, similar to the `fuel` limit?

I'm building a platform for running untrusted Wasm code and I need to limit the memory usage of a particular Store (heap & tables). It could work similar to the `fuel` property, if a memory limit is reached the call to a Wasm function would trap.

Currently I'm working around it by forcing users to import a memory and table, but that's not ideal because you can't use multi-memory/table modules and there is no way to enforce` table + heap < max_memory`, only `table < max_table && heap < max_heap`

**Comment by peterhuene** [comment]
Hi @bkolobara.

While it doesn't inherently trap, [Store::limiter](https://docs.rs/wasmtime/0.28.0/wasmtime/struct.Store.html#method.limiter) can be used to configure a resource limiter for the store that will be notified for any attempt to grow a linear memory or table in the store.

If the resource limiter prevents the requested operation, the `memory.grow` and `table.grow` instructions will behave as if limits have been reached, at which point it's up to the Wasm program to handle it, either by trapping or internally GC'ing or whatever it wants to do in low-memory conditions.

Would that suffice for your use-case or would additional functionality be needed?

**Comment by bkolobara** [comment]
This is exactly what I need. I keep looking at the docs every day, but somehow missed this limiter :)

Thanks @peterhuene!
