### ISSUE TITLE
assert failure on modern intel cpus with avx512_bf16

### ISSUE THREAD

**Issue by programmerjake** [bytecodealliance/wasmtime#3053]
See upstream: https://github.com/gz/rust-cpuid/issues/45#issuecomment-873001709
Running into this issue via wasmtime PyPI package used by yowasp-yosys.
See also: https://github.com/YoWASP/yosys/issues/22

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like this is coming from the raw-cpuid crate which was removed in https://github.com/bytecodealliance/wasmtime/pull/2607. Looking [at yosys](https://github.com/YoWASP/yosys/blob/develop/pypi/setup.py#L40) I think an older version of Wasmtime is being pulled in, so I think that this isn't a bug in Wasmtime itself but perhaps a place where the python wasmtime dep needs to be updated?

**Comment by programmerjake** [comment]
Ok, thanks!
