### ISSUE TITLE
Document the impact of the fields on ModuleLimits and InstanceLimits

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#3080]
Wasmtime's `ModuleLimits` and `InstanceLimits` structs in [config.rs](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/config.rs#L24) can be used to tweak various limits imposed on modules/instances when using the pooling instance allocator. Unfortunately it's not easy to tell what the impact is of changing any of these limits. As an example, the limit on functions has a default of 10k; how bad is the impact of increasing that limit? Is it a relatively minor increase in module size, or a meaningful difference in instance size?

@peterhuene, do you think it's relatively straightforward to add a sentence or two on the impact of each of these?

**Comment by peterhuene** [comment]
Absolutely, I'll add more context as to what the cost is for increasing these values.
