### ISSUE TITLE
A bit of inconsistency in the WASI tutorial 

### ISSUE THREAD

**Issue by TheLeonsver1** [bytecodealliance/wasmtime#3093]
In here: https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-tutorial.md

In the C version you have
`fprintf(stderr, "usage: %s <from> <to>\n", argv[0]);`

In the Rust version you have 
`eprintln!("usage: {} <input_file> <output_file>", program);`

In this section: https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-tutorial.md#executing-in-wasmtime-runtime you are showing the output of the C version, which isn't the same as the output of the Rust version(`input_file` vs `from` and `output_file` vs `to`).
It is a minor issue but people looking only at the Rust code could be confused as to why the output is not what they expect.

**Comment by pchickey** [comment]
Thanks for the report, this is fixed now.
