### ISSUE TITLE
Debug info are no longer valid after fork

### ISSUE THREAD

**Issue by shingfeel** [bytecodealliance/wasmtime#3118]
I use nginx to process http requests. and load wasm file, set "wasmtime_config_debug_info_set" flag, compile modules and link modules in main process. Then fork and call wasm func in child process. 
When i use a debugger: gdb -p [pid] to attach to child process and want to beak point in wasm function. It failed with:"Function "xxxxxx" not defined"。It seem's debuger can't find debug_info in child process.
I wonder why debuger work fine in main process and don't work in child process?

**Comment by alexcrichton** [comment]
Wasmtime [manually has to tell GDB](https://github.com/bytecodealliance/wasmtime/blob/b5f7b2f86a828fd777e3d022e7e1066e9291c2fa/crates/runtime/src/jit_int.rs#L103-L120) about code that we've generated (along with debuginfo), but maybe GDB doesn't preserve this information across forks? Wasmtime doesn't do anything after a fork to re-inform GDB about dynamically generated code.

My guess is that GDB "forgets" about dynamically loaded code after a fork and we'd have to re-inform it of code, but that's just a hunch and I don't actually know how gdb works in this regard.

**Comment by shingfeel** [comment]
thank @alexcrichton for your answer.

It seems GDB really "forgets" to dynamically loaded code after fork. in my code, recompile wasm module after fork and GDB now working correctly.
