### ISSUE TITLE
fuzz: log WebAssembly modules to files instead of to stdout or `log::debug`

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#3140]
@alexcrichton suggested moving to use `log_wasm` to output the contents of fuzzed WebAssembly modules instead of printing them to stdout or `log::debug` as is done currently. There are some advantages to doing this, mainly it is very convenient to run the Wasm file in `wasmtime` directly or upload it somewhere. Any opinions on this, @fitzgen? If we all agree then I will do this refactoring after #3124 is resolved.

**Comment by fitzgen** [comment]
I would only add that this should only be done when debug logging is enabled, so that we aren't doing a bunch of file I/O on every iteration by default.

**Comment by abrown** [comment]
Yeah, that's a good point. I also saw a few cases in there where we log when something goes wrong--should we do both?

**Comment by fitzgen** [comment]
Yeah, we just want to make sure not to do any file I/O on the typical, error-free paths.
