### ISSUE TITLE
Skip CI if only parts of the repo were modified that aren't tested

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#3166]
We currently run CI unconditionally on all changes, but there are parts of the repository that aren't tested, and never will be. It's possible that for now the only part this applies to is the newly-introduced `meetings` directory, though there may be others for all I know.

**Comment by alexcrichton** [comment]
I ended up inadvertently doing this in https://github.com/bytecodealliance/wasmtime/commit/9e8e0e8352a840df5d75d1385cb3144f9a3b13e7, so I think this is covered now.
