### ISSUE TITLE
fuzz: fully fuzz Wasmtime against the spec interpreter

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#3175]
https://github.com/bytecodealliance/wasmtime/pull/3124 adds the initial steps for fuzzing Wasmtime against the official WebAssembly spec interpreter. There are several pieces to finish for more complete coverage:

- [ ] After execution, compare the memory contents of Wasmtime against the memory contents of the spec interpreter
- [ ] After execution, compare the global values of the module in Wasmtime against those in the spec interpreter
- [x] Add support in the `wasm-spec-interpreter` crate for `v128` types; this implies turning on SIMD for the `differential_spec` fuzz target as well as merging the Wasm SIMD proposal into https://github.com/bytecodealliance/wasm-spec-mirror.
- [ ] Add support in the `wasm-spec-interpreter` crate for `ref` types

**Comment by abrown** [comment]
SIMD support added by @conrad-watt in #3843.

**Comment by alexcrichton** [comment]
This is more-or-less done now modulo reference types, but that seems ok for now so I'm going to close.
