### ISSUE TITLE
[lightbeam] the lightbeam compiler doesn't work

### ISSUE THREAD

**Issue by lei-april** [bytecodealliance/wasmtime#3181]
### Test Case

Example for C embedding from the official doc site: https://docs.wasmtime.dev/examples-c-hello-world.html

With a few changes to enable the lightbeam compiler:
```diff
48c48,50
<   wasm_engine_t *engine = wasm_engine_new();
---
>   wasm_config_t* config = wasm_config_new();
>   wasmtime_config_strategy_set(config, WASMTIME_STRATEGY_LIGHTBEAM);
>   wasm_engine_t *engine = wasm_engine_new_with_config(config);
```

### Steps to Reproduce

Compile and run the above example, using wasmtime's main branch with lightbeam enabled.

### Expected Results

The example runs correctly.

### Actual Results

The compiler panics:
```
Initializing...
Compiling module...
thread '<unnamed>' panicked at 'not implemented', crates/lightbeam/wasmtime/src/lib.rs:224:9
```

### Versions and Environment

Wasmtime version or commit: 44f9ccd31640f8d88073d7e57347573d4fd01c14

Operating system: Linux

Architecture: x86-64

**Comment by lei-april** [comment]
> Lightbeam is unmaintained and has probably been broken for quite a while.

So is there any plan to fix it?

**Comment by bjorn3** [comment]
Not that I am aware of.

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
