### ISSUE TITLE
Wasmtime doesn't work on Linux AArch64 with PAC enabled

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#3183]
As of https://github.com/bytecodealliance/wasmtime/pull/3180 Wasmtime will stop workong on AArch64 Linux with PAC enabled. Debugging this issue at https://bytecodealliance.zulipchat.com/#narrow/stream/217126-wasmtime/topic/arm64.2C.20pointer.20auth.2C.20unwinding seems to indicate that this is a libgcc bug which only accidentally worked before because the `DW_OP_lit0` we specify for register 34, the pointer auth enabling register, just happened to show up at an even address in memory. After #3180 the encoding of the FDE is changing just enough that some expressions show up at odd addresses, which tricks libgcc to thinking that pointer authentication is enabled, when it actually isn't.

This commit is tracking improving this by either figuring out a workaround for gcc, implementing pointer authentication, or something similar.

**Comment by akirilov-arm** [comment]
[An associated libgcc issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104689) has been created.

**Comment by akirilov-arm** [comment]
And [a patch](https://gcc.gnu.org/pipermail/gcc-patches/2022-May/594414.html) has been posted.

**Comment by akirilov-arm** [comment]
The fix has been [committed](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=0d344b557604e966dc7f91739881f03e1f221efd).
