### ISSUE TITLE
Support for debugging wasi produced by tinygo

### ISSUE THREAD

**Issue by ckaznocha** [bytecodealliance/wasmtime#3184]
### Test Case

[test.wasm.zip](https://github.com/bytecodealliance/wasmtime/files/6978549/test.wasm.zip)

### Steps to Reproduce

```
> gdb --args wasmtime -g test.wasm  
```

### Expected Results

The ability to attach lldb or gdb.

### Actual Results

```
Reading symbols from wasmtime...
(No debugging symbols found in wasmtime)
(gdb) 
```

```sh
> WASMTIME_BACKTRACE_DETAILS=1 wasmtime -g test.wasm
Error: failed to run main module `test.wasm`

Caused by:
    0: Debug information error
    1: comp_dir

```

### Versions and Environment

Wasmtime version or commit: 0.29.0

Operating system: macOS

Architecture: amd64

### Extra Info

```sh
> ./tinygo version
tinygo version 0.20.0-dev-5e5ce98d darwin/amd64 (using go version go1.16.6 and LLVM version 11.0.0)
```

Source code:
```Go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, World!")
}
```

Command to produce the wasm file:
```sh
> tinygo build -target=wasi -opt=1 -o test.wasm 
```

**Comment by bjorn3** [comment]
The debuginfo seems to be missing a `DW_AT_comp_dir`. Wasmtime expects it to exist: https://github.com/bytecodealliance/wasmtime/blob/d7053ea9c71b4a240c1966bd1bd9424e36a44f28/crates/debug/src/transform/line_program.rs#L671 I think it is valid to omit it though for as long as it is not referenced from the line program (it isn't for this file)
