### ISSUE TITLE
Cranelift interpreter: handle overflows during division

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#3191]
The Cranelift interpreter appears not to properly handle an overflow (from e.g. `INT_MIN / -1`), resulting in a panic rather than  an explicit error type returned to the caller. Found via fuzzing.

In the implementation [here](https://github.com/bytecodealliance/wasmtime/blob/0313e30d7607439183fe837502525454aafbfd06/cranelift/interpreter/src/value.rs#L352-L358), it appears that we need to check for this case specifically.

**Comment by cfallin** [comment]
cc @abrown

**Comment by abrown** [comment]
also cc: @afonso360
