### ISSUE TITLE
CI windows builds failing

### ISSUE THREAD

**Issue by frehberg** [bytecodealliance/wasmtime#32]
For latest pull request #31 , 4 windows builds are failing for different reasons eg: gnu-build finding sh.exe  in wrong directory, or for native-build the preprocessor cannot find header file windows.h
https://ci.appveyor.com/project/CraneStation/wasmtime/builds/20665286

**Comment by sunfishcode** [comment]
Yes, the appveyor build was an experiment, though there appear to be problems building dependent crates that use cmake, such as wabt. I've now disabled the appveyor builds so that they don't get in the way.

**Comment by alexcrichton** [comment]
We've got Windows CI up and running now :)
