### ISSUE TITLE
[Help] Use struct as argument

### ISSUE THREAD

**Issue by silence-coding** [bytecodealliance/wasmtime#3200]
How to use struct as a parameter? I don't find any useful information in the example.

```
#[derive(Debug, Default)]
#[repr(C)]
pub struct Msg {
    id: u64,
    data: String,
}

use model::Msg;

#[no_mangle]
pub extern "C" fn print_msg(msg: Msg) {
    println!("Hello: {:?}", msg);
}

pub fn test_struct() -> Result<(), Box<dyn Error>> {
    let engine = Engine::default();
    let mut linker = Linker::new(&engine);
    wasmtime_wasi::add_to_linker(&mut linker, |s| s)?;
    let module = Module::from_file(&engine, "target/wasm32-wasi/debug/struct.wasm")?;
    let wasi = WasiCtxBuilder::new()
        .inherit_stdio()
        .inherit_args()?
        .build();
    let mut store = Store::new(&engine, wasi);
    let instance = linker.instantiate(&mut store, &module)?;
    let greet = instance.get_typed_func::<Msg, (), _>(&mut store, "print_msg")?;
    greet.call(&mut store, Msg::default())?;
    Ok(())
}

```

```
error[E0277]: the trait bound `Msg: WasmTy` is not satisfied
  --> run\src\struct2.rs:17:26
   |
17 |     let greet = instance.get_typed_func::<Msg, (), _>(&mut store, "print_msg")?;
   |                          ^^^^^^^^^^^^^^ the trait `WasmTy` is not implemented for `Msg`
   |
   = note: required because of the requirements on the impl of `WasmParams` for `Msg`
```

**Comment by bjorn3** [comment]
You will need to serialize the struct into raw bytes on one side and write it to the linear memory and then pass the address of the linear memory. On the wasm side you can then load the struct.

Alternatively I think you can use wiggle: https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime

**Comment by alexcrichton** [comment]
Thanks for the report here, but this is a scenario where the literal way the wasm module is communicated with is much more strict than using a type. If you'd like to explore typed communication between the runtime and a wasm module this is what the WebAssembly [interface types proposal](https://github.com/webassembly/interface-types) is for. You can demo and use that today with [`witx-bindgen`](https://github.com/bytecodealliance/witx-bindgen) which should eanble what you've got here with a `Msg` structure.

If neither of those helps though let us know and we can try to figure out a solution!

**Comment by silence-coding** [comment]
@alexcrichton Thanks

**Comment by silence-coding** [comment]
@alexcrichton I read the wix-bindgen. It seems that the map and set types are not supported. Is there a perfect solution? For example, I want to use the request object of [hyper](https://github.com/hyperium/hyper) as an argument.

**Comment by silence-coding** [comment]
@bjorn3 Does this mean that I understand the memory status of each complex parameter myself? Is there an example for me to learn? I just started to get into Wasmtime recently and found that there was a lack of perfect development materials. Thank you very much.

**Comment by alexcrichton** [comment]
@silence-coding yes the interface types grammar is intentionally not as rich as having sets/maps. For that you'll want to use lists, you won't be able to take types off the shelf from libraries and pass them over a wasm boundary.

**Comment by silence-coding** [comment]
Well, I don't think wasm needs rich data types, but some common ones, I think, can be reasonably provided.
