### ISSUE TITLE
Mac M1 Docker crash

### ISSUE THREAD

**Issue by otaviopace** [bytecodealliance/wasmtime#3203]
### Test Case

I've created a repo just for this: https://github.com/otaviopace/mac-m1-wasmtime-docker.

To reproduce the error, one should build the docker image in a linux computer, than try to run it on a Mac M1 computer.

For moving the image from one computer to the other, Docker Hub can be used, but [this](https://stackoverflow.com/questions/24482822/how-to-share-my-docker-image-without-using-the-docker-hub/48856787#48856787) works the same.

### Steps to Reproduce

* Build docker image on Linux computer
* Load/pull built image on a Mac M1 computer
* Run the container

### Expected Results

`wasmtime` shouldn't crash from running amd64 on a Mac M1 computer.

### Actual Results

`wasmtime` crashes on the traphandlers file, like this:

```
thread 'cool thread name' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `0`: registering new sigaltstack failed', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-0.27.0/src/traphandlers/unix.rs:238:9
```

### Versions and Environment

Wasmtime version or commit: 0.27.0

Operating system: Mac M1

Architecture: arm64

### Extra Info

This issue has been created because we're having this problem on `graph-node`: https://github.com/graphprotocol/graph-node/issues/2325.

The weird thing is that we had no issues on the M1 running a Docker image built in Linux with `wasmtime` before. We have an automated process to generate the images for `graph-node`, and at some point in time, new images started to break without us changing this Docker automation, `wasmtime` version, or Docker for Mac version.

To isolate the problem, I've created a repository that has a simple example with the same issue.

**Comment by cfallin** [comment]
Interesting -- it looks like this is an x86-64 binary running (via Rosetta 2) on M1 hardware? Does Docker on M1 run an x86-64 Linux kernel in a VM (as I think it works on Intel Mac hardware) or something else?

@bnjbvr is our resident has-M1-hardware-and-knows-how-to-use-it person for M1 issues -- Ben, what do you think?

**Comment by alexcrichton** [comment]
If you can test out a custom build, https://github.com/bytecodealliance/wasmtime/pull/3204 may help by providing the error code that `sigaltstack` is failing with (although I don't think it will help too much here in determining a cause...)

**Comment by otaviopace** [comment]
@cfallin on the questions you've pointed out

> it looks like this is an x86-64 binary running (via Rosetta 2) on M1 hardware?

Yes, it the problem seems to be related to Rosetta 2 translation.

> Does Docker on M1 run an x86-64 Linux kernel in a VM (as I think it works on Intel Mac hardware) or something else?

I don't think Docker runs a VM for linux, I think it probably just uses Rosetta for the translation, but I'm not completly sure.

@alexcrichton Thank you so much for the debug build, I'll try it and post the results here 🙂

**Comment by peterhuene** [comment]
From Docker:

```
If you are trying to run Intel-based containers on an M1 machine, they can sometimes crash.
We are using a piece of software called qemu to emulate Intel chips on M1 but it occasionally
fails to run the container. Where possible we recommend sticking to arm64 containers on M1
machines; they will also be faster.
```

From some Google searches, it seems that QEMU might have issues with `signaltstack` on M1 for x86-64 containers (seeing references to `EINVAL` for other projects).

I think this might not be a Wasmtime issue currently.

**Comment by otaviopace** [comment]
@alexcrichton , with your debug change the log went from:

```
registering new sigaltstack failed
```

to this:

```
registering new sigaltstack failed: Invalid argument (os error 22)
```

Does this mean the Rosetta 2 translation expects a different argument for `sigalstack`?

**Comment by otaviopace** [comment]
Unfortunetally this really isn't a problem with `wasmtime` itself, I'll close this for now, thanks a lot for the help ❤️

**Comment by peterhuene** [comment]
22 is `EINVAL`.

My gut tells me that the bug fixed by this [QEMU commit](
I also found [this QEMU commit](https://github.com/qemu/qemu/commit/ce437484fced8292d90497d7b740335428fffed6) seems relevant as something that could lead to misinterpretation of a field like `ss_flags`.

That fix went into QEMU 5.2; Docker For Mac seems to package QEMU 5.0.1.

**Comment by otaviopace** [comment]
How do you know which version of QEMU does Docker for Mac use?

I would like to keep an eye where I can know this version bump happened.

**Comment by peterhuene** [comment]
I pulled it from the [Docker for Mac's release notes](https://docs.docker.com/desktop/mac/release-notes), last upgrade mentioning QEMU was 3.2.0, so I assume it hasn't been bumped since.

**Comment by otaviopace** [comment]
I've created an issue in Docker for Mac to know if they plan or not to do this version bump soon (of QEMU).

So if anyone wants to keep an eye/track this, here it is: https://github.com/docker/for-mac/issues/5919
