### ISSUE TITLE
Cranelift: cls instruction is not correctly implemented  for `i16` and `i8` in any backend.

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#3248]
Hey, @dheaton-arm [reported](https://bytecodealliance.zulipchat.com/#narrow/stream/217117-cranelift/topic/interpreter/near/250753986) an interesting implementation detail from the aarch64 backend on the `cls` instruction. However, further testing shows that this instruction is not correctly implemented in any backend for `i16` and `i8` types.

### `.clif` Test Case

```
test run
target aarch64
target x86_64 machinst
target s390x

function %cls_i16(i16) -> i16 {
block0(v0: i16):
    v1 = cls.i16 v0
    return v1
}
; run: %cls_i16(0x0000) == 15
; run: %cls_i16(0xFFFF) == 15
; run: %cls_i16(0x8000) == 0
; run: %cls_i16(0xC000) == 1
; run: %cls_i16(0x4000) == 0
; run: %cls_i16(0x2000) == 1


function %cls_i8(i8) -> i8 {
block0(v0: i8):
    v1 = cls.i8 v0
    return v1
}
; run: %cls_i8(0x00) == 7
; run: %cls_i8(0xFF) == 7
; run: %cls_i8(0x80) == 0
; run: %cls_i8(0xC0) == 1
; run: %cls_i8(0x40) == 0
; run: %cls_i8(0x20) == 1
```

### Steps to Reproduce

`clif-util test ./the-above.clif`

### Expected Results

All three backends should pass the run tests.

### Actual Results

x86_64: `cls` is not implemented, for either type.
aarch64: Returns the wrong results (i.e. ` run: %cls_i16(0x0000) == 15` returns `31`)
s390x: Returns the wrong results (i.e. ` run: %cls_i16(0x0000) == 15` returns `4096`)

### Versions and Environment

Cranelift version or commit: main
Operating system: Linux / qemu emulator for aarch64 and s390x
Architecture: x86_64 / aarch64 / s390x

**Comment by sparker-arm** [comment]
At least for AArch64, we can't use a 1-1 mapping between CLIF and machine instructions when using a type smaller than a naturally supported register width (32 and 64-bits). I think we need to expand this instruction in the case that the target doesn't directly support the type, something like:
cls (x) -> sub (cls (swiden (x)), bitwidth(x))
