### ISSUE TITLE
Mobile Version? Or Swift Package?

### ISSUE THREAD

**Issue by Ge-Ne-On** [bytecodealliance/wasmtime#3284]
Thanks for filing a feature request! Please fill out the TODOs below.

#### Feature

TODO: Brief description of the feature/improvement you'd like to see in
Cranelift/Wasmtime.

#### Benefit

TODO: What is the value of adding this in Cranelift/Wasmtime? What problems does
it solve?

#### Implementation

TODO: Do you have an implementation plan, and/or ideas for data structures or
algorithms to use?

#### Alternatives

TODO: What are the alternative implementation approaches or alternative ways to
solve the problem that this feature would solve? How do these alternatives
compare to this proposal?

**Comment by bjorn3** [comment]
What do you mean with mobile version?

**Comment by fitzgen** [comment]
Filling out the TODOs in the issue template would really help maintainers understand what you're asking for.

**Comment by alexcrichton** [comment]
I'm going to close this for now since this is a pretty old issue and it doesn't have information necessary to make this actionable. If you're interested in Swift support and/or building Wasmtime for iOS or Android I think it would be good to file separate issues for that specifically.
