### ISSUE TITLE
[Question] Stable release 1.0.0

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasmtime#3311]
Hi all,

I watching this project long time ... and still it has no stable release ...
When do you plan make `1.0.0` wasmtime ?

**Comment by pchickey** [comment]
Great question. We have an RFC where we are working this out: https://github.com/bytecodealliance/rfcs/pull/14

**Comment by alexcrichton** [comment]
I'm going to close this in favor of discussion on the RFC
