### ISSUE TITLE
Remove the global exports mechanism

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#332]
The global exports mechanism is a stop-gap solution that we should replace with something more flexible.

Longer term, better mechanisms available through interface types and related things will give us better ways to express this. However for now, in talking with @steveeJ, I think the best way to proceed is to have callers pass their vmctx into callees, so that WASI routines can use them to obtain the linear memories of their callers, rather than using the global exports mechanism.

**Comment by alexcrichton** [comment]
Done in https://github.com/bytecodealliance/wasmtime/pull/789
