### ISSUE TITLE
wasmtime will support compile and execute  AOT format wasm module?

### ISSUE THREAD

**Issue by flyflypeng** [bytecodealliance/wasmtime#3328]
I read the post [Bytecode Alliance: One year update](https://bytecodealliance.org/articles/1-year-update), which have announced that "The Lucet and Wasmtime teams join forces", so I have a question, wasmtime will port the benefits of the lucet runtime to support AOT style execution model?

**Comment by tschneidereit** [comment]
This is indeed implemented now: you can use `wasmtime compile your.wasm` and then run it with `wasmtime run your.cwasm`, or load it in your embedding.

**Comment by tschneidereit** [comment]
I'll close this issue as I don't think there's anything else to address here, but feel free to open new issues if problems arise in using Wasmtime! :)

**Comment by peterhuene** [comment]
Please note: currently running a AOT compiled module using `wasmtime run` is not supported (this changed [back in April](https://github.com/bytecodealliance/wasmtime/pull/2858)) as it is considered an unsafe operation to deserialize a pre-compiled module (see comment [here](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/module.rs#L438-L468)).

Right now you will need to write your own version of `wasmtime run` that uses `Module::deserialize` (or better yet the recently added `Module::deserialize_file`) to load the module.

**Comment by peterhuene** [comment]
Actually, it looks like @alexcrichton already put up a PR to restore this functionality to `wasmtime run` (that's what I get for going from oldest to newest in my github notifications 🙃).
