### ISSUE TITLE
Intermittent failures in `wasi_tokio::poll_oneoff_files` on Apple M1

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/wasmtime#3339]
The `wasi_tokio::poll_oneoff_files` intermittently fails on the Apple M1, e.g. in https://buildkite.com/embark-studios/wasmtime-aarch64-apple-darwin/builds/115#7814f129-a70a-4027-82c4-5af72ba9c34b:

```
failures:

---- wasi_tokio::poll_oneoff_files stdout ----

preopen: "/var/folders/5z/j5zd8w8s7cg2hw5z78xxq0zm0000gp/T/wasi_common_poll_oneoff_files5PpIrI"
guest stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`: should return 2 events, got: [Event { userdata: 1, error: 0, type: 1, fd_readwrite: EventFdReadwrite { nbytes: 1, flags: 0 } }]', src/bin/poll_oneoff_files.rs:128:5

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

===

Error: error while testing Wasm module 'poll_oneoff_files'

Caused by:
    wasm trap: unreachable
    wasm backtrace:
        0: 0xa43d - <unknown>!__rust_start_panic
    note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable to may show more debugging information    

thread 'wasi_tokio::poll_oneoff_files' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/test/src/lib.rs:194:5

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    wasi_tokio::poll_oneoff_files
```

**Comment by cfallin** [comment]
cc @sunfishcode -- IIRC this test has some timing-dependent nondeterminism. Thoughts on making it more robust here?

**Comment by sunfishcode** [comment]
Hmm, it may make sense to make this test retry the `poll` if the first one doesn't return all the expected events. Because `poll` doesn't generally guarantee to return all the events at once, even if multiple events have occurred. I'll look into this.

**Comment by sunfishcode** [comment]
I don't have a machine where the intermittent failure is visible, but I submitted #3346 with a speculative fix for this.

**Comment by alexcrichton** [comment]
🙏-ing this is good to go,  so closing (can reopen if this arises again)

**Comment by bnjbvr** [comment]
Sorry, forgot to follow up about this: I've ran the test 100 tests in debug and 100 tests in release mode and saw no failures. Thanks for the fix!
