### ISSUE TITLE
Regression :  GDB/JIT symbols required to bind to debugger must be exported on Windows so debugger can bind.

### ISSUE THREAD

**Issue by adv-sw** [bytecodealliance/wasmtime#3371]
crates/runtime/src/helpers.c | 12 ++++++++++--
 1 file changed, 10 insertions(+), 2 deletions(-)

diff --git a/crates/runtime/src/helpers.c b/crates/runtime/src/helpers.c
index 4865928a1..c743e244e 100644
--- a/crates/runtime/src/helpers.c
+++ b/crates/runtime/src/helpers.c
@@ -42,7 +42,12 @@ void wasmtime_longjmp(void *JmpBuf) {
 // Note the `weak` linkage here, though, which is intended to let other code
 // override this symbol if it's defined elsewhere, since this definition doesn't
 // matter.
-#ifndef CFG_TARGET_OS_windows
+
+
+#ifdef CFG_TARGET_OS_windows
+// ADV_SW_PATCH - export required for external access.
+__declspec(dllexport)
+#else
 __attribute__((weak, noinline))
 #endif
 void __jit_debug_register_code() {
@@ -61,7 +66,10 @@ struct JITDescriptor {
 // Note the `weak` linkage here which is the same purpose as above. We want to
 // let other runtimes be able to override this since our own definition isn't
 // important.
-#ifndef CFG_TARGET_OS_windows
+#ifdef CFG_TARGET_OS_windows
+// ADV_SW_PATCH - export required for external access.
+__declspec(dllexport) 
+#else
 __attribute__((weak))
 #endif
 struct JITDescriptor __jit_debug_descriptor = {1, 0, NULL, NULL};

**Comment by alexcrichton** [comment]
Fixed by https://github.com/bytecodealliance/wasmtime/pull/3373
