### ISSUE TITLE
Cranelift: "this" not populated correctly during debug session.

### ISSUE THREAD

**Issue by adv-sw** [bytecodealliance/wasmtime#3419]
Unzip test case.

On Linux :

Run make_wasm.sh to build

Optional lldbg debugging front end - tested linux & windows : https://github.com/adv-sw/lldbg
Modify dbg_wasm.sh to run under lldb direct instead of new lldbg front end if you want to skip that - same command line, just s/lldbg/lldb

Run dbg_wasm.sh to run under debugger.

Place breakpoint in test.cpp in Thing constructor on assignment m_i = i;

Start program, hit breakpoint.

Inspect "this"

### Expected Results
Should contain single integer member m_i

### Actual Results

"this" is empty - not populated correctly.

Console : warning: `this' is not accessible (substituting 0)

LLDB is complaining "this" is not a standard pointer. LLDB refuses to evaluate non-standard this & self pointers.

Hence we need a workaround to resolve from sandbox pointer, which is provided here :

https://github.com/bytecodealliance/wasmtime/commit/92a10d1ace70fe75c3e2c646ea613168fc417851

### Versions and Environment

Cranelift & wasmtime trunk as of 3/10/21
lldb trunk as of late Sept 21.
lldbg trunk

Operating system:  Windows 11 & Ubuntu tested.

Architecture: x64
[test.zip](https://github.com/bytecodealliance/wasmtime/files/7286614/test.zip)

Severe C++ web assembly development productivity issue because webdevs need to be able to effectively debug their code.

**Comment by adv-sw** [comment]
Resolved here. 

https://github.com/bytecodealliance/wasmtime/commit/92a10d1ace70fe75c3e2c646ea613168fc417851

Please review/merge.

**Comment by bacongobbler** [comment]
looks like https://github.com/bytecodealliance/wasmtime/pull/3443 has been merged, so this can be closed.

**Comment by cfallin** [comment]
Yes indeed, thank you for pointing this out!
