### ISSUE TITLE
no_std support for my OS

### ISSUE THREAD

**Issue by ethindp** [bytecodealliance/wasmtime#3451]
I'm working on a hobby operating system and want to develop my drivers in something other than native code. I'd really like to go for web assembly but there are no good web assembly runtimes for no_std, and the only one I know of -- Wasmi -- appears very confusing to use and to work with. This is (possibly another) use-case for no_std support. Can this be done right now or do I have to try to figure out wasmi? (I'm not aware of any other Wasm runtimes, but if there's one I just don't know about, well...).

**Comment by bjorn3** [comment]
Cranelift could get no_std support, but wasmtime can't as it depends on the OS for example for mapping memory with the right priveleges.

**Comment by alexcrichton** [comment]
I realize it's been years since this was originally opened, but in case anyone cc'd on this issue is still interested I've opened https://github.com/bytecodealliance/wasmtime/issues/8341 with a proposal to add no_std support for wasmtime which would address this issue as-stated.

**Comment by alexcrichton** [comment]
This is done now with documentation [here](https://docs.wasmtime.dev/stability-platform-support.html#support-for-no_std) to be released with Wasmtime 21, so closing.
