### ISSUE TITLE
Cranelift: do something better with generated source from meta-DSL?

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#3540]
Now that we have a checked-into-git approach for ISLE's generated source, we should consider doing a similar thing with the generated source from the meta-DSL, including the CLIF definitions, etc. This would yield the same build-time improvements and possibly make some of the data-structure definitions less mystical for new contributors.

We should reuse our "check if stale but don't update automatically" infrastructure we have for ISLE in #3534, if we do this.

Whether or not we do it, separately, we should reconsider whether the "Meta deterministic check" CI job continues to make sense to keep.

**Comment by fitzgen** [comment]
I think this is a ~dupe of https://github.com/bytecodealliance/wasmtime/issues/3531 ?

**Comment by cfallin** [comment]
Ah, yes, almost; I think my imagined future state still includes a `build.rs` that does the check for stale generated sources, to avoid that footgun for new contributors, though. I can add my thoughts on that over there and close this issue.
