### ISSUE TITLE
ISLE: support a block-comment syntax

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#3542]
I've noticed that `;;` works for comments, but I think it would also be nifty to support block comments along the same lines as wasm with `(; ... ;)` to handle blocks of code during development as well.

**Comment by Kmeakin** [comment]
Closed by https://github.com/bytecodealliance/wasmtime/commit/4ee35532ac23670f23a61f2a23e497d69ce2c531
