### ISSUE TITLE
Question: How much memory does wasmtime allocates by default?

### ISSUE THREAD

**Issue by PureWhiteWu** [bytecodealliance/wasmtime#3564]
As title discribes, I wonder how much memory does wasmtime allocates to an instance by default.

I ran into some strange behaviour, and I need to confirm this first.

Thanks.

**Comment by bjorn3** [comment]
On 64bit systems wasmtime reserves 6GB by default for the wasm linear memory I believe. Only the part corresponding with the size of the linear memory as the wasm module sees it is allocated. The rest doesn't use RAM. Each wasm module sets it's own default size for the linear memory. https://github.com/bytecodealliance/wasmtime/blob/81f6228c574670dcdacd42e40ce53e9e1a685a15/crates/environ/src/tunables.rs#L51-L57

**Comment by PureWhiteWu** [comment]
@bjorn3 Thanks!
I've found something quite strange and submited another issue #3565 so close this now.

**Comment by alexcrichton** [comment]
Note that the number reported above is not accurate, the full default address space reservation is 8GB large. There's a 2GB guard region, the 4GB region for a 32-bit memory, and a trailing 2GB guard region. All of this is configurable via the `Config` struct and its various methods as well.
