### ISSUE TITLE
Is there any way to reduce wasi's size

### ISSUE THREAD

**Issue by fengqi2019** [bytecodealliance/wasmtime#3596]
hello, i just learn wasi. i compile the helloworld's code  to wasi in release, and the wasi's size is 1.78M(i think it is too big.), is there any way to reduce wasi's size? 
the helloworld code: 
```
fn main() {
    println!("Hello, world!");
}
```

**Comment by bjorn3** [comment]
Did you enable LTO? That helps a lot with removing dead code.

**Comment by fengqi2019** [comment]
it is useful, now it's size is 250k. thanks a lot!

**Comment by tschneidereit** [comment]
Most of that is probably still debug symbols, and running [wasm-strip](https://webassembly.github.io/wabt/doc/wasm-strip.1.html) on the result will further reduce the size substantially. Running it through [wasm-opt](https://github.com/WebAssembly/binaryen#tools) with `-O3` or `-Os` makes it even smaller.

The smallest I can get this is 61kb, with these commands:
```sh
rustc --target wasm32-wasi main.rs -o main.wasm
wasm-opt -Os --strip -o main.wasm main.wasm
```
