### ISSUE TITLE
How do I pass JSON/Map/Vec<u8> into WASI?

### ISSUE THREAD

**Issue by fengqi2019** [bytecodealliance/wasmtime#3613]
hello, Actually, I wanted tochange this function to wasi :
```
fn wasi_fn(
    _topic: &str,
    params: Value,
    _context: &HashMap<String, String>,
) -> Result<Vec<u8>>
```
so, i think if i can pass json/map into wasi, or i pass Vec<u8> then will be transformed to json/map in wasi.Does the idea work?

**Comment by alexcrichton** [comment]
Right-this-red-hot-second I don't think this will work with WASI, but with interface types and an implementation like [wit-bindgen](https://github.com/bytecodealliance/wit-bindgen) everything except the hash map should work. 

Unfortunately this is still somewhat nontrivial to implement today, but for following this work I'd recommend following the interface-types and wit-bindgen repositories.
