### ISSUE TITLE
Patch-release process should handle non-`main` branches.

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#3621]
In [this CI job](https://github.com/bytecodealliance/wasmtime/actions/runs/1594257673), I manually triggered the bump-version job on the `release-0.32.x` branch in order to do a 0.32.1 patch release (#3620). It seems that the CI-job yaml refers to `main` in at least two places: when pushing from a local refspec to the repository, and when creating a PR. The former can be `HEAD` and the latter has to be the actual name of the branch we're running on, which can likely be found from the script's environment.

**Comment by alexcrichton** [comment]
Fixed now!
