### ISSUE TITLE
Is there a way to print out the Cranelift IR of a module?

### ISSUE THREAD

**Issue by teymour-aldridge** [bytecodealliance/wasmtime#3626]
I've tried using [`Module::declarations`](https://docs.rs/cranelift-module/latest/cranelift_module/trait.Module.html#tymethod.declarations) and then [`ModuleDeclarations::get_functions`](https://docs.rs/cranelift-module/latest/cranelift_module/struct.ModuleDeclarations.html#method.get_functions) but it doesn't seem to implement `Display`.

Sorry if this is me being silly.

**Comment by bjorn3** [comment]
No, a `Module` only contains the code after compilation. `define_function` immediately compiles functions. You can print a `Function` before calling `define_function` though. I believe it implements `Display`.

**Comment by teymour-aldridge** [comment]
Thanks!
