### ISSUE TITLE
Unsafe function pointers

### ISSUE THREAD

**Issue by mrowqa** [bytecodealliance/wasmtime#363]
During module compilation we're casting memory reference to fat pointers to work around problems with borrow checker ([here](https://github.com/CraneStation/wasmtime/blob/1c22211d57a9a57d93782240326b2c1bc6b245d3/wasmtime-jit/src/compiler.rs#L306)). It's actually unsafe: when the Compiler struct gets dropped, it causes to drop CodeMemory field in it, which drops Mmap in it, which deallocates the code memory. This results in dangling pointers to the functions.

Some ideas to consider:
1. Leak the executable memory.
2. Clone reference with appropriate lifetime using unsafe, so we can cheat on borrow checker this way.
3. Have a newtype for function references with lifetime shorter than `'static`.

CC @sunfishcode

**Comment by alexcrichton** [comment]
I believe these issues are handled now with the `wasmtime` crate itself (it internally holds onto all the various allocations as necessary). The internal crates are all documented as pretty unsafe and require pretty deep knowledge of how they work to use them safely, but that's unlikely going to change too too much in the near future, so I'm going to close this as "basically solved at the `wasmtime` crate layer"
