### ISSUE TITLE
IO capabilities?

### ISSUE THREAD

**Issue by xpepermint** [bytecodealliance/wasmtime#3630]
Hey, I try to find information on IO [capabilities](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md) for WASI. I need to get chunks of data in and out in parallel from a host process/app. I think of a state machine (e.g. events) or input and output channels/streams.

What would be a good way to achieve this? Does my question relate to [rustix](https://github.com/bytecodealliance/rustix)?

**Comment by sunfishcode** [comment]
I don't think there any simple ways to do parallel I/O right now, however wit-bindgen is working on `async` stream support, and once that's ready, it'll likely be what you want, or a building block for the thing you want.

**Comment by xpepermint** [comment]
Got it. Thanks.
