### ISSUE TITLE
Add an ISA builder for Wasm

### ISSUE THREAD

**Issue by teymour-aldridge** [bytecodealliance/wasmtime#3640]
#### Feature

Add support for WebAssembly to [cranelift_codegen::isa](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/isa/)

#### Benefit

It is a prerequisite for #2566.

**Comment by cfallin** [comment]
Closing this in favor of #2566 -- I don't think we need a separate tracking issue for the ISA builder specifically, just for Wasm backend support in general. Thank you though!
