### ISSUE TITLE
Is support mipsel-unknown-linux-musl?

### ISSUE THREAD

**Issue by fengqi2019** [bytecodealliance/wasmtime#3651]
hello, i want to use this crate in openwrt. an error occurred while compiling: "wasmtime doesn't support fibers on platform: mipsel-unknown-linux-musl". how i should do to compile? if it don't support, have you a plan to support ?

**Comment by bjorn3** [comment]
Cranelift and by extension Wasmtime currently only supports x86_64, AArch64 and s390x. Cranelift doesn't yet have a mips backend, so Wasmtime can't be compiled for mips.

**Comment by fengqi2019** [comment]
ok,thanks!
