### ISSUE TITLE
Wrong externref_returns_count for WasmFuncType in the wasmtime-types crate

### ISSUE THREAD

**Issue by biuld** [bytecodealliance/wasmtime#3749]
<img width="958" alt="截屏2022-02-02 上午1 35 11" src="https://user-images.githubusercontent.com/36144654/152020679-a7afd996-48be-4ccb-8a6d-c454a4338b67.png">
Just studying the source code and I found this. Is that externref_returns_count should be obtained from returns instead of params?

**Comment by pchickey** [comment]
Great job spotting this bug, thanks for the report! This was a correctness issue, but we don't believe that its a security-critical bug since, internally, the only effect this could have is letting wasmtime miss an opportunity to gc.
