### ISSUE TITLE
cranelift-isle crate is missing the LICENSE file

### ISSUE THREAD

**Issue by decathorpe** [bytecodealliance/wasmtime#3761]
It looks like the cranelift-isle is missing a LICENSE file (or symlink). Since all other crates I see in this repository contain a LICENSE file or symlink, this seems to have been a simple oversight when creating the cranelift-isle crate a few months ago.

**Comment by cfallin** [comment]
Thanks for noticing this!

**Comment by decathorpe** [comment]
It now looks like the cranelift-isle crate was split into multiple crates, and the LICENSE file was not moved / copied accordingly :(

**Comment by cfallin** [comment]
Sorry about that! I'll fix it, and see about adding a check to our CI to ensure we don't break this again.
