### ISSUE TITLE
`wasmtime` CLI has `--consume-fuel` option but no way to configure amount of fuel available

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#3779]
Seems like an oversight on our part.

I'm imagining that we would

1. Make the default amount of fuel `0` in the CLI
2. Add a `--add-fuel <N>` option to add `N` fuel to the store

I think (1) miiiiight be slightly controversial? As an alternative, we would have a `--set-fuel <N>` option, instead of `--add-fuel <N>`, and then we would have to ensure that the store gets exactly `N` fuel rather than adding `N` additional fuel to it. This is a little bit of a divergence from the `Config` methods, so I prefer the former, but I'm open either way.

------------------------

In any case, this should be a pretty easy thing to implement for anyone looking to dive into the Wasmtime code base for the first time. The changes would need to be made around here:

https://github.com/bytecodealliance/wasmtime/blob/4f01711d42906c34ae566f0d8eaafd824b711587/src/lib.rs#L237-L239

https://github.com/bytecodealliance/wasmtime/blob/4f01711d42906c34ae566f0d8eaafd824b711587/src/lib.rs#L331

See https://docs.wasmtime.dev/contributing.html for contributing details.

**Comment by ilikepi63** [comment]
https://github.com/bytecodealliance/wasmtime/pull/3792

**Comment by sdeleuze** [comment]
Hi, should this issue be closed since #3792 has been merged via 85cf4b042a67706669a1f1edea582d885b787a93?

**Comment by fitzgen** [comment]
Yes, thanks.
