### ISSUE TITLE
Unable to build on M1 mac

### ISSUE THREAD

**Issue by anistark** [bytecodealliance/wasmtime#3801]
Getting `error: failed to load manifest for workspace member` on running `cargo build` or even `cargo metadata`.

### Steps to Reproduce

1. Cloned the repo
2. Ran `cargo metadata`

### Expected Results

Should have displayed metadata as output.

### Actual Results

```sh
error: failed to load manifest for workspace member `/path/to/wasmtime/crates/bench-api`

Caused by:
  failed to load manifest for dependency `wasi-cap-std-sync`

Caused by:
  failed to load manifest for dependency `wasi-common`

Caused by:
  failed to load manifest for dependency `wiggle`

Caused by:
  failed to load manifest for dependency `wiggle-macro`

Caused by:
  failed to load manifest for dependency `wiggle-generate`

Caused by:
  failed to load manifest for dependency `witx`

Caused by:
  failed to read `/path/to/wasmtime/crates/wasi-common/WASI/tools/witx/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

### Versions and Environment

Wasmtime version or commit: On Commit `ca0e8d0a1d8cefc0496dba2f77a670571d8fdcab`

Operating system: Mac M1

### Extra Info

Anything else you'd like to add?

Tried using multiple rust toolchains
`stable-aarch64-apple-darwin (default)` and `stable-x86_64-apple-darwin`.

---

Same result when trying to run `cargo build` or `cargo build -p wasmtime-c-api`.

**Comment by bjorn3** [comment]
You will need to run `git submodule update --init` to fetch all submodules.

**Comment by anistark** [comment]
> You will need to run `git submodule update --init` to fetch all submodules.

This worked. Perfect. 🙏🏼  Thanks.
