### ISSUE TITLE
Cranelift: support vector instructions without optional ISA extensions

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#3810]
In #3809, a new extension to our fuzzing found that some of our Wasm-SIMD support requires nominally optional ISA features, at least on x86-64.

I think we should *try* to have fallbacks such that we can support all relevant features on any machine that supports the base ISA. On x86-64, this means just SSE2. Or if this is very difficult for some reason, we should document why and then possibly consider raising our minimum required ISA version.

**Comment by cfallin** [comment]
Reopened; GH mis-parsed "once we fix #3810" as "fix #3810" in #4231's commit.

**Comment by alexcrichton** [comment]
I believe that this is now done, so closing.
