### ISSUE TITLE
Mention `--invoke` on "CLI Options for `wasmtime`" page

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/wasmtime#3827]
#### Feature

Document the `run` command's `--invoke` options on the [CLI Options for `wasmtime`](https://docs.wasmtime.dev/cli-options.html) page.

#### Benefit

This page is where users will likely look for features like running a specific function from the CLI.
Including it here will improve the discoverability of `--invoke` by new users.

Having remembered that this was possible after seeing it somewhere,
it took me longer than I expected to find the syntax for this.

#### Implementation

This change can be made in the [`cli-optioms.md`](https://github.com/bytecodealliance/wasmtime/blob/main/docs/cli-options.md) file.
I will submit a PR that makes the change.

#### Alternatives

N/A

**Comment by srenatus** [comment]
Looks done to me? 🤔
