### ISSUE TITLE
Debugging module with lldb shows local variables as not available

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/wasmtime#3884]
### Test Case

[test.wasm.zip](https://github.com/bytecodealliance/wasmtime/files/8189246/test.wasm.zip)

```c
#include <stdio.h>

int main() {
    int i;
    for(i = 0; i < 5; i++) {
        printf("%d\n", i);
    }
    return 0;
}
```
compiled with: `wasi-sdk-14.0/bin/clang -g -O0 test.c -o test.wasm`

### Steps to Reproduce

```
> lldb -- wasmtime run -g test.wasm                  
(lldb) target create "wasmtime"
Current executable set to 'wasmtime' (arm64).
(lldb) settings set -- target.run-args  "run" "-g" "test.wasm"
(lldb) settings set plugin.jit-loader.gdb.enable on
(lldb) b test.c:6
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) run
Process 40146 launched: '/Users/jeffcharles/.cargo/bin/wasmtime' (arm64)
1 location added to breakpoint 1
Process 40146 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100e940e0 JIT(0x1102b0000)`main at test.c:6:24
   3   	int main() {
   4   	    int i;
   5   	    for(i = 0; i < 5; i++) {
-> 6   	        printf("%d\n", i);
   7   	    }
   8   	    return 0;
   9   	}
Target 0: (wasmtime) stopped.
(lldb) fr v
(WasmtimeVMContext *) __vmctx = <variable not available>

(int) i = <no location, value may have been optimized out>
```

### Expected Results

Running `fr v` in lldb in this context should display:
```
(int) i = 0
```

### Actual Results

```
(int) i = <no location, value may have been optimized out>
```

### Versions and Environment

Wasmtime version or commit: 0.34.0

Operating system: MacOS Monterrey (12.2.1)

Architecture: arm64

### Extra Info

LLDB version:
```
> lldb --version
lldb-1300.0.42.3
Swift version 5.5.2-dev
```

This is what happens when I try to compile and run natively to show what I'm expecting:
```
> clang -g -O0 test.c -o test
> lldb -- test
(lldb) target create "test"
Current executable set to '/Users/jeffcharles/projects/wasm32-wasi/test-c-app/test' (arm64).
(lldb) b test.c:6
Breakpoint 1: where = test`main + 32 at test.c:6:24, address = 0x0000000100003f6c
(lldb) run
Process 40384 launched: '/Users/jeffcharles/projects/wasm32-wasi/test-c-app/test' (arm64)
Process 40384 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100003f6c test`main at test.c:6:24
   3   	int main() {
   4   	    int i;
   5   	    for(i = 0; i < 5; i++) {
-> 6   	        printf("%d\n", i);
   7   	    }
   8   	    return 0;
   9   	}
Target 0: (test) stopped.
(lldb) fr v
(int) i = 0
```

**Comment by cfallin** [comment]
It looks like the `i` variable is placed on the in-wasm-heap pseudostack by LLVM:

```
$ /opt/wasi-sdk/bin/llvm-dwarfdump test.wasm

    [ ... ]

0x0000003e:     DW_TAG_variable
                  DW_AT_location	(DW_OP_fbreg +8)
                  DW_AT_name	("i")
                  DW_AT_decl_file	("/Users/jeffcharles/projects/wasm32-wasi/test-c-app/test.c")
                  DW_AT_decl_line	(4)
                  DW_AT_type	(0x0000004d "int")
```

(`fbreg` is the frame-buffer "register".) I'm not sure how well-supported this is; I'm more familiar with the machinery that passes through debug locations for SSA values, which come from Wasm locals. @yurydelendik wrote the original DWARF expression translation code I think -- Yury, any thoughts on this (whether it is expected to work with the existing code, what it would take if not)?

**Comment by yurydelendik** [comment]
> whether it is expected to work with the existing code, what it would take if not

Based on https://github.com/bytecodealliance/wasmtime/pull/842 it was supported at some time. Missing tests though because format was evolving on LLVM side.

**Comment by YoungWenMing** [comment]
Any updates about this issue?

**Comment by bjorn3** [comment]
To quote @cfallin from https://github.com/bytecodealliance/wasmtime/issues/4669#issuecomment-1210997950 (which is another debuginfo issue):

> We currently don't have anyone on the project who understands our DWARF-handling code well and has time to work on it; so while this is definitely a bug, it's not likely to have a fast resolution. We do have an intent to have someone eventually focus on this, as priorities allow, so we should keep this issue open. Just wanted to give some context on the current situation...

**Comment by SingleAccretion** [comment]
I think I see what is going here quite clearly now. During DWARF translation, actual as-reported-by-the-code-generator live ranges of "value labels" (side note: quite the confusing name for what are actually simply WASM locals) are intersected with the ranges in the WASM DWARF. So for a composite `DW_OP_fbreg`-based expression like the above, availability of the final result is limited by the availability of all its constituent locals. Importantly, one of those locals, the WASM LLVM stack pointer, is not always available. This is presumably due to the limitation that only register locations are supported right now. This explains the sparce ranges: in the disassembly, they correspond to spots where the the LLVM stack pointer is reloaded from the native frame for temporary use.
