### ISSUE TITLE
how to run module A that should import module B in CLI

### ISSUE THREAD

**Issue by wuhuizuo** [bytecodealliance/wasmtime#3898]
It is the example for module linking in Wasmtime-go:
https://github.com/bytecodealliance/wasmtime-go/blob/1b44fcb61fe2a7619b8c14908009794ee6115bf7/linker_test.go#L95

And I want to know how to run module linking in Wasmtime CLI, is there any example or document?

**Comment by alexcrichton** [comment]
The `wasmtime run` command has a `--preload` option which can be used for this, but it's worth saying that the linking story between modules is still very young and there probably aren't that many real world modules which "simply work with `--preload`" today.
