### ISSUE TITLE
Android NDK  link arm64-v8a/libwasmtime.a failed?

### ISSUE THREAD

**Issue by LukiYLS** [bytecodealliance/wasmtime#3921]
My project link arm64-v8a/libwasmtime.a error

rustix.dcbac7fd-cgu.5.rcgu.o): In function `rustix::imp::io::syscalls::pwritev::hdad5057263d83a9f':
  rustix.dcbac7fd-cgu.5:(.text._ZN6rustix3imp2io8syscalls7pwritev17hdad5057263d83a9fE+0x10): undefined reference to `pwritev64'
  /Users/lukiyang/Work/sourcecode/DynamicFramework/core/third_party/wasmtime/lib/android/arm64-v8a/libwasmtime.a(fastcover.o): In function `ZDICT_trainFromBuffer_fastCover':
  fastcover.c:(.text.ZDICT_trainFromBuffer_fastCover+0x110): undefined reference to `stderr'
  fastcover.c:(.text.ZDICT_trainFromBuffer_fastCover+0x114): undefined reference to `stderr'
  fastcover.c:(.text.ZDICT_trainFromBuffer_fastCover+0x28c): undefined reference to `stderr'
  fastcover.c:(.text.ZDICT_trainFromBuffer_fastCover+0x290): undefined reference to `stderr'
  fastcover.c:(.text.ZDICT_trainFromBuffer_fastCover+0x2b8): undefined reference to `stderr'

Compile libwamtime.a config
ndk = 21.4.7075529
AndroidVersion = 21

My Project config
ndk = 21.4.7075529
minSdkVersion 16
targetSdkVersion 29

**Comment by alexcrichton** [comment]
Thanks for the report, but Android isn't supported at this time so it's expected that the source either doesn't compile, doesn't link, or may not work at runtime. It seems that you previously hit compiler errors in https://github.com/bytecodealliance/wasmtime/issues/3877 which is what I would naively expect. If you're getting link errors then I'm not entirely sure how you got past the compiler errors and whether these are related. PRs for more platforms are fine to add support for so long as it isn't too much for us to maintain, otherwise if you'd like to see official support for Android that's also a discussion that can be had, but would probably be an RFC.

**Comment by LukiYLS** [comment]
> Thanks for the report, but Android isn't supported at this time so it's expected that the source either doesn't compile, doesn't link, or may not work at runtime. It seems that you previously hit compiler errors in #3877 which is what I would naively expect. If you're getting link errors then I'm not entirely sure how you got past the compiler errors and whether these are related. PRs for more platforms are fine to add support for so long as it isn't too much for us to maintain, otherwise if you'd like to see official support for Android that's also a discussion that can be had, but would probably be an RFC.

I successfully compiled libwasmtime.a with command:
`cargo build --target=aarch64-linux-android --release --manifest-path crates/c-api/Cargo.toml`

But there is a link error of std in my android project, i tried many ndk version and still get this error

**Comment by LukiYLS** [comment]
Can you give me a try

**Comment by alexcrichton** [comment]
It looks like you're using the right compile target, but again this is an unsupported target, so it's not expected that everything works out of the box. At this point you'll probably need to work backwards from the errors you're seeing and see if the symbols actually do exist and if they don't then the projects using them need to get patched to not use them on android.

**Comment by alexcrichton** [comment]
I believe that this has since been resolved so closing.
