### ISSUE TITLE
Build error related with `thread_local_const_init`

### ISSUE THREAD

**Issue by kimdora** [bytecodealliance/wasmtime#3968]
Hello, when I tried to build `wasmtime` from source code, I got a following error.

```
error[E0658]: use of unstable library feature 'thread_local_const_init'
   --> crates/runtime/src/traphandlers.rs:390:9
    |
390 |         thread_local!(static PTR: Cell<(Ptr, bool)> = const { Cell::new((ptr::null(), false)) });
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #84223 <https://github.com/rust-lang/rust/issues/84223> for more information
    = note: this error originates in the macro `$crate::__thread_local_inner` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
```
How can I fix it?

**Comment by kimdora** [comment]
So I built `wasmtime` from current master branch [`5d8dd64`](https://github.com/bytecodealliance/wasmtime/tree/5d8dd648d71db22838e376b18ecd03b015a08485) so that I got the error.
But when I change the version to [`release-0.35.1`](https://github.com/bytecodealliance/wasmtime/tree/release-0.35.1) which is the latest version now, I successfully build `wasmtime`.

**Comment by cfallin** [comment]
@kimdora It's likely that your Rust compiler is a bit out-of-date. We test Wasmtime with the latest stable Rust; you should be able to build our `main` branch if you update (if you installed via `rustup`) with:

```
$ rustup update
```

If that doesn't work, let us know what `rustc --version` says and we can try to help further!

**Comment by kimdora** [comment]
@cfallin , thank you for your comment! After I updated `rustup` that you said, I can build successfully on master branch!
Thank you!
