### ISSUE TITLE
M1 pre-built binary

### ISSUE THREAD

**Issue by ricochet** [bytecodealliance/wasmtime#3982]
#### Feature

Add pre-built binaries for M1 and other arm architectures. The following message occurs when running intall.sh on a 2020 macbook pro. I see `aarch64` is already available in the github workflow so perhaps only `aarch64-apple-darwin` is needed.

```bash
curl https://wasmtime.dev/install.sh -sSf | bash

Error: Sorry! Wasmtime currently only provides pre-built binaries for x86_64 architectures.
```

#### Benefit

The demand for m1 support will only grow with time.

#### Implementation

It looks like we only need to add a cross-compile target in the github workflow. 

I searched for arm related github issues and only found a few
* https://github.com/bytecodealliance/wasmtime/issues/2808
* https://github.com/bytecodealliance/wasmtime/issues/2127
* https://github.com/bytecodealliance/wasmtime/issues/2907
* https://github.com/bytecodealliance/wasmtime/issues/2735

IMO the above bugs shouldn't prevent releasing a binary.

**Comment by cfallin** [comment]
We've now released Wasmtime 0.37, which includes the change in #3983 to build `aarch64-apple-darwin` binaries, and just now we added the platform to the `install.sh` script at `wasmtime.dev` (bytecodealliance/wasmtime.dev#13). Given that, I think we can call this complete and close it!
