### ISSUE TITLE
Idea: Keep track of set condition codes

### ISSUE THREAD

**Issue by Vurich** [bytecodealliance/wasmtime#401]
If we kept track of what conditions were set we could get better performance on the idiom:

```c
for (int i = something; i != 0; i--) {
  // ...
}
```

Instead of emitting a `cmp` after the `dec`, we can work out that we already have the zero flag set from the `dec` and just emit a `jnz`. Currently there's no way to abstract over different instructions and get metadata for them, so this would be very complicated to implement without a new assembler.

EDIT: Keeping track of what instructions mutate which condition codes would allow us to implement CraneStation/lightbeam#16 in a way that only spills the "condition" if we're about to emit an instruction that would invalidate it.

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
