### ISSUE TITLE
Licenses container boilerplate text

### ISSUE THREAD

**Issue by curiositycasualty** [bytecodealliance/wasmtime#4064]
Both in the top-level `LICENSE` file and in the subsidiary ones.

https://github.com/bytecodealliance/wasmtime/blob/99e9e1395d5d31f4121c8fa5d1d910bac4908006/LICENSE#L190

**Comment by cfallin** [comment]
That line is part of the appendix, which states "To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information." In other words, that seems to be a bit of the license intended to be that way; it's a set of instructions, and we're not supposed to fill in the info there.

More generally, it seems to be pretty standard to copy the `LICENSE` file wholesale, without modifying it. For a random example, here's Cargo's copy of the Apache license, with the same line you highlighted:

https://github.com/rust-lang/cargo/blob/master/LICENSE-APACHE

Thanks in any case! I'll go ahead and close this issue.
