### ISSUE TITLE
Cranelift: register allocation fails with "EntryLivein" for load-and-umax snippet

### ISSUE THREAD

**Issue by Mrmaxmeier** [bytecodealliance/wasmtime#4067]
### `.clif` Test Case

This snipped started crashing with `register allocation: EntryLivein` in e4b7c8a7376c0b4196262b176373b606c7b4c760 (x86_64):

```
function u0:0(i32, i64) -> i32 fast { 
block0(v1: i32, v2: i64): 
    v3 = load.i32 notrap aligned v2
    v4 = umax v1, v3
    return v4
}

```

I'm not sure why/if this issue is only present with the integer min/max implementations, but I'd guess that it only surfaces with load operands reused in both a conditional move and compare.

CC @cfallin 

### Versions and Environment

Cranelift version or commit: e4b7c8a7376c0b4196262b176373b606c7b4c760

Operating system: Linux

Architecture: x86_64

**Comment by cfallin** [comment]
Thanks for the report -- taking a look right away!
