### ISSUE TITLE
Can't build wasmtime with `cargo build -p wasmtime-c-api`

### ISSUE THREAD

**Issue by HowJMay** [bytecodealliance/wasmtime#4075]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Test Case

TODO: upload Wasm file here

### Steps to Reproduce

* TODO: first, ...
* TODO: second, ...
* Etc...

### Expected Results

successfully built

### Actual Results

```
error[E0658]: use of unstable library feature 'thread_local_const_init'
   --> crates/runtime/src/traphandlers.rs:390:9
    |
390 |         thread_local!(static PTR: Cell<(Ptr, bool)> = const { Cell::new((ptr::null(), false)) });
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #84223 <https://github.com/rust-lang/rust/issues/84223> for more information
    = note: this error originates in the macro `$crate::__thread_local_inner` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `wasmtime-runtime` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Versions and Environment

Wasmtime version or commit: branch: release-v0.36.0

Operating system: MacOS

Architecture: ARM64

### Extra Info

Anything else you'd like to add?

**Comment by cfallin** [comment]
Hi @HowJMay -- it's likely that you're building with a Rust compiler that's slightly too old.

Can you try `rustup update` and then build again? (This is assuming you installed Rust with rustup.)

If that still doesn't work, could you let us know what you see from `rustc --version`?

**Comment by HowJMay** [comment]
It works thank you!
