### ISSUE TITLE
get arity of function in c api

### ISSUE THREAD

**Issue by pannous** [bytecodealliance/wasmtime#4144]
How to get the arity of a wasmtime function in the c api?
```
 int nresults = wasm_func_result_arity(wasmFunc);
```
works for wasm_func_t  but doesn't work for wasmtime_func_t (EXC_BAD_ACCESS)

**Comment by bjorn3** [comment]
It doesn't look like there is a function for that in the wasmtime c api. That wasm_func_result_arity doesn't work for wasmtime_func_t is expected as you are mixing two different api's in that case. You need to use either the wasm_* api's or the wasmtime_* api's, you can't use both at the same time.

**Comment by pannous** [comment]
that worked, thanks a lot!
