### ISSUE TITLE
Create CI test-runner job for aarch64-macos (M1 Mac)

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#4177]
We've discussed this in various places (most recently #3982) but we don't seem to have an open issue tracking the eventual addition of an actual CI job for aarch64-macos ("M1" / "Apple Silicon").

It looks like GitHub is perhaps making slow progress toward having runners: see actions/runner#805 where just today, a GitHub PM indicated that next week there will be a pre-release of a self-hosted M1 runner. Now, we likely want to wait until there are GitHub runners, as there are serious security concerns with self-hosted ones; but this is progress.

The relevant issue for GitHub-hosted VM runners seems to be actions/virtual-environments#2187.

**Comment by cfallin** [comment]
And for maximal clarity and to give background info: we have a build job that produces M1 binaries (thanks to #3983) but our CI does not run tests on this platform. We have various folks running tests manually, and Embark Studios (thanks to bnjbvr) runs an M1-hosted CI internally with wasmtime. But ideally we'd get tests run on every PR, as for the other platforms we support.

**Comment by afonso360** [comment]
It looks like Github Actions has released M1 Runners publicly today (https://github.com/github/roadmap/issues/528)

**Comment by cfallin** [comment]
Woah, neat! I'll see if I can switch us over now.

**Comment by alexcrichton** [comment]
This is now done, so closing.
