### ISSUE TITLE
Memory usage of a wasm program

### ISSUE THREAD

**Issue by hainsdominic** [bytecodealliance/wasmtime#4178]
Greetings,

Is there a way of knowing how many pages a wasm program used during its execution? I did not find references to this on the documentation. Would it be possible to use the [data method](https://docs.rs/wasmtime/0.28.0/wasmtime/struct.Store.html#method.data) of the Store in order to do this?

Thanks!

**Comment by alexcrichton** [comment]
For this you can use the [`ResourceLimiter`](https://docs.rs/wasmtime/latest/wasmtime/trait.ResourceLimiter.html) trait combined with [`Store::limiter`](https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.limiter) to sum up all memories grown within a `Store`. That will indicate memory that wasm had accessible but not necessarily the memory that wasm used (e.g. reserved address space but it it may not all be paged in by the OS). If you're curious about actual page usage you'd need to get the actual `Memory` object to use APIs like `mincore` to see if it's actually paged in.

**Comment by alexcrichton** [comment]
I think this is solved with what I mentioned above so I'm going to close this, but if it doesn't work for you feel free to reopen and we can try to continue helping.

**Comment by hainsdominic** [comment]
Would `memory.data_size` work in this use case?
