### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by kazimuth** [bytecodealliance/wasmtime#419]
Is multithreading support coming to wasmtime in the forseeable future?

**Comment by bjorn3** [comment]
Blocked on https://github.com/CraneStation/cranelift/issues/582

**Comment by sunfishcode** [comment]
Yep, and the bigger picture is, multithreading is really important to us, so while I don't have a specific timeframe yet, it will happen.

**Comment by alexcrichton** [comment]
Looks like we have a few of these issues open in the issue tracker so I'm going to close this in favor of a dedicated tracking issue -- https://github.com/bytecodealliance/wasmtime/issues/888
