### ISSUE TITLE
wasi-crypto: unable to build on Windows CI

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#4213]
@jedisct1, I thought it would be interesting to build in `wasi-crypto` to the benchmarking engine used in Sightglass over in #4207. I changed the `wasmtime-bench-api` default features to include `wasi-crypto`, but when I did, I observed build errors on Windows related to `pqcrypto-internals`:

https://github.com/bytecodealliance/wasmtime/runs/6700498078?check_suite_focus=true#step:12:399

Understanding that neither the `wasmtime-bench-api` crate or the `wasi-crypto` feature are completely "done," this issue is not a high priority one; I did want to get your eyes on this to see if there is anything simple that can be done to fix things. In the meantime, I will leave `wasi-crypto` disabled by default in `wasmtime-bench-api`.

**Comment by jedisct1** [comment]
Thanks for reporting this!

I think it was fixed [here](https://github.com/rustpq/pqcrypto/pull/37), about a week after the crate published :/

So, the next release won't have that issue. As a workaround, the `wasi-crypto` hostcalls can be compiled without the default features, effectively removing the `pqcrypto` dependency.

**Comment by alexcrichton** [comment]
We've since removed wasi-crypto from in-tree, so Im' going to close this.
