### ISSUE TITLE
Change how the wasmtime CLI works to be driven by wit-bindgen

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#4272]

**Comment by kulakowski-wasm** [comment]
The wasmtime CLI driver currently needs you to manually add APIs. We should instead leverage wit-bindgen to include those APIs.

**Comment by kulakowski-wasm** [comment]
@pchickey

**Comment by pchickey** [comment]
we support preview 2 in the CLI at this time, for both cli commands worlds and http proxy worlds.
