### ISSUE TITLE
Implement wasi-filesystem in Wasmtime

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#4273]
- [ ] https://github.com/WebAssembly/wasi-filesystem/issues/48

**Comment by kulakowski-wasm** [comment]
We should implement the https://github.com/webassembly/wasi-filesystem proposal in wasmtime.

**Comment by pchickey** [comment]
This is gated behind `wit-bindgen-gen-host-wasmtime-rust` being rewritten for components

**Comment by ricochet** [comment]
This appears to have been completed with the latest changes having landed with https://github.com/bytecodealliance/wasmtime/pull/6791
