### ISSUE TITLE
Implement wasi-clocks in Wasmtime

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#4274]

**Comment by cdmurph32** [comment]
I'll take this, but I can't self-assign.

**Comment by ricochet** [comment]
Waiting on release of cap-std for updated cap-time-ex

https://github.com/bytecodealliance/cap-std/pull/327

**Comment by pchickey** [comment]
https://github.com/bytecodealliance/wasmtime/pull/7515 https://github.com/WebAssembly/wasi-clocks/pull/55 gets us to a place on wasi-clocks where we are stable for a preview 2 RC tag and phase 3 vote, and we can add timezones back in as clocks 0.2.1 after preview 2 ships.
