### ISSUE TITLE
Implement wasi-sockets in Wasmtime

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#4276]
- [ ] Update wasi-sockets to use streams instead of push/pullbuffer

**Comment by spacewander** [comment]
Is there any update for the wasi-sockets support?

**Comment by huangjj27** [comment]
maybe releated to https://github.com/bytecodealliance/wasmtime/pull/4776

**Comment by sunfishcode** [comment]
Wasmtime does have support for the `sock_accept` sockets API that was added to preview1.

"wasi-sockets" refers to [this preview2 proposal](https://github.com/WebAssembly/wasi-sockets/), which wasmtime doesn't support yet, though we are working on it.

**Comment by badeend** [comment]
I think this can be closed now
