### ISSUE TITLE
Implement the new preopen scheme in Wasmtime

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#4277]
- [x] https://github.com/bytecodealliance/wasmtime/issues/4278

**Comment by ricochet** [comment]
There is no longer a "new" preopen scheme and it's the same as the preview 1 scheme. @pchickey created the implementation first in https://github.com/bytecodealliance/preview2-prototyping/pull/123) and it has since been moved into wasmtime. This one is OK to close.
