### ISSUE TITLE
How to interrupt execution

### ISSUE THREAD

**Issue by vavrusa** [bytecodealliance/wasmtime#43]
Hi 👋 What do you have in mind for interrupting execution in situations like execution time or instruction limit? Are you planning to insert traps in generated code in cranelift in strategic places (e.g. jump points), or rely on signals (like setitimer on POSIX)?

**Comment by vavrusa** [comment]
Thanks! I'll take a look at the `translate_loop_header`, that looks feasible.

**Comment by alexcrichton** [comment]
This issue has sat around for some time now so I'm going to close in favor of https://github.com/bytecodealliance/wasmtime/issues/860, but also copy @sunfishcode's idea onto the thread there.
