### ISSUE TITLE
Add debug symbol transformation for AArch64

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/wasmtime#4393]
#### Feature

Debug symbol transformation for AArch64. That is, when running `wasmtime compile -g <path_to_wasm>`, `wasmtime` does not exit with an error message and debug symbols are included in the resulting `.cwasm` file.

#### Benefit

It enables developers writing code targeting a Wasm environment to be able to step debug their code in a Wasm environment if they are using Apple Silicon.

#### Implementation

https://github.com/jeffcharles/wasmtime/pull/1/files. This uses a similar approach to how the symbols are mapped for x86_64. I can open that PR on this repo instead. The contribution guidelines mentioned I should open an issue here first to discuss.

The PR above seems to work for a number of test cases that I've tried.

#### Alternatives

I'm not sure what the alternatives are.

**Comment by jeffcharles** [comment]
I had not seen that issue. I can take a look at those details.

Even without changes to the debug crate though, given my change, I'm currently able to get a reasonable debugging experience on AArch64 as opposed to an error message with the status quo.

**Comment by jameysharp** [comment]
I see the PR just makes aarch64 do exactly what x64 and s390x already do. I don't know much yet about Cranelift's target backends, but it seems plausible to me that `inst::unwind::systemv::map_reg` would be the right choice for aarch64 as well. @akirilov-arm, is there any reason not to merge this?

Also, maybe we should edit the contributor guidelines to say that if it's easier to explain your issue by just opening a pull request showing what you want changed, then you don't need to open an issue first? Anyway I'd say go ahead and open a PR here with your proposed changes.

**Comment by akirilov-arm** [comment]
> @akirilov-arm, is there any reason not to merge this?

I don't know, usually I don't look at PRs that have not been opened in this repository. From a cursory glance it looks OK, but I am not really familiar with that part of the code.

**Comment by jeffcharles** [comment]
I've opened a PR at #4468.

**Comment by jameysharp** [comment]
Merged, thank you!
