### ISSUE TITLE
How to use AOT mode and JIT mode in Rust api ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#4437]
## Cli
As shown in documentation, there are 2 ways to execute wasm, JIT and AOT.
#### (1) JIT
`wasmtime run xxx.wasm`
#### (2)AOT
`wasmtime compile xxx.wasm`
`wasmtime run --allow-precompiled xxx.cwasm`
Are these two ways different ?

## Rust api
How to execute in rust api through JIT and AOT ?

**Comment by bjorn3** [comment]
You can use `Module::new`, `Module::from_file` or `Module::from_binary` for JIT compilation. For AOT compilation you first JIT compile and then call `.serialize()` on the resulting compiled module to get a blob you can write to a file (eg with the `.cwasm` extension). You can then use `Module::deserialize` or `Module::deserialize_file` to load the serialized module into memory again.

**Comment by Zhangyx24** [comment]
Thanks for your answer !
