### ISSUE TITLE
Store::consume_fuel with u64::MAX prevents future use of Store::add_fuel

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#4439]
Currently the following test will fail:

```rust
    let mut config = Config::new();
    config.consume_fuel(true);
    let engine = Engine::new(&config).unwrap();
    let mut store = Store::new(&engine, ());
    store.add_fuel(u64::MAX).unwrap();

    // fuel wraps to i64 so the store has i64::MAX fuel now
    assert_eq!(store.consume_fuel(0).unwrap(), i64::MAX as u64);

    // consume all but one fuel
    assert_eq!(store.consume_fuel(i64::MAX as u64 - 1).unwrap(), 1);

    // confirm that one fuel remains
    assert_eq!(store.consume_fuel(0).unwrap(), 1);

    // try to add fuel to get to 11 more fuel
    store.add_fuel(10).unwrap();
    assert_eq!(store.consume_fuel(0).unwrap(), 11);  // <-- this assertion will fail since the store says it has 1 fuel
```

The "bug" is [here](https://github.com/bytecodealliance/wasmtime/blob/e31ff9dc67b6ea2cc2611307291e86fbaff548de/crates/wasmtime/src/store.rs#L1419-L1425) where when 10 fuel is added the counters there look like:

```
[crates/wasmtime/src/store.rs:1411] adj = 9223372036854775807
[crates/wasmtime/src/store.rs:1412] &consumed_ptr = -1
[crates/wasmtime/src/store.rs:1413] fuel = 10
```

where `adj` is already `i64::MAX`  so `adj.checked_add(fuel)` overflows and we hit the overflow case which resets everything back to its prior value. 

Unfortunately I don't think that this is fixable with the current APIs of `Store`. Currently `Store::consumed_fuel` will report how much fuel has been consumed for the entire lifetime of the store which requires keeping the `fuel_adj` counter around, meaning that we can't actually represent consuming `u64::MAX` fuel since the `fuel_adj` is an `i64`. 

I don't know how to best fix this myself, but we have some fuzz targets using this pattern and suffering from it so we'll need to fix them.

**Comment by fitzgen** [comment]
Rather than resetting on overflow, what if we set to `MAX - 1`? or just `MAX` itself?

**Comment by alexcrichton** [comment]
I believe this is now fixed now that `consume_fuel` is gone.
