### ISSUE TITLE
Component model: implement support for type imports and exports

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime#4494]
#### Feature

This is a tracking issue filed during the implementation of #4488.

The component model specifies that types can be imported and exported in components.

Previously, a component that imported or exported a type would hit an `unimplemented!()` panic.

With #4488, type exports are now explicitly ignored while type imports continue to hit the `unimplemented!()` panic. This tracking issue exists so that we remove the code that skips type exports while translating the component.

The reason for this is that exports are useful with the current component model proposal as a way of giving a type a name, which is one way the component tooling can keep a faithful representation of the component's interface directly in the binary encoding.

The component model tooling does not make use of type imports yet, as those will be useful once the component model proposal includes support for resource types.

#### Benefit

Eventually type imports and exports will be used from components and Wasmtime will need to be able to instantiate such components.

#### Implementation

If type imports and exports remain in the component model proposal, Wasmtime will need to represent them both in the `Component` and `Instance` representations for components.

It will also need to properly implement resolving type imports and exports in a way that allows types imports to be satisfied for component instantiation.

**Comment by alexcrichton** [comment]
I think that this has settled nowadays so I'm going to close this as "done"
