### ISSUE TITLE
A failed execution

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasmtime#4511]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Test Case

[hw_inco.zip](https://github.com/bytecodealliance/wasmtime/files/9169312/hw_inco.zip)

### Steps to Reproduce

Run
```bash
wasmtime hw_inco.wat
```

### Expected Results
```
Hello World!
```

### Actual Results
```
Error: failed to run main module `xxx/hw_inco.wat`

Caused by:
    0: failed to instantiate "xxx/hw_inco.wat"
    1: command export 'one_i32_global' is not a function
```

### Versions and Environment

Wasmtime version or commit: commit ID :35b750ab9a9c4e70e80c4a795e9f51d9f83ee6fc

Operating system: Ubuntu 20.04.1

Architecture: AMD Ryzen Threadripper 3960X

### Extra Info

I have executed the same test case on `wasmer` and `WAVM` and the outputs are as expected.

**Comment by peterhuene** [comment]
By default, `wasmtime` does not allow unknown exports (such as `one_i32_global`) from command modules.

To run this with module with `wasmtime`, use the `--allow-unknown-exports` flag:

```
wasmtime --allow-unknown-exports hw_inco.wat
```

As this is by design with Wasmtime, I'm going to close this issue for now.

Thanks for reporting it to us!
