### ISSUE TITLE
Failed to build for aarch64-linux-android

### ISSUE THREAD

**Issue by gneworld** [bytecodealliance/wasmtime#4523]
cargo build --release --target=aarch64-linux-android
   Compiling gimli v0.26.1
   Compiling wasmparser v0.87.0
   Compiling object v0.29.0
   Compiling cranelift-bforest v0.87.0 (wasmtime/cranelift/bforest)
   Compiling clap v3.2.8
   Compiling ittapi v0.3.1
   Compiling zstd v0.11.1+zstd.1.5.2
   Compiling wiggle-macro v0.40.0 (wasmtime/crates/wiggle/macro)
error[E0412]: cannot find type `__itt_domain` in crate `ittapi_sys`
 --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/ittapi-0.3.1/src/domain.rs:9:36
  |
9 | pub struct Domain(*mut ittapi_sys::__itt_domain);
  |                                    ^^^^^^^^^^^^ not found in `ittapi_sys`

error[E0425]: cannot find value `__itt_domain_create_ptr__3_0` in crate `ittapi_sys`
  --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/ittapi-0.3.1/src/domain.rs:20:40
   |
20 |         let create_fn = access_sys_fn!(__itt_domain_create_ptr__3_0);
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ittapi_sys`

error[E0412]: cannot find type `__itt_domain` in crate `ittapi_sys`
  --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/ittapi-0.3.1/src/domain.rs:30:55
   |
30 |     pub(crate) fn as_ptr(&self) -> *const ittapi_sys::__itt_domain {
   |                                                       ^^^^^^^^^^^^ not found in `ittapi_sys`

error[E0412]: cannot find type `__itt_event` in crate `ittapi_sys`
 --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/ittapi-0.3.1/src/event.rs:6:30
  |
6 | pub struct Event(ittapi_sys::__itt_event);
  |                              ^^^^^^^^^^^ not found in `ittapi_sys`

error[E0425]: cannot find value `__itt_event_create_ptr__3_0` in crate `ittapi_sys`
  --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/ittapi-0.3.1/src/event.rs:11:46
   |
   |
61 |         if let Some(end_fn) = unsafe { ittapi_sys::__itt_event_end_ptr__3_0 } {
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ittapi_sys`

**Comment by cfallin** [comment]
Thanks for the report!

Android isn't an officially supported platform for Wasmtime. However, there may be things we can do on a best-effort basis to solve issues. @abrown or @jlb6740 , it looks like this is an issue with the `ittapi` crate -- would you be willing to take a look (maybe just conditionalize its use)?

**Comment by abrown** [comment]
@gneworld, can you take a look at #4533 and check that it fixes the issue you observed?
