### ISSUE TITLE
Question: Rust non-multithreaded Async support

### ISSUE THREAD

**Issue by Max-Meldrum** [bytecodealliance/wasmtime#4541]
Hi! 

It seems to me that many internal functions such as ``call_async`` or ``wrap_async`` have explicit requirements on ``Send + Sync``. Is there any way of running wasmtime with a non-multithreaded runtime, or is it mainly supposed to integrate well with tokio?

Cheers

**Comment by alexcrichton** [comment]
Currently, no, there's no support for futures without `Send`/`Sync` natively in the API. It may be possible with unsafe wrappers that document that it's not actually used in a `Send`/`Sync` context but short of that Wasmtime isn't well-built for this use case unfortunately.

**Comment by Max-Meldrum** [comment]
> Currently, no, there's no support for futures without `Send`/`Sync` natively in the API. It may be possible with unsafe wrappers that document that it's not actually used in a `Send`/`Sync` context but short of that Wasmtime isn't well-built for this use case unfortunately.

Thanks for the great answer.
