### ISSUE TITLE
Create an actually runnable executable in `wasm compile`

### ISSUE THREAD

**Issue by NobodyXu** [bytecodealliance/wasmtime#4563]
#### Feature

`wasmtime compile` currently generates an ELF on Linux/Mac but it cannot be executed from cmdline as a regular executable.

I would like a new option there to generate an actually runnable executable.

#### Benefit

This issue originally stems from [`cargo-binstall`](https://github.com/ryankurte/cargo-binstall), a cmdline utility similar to `cargo-install` except that `cargo-binstall` installs binaries instead of compiling everything from source for rust binaries.

It can either install it from the url specified in the `Cargo.tom` of the upstream, or from [`cargo-quickinstall`](https://github.com/alsuren/cargo-quickinstall/), or fallback to `cargo-install`.

We now want to support installation of wasm binaries as a fallback if the native executable isn't available for various reasons https://github.com/ryankurte/cargo-binstall/issues/246 and a problem we faced is that the wasm executable requires users to launch them using an wasm interpreter or using `binfmt_misc` on Linux.

We would have to wrap the wasm in a script to launch it, which makes the feature harder to implement and more prune to error.
`binfmt_misc` on the other hand is only available on Linux and not every user configure that on installation.

We tried `wasm compile`, but the native binaries it generated cannot be run directly from cmdline.

#### Implementation

Since wasm can already generates an ELF on linux, I think it won't be too hard to actually generate something runnable from cmdline and can be used as any other native executables.

Though I am not familiar with the internal designs of wasmtime at all and could be wrong.

#### Alternatives

A universal way to run wasm binaries without having to specify the interpreters on Linux/Mac/Windows.

We want to use the wasm binaries as if it is a native executable.

**Comment by bjorn3** [comment]
> Since wasm can already generates an ELF on linux, I think it won't be too hard to actually generate something runnable from cmdline and can be used as any other native executables.

The ELF files are dependent on the wasmtime runtime for everything from handling traps, to managing the linear memory and tables, to calling wasi api's. Generating executable files would require embedding wasmtime inside the executables.

**Comment by NobodyXu** [comment]
> > Since wasm can already generates an ELF on linux, I think it won't be too hard to actually generate something runnable from cmdline and can be used as any other native executables.
> 
> The ELF files are dependent on the wasmtime runtime for everything from handling traps, to managing the linear memory and tables, to calling wasi api's. Generating executable files would require embedding wasmtime inside the executables.

Can we split that part as a dynamic library and let the generated executable to depend on that?

**Comment by bjorn3** [comment]
Probably. A part of it would need to be embedded in the executable though to invoke wasmtime. In addition you would need to make sure that the dylib version matches the version of wasmtime that compiled it.

**Comment by NobodyXu** [comment]
> In addition you would need to make sure that the dylib version matches the version of wasmtime that compiled it.

Right, I forgot about that part.

So I think it is better to embed the wasi binary to a script and let the script dynamically detect the wasm runtime.
Will that interfere with wasmtime's caching system @bjorn3 ?

**Comment by bjorn3** [comment]
Not sure. I think wasmtime hashes the wasm binary to determine the cache key, in which case caching should work.

**Comment by NobodyXu** [comment]
> Not sure. I think wasmtime hashes the wasm binary to determine the cache key, in which case caching should work.

Thanks!
