### ISSUE TITLE
Debug info support / method for debugging lightbeam needed

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#460]
Hi,

I was looking to debug a trap error while running a benchmark:

> error: failed to process main module `/home/jlb6740/wasm_files/wasmtime/shootout/strcat2.c.debug.wasm`
>     caused by: Instantiation error: Trap occurred while invoking start function: wasm trap: call stack exhausted, source location: @rep-nop 

In doing so I realized I would not be able to step through the code due to supported needed for generating_debug_info. 

> error: failed to process main module `/home/jlb6740/wasm_files/wasmtime/shootout/strcat2.c.debug.wasm`
>     caused by: WebAssembly compilation error: Debug info is not supported with this configuration

This issue is to track that issue, but also to solicit comments on alternative ways of tracking down the trap error I am seeing.

Thanks.

**Comment by yurydelendik** [comment]
I would be nice to generate at least `ModuleAddressMap` data.

@jlb6740 did you try removing https://github.com/CraneStation/wasmtime/blob/a3dd4b91e1986d419a97ff708cb34f46a2e502b5/wasmtime-environ/src/lightbeam.rs#L39-L41 and let lightbeam to generate empty ModuleAddressMap ? I wonder if https://github.com/CraneStation/wasmtime/pull/267 can help here.

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
