### ISSUE TITLE
Make `Vec<T>` a wasmtime interface type

### ISSUE THREAD

**Issue by Limeth** [bytecodealliance/wasmtime#463]
As far as I can tell, there currently is no straightforward way to transfer `Vec<T>` types from a wasm module to the host. It would be desirable to let exported functions return other structured types, than [those already supported](https://docs.rs/wasmtime-interface-types/0.3.0/wasmtime_interface_types/enum.Value.html), like so:
```rust
#[wasmtime_rust::wasmtime]
pub trait Module {
    fn test1(&mut self) -> Vec<f32>;
    fn test2(&mut self) -> [f32; 3];
    fn test3(&mut self) -> CustomType;
}

#[wasm_bindgen]
struct CustomType([f32; 3]);
```

The minimal implementation would add `Vec<T> where T: wasmtime_interface_types::Value` as a supported type. This would allow `CustomType` and other types to be serialized to `Vec<u8>` and passed through the ABI.

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!
