### ISSUE TITLE
wasmtime-py doesn't build with `cargo test`

### ISSUE THREAD

**Issue by joshtriplett** [bytecodealliance/wasmtime#468]
wasmtime-py uses pyo3's "extension-module" feature flag, which makes it not link libpython directly, so that it works in whatever python or libpython the address space already has loaded.

This seems perfectly reasonable, but as far as I can tell, that means that cargo test --package=wasmtime-py can't work, as it tries to link a binary. That link results in unresolved symbol errors for all the Python symbols.

@sunfishcode suggested filing this as an issue. cc @fitzgen and @alexcrichton.

**Comment by bjorn3** [comment]
Would this work?

```rust
#[cfg(test)]
#[link(name = "python")]
extern "C" {}
```

**Comment by joshtriplett** [comment]
@bjorn3 Linking Python is not quite as simple as `#[link(name = "python")]`; pyo3 has some logic in its build script to figure that out.

Apparently [pyo3 documents this issue](https://github.com/PyO3/pyo3/blob/master/guide/src/advanced.md), and recommends disabling the extension-module feature when testing.

**Comment by konstin** [comment]
Afaik the only proper solution to this problem would be introducing something like `rustc-bin-link-arg` as bin equivalent to `rustc-cdylib-link-arg` introduced in https://github.com/rust-lang/cargo/pull/6298, thereby solving https://github.com/rust-lang/cargo/issues/5928

**Comment by alexcrichton** [comment]
This was sinced moved to https://github.com/bytecodealliance/wasmtime-py, so closing.
