### ISSUE TITLE
Question about the jitdump profileragent

### ISSUE THREAD

**Issue by scarlet25151** [bytecodealliance/wasmtime#4681]
Hi all, thanks for your answer, 
I saw in the code:
https://github.com/bytecodealliance/wasmtime/blob/a25d52046b0b641ab5acc447d7702f91d43b2bbd/crates/jit/src/profiling/jitdump_linux.rs#L85
the agent would load all the function, and for the function `finished_functions` 
https://github.com/bytecodealliance/wasmtime/blob/a25d52046b0b641ab5acc447d7702f91d43b2bbd/crates/jit/src/instantiate.rs#L540-L553
I saw it will return map of all finished JIT functions, so I would like to make sure if I would use AOT compile the function it will be listed here or not? Or are all functions, no matter where it comes from, they would be listed here?

**Comment by alexcrichton** [comment]
I don't fully understand your question, but if you're asking whether an AOT-compiled module and a JIT-compiled module both work with profiling the answer is yes, both should work the same way. Or are you perhaps asking a different question?

**Comment by scarlet25151** [comment]
@alexcrichton thank you for the confirmation, I think what I would like to make sure is for both AOT-compiled and JIT-compiled module, the functions inside the module should be load in the same way so when we calling `module.finished_functions()` they should be the same?

**Comment by scarlet25151** [comment]
Cool, appreciate for the answer, I think the issue can be closed.
