### ISSUE TITLE
Automatically test examples in the book

### ISSUE THREAD

**Issue by joshtriplett** [bytecodealliance/wasmtime#470]
What would it take to automatically test code examples in the book when we run cargo test --all, to make sure they keep working as the API evolves?

**Comment by JakeChampion** [comment]
That's a great idea @joshtriplett - it looks like this was implemented after you opened this issue, testing of the examples in the book has was added in https://github.com/bytecodealliance/wasmtime/commit/c7fb1354528f5c431d6d82b5500be1f70539671a and is still present in the current version of the codebase:
https://github.com/bytecodealliance/wasmtime/blob/b438617e1238bec01ebc804c0087e4849df0dc87/.github/workflows/main.yml#L84

I believe that we can mark this issue as resolved/closed 👍
