### ISSUE TITLE
Why not put pull_request_template.md and ISSUE_TEMPLATE?

### ISSUE THREAD

**Issue by igrep** [bytecodealliance/wasmtime#471]
If most of the [CONTRIBUTING.md of Cranelift](https://github.com/CraneStation/cranelift/blob/master/CONTRIBUTING.md) is applied to this project, I think this porject should have almost same templates.
They would make this project more contributor-friendly.

**Comment by sunfishcode** [comment]
I agree. This was something that was added in Cranelift pretty recently. We should look at Wasmtime too.

**Comment by bjorn3** [comment]
The cranelift and wasmtime repos have been merged a while ago. The issue and PR templates have been merged.
