### ISSUE TITLE
Incremental cache: fuzzbug: subtract underflow

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#4731]
OSS-Fuzz produced the following crashing testcase for the `cranelift-icache` fuzz target with the following base64 encoding:

```
/////wAAARQAAAAAAAAAgADu
```

(cat that into `base64 -d` to decode)

The crash is a panic with the message "attempt to subtract with overflow". The stackframe in the oss-fuzz report is fairly useless (line 0 in cranelift-icache.rs?) but hopefully the above reproduces easily.

cc @bnjbvr to diagnose?

**Comment by bnjbvr** [comment]
So I haven't managed to reproduce:

`base64 -d /tmp/encoded.txt > /tmp/decoded.txt` gives me what looks like a binary file,

Then I've run

`cargo +nightly fuzz run -O --no-default-features cranelift-icache /tmp/decoded`

and it runs the binary input without problems (i.e. no crash). I've ran it many times, just to make sure there wasn't any non-determinism. Am I missing something?

I'll post a PR with what could be a fix in the fuzz target itself, though.

**Comment by bnjbvr** [comment]
Can one of the people who have access to the oss-fuzz infra confirm whether the linked PR fixed this, please?

**Comment by jameysharp** [comment]
Ah, thanks for checking. Yes, oss-fuzz confirmed this fixed a few days ago: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50398
