### ISSUE TITLE
 `cargo build` failed

### ISSUE THREAD

**Issue by Ajkcki** [bytecodealliance/wasmtime#4746]
Git clone the latest code:

===================================
commit d620705a323e3da59bd90473b4e627c8502b1255 (HEAD -> main, tag: dev, origin/main, origin/HEAD)
Author: Afonso Bordado <afonso360@users.noreply.github.com>
Date:   Sat Aug 20 01:49:54 2022 +0100

    Fix Invalid Instruction format in fuzzgen (#4738)
    
    * cranelift: Add assert to prevent wrong InstFormat being used for the wrong opcode
    
    * cranelift: Use correct instruction format when inserting opcodes in fuzzgen (fixes #4733)
    
    * cranelift: Use debug assert on InstFormat assert
 =========================================

And `cargo build --release` did not work
$ cargo build --release
error: failed to load manifest for workspace member `wasmtime/crates/bench-api`

Caused by:
  failed to load manifest for dependency `wasi-cap-std-sync`

Caused by:
  failed to load manifest for dependency `wasi-common`

Caused by:
  failed to load manifest for dependency `wiggle`

Caused by:
  failed to load manifest for dependency `wiggle-macro`

Caused by:
  failed to load manifest for dependency `wiggle-generate`

Caused by:
  failed to load manifest for dependency `witx`

Caused by:
  failed to read `wasmtime/crates/wasi-common/WASI/tools/witx/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

**Comment by bjorn3** [comment]
Try `git submodule update --init` as documented at https://docs.wasmtime.dev/contributing-building.html#git-submodules.

**Comment by peterhuene** [comment]
Hi @Ajkcki. The fix suggested by @bjorn3 should hopefully resolve the problem for you. As such, I'm going to close this issue for now.

If it does not, please reopen this issue and let us know. Thanks!
