### ISSUE TITLE
Implement more features when fuzzing against the spec interpreter

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#4852]
Currently the spec interpreter is very rarely used when differential fuzzing due to the current constraints of the integration. Some new features are required (all of which I think require writing some OCaml) to support better integration:

* The instantiation and execution phases of a wasm instance need to be split apart. Right now [instantiation always feigns success](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L55-L60) which means that wasm modules which fail to instantiate (with an out-of-bounds element segment for example) fail later than other engines. This is why the spec fuzzer [disallows tables](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L29-L37)
* Currently the integration with the spec test fuzzing [does not support more than one function](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L21-L27) because the current OCaml harness I believe executes the first function. Instead [the function name should get threaded through here](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L90) and executed.
* Getting the values of linear memory and/or wasm globals [is currently unimplemented](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L96-L104).
* Less critical but still nice-to-have, [error messages are not validated](https://github.com/bytecodealliance/wasmtime/blob/d2e19b8d74f557d862214938aa3184efe2409641/crates/fuzzing/src/oracles/diff_spec.rs#L62-L65) to ensure that Wasmtime and the spec interpreter produce the same flavor of trap.

cc @conrad-watt IIRC you've been working with @abrown to make a more generalized harness and I think the intention was to land it in https://github.com/bytecodealliance/wasm-spec-interpreter but if you're willing I think it'd also be good to get the updates into this repository ahead of that if there are orthogonal issues there to tackle (I'm unsure of its status, we could also fill out that repo and then replace the in-tree copy of the repo here with the external dependency)

**Comment by conrad-watt** [comment]
@abrown, I believe that the new interface I implemented for the interpreter [here](https://github.com/bytecodealliance/wasmtime/compare/main...conrad-watt:wasmtime:main) addresses the first three bullet points in the OP. How much effort would it be to merge this in?

**Comment by abrown** [comment]
Sure, I like the idea of trying it out here first. I can work in the changes we made next week and submit a PR.

**Comment by conrad-watt** [comment]
With the merging of https://github.com/bytecodealliance/wasmtime/pull/4881, where are we on this now?

**Comment by abrown** [comment]
It looks like mostly done; maybe matching up the error messages to the Wasmtime trap equivalent is all that is left?
