### ISSUE TITLE
How to compile the wasmtime project from source code ?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#4921]
How to compile the wasmtime project from source code and generate the wasmtime command?

**Comment by bjorn3** [comment]
If you have rust installed you can do `cargo build --release` and then get the wasmtime command from target/release. If you didn't checkout submodules yet, you may need to run `git submodule update --init` before running `cargo build --release`. See https://docs.wasmtime.dev/contributing-building.html

**Comment by Zhangyx24** [comment]
Thanks a lot !
