### ISSUE TITLE
Avoid quadratic behavior in `can_optimize_var_lookup`

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#4938]
Originally fixed in https://github.com/bytecodealliance/wasmtime/pull/4924 but that fix was [found to be flawed](https://github.com/bytecodealliance/wasmtime/pull/4924#issuecomment-1252999878) and reverted in #4937. We need a new approach, and IIUC @jameysharp is working on a patch.

cc @jameysharp @adambratschikaye

**Comment by jameysharp** [comment]
I think we should just re-open #4923 for this, since it has all of @adambratschikaye's notes on the problem.
