### ISSUE TITLE
Unable to run tcp socket in wasmtime

### ISSUE THREAD

**Issue by expploitt** [bytecodealliance/wasmtime#4978]
I would like to know the state of networking in wasmtime 1.0.0, because I can compile tcplistener with the target wasm32-wasi but then wasmtime throws error "funcionality not supported". 

I would like to know if I have to preopend sockets or to use some specific crate in the case of having basic networking available.

Thanks!

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/pull/3729 added the arguments of which you need to use one to open the socket and https://github.com/rust-lang/rust/pull/93158 implemented rust support and provides a code snippet you can use.

**Comment by alexcrichton** [comment]
Indeed I believe this is implemented to the extent that WASI supports sockets today, if you'd like more functionality I'd recommend opening an issue on the WASI proposal to extend the sockets proposal.
