### ISSUE TITLE
Trap handling for Windows ARM64

### ISSUE THREAD

**Issue by Berrysoft** [bytecodealliance/wasmtime#4992]
After #4990 merged, we can build wasmtime for Windows ARM64, and it should work without trap handling.

We now need to add trap handling to make it totally work.

**Comment by Berrysoft** [comment]
https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/isa/aarch64/mod.rs#L152

**Comment by hwoodiwiss** [comment]
Is this something that's being looked at actively at the moment, and would a community contributions be welcome for this?

**Comment by cfallin** [comment]
No one has indicated they're working on it, so if you or anyone who is familiar with Windows on Arm is willing to build it, we'd very much welcome it!

**Comment by dpaoliello** [comment]
It's hackathon week at Microsoft, so I'm going to have a go at this as my project...

**Comment by dpaoliello** [comment]
I have a draft PR: #9266

Currently most tests are passing, but there is a crash in the JITted code. Unfortunately, there doesn't seem to be debug info (or stack is corrupted just for the JIT frames) and WinDbg is crashing when I try to capture a Time Travel Trace.

**Comment by dpaoliello** [comment]
Update: I got everything working (required a more careful reading of the spec and how wasmtime emits instructions).
PR has been published.

**Comment by cfallin** [comment]
Very exciting, thanks @dpaoliello! It looks like Alex has looked at the PR at a high level; I'll do a detailed review.

**Comment by kpreisser** [comment]
Thank you very much for implementing unwind support for Windows Arm64, and providing release artifacts!
When running the unit tests of [`wasmtime-dotnet`](https://github.com/bytecodealliance/wasmtime-dotnet/) on Windows 11 Version 23H2 Arm64 (using the `wasmtime-dev-aarch64-windows-c-api.zip` artifact of the latest dev release), all tests now succeed.
