### ISSUE TITLE
C-API: wasm_valtype_new_funcref panics

### ISSUE THREAD

**Issue by amusingimpala75** [bytecodealliance/wasmtime#4993]
### Expected behaviour:
`wasm_valtype_new_funcref()` or `wasm_valtype_new(WASM_FUNCREF)` return a `wasm_valtype_t *` with a FuncRef type.
### Actual behaviour:
errors with
> thread '< unnamed>' panicked at 'unexpected kind: 129', crates/c-api/src/types/val.rs:40:14

and terminates

**Comment by bjorn3** [comment]
There is no wasm_valtype_new_funcref function in wasmtime. As for WASM_FUNCREF it exists and should be handled at https://github.com/bytecodealliance/wasmtime/blob/3fa545bd89d6e18e6e85eab57499ee9c9f5032f2/crates/c-api/src/types/val.rs?q=WASM_FUNCREF#L38. Are you using the latest wasmtime version?

**Comment by amusingimpala75** [comment]
wasmtime-v1.0.1-aarch64-macos-c-api

**Comment by amusingimpala75** [comment]
also include/wasm.h defines an inline `wasm_valtype_new_funcref()` which just defers to `wasm_valtype_new(WASM_FUNCREF)`.

**Comment by amusingimpala75** [comment]
externref does not work either.

**Comment by alexcrichton** [comment]
Thanks for the report, but this looks like something may be going wrong on your end somewhere, although I'm not sure where. The error message

> `thread '< unnamed>' panicked at 'unexpected kind: 129', crates/c-api/src/types/val.rs:40:14`

says that 129 wasn't expected but that's the value of `WASM_FUNCREF` which is in the `match` arm. This may mean that while you think you're using 1.0.1 you're using an older binary by accident or something like that (or a completely different binary?)

I've tested this locally with the Python bindings for the C API and these functions work and return the expected result.

**Comment by alexcrichton** [comment]
Although now that I think this could also be an aarch64-macos ABI-specific issue, unfortunately though I do not have access to such hardware to test myself.

**Comment by bjorn3** [comment]
Could this be https://github.com/rust-lang/rust/issues/97463?

**Comment by amusingimpala75** [comment]
I have not used Wasmtime previously, so it is not a stale binary problem.
Yeah, it just doesn’t make sense because WASM_FUNCREF is clearly being evaluated as 129 from vals.rs, but then a direct comparison to that variable in the rust function fails, so I suspect it might be the ABI problem.

**Comment by amusingimpala75** [comment]
I have now tried building the c-api with +nightly (1.66.0-nightly, from Oct 3), and it is producing a binary with a different hash, but it still will not work, creating the same error. I've never really fiddled with Rust before, so maybe I just do not know what I am doing.

**Comment by amusingimpala75** [comment]
Nevermind, I just have to use the debug build, not the release build.
