### ISSUE TITLE
Implement Windows unwind information for lightbeam

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime#501]
Now that cranelift can emit unwind, a similar implementation should be made to lightbeam to allow the registration of unwind information for JIT functions.

See https://github.com/CraneStation/cranelift/pull/1155 for the cranelift implementation.

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
