### ISSUE TITLE
broken polyfill links

### ISSUE THREAD

**Issue by kulakowski-wasm** [bytecodealliance/wasmtime#5038]
https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-intro.md

The links in the `browser polyfill` section 404.

**Comment by sunfishcode** [comment]
We should remove that link, as we're no longer maintaining the original polyfill.

**Comment by jameysharp** [comment]
This is a long-standing issue, previously reported at #937. So I'm closing it as a duplicate, but yes, we really should actually fix this.
