### ISSUE TITLE
Bench-api --engine-flags can't accept text leading with '--'

### ISSUE THREAD

**Issue by brianjjones** [bytecodealliance/wasmtime#5057]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Test Case

TODO: upload Wasm file here

### Steps to Reproduce

1.) Build bench-api.
2.) sightglass-cli benchmark ... --engine-flags '--wasi-modules experimental-wasi-nn'

### Expected Results

Benchmark runs to completion

### Actual Results
error: Found argument '--wasi-modules experimental-wasi-nn' which wasn't expected, or isn't valid in this context

### Versions and Environment

wasmtime commit ff0c45b4a069a84b131c8265d8d14c2f7d0566d7

Operating system: ubuntu 20.04

Architecture: x86

### Extra Info

--engine-flags appears to not be able to accept a string that starts with --, so you are unable to set the flag needed to cause wasi-nn to be linked at runtime. This means wasi-nn can't be used by Sightglass currently.

**Comment by brianjjones** [comment]
@abrown This is the issue we discussed today.

**Comment by fitzgen** [comment]
It works if you do `--engine-flags="--foo"` with the `=` in there. This makes sense to me since the CLI parser otherwise can't determine whether this should be parsed as `["--engine-flags", "--foo"]` or `["--engine-flags=--foo"]`.

**Comment by brianjjones** [comment]
This appears to be a Sightglass issue, so most likely not a Wasmtime bug.
