### ISSUE TITLE
egraphs fuzzbug: "assertion failed: self.values[v].ty().is_invalid()"

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#5100]
On `spectests` fuzz target, with input (base64'd)

```
ICAgIP//ICAgICAg//8gICAgICAgICAgIP8gICAgICAgIP8gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAAa
```

we get

```
  assertion failed: self.values[v].ty().is_invalid()
  cranelift_codegen::egraph::FuncEGraph::elaborate::h6d3baada5c13884e
  cranelift_codegen::context::Context::optimize::hd81b91acfa46eca1
```

I suspect this is an issue related to recent optimizations and is probably an easy fix; I'll take a look on Monday.

OSS-Fuzz issue [52640](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52640)

**Comment by afonso360** [comment]
It looks like cranelift-fuzzgen found the same issue, I *just* filed a similar bug report in #5099!

**Comment by cfallin** [comment]
Ah, and your bug report is much more useful with a CLIF input too -- thanks!
