### ISSUE TITLE
cranelift: Rename `iadd_carry`/ `iadd_cout` instructions 

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5165]
👋 Hey,

While implementing `iadd_cout` for aarch64 I realized that the output of the carry bit depends on signedness of the operation. If we implement it as unsigned we only signal overflow on `0xFF` + 1, and if we implement it as signed we signal overflow on `0x7F` + 1

Thus  should we rename this operation to `sadd_cout` to keep consistency with our other operations that depend on signedness (i.e. `sdiv`/`udiv`)? The operation seems to be signed based on the [existing test suite](https://github.com/bytecodealliance/wasmtime/blob/faeeed4fb94e03b5108940dd71f2b360f97d3983/cranelift/filetests/filetests/runtests/iaddcout.clif#L21).

Does the existence of `sadd_cout` also imply that we should have `uadd_cout`?

The same question applies for `iadd_carry`, but not for `iadd_cin`.

**Comment by bjorn3** [comment]
Makes sense. I would have expected iadd_cout to be unsigned. As the name carry is often used for unsigned overflow AFAIK. For example x86 has the carry and overflow flags for unsigned cq signed overflow.

> Does the existence of sadd_cout also imply that we should have uadd_cout?

IMO yes there should be.

**Comment by afonso360** [comment]
It looks like we also [discussed the naming of the new `iadd_overflow_trap` instruction](https://github.com/bytecodealliance/wasmtime/pull/5123#issuecomment-1292419397) last week, and it got renamed to `uadd_overflow_trap`. 

And it looks like folks preferred `uadd_overflow_trap` instead of `uadd_carry_trap`, so maybe we should apply the same naming convention here? (I'd be in favor of this.)
