### ISSUE TITLE
Case sensitivity on Windows

### ISSUE THREAD

**Issue by Mrowqa** [bytecodealliance/wasmtime#518]
I was thinking about making wasmtime work with Windows paths and read [this](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file). I've found such a statement:
> Do not assume case sensitivity.

It turns out that Windows actually have `FILE_FLAG_POSIX_SEMANTICS` flag for [CreateFileA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) function. We have discussed with @sunfishcode for a little bit what should be the semantics for WASI: case sensitive or host dependent. Or maybe even case insensitive. Some apps would like to integrate better with the OS while some other ones would like to be platform independent. Yet another aspect is the compatibility with older systems (how old is the mentioned flag?). I'm opening a discussion here linking two random blog posts that I have found quickly during the short discussion with @sunfishcode  (haven't read the full content of them though): [one](https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/) and [two](https://tyranidslair.blogspot.com/2019/02/ntfs-case-sensitivity-on-windows.html).

**Comment by Serentty** [comment]
It's also important to consider that Apple's operating systems also create case-insensitive filesystems by default. This is a bad decision in my mind, especially considering that Microsoft and Apple both do their case mapping in different ways, based on different outdated Unicode charts, but it is what it is.

**Comment by sunfishcode** [comment]
Indeed. And I don't know of any good ways to emulate case sensitivity on a filesystem that doesn't have it, or vice versa. We could mangle names, but that creates new problems for users. We could scan for names differing only by case, but that's slow and not atomic.

So here's an outline of a possible strategy:

When you create a file, the host may do a host-specific and transformation on its name. When you open a file, the host may do a host-specific match on the name. The two things you can count on are:
 - The transformation is some form of case transformation. It may be based on an outdated Unicode version, but it won't be an arbitrary transform.
 - You can always name a file at least by the same path as you created it with.

This does imply a portabilty hazard, where WASI programs could come to depend on filesystems being case-sensitive, or being case-insensitive. One thing we can do is encourage engines to have developer features where developers can test their apps in a mode that helps detect such errors, such as by occasionally scanning for files that differ only in case.

**Comment by sunfishcode** [comment]
It turns out, there's also an open issue for this in the WASI repo, so let's continue the discussion [there](https://github.com/WebAssembly/WASI/issues/72).
