### ISSUE TITLE
Use safe code for calling `readlinkat`

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime#519]
On Linux, `readlinkat` returns `EINVAL` if given a zero-length buffer. WASI's `wasi_path_readlink` should follow the POSIX semantics for `readlinkat` instead. wasi-common implements this, however it uses an `unsafe` call to the libc `readlinkat` rather than calling through a safe nix wrapper.

See the discussion [here](https://github.com/CraneStation/wasi-common/pull/27/#discussion_r294497606) for more details.

**Comment by kubkon** [comment]
Similarly to the story in #521, given that we've decided to replace `nix` dependency with our own thin, low-level in-house wrapper crate `yanix` (see #649), I'm closing this issue as it's no longer relevant.
