### ISSUE TITLE
invoke doesn't check that the right number of arguments are passed

### ISSUE THREAD

**Issue by sfackler** [bytecodealliance/wasmtime#52]
The function checks that all provided arguments have the correct type, but not that the right number were provided. In particular, you can pass 0 arguments to any function and the call will succeed with all parameters set to 0.

https://github.com/CraneStation/wasmtime/blob/602e81a895b251d49c60f0c6ffed9cb71d0509c5/lib/jit/src/action.rs#L155-L158

**Comment by sunfishcode** [comment]
Thanks for the report! You're right, we should check the number of parameters as well.

**Comment by lostman** [comment]
We just have been bitten by the same issue! Thanks for reporting. Otherwise I'd be searching for the reason.
