### ISSUE TITLE
Any examples to bind host function in C++ embedded code?

### ISSUE THREAD

**Issue by alexthomas1** [bytecodealliance/wasmtime#5260]
I have a WASM file that calls a function in the host, but the name of the label becomes env::_Z5hellov.

How do I register the binding in C++? Thank you!

**Comment by bjorn3** [comment]
You have to put the function prototype in a `extern "C" { ... }` block to disable name mangling.

**Comment by alexthomas1** [comment]
Thank you, I did that and I get

(import "env" "_Z5hellov" (func $hello__ (type 2)))

and 

unknown import: `env::_Z5hellov` has not been defined

when I put the function prototype in the extern block.

**Comment by bjorn3** [comment]
What is the exact code you used?

**Comment by alexthomas1** [comment]
I have been trying to modify the example: third_party/wasmtime/examples/hello.c, to load the binary directly (instead of using the wat representation). 

`#include <stdio.h>

extern "C" {
    void hello();
}

int main(int argc, char **argv){
    hello();
}`

This is what my hello.cc looks like.

**Comment by bjorn3** [comment]
It works for me: https://godbolt.org/z/YGccKMhWY

```wasm
__main_argc_argv:                       # @__main_argc_argv
        call    hello
        i32.const       0
        end_function
```

**Comment by alexthomas1** [comment]
On the host-side, in third_party/wasmtime/examples/hello.c, how does wasmtime know the correct symbol to use (i.e. hello)?

**Comment by bjorn3** [comment]
I think it sets hello_callback as the first import, not for the import named "hello".

**Comment by alexthomas1** [comment]
So when I have multiple imports, how does that work? Are there any examples of this?

I also still get: 

`unknown import: `env::_Z5hellov` has not been defined`

**Comment by alexcrichton** [comment]
Thanks for the report here, and I'd recommend reading the documentation at https://docs.rs/wasmtime/latest/wasmtime/. The C++ embedding API for Wasmtime is documented at https://bytecodealliance.github.io/wasmtime-cpp/ and you might want to look at the [examples and tests as well](https://github.com/bytecodealliance/wasmtime-cpp/).

The embedding documentation should explain a "linker" which can be used to provide host functionality to a guest module.
