### ISSUE TITLE
test: flaky test in `wait`/`notify` implementation

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#5312]
### Test Case

Already present in the test suite: `wait_notify::atomic_wait_timeout_length`.

### Steps to Reproduce

Not always reproducible; flaky test, see: https://github.com/bytecodealliance/wasmtime/actions/runs/3518335769/jobs/5897139376#step:15:1843.

### Expected Results

The test should pass.

### Actual Results

The test fails:

```
---- wait_notify::atomic_wait_timeout_length stdout ----
thread 'wait_notify::atomic_wait_timeout_length' panicked at 'duration: 499.7351ms < 500000000', tests\all\wait_notify.rs:33:5
```

### Versions and Environment

CI

**Comment by abrown** [comment]
cc: @haraldh, @alexcrichton

**Comment by haraldh** [comment]
please reopen, if it happens again
