### ISSUE TITLE
Unexpted error "called `Option::unwrap()` on a `None` value" (or an access violation) with Wasmtime 3.0.0 (wasmtime-dotnet / C API)

### ISSUE THREAD

**Issue by kpreisser** [bytecodealliance/wasmtime#5325]
Hi, 
we use Wasmtime 3.0.0 with `wasmtime-dotnet` in an application where we load a 8 MB .wasm file produced by the WASI SDK for .NET. 

After instantiating the module and calling the exported `_start` function, we either get an access violation, or the following error is printed to the console and returned as trap (with `RUST_BACKTRACE=full` (this is on Windows 10 x64 (Build 19044)):
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\c-api\src\linker.rs:104:63
stack backtrace:
   0:     0x7ffdf2b36d42 - impl_new_epoch
   1:     0x7ffdf2b5283b - impl_new_epoch
   2:     0x7ffdf2b31f7a - impl_new_epoch
   3:     0x7ffdf2b39464 - impl_new_epoch
   4:     0x7ffdf2b3909a - impl_new_epoch
   5:     0x7ffdf2b39c51 - impl_new_epoch
   6:     0x7ffdf2b39b1a - impl_new_epoch
   7:     0x7ffdf2b3776f - impl_new_epoch
   8:     0x7ffdf2b39820 - impl_new_epoch
   9:     0x7ffdf2bf4a85 - _jit_debug_register_code
  10:     0x7ffdf2bf492c - _jit_debug_register_code
  11:     0x7ffdf2533d52 - wasm_foreign_delete
  12:     0x7ffdf259008d - wasm_globaltype_copy
  13:     0x7ffdf25b7cad - wasmtime_val_delete
  14:     0x7ffdf24edb09 - wasm_foreign_delete
  15:      0x1b7f0bfa26d - <unknown>
  16:      0x1b7f0bfa090 - <unknown>
  17:      0x1b7f0bf8501 - <unknown>
  18:      0x1b7f086102c - <unknown>
  19:      0x1b7f0c22bee - <unknown>
  20:      0x1b7f0c230eb - <unknown>
  21:     0x7ffdf2bb2c73 - _jit_debug_register_code
  22:     0x7ffdf25c2d74 - wasmtime_val_delete
  23:     0x7ffdf25d55f6 - wasm_tabletype_copy
  24:     0x7ffdf24f4ef7 - wasm_foreign_delete
  25:     0x7ffdf24f7de5 - wasm_foreign_delete
  26:     0x7ffdf25e3ed0 - wasmtime_func_call
  27:     0x7ffd9e0b0f8c - <unknown>
  28:     0x7ffd9e0b0c79 - <unknown>
  29:     0x7ffd9e0b08a3 - <unknown>
  30:     0x7ffd9e0b06b8 - <unknown>
  31:     0x7ffd9e0a553c - <unknown>
  32:     0x7ffd9e0a2eb1 - <unknown>
  33:     0x7ffdfdc4aac3 - coreclr_shutdown_2
  34:     0x7ffdfdb681a6 - <unknown>
  35:     0x7ffdfdbeeff7 - MetaDataGetDispenser
  36:     0x7ffdfdbeee76 - MetaDataGetDispenser
  37:     0x7ffdfdbeed25 - MetaDataGetDispenser
  38:     0x7ffdfdbeeae6 - MetaDataGetDispenser
  39:     0x7ffdfdc05dd2 - coreclr_execute_assembly
  40:     0x7ffe93b3971b - <unknown>
  41:     0x7ffe93b39a4c - <unknown>
  42:     0x7ffe93b3a3e7 - corehost_main
  43:     0x7ffe9fb6b77c - hostfxr_close
  44:     0x7ffe9fb6e3f7 - hostfxr_close
  45:     0x7ffe9fb7075f - hostfxr_close
  46:     0x7ffe9fb6ea53 - hostfxr_close
  47:     0x7ffe9fb6850b - hostfxr_main_startupinfo
  48:     0x7ff6c39d1eb8 - <unknown>
  49:     0x7ff6c39d222b - <unknown>
  50:     0x7ff6c39d36d8 - <unknown>
  51:     0x7ffebb5774b4 - BaseThreadInitThunk
  52:     0x7ffebbce26a1 - RtlUserThreadStart
Unhandled exception. Wasmtime.TrapException: called `Option::unwrap()` on a `None` value
```

I can reproduce the error, using the following configuration:
- Create a C# application (.NET 6.0) with "dotnet new console", containing a project reference to `Wasmtime.Dotnet` from commit https://github.com/bytecodealliance/wasmtime-dotnet/commit/415438c88eb9c3b8d52de924020ce21630fe070b.
- In the `Wasmtime.csproj`, remove the code for downloading `wasmtime`, and instead download `wasmtime-v3.0.0-x86_64-windows-c-api.zip` , and use the `wasmtime.dll` from there.
- Use the following code in the C# application (`Program.cs`):
```cs

using Wasmtime;

using var engine = new Engine();
using var module = Module.FromBytes(engine, "main", File.ReadAllBytes(@"dotnet-codabix-wasm-build.wasm"));

using var linker = new Linker(engine);
using var store = new Store(engine);
linker.DefineWasi();
var instance = linker.Instantiate(store, module);

var run = instance.GetAction("_start")!;
run();
```
- Download the following .Zip file and extract `dotnet-codabix-wasm-build.wasm` from it (this is not actually a movie; I renamed the .zip to .mov to be able to upload it):
  https://user-images.githubusercontent.com/13289184/203989968-4639d6d5-15c9-4e57-bf01-c2eccd756642.mov

When running the C# application, it should print the above error to the console.

I did not yet have a chance to try to reproduce it using a plain C application. Also, I did not manage to reproduce the access violation in the above C# application, as it seems a bit hard to reproduce, but I would assume it has the same cause as the above error.

Do you have any idea what could be causing this? Do you need any further information?

On a related note, I can also reproduce this error using the Wasmtime **dev** release from commit 28cf995fd3f9926a95036758c78390f54a0289ae, but it seems it needs much more time for compiling the module (18.6 seconds for the dev version, but only 2.8 seconds for the 3.0.0 version).

Thank you!

**Comment by bjorn3** [comment]
I think you need to call the C# equivalent of `wasmtime_context_set_wasi` on the store.

**Comment by kpreisser** [comment]
Thanks! You are right, this fixes the error. Unfortunately, this doesn't fix the access violation in our other application (where the call to `store.SetWasiConfiguration()` already occurs), so this actually seems to be a different error.

I will continue to try to reproduce that and then open a new issue.
