### ISSUE TITLE
Unable to Obtain Current Stack Trace without a Trap

### ISSUE THREAD

**Issue by jtenner** [bytecodealliance/wasmtime#5339]
Hey! I am trying to obtain the current stack trace without invoking a panic, inside a linked function.

```rs
// this is awesome!
let backtrace = Backtrace::new();
```

I can access the stack frames using `Backtrace::new()` but I can't really do anything with it because all the functions that translate these into function names and strings are `pub(crate)` and internal to wasmtime.

Is there perhaps a safe way to obtain the current stack trace without calling a wasm function that executes an unreachable() instruction?

**Comment by alexcrichton** [comment]
While not currently possible now I opened https://github.com/bytecodealliance/wasmtime/pull/5341 to expose a method for doing this.

**Comment by jtenner** [comment]
@alexcrichton it looks like the `WasmBacktrace::new()` function is private and not exposed. Can I get some help with this?

**Comment by jtenner** [comment]
```rs
error[E0599]: no function or associated item named `capture` found for struct `WasmBacktrace` in the current scope
   --> crates\lunatic-process-api\src\lib.rs:805:36
    |
805 |     let backtrace = WasmBacktrace::capture();
    |                                    ^^^^^^^ function or associated item not found in `WasmBacktrace`
```

**Comment by alexcrichton** [comment]
Are you using `main` or the `release-4.0.0` branch? This feature isn't present in any crates.io-based release of Wasmtime yet.
