### ISSUE TITLE
Is there any tool that could transform cranelift IR back to Wasm binaries?

### ISSUE THREAD

**Issue by Zhangyx24** [bytecodealliance/wasmtime#5436]
Is there any tool that could transform cranelift IR back to Wasm binaries?

**Comment by cfallin** [comment]
What you're looking for is a "WebAssembly backend", i.e., a backend for the compiler that targets Wasm rather than another ISA (like x86 or aarch64). We have an issue to track that: #2566. Unfortunately it doesn't exist yet. I'll close this issue in favor of that one.

**Comment by Zhangyx24** [comment]
Thanks for your answer !
