### ISSUE TITLE
Cranelift: `vconcat` is not implemented in the interpreter

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5457]
👋 Hey!

### `.clif` Test Case

```
test interpret

function %vconcat_i32x4(i32x2, i32x2) -> i32x4 {
block0(v0: i32x2, v1: i32x2):
    v2 = vconcat.i32x2 v0, v1
    return v2
}
; run: %vconcat_i32x4([1 2], [3 4]) == [1 2 3 4]

function %vconcat_i64x2(i64, i64) -> i64x2 {
block0(v0: i64, v1: i64):
    v2 = vconcat.i64 v0, v1
    return v2
}
; run: %vconcat_i64x2(1, 2) == [1 2]
```

### Steps to Reproduce

* Run `cargo run -- test ./the-above-file.clif` in the `cranelift` directory of this repository

### Expected Results

The test to pass!

### Actual Results

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `/home/afonso/git/wasmtime/target/debug/clif-util test lmao.clif`
thread 'worker #0' panicked at 'not implemented: Vconcat', cranelift/interpreter/src/step.rs:1073:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #0: not implemented: Vconcat
FAIL lmao.clif: panicked in worker #0: not implemented: Vconcat
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main
Operating system: Linux
Architecture: x86_64

### Extra Info

The above test is failing in [this assertion](https://github.com/bytecodealliance/wasmtime/blob/2cfa024855f4b542999c7bf547838e2f85b244a5/cranelift/interpreter/src/step.rs#L989).

Some documentation about the expected behavour of `vconcat` can be found [here](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/trait.InstBuilder.html#method.vconcat).

**Comment by jameysharp** [comment]
After discussion offline with @cfallin, I think we should close this in favor of deleting this instruction, which I've written up in #5463. That is also a good first issue for anyone who wants to tackle it.
