### ISSUE TITLE
wasmtime-runtime 1.0 doesn't build on Windows

### ISSUE THREAD

**Issue by ark0f** [bytecodealliance/wasmtime#5494]
Same as #5133 but for 1.0

**Comment by jameysharp** [comment]
Thanks for reporting this! However, according to [Wasmtime's release process](https://docs.wasmtime.dev/stability-release.html), "Security bugs and correctness fixes will be backported to the latest two releases of Wasmtime and issued as patch releases."

The last two releases now are 4.0 and 3.0, so we no longer support 1.0. As a result, I'm closing this issue.

If there's something we can fix that's keeping you from upgrading to a newer version of Wasmtime, please open an issue for that. We'd like to help!
