### ISSUE TITLE
Cranelift: can we get rid of `debug_trap`?

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#5518]
I *think* these were a SpiderMonkey-ism? Unused now, AFAICT.

**Comment by bjorn3** [comment]
It may be useful for other jit's in the future.

**Comment by fitzgen** [comment]
After discussing this in today's cranelift meeting, it seems like the best course of action is probably to remove `debug_trap` instead, and keep `resumable_trap`. They are identical except that `resumable_trap` has a trap code. If the user doesn't want a trap code they can always ignore it or use a custom user trap code that effectively means "no trap code".

**Comment by bjorn3** [comment]
Note that `debug_trap` must keep `int3` as lowering. Otherwise debuggers get confused. This could be done by adding a trap code for a breakpoint. I don't think there is precedent for changing codegen depending on the trap code though. I believe it is currently extra information that can be stored in a side table.

**Comment by fitzgen** [comment]
I think we must have gotten rid of this at some point, because `debug_trap` no longer exists in the code base.

**Comment by bjorn3** [comment]
It is now called `debugtrap` and still used by cg_clif for implementing the `breakpoint` rust intrinsic.

**Comment by fitzgen** [comment]
Yeah, I actually discovered the renaming that took place at some point just now as well.

Is there a reason that cg_clif has to use `debugtrap` instead of a normal `trap`?

**Comment by bjorn3** [comment]
`trap` generates `ud2` which is not resumable and produces `SIGILL`, while `debugtrap` generates `int3` which is resumable and which debuggers handle identical to a breakpoint set using the debugger itself.

**Comment by fitzgen** [comment]
Gotcha.

FWIW, `debugtrap` produces `hlt`, not `int3`, on x64 right now. I guess this doesn't matter though?

**Comment by bjorn3** [comment]
It actually generates `int3`, but the instruction is called wrong in the Cranelift backend: https://github.com/bytecodealliance/wasmtime/blob/34b6b6738e22e13e66336a28fb4f1a1beb3e46e5/cranelift/codegen/src/isa/x64/inst/emit.rs#L4018-L4020 `0xcc` is `int3`. `hlt` would be `0xf4`.

**Comment by fitzgen** [comment]
Good to know. Either way, it seems like we shouldn't actually get rid of this, so I'm leaving the issue closed.
