### ISSUE TITLE
Cranelift: Remove `table_addr` and tables from CLIF, move them into `cranelift-wasm`'s Wasm -> CLIF lowering

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#5532]
Similar to what we did with heaps in https://github.com/bytecodealliance/wasmtime/issues/5283

**Comment by bjorn3** [comment]
Got a commit which removes the table_addr instruction at https://github.com/bjorn3/wasmtime/tree/remove_table_addr. I'm not sure how to implement a replacement in cranelift-wasm, but if someone else wants to pick this issue up, feel free to use my code.
