### ISSUE TITLE
host import function declaration order causes incompatible import types

### ISSUE THREAD

**Issue by RinLovesYou** [bytecodealliance/wasmtime#5626]
Hi there! I'm just starting to explore using wasm to create a plugin framework.

I was starting to play with host import functions, and noticed i was unable to have more than one.

### Host
```rs
let log_str = Func::wrap(&mut store, exports::log_str);
let instance = Instance::new(&mut store, &module, &[ log_str.into() ])?;
```

### Wasm
```rs
extern "C" {
    fn log_str(ptr: i32, len: i32);
}
```

### Output
`[17:50:14.104] Hello from wasm!`

If i now add a second function:

### Host
```rs
let get_assembly_count = Func::wrap(&mut store, exports::get_assembly_count);
let log_str = Func::wrap(&mut store, exports::log_str);

let instance = Instance::new(&mut store, &module, &[get_assembly_count.into(), log_str.into() ])?;
```
### Wasm
```rs
extern "C" {
    fn get_assembly_count() -> i32;
    fn log_str(ptr: i32, len: i32);
}
```
### Output
``` [17:56:14.791] [ERROR] Failed to load mod: incompatible import type for `env::log_str` ```

I've looked through the documentation/examples/issues and i've never seen this mentioned, so i'm a bit lost

**Comment by RinLovesYou** [comment]
Even more perplexing behavior, if i switch

```rs
let instance = Instance::new(&mut store, &module, &[get_assembly_count.into(), log_str.into() ])?;
```

to

```rs
let instance = Instance::new(&mut store, &module, &[ log_str.into(), get_assembly_count.into() ])?;
```

it now works...
```
[18:02:18.073] Hello from wasm!
[18:02:18.073] There are 97 assemblies
```

**Comment by alexcrichton** [comment]
Thanks for the report! As the documentation for [`Instance::new`](https://docs.rs/wasmtime/latest/wasmtime/struct.Instance.html#providing-imports) indicates:

> The entries in the list of imports are intended to correspond 1:1 with the list of imports returned by [Module::imports](https://docs.rs/wasmtime/latest/wasmtime/struct.Module.html#method.imports)

You can't rely on the order in the source being the exact same order in the output module. When using `Instance::new` you'd instead need to use` Module::imports` to learn what order to pass things in.

Instead, though, as [`Instance::new`](https://docs.rs/wasmtime/latest/wasmtime/struct.Instance.html#providing-imports) indicates, it's recommended to use the [`Linker`](https://docs.rs/wasmtime/latest/wasmtime/struct.Linker.html) type which does name-based resolution which is generally easier to work with.

**Comment by RinLovesYou** [comment]
Ahh thank you, the Linker does indeed solve that problem!
