### ISSUE TITLE
Adding versioning macros to the C API?

### ISSUE THREAD

**Issue by thibaultcha** [bytecodealliance/wasmtime#5635]
#### Feature

Could we add versioning macros to the C API in `wasmtime.h`?

#### Benefit

As our embedder program can be linked against several Wasm runtimes, we wish to add compilation guards ensuring the version of these runtimes is either tested or compatible with the targets chosen by our users; without them having to face numerous compilation errors or more obscure behavior when it is not the case.

E.g.
```c
#if WASMTIME_VERSION_MAJOR != 5
#error Unsupported Wasmtime version detected, please use Wasmtime 5.x.y
#endif
```

#### Implementation

E.g.
```c
// wasmtime.h
#define WASMTIME_VERSION "5.0.0"
#define WASMTIME_VERSION_MAJOR 5
#define WASMTIME_VERSION_MINOR 0
#define WASMTIME_VERSION_PATCH 0
```

#### Alternatives

N/A

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

One thing to watch out for though is that we'll want support in https://github.com/bytecodealliance/wasmtime/blob/main/scripts/publish.rs to have that script update these version numbers along with other version numbers.
