### ISSUE TITLE
Make `FunctionBuilder::is_pristine(...)` public again

### ISSUE THREAD

**Issue by ptitSeb** [bytecodealliance/wasmtime#5654]
Thanks for filing a feature request! Please fill out the TODOs below.

#### Feature

With Cranelift 0.90, `FunctionBuilder::is_pristine(...)`  is private and not public.
Is there a way to know if a block is empty or not?

#### Benefit

For example knowing if an `Else` branch of an `If` exist or not.

#### Implementation

Make the current function public

#### Alternatives

I don't see any practical alternative

**Comment by jameysharp** [comment]
I believe this should work as an alternative:
```rust
let current_block = builder.current_block();
let is_pristine = builder.func.layout.first_inst(current_block).is_none();
```

Does that work for you?

**Comment by ptitSeb** [comment]
Probably, I'll check that. Thanks.

**Comment by ptitSeb** [comment]
Well, even with the workaround, I still think this function could be public, it seems more logical to use than the workaround.
