### ISSUE TITLE
Enable `all-arch` by default.

### ISSUE THREAD

**Issue by martindevans** [bytecodealliance/wasmtime#5655]
#### Feature

Enable the `all-arch` feature for `wasmtime` executable.

#### Benefit

I'm using the `compile` command to automatically precompile wasm assets for a range of platforms. At the moment this requires me to recompile wasmtime.exe every time there's a new release just to add this feature. Adding this to the executable doesn't seem to have any major drawbacks.

**Comment by cfallin** [comment]
The main reasons to include only the host architecture's compiler backend by default are (wasmtime) build time and binary size.

It might be useful to have some data here to determine whether this is a good idea:
- Could you measure the size of the binary (on any platform) with just the default features, and `all-arch` enabled?
- Could you measure the build-time difference, from a clean state, of wasmtime with/without, and also the `cranelift-codegen` crate alone?

**Comment by alexcrichton** [comment]
To clarify, though, do you mean by default as in "modify `Cargo.toml`" or do you mean only for the release assets produced [here for example](https://github.com/bytecodealliance/wasmtime/releases/tag/v5.0.0)? I'd agree with Chris for the former but for the latter we could pretty easily make that change to the CI production of the binaries.

**Comment by martindevans** [comment]
I don't know Rust particularly well so I'm not too sure about modifying `cargo.toml`, but I don't think that's what I mean. I'm definitely talking only about enabling it for the release assets you linked.

**Comment by cfallin** [comment]
Seems like a reasonable change; I just created #5657 for this.

**Comment by martindevans** [comment]
Wow, thanks for the fast turnaround!
