### ISSUE TITLE
`Linker::instantiate_pre` could avoid mutating a `Store`

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#5675]
In #5484, it would have been ideal to check if an instance was "instantiatable" by a `Linker` much sooner than when we currently check it (at startup instead of when a thread is spawned). Because a `Store` is not available until the thread is spawned and `Linker::instantiate_pre` requires a mutable `Store`, we cannot do this check sooner. If `Linker::instantiate_pre` were refactored to be called without a `Store` or if some other method were available to "check that all the imports can be satisfied," then the check in wasi-threads could be moved up and this issue closed.

**Comment by jameysharp** [comment]
I was just looking at a wasmtime embedder that constructs an otherwise-unused `Store` solely for use with `instantiate_pre`. I agree that it'd be nice to not have to do that!

**Comment by pchickey** [comment]
This isn't a very helpful answer, but I wanted this as well when we introduced instantiate_pre, and there was some complexity of the implementation that made it extremely difficult, so I gave up.

**Comment by alexcrichton** [comment]
I was struck with inspiration when thinking about this again and created https://github.com/bytecodealliance/wasmtime/pull/5683
