### ISSUE TITLE
`wasi-nn` test broken on `main`

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#5680]
In [this CI run](https://github.com/bytecodealliance/wasmtime/actions/runs/4059348118/jobs/6987292821) on `main`, the `wasi-nn` test job appears to fail with a Wasm trap in `wasm-nn-example.wasm`. The same test [passed](https://github.com/bytecodealliance/wasmtime/actions/runs/4058962235/jobs/6986493872) on the PR that just merged and triggered the CI run on main.

It appears that the `wasi-nn` test is influenced by model data or other bits downloaded from the Internet; as such, I suspect there is an issue due to changing inputs.

@abrown / @jlb6740, would you be able to look into this? Since wasi-nn support is tier 3, we'll need to disable the test tomorrow if not fixed urgently, since it blocks any other PR from merging.

**Comment by elliottt** [comment]
Let's go ahead and disable the test for now so that we can unblock any other in-flight work. I'll make a PR.

**Comment by abrown** [comment]
From a first glance, it doesn't look like this is wasi-nn related... at least the bits that would do any inference with a model. The backtrace points to wasi-libc as the issue, right? I think that might bear some looking into. Maybe this test is the only one exercising some aspect of wasi-libc?

**Comment by cfallin** [comment]
Possibly, but passing and then failing later on the same tree indicates to me at least that it's not a simple broken-codegen sort of issue... I'll poke at this locally a little bit.

**Comment by cfallin** [comment]
Hmm,  nevermind, I don't have a functioning OpenVINO setup.

I think the most reasonable call is: given flake + tier 3, let's disable then debug off the critical path so `main` isn't blocked.

**Comment by abrown** [comment]
I think this is a bit more worrying than that. This [install.sh](https://github.com/abrown/install-openvino-action/blob/main/install.sh) script is how one could get an OpenVINO installation.

**Comment by cfallin** [comment]
OK, @elliottt noticed that the failure started on `main` after #5676, and actually failed on the PR itself too. #5605 had clean CI because it didn't include #5676 while running. #5676 merged despite one failing test because it had auto-merge enabled, and the wasi-nn test was erroneously not included in our list of required tests for `main`'s branch protection.

**Comment by abrown** [comment]
So there must be something in wasi-libc's `memset` that doesn't play nicely with that optimization? That optimization seemed reasonable to me...

**Comment by abrown** [comment]
(thought: we should have more tests exercising wasi-libc if the wasi-nn test is the only one that found this... still puzzled at what is going on)

**Comment by cfallin** [comment]
I suspect if it's a really subtle codegen thing then fuzzing would have caught it *eventually* too... though I agree, and I hope a few good tests of a reduced kernel of the bug come out of this!
