### ISSUE TITLE
Cranelift panics on a shift right overflow

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#5696]
Given this input wasm:

```wasm
(module
  (type (;0;) (func (param i64)))
  (func (;0;) (type 0) (param i64)
    i64.const 32
    i64.const -19
    i64.shr_u
    call 0
  )
)
```

wasmtime panics with:

```
$ cargo run -q compile foo.wasm
thread '<unnamed>' panicked at 'attempt to shift right with overflow', cranelift/codegen/src/opts.rs:89:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

cc @fitzgen this is connected to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55588 which you mentioned would be fixed by https://github.com/bytecodealliance/wasmtime/pull/5684 but I think it's still persistent on `main`

**Comment by jameysharp** [comment]
This will be fixed once we finish #5695. It wasn't related to #5684.
