### ISSUE TITLE
Cranelift: `uextend.i128` is optimized into `iconst.i128` via egraphs

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5711]
👋 Hey,

Fuzzgen pointed this out today.

### `.clif` Test Case

```
test compile
set opt_level=speed
target x86_64

function u1:0() system_v {
block0:
    v0 = iconst.i64 0
    v1 = uextend.i128 v0  ; v0 = 0
    v2 = icmp_imm eq v1, 0xd700_0008_08be_ff00
    brif v2, block1, block1

block1:
    return
}
```

### Steps to Reproduce

* `clif-util test ./the-above.clf`

### Expected Results

The test to pass

### Actual Results

```
thread 'worker #0' panicked at 'unimplemented for > 64 bits', cranelift/codegen/src/opts.rs:89:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #0: unimplemented for > 64 bits
FAIL ./lmao.clif: panicked in worker #0: unimplemented for > 64 bits
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: `main`
Operating system: Linux
Architecture: x86_64

### Extra Info

This was introduced in 97381792ac301271f691d6c69f16ad1130df1286 (cc @jameysharp), it looks like we are extending the `uextend` into a `iconst.i128` which does not exist.

**Comment by cfallin** [comment]
This is also [this oss-fuzz issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55698), when it becomes public, which is very similar except for riscv64.

**Comment by cfallin** [comment]
Also [this oss-fuzz issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55703).

Just to write it here so we don't forget: once we resolve this, we'll want to backport it to the 6.0 branch, which forked recently (and get it in before the release on Feb 20!).

**Comment by cfallin** [comment]
Finally [this oss-fuzz issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55697) also appears to be this bug.

**Comment by bjorn3** [comment]
Hit this while checking for regressions in the Cranelift 0.93 branch: https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/4105124329/jobs/7081547989
