### ISSUE TITLE
Support iOS target build

### ISSUE THREAD

**Issue by cbrzn** [bytecodealliance/wasmtime#5754]
#### Feature
I would like to be able to compile a library that uses Wasmtime to iOS devices (currently you only support MacOS, and works as expected).

#### Benefit
The benefit would be that we would be able to use wasmtime in iOS devices. For context, we have developed a library (https://github.com/polywrap/rust-client/) that uses wasmtime as the WASM runtime. We're on the process of research where we wrap our library into FFI with the objective of using these in mobile apps (with android works as expected) but when trying to run it on iOS device, with the command `cargo build --target aarch64-apple-ios --release` it fails (here's [the error logs](https://gist.github.com/cbrzn/75dfeb2c01bfb1e2724ce31bc8065ed7) for more context)

#### Implementation

N/A

#### Alternatives

N/A

**Comment by bjorn3** [comment]
iOS doesn't allow JIT engines, right?

**Comment by cbrzn** [comment]
@bjorn3 ugh, you're totally right ser. this means that wasmtime is not compatible with iOS. sorry for opening this without the appropriate knowledge hehe.

going to close this, thanks for your comment :-)

**Comment by bjorn3** [comment]
No worries. It is an annoying restriction even though I mostly understand why. Maybe the EU will force then to allow it in the future :)

**Comment by bjorn3** [comment]
By the way if the set of wasm modules you need to run is fixed, it may be possible to precompile all wasm modules when building the app and then run them without JIT. That does require the error you mentioned to be fixed first.

**Comment by cbrzn** [comment]
> By the way if the set of wasm modules you need to run is fixed

yes, that is possible in our use case, but my question would be:

based on this,
> That does require the error you mentioned to be fixed first.

do you think that's doable with little effort?

**Comment by bjorn3** [comment]
I don't think it would be too much effort to fix for someone with (some) experience with assembly.
