### ISSUE TITLE
Is the relationship between store and instance one-to-one or one-to-many

### ISSUE THREAD

**Issue by Duslia** [bytecodealliance/wasmtime#5774]
I have read the docs. It seems that a store can create multi instances.
<img width="995" alt="image" src="https://user-images.githubusercontent.com/37136584/218698949-9607bab1-a676-4fc1-86a6-8eee0ad0098f.png">
But the interface is defined as follows:
```
pub fn get_typed_func<Params, Results, S>(
        &self,
        mut store: S,
        name: &str,
    ) -> Result<TypedFunc<Params, Results>>
```
Store cannot be owned by multi instances simultaneously。 So I want to ask if the documentation says that I can build multiple instances with one store, but only one instance can have it at the same time. Does the second instance need to wait until the first instance is executed and released before building the second instance?

**Comment by alexcrichton** [comment]
Note that the `S` bound on that function is an `AsContextMut` which means you can pass in `&mut store`, the API doesn't actually take ownership of the store.

You can instantiate many instances within a store, e.g.:

```rust
let i1 = linker.instantiate(&mut store, &module1)?;
let i2 = linker.instantiate(&mut store, &module2)?;
```

where here both `i1` and `i2` live in the same `Store`.

Does that answer your question?

**Comment by Duslia** [comment]
emm. But it seems that I cannot execute them asynchronously.
```
ins.get_typed_func::<(), (), _>(&mut store, &self.method)?
            .call_async(&mut store, ())
            .await?;
```

**Comment by alexcrichton** [comment]
That's correct, only one asynchronous computation within a store may happen at any one point in time.

**Comment by Duslia** [comment]
Ok, I got it. Thanks!
