### ISSUE TITLE
Set `wasmtime::component::values` to be public

### ISSUE THREAD

**Issue by Officeyutong** [bytecodealliance/wasmtime#5788]
I'm trying to call an exported function with signature `func (seq: list<s64>) -> s64`, but I find that I can't construct `wasmtime::component::Val::List(wasmtime::component::values::List())` since `wasmtime::component::values::List` is not public. 

#### Feature

Add `pub` to [https://github.com/bytecodealliance/wasmtime/blob/e10094dcd6d0354628255a6f2e69c1e4c327d6e7/crates/wasmtime/src/component/mod.rs#L16](https://github.com/bytecodealliance/wasmtime/blob/e10094dcd6d0354628255a6f2e69c1e4c327d6e7/crates/wasmtime/src/component/mod.rs#L16)

#### Benefit

If accepted, We can invoke functions which contains a param with type list

#### Implementation

Just add a `pub` prefix

#### Alternatives

May be no alternatives available?

**Comment by pchickey** [comment]
At the moment, you can construct a list `Val` by way of `wasmtime::component::types::List::new_val` https://docs.rs/wasmtime/latest/wasmtime/component/types/struct.List.html#method.new_val - does that meet your needs?

I think it would be ok to make the `values` mod public, just on the grounds that if the `Val` enum is public, the types in all of its variants should be as well (https://docs.rs/wasmtime/latest/wasmtime/component/enum.Val.html), but I don't know if there is something about the design of using the `types` module to construct `Val` vs the direct use of the enum that I am missing. @alexcrichton what do you think?

**Comment by alexcrichton** [comment]
The original intention was to reexport everything necessary form the `values` module into the top-level `component` module, so this may be a forgotten reexport?

**Comment by pchickey** [comment]
Ok! I'll add the forgotten reexports :)
