### ISSUE TITLE
cranelift-interpreter: Implement the `AtomicRMW` instruction

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5817]
👋 Hey,

Our interpreter implementation is missing the [`AtomicRMW`](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/trait.InstBuilder.html#method.atomic_rmw) instruction [here](https://github.com/bytecodealliance/wasmtime/blob/db9efcb099e07dbb3b433668a5404deefc0eb709/cranelift/interpreter/src/step.rs#L1190).

AtomicRMW usually performs some [operation](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/enum.AtomicRmwOp.html) atomically, but we've decided that our interpreter is thread unsafe and should be able to do this non atomically.

This means that the implementation of this instruction is fairly straight forward.

1. We do a [load to an address](https://github.com/bytecodealliance/wasmtime/blob/db9efcb099e07dbb3b433668a5404deefc0eb709/cranelift/interpreter/src/step.rs#L1197)
2. Perform the operation using the [pre existing methods on `DataValue`](https://github.com/bytecodealliance/wasmtime/blob/db9efcb099e07dbb3b433668a5404deefc0eb709/cranelift/interpreter/src/value.rs#L688-L702)
3. We [store the new value to the same address](https://github.com/bytecodealliance/wasmtime/blob/db9efcb099e07dbb3b433668a5404deefc0eb709/cranelift/interpreter/src/step.rs#L1205)

We already have a [pre-existing testsuite](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/filetests/filetests/runtests/atomic-rmw-little.clif) for this functionality so, it should just be enabling those tests for the interpreter by adding a `test interpret` to the top of the file.

If someone wants to give this a go and has any questions let me know!

**Comment by jan-justin** [comment]
Hey @afonso360 👋  ,

I am a first-time contributor and keen to take a look at it.

I have a question regarding the tests, specifically [these tests](https://github.com/bytecodealliance/wasmtime/blob/c65de1f1b1a59155abbb9cbbe5aaa5abacd8e794/cranelift/filetests/filetests/runtests/atomic-rmw-little.clif#L119-L123). Are they meant to be `%atomic_rmw_and_i64` or `%atomic_rmw_and_i32`? The tests panic with the former, but pass with the latter.

**Comment by jameysharp** [comment]
I think you are correct: Those tests look like they're meant to run the function declared immediately beforehand, which is `%atomic_rmw_and_i32`.

I'm surprised that these runtests didn't fail before. I think I remember something about our test-runner ignoring function names and just calling the last-defined function sometimes, which would explain this. I suspect @afonso360 knows the answer to this puzzle.

**Comment by afonso360** [comment]
> I have a question regarding the tests, specifically [these tests](https://github.com/bytecodealliance/wasmtime/blob/c65de1f1b1a59155abbb9cbbe5aaa5abacd8e794/cranelift/filetests/filetests/runtests/atomic-rmw-little.clif#L119-L123). Are they meant to be %atomic_rmw_and_i64 or %atomic_rmw_and_i32? The tests panic with the former, but pass with the latter.

Wow, those should definitely call `atomic_rmw_and_i32`, Good catch!

> I'm surprised that these runtests didn't fail before.

I suspect we just zero extend all of these values up to `i64` and since it's an `and` operation everything aligns and works correctly? I'm not sure

> I think I remember something about our test-runner ignoring function names and just calling the last-defined function sometimes, which would explain this.

I think that used to be how our test runner worked, but IIRC (this was a while ago) this was changed in #4667 and we now require the function names to exist in the testcase.

**Comment by jan-justin** [comment]
Thank you both for the clarification!

Given the other tests I suspected as much, however, I did not want to make any assumptions.
