### ISSUE TITLE
Bump version of `wit-parser` in `wasmtime-component-macro`

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/wasmtime#5833]
Currently the `wasmtime-component-macro` crate pulls in `^3.0` of the `wit-parser` crate and is missing what appear to be significant improvements since `0.3.1`.

For example, the version it pulls in doesn't understand the `default` keyword and gives the following confusing error which has since been fixed.
```
expected `default`, `world` or `interface`, found keyword `default`
      |
    7 | default world template {
      | ^------
```
[source](https://docs.rs/wit-parser/0.3.1/src/wit_parser/ast.rs.html#50)

**Comment by alexcrichton** [comment]
I think you were using Wasmtime 5.0.0 from crates.io perhaps? If that's the case then the Wasmtime 6.0.0 version should suffice as that, and `main`, depend on tha latest `wit-parser`. I'm going to go ahead and close this as I think that addresses the issues here, but let me know if there's still problems.
