### ISSUE TITLE
documentation refers to nonexistent function

### ISSUE THREAD

**Issue by wtholliday** [bytecodealliance/wasmtime#5838]
From:

https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/entities/struct.StackSlot.html

"StackSlots can be created with [FunctionBuilder::create_stackslot](https://docs.rs/cranelift-frontend/*/cranelift_frontend/struct.FunctionBuilder.html#method.create_stack_slot)."

There isn't such a function AFAICT. Perhaps it should be `create_sized_stack_slot`? I'm new to cranelift.

**Comment by bjorn3** [comment]
Indeed. create_stackslot was renamed to create_sized_stack_slot a while ago. Seems this reference was missed. Would you mind opening  a PR to update it?
