### ISSUE TITLE
Compile error on Android Emulator

### ISSUE THREAD

**Issue by n-prat** [bytecodealliance/wasmtime#5852]
Hello,

My goal is to run a Substrate client[Integritee to be precise] on Android(and soon iOs).
The issue is that `integritee-cli` pulls **a lot** of dependencies, including this crate.
Unfortunately, it does not compile on Android Emulator.

See [this](https://github.com/integritee-network/worker/issues/1167) for a bit more context.

I know these targets are not supposed to be supported, but as I created a fork (and used a cargo `[patch]`), I thought I might as well share it.

#### Benefit

Allow this crate to compile on Android *Emulator*(and Android aarch64).
While I'm at it, I can probably add iOs *Simulator* and aarch64 too?

#### Implementation

I have started a branch (based on `v5` b/c of transitive deps) here: https://github.com/Interstellar-Network/wasmtime/tree/v5-fix-android-emulator-build-for-substrate-client [still WIP, CI pass for Android but breaks for other targets... I need to improve the `#[cfg]`)

Note: this project is way beyond my Rust skills so:
- I have simply added what I needed to make it compile; but **no idea** if it would run
- -> the CI is only running `cargo build`
Note: the CI job is in main.yml as a starting point; but maybe build.yml would be better?
I did try it there but could not understand how to make qemu work?

**Comment by afonso360** [comment]
We currently have a CI job that checks the aarch64-android build using `cargo-ndk`. Are you encountering issues that it did not catch?

https://github.com/bytecodealliance/wasmtime/blob/6e6a1034d73b10775f41b7bcd5675815021d3510/.github/workflows/main.yml#L282-L292

**Comment by nathanprat** [comment]
Ah, I did not see it b/c I am using `v5.0.0` b/c of [Substrate](https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/Cargo.toml#L22).

But the issue should still be there on master: I want to compile for Android Emulator(ie target `x86_64-linux-android`).
The problem being that it is `target_arch = "x86_64"` + `target_os = "linux"` but does not support VTune etc so some `#[cfg]` logics fall off.

**Comment by jameysharp** [comment]
When you get to working on iOS, note that, as I understand it, iOS App Store policy prohibits JIT compilers. In theory Wasmtime could work on iOS as long as you have your WebAssembly input available already when compiling your app and precompile it to native code at that point. But as far as I know nobody has yet tried that on iOS.

**Comment by nathanprat** [comment]
Thanks for the heads-up!

I am 50% sure that this crate is not used in practice with my use case and could be behind a `feature`. I definitely need to investigate how the dependency tree works

**Comment by alexcrichton** [comment]
I believe that this has since been fixed, so I'm going to close this.
