### ISSUE TITLE
wasi-common no longer has the wasm_tests feature, which contradicts README.md

### ISSUE THREAD

**Issue by marmistrz** [bytecodealliance/wasmtime#586]
The feature `wasm_tests` has been removed by https://github.com/bytecodealliance/wasmtime/commit/d4fd229e5ee67b2da4352ff56be166bddd85200e, but [`README.md`](https://github.com/bytecodealliance/wasmtime/blob/9896a5cabd7b948d509b6d8aea868d32e6802b89/crates/wasi-common/README.md#development-hints) still says that one should use the `wasm_tests` feature:

> Now, you should be able to run the integration testsuite by enabling the wasm_tests feature
> ``` 
> cargo test --features wasm_tests 
> ```

README.md for wasi-common should definitely describe how to run the misc testsuite.

cc @sunfishcode

**Comment by sunfishcode** [comment]
Thanks for the report! I've now submitted #587 to fix that.
