### ISSUE TITLE
Cranelift: Interpreter panic when bitcasting SIMD values

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5915]
👋 Hey,

### `.clif` Test Case

```
test interpret

function %a(i16x8) -> i64x2 {
block0(v3: i16x8):
    v23 = bitcast.i64x2 little v3
    return v23
}

; run: %a(0x00000000000000000000000000000000) == 0x00000000000000000000000000000000
```

### Steps to Reproduce

* `cd cranelift`
* `cargo run -- test ./the-above.clif`

### Expected Results

The test to pass.

### Actual Results

```
     Running `/home/afonso/git/wasmtime/target/debug/clif-util test ./lmao.clif`
thread 'worker #0' panicked at 'index out of bounds: the len is 16 but the index is 16', cranelift/interpreter/src/step.rs:1565:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #0: index out of bounds: the len is 16 but the index is 16
FAIL ./lmao.clif: panicked in worker #0: index out of bounds: the len is 16 but the index is 16
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: Interpreter (x86_64 host)

### Extra Info

If anyone needs help working on this let me know!

**Comment by jameysharp** [comment]
Here's the line where the array index is out of bounds. (The line number is different on current `main` than in the above stack trace.)
https://github.com/bytecodealliance/wasmtime/blob/3ff3994a1/cranelift/interpreter/src/step.rs#L1578

I don't much like the structure of the loop here, but despite that it looks to me like it ought to work. Interesting!
