### ISSUE TITLE
Cranelift: Interpreter returns the wrong result for `vall_true.i8x16`

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5916]
👋 Hey,

### `.clif` Test Case

```
test interpret

function %a(i8x16) -> i8 {
block0(v0: i8x16):
    v20 = vall_true v0
    return v20
}

; run: %a(0xe66021830506f2fffdfebfc8c8c8c8c8) == 1
```

### Steps to Reproduce

* `cd cranelift`
* `cargo run -- test ./the-above.clif`

### Expected Results

The test to pass

### Actual Results

```
     Running `/home/afonso/git/wasmtime/target/debug/clif-util test ./lmao.clif`
 ERROR cranelift_filetests::concurrent > FAIL: interpret
FAIL ./lmao.clif: interpret

Caused by:
    Failed test: run: %a(0xe66021830506f2fffdfebfc8c8c8c8c8) == 1, actual: 0
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: Interpreter (x86_64 host)

### Extra Info

If anyone needs help looking into this, let me know!

**Comment by ms140569** [comment]
I like to take a look into it. Should I claim this somewhere/somehow?

**Comment by afonso360** [comment]
Awesome! I think that comment is probably enough. Let me know if you run into any issues!
