### ISSUE TITLE
Cranelift: `sqmul_round_sat.{i16,i32}` does not exist for scalars

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5923]
👋 Hey,

This is probably a docs issue.

The [docs for this instruction](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/trait.InstBuilder.html#method.sqmul_round_sat) state that it is "Polymorphic over all integer types (scalar and vector) with 16- or 32-bit numbers.".

But it isn't, and trying to compile it with either `i32` / `i16` causes a verifier error.

Do we want to enable this instruction for scalars? Or should we update the docs so that they are SIMD only?

### `.clif` Test Case

```
test run
target x86_64
target aarch64
target s390x

function %a() -> i32 system_v {
block0:
    v0 = iconst.i32 0
    v1 = sqmul_round_sat v0, v0
    return v1
}

; run: %a() == 0
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

The test to pass.

### Actual Results

```
 ERROR cranelift_filetests::concurrent > FAIL: failed to parse ./lmao.clif
FAIL ./lmao.clif: failed to parse ./lmao.clif

Caused by:
    11: i32 is not a valid typevar for sqmul_round_sat
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: x86_64

**Comment by abrown** [comment]
I think the conservative thing to do is to restrict this to SIMD types since this is a lowering for `i16x8.q15mulr_sat_s` (originally added in https://github.com/bytecodealliance/wasmtime/pull/3035).
