### ISSUE TITLE
[wasmtime-wasi] Support WebAssembly component-model

### ISSUE THREAD

**Issue by eliabieri** [bytecodealliance/wasmtime#5933]
#### Feature

`wasmtime-wasi` currently does not support the being worked on WebAssembly component-model in the `wasmtime` crate.
`wasmtime_wasi::add_to_linker` only accepts the `wasmtime::Linker` and not the `wasmtime::component::linker::Linker`.

#### Benefit

It would be really cool to use the new component model together with WASI

#### Implementation

I do not have the knowledge required to judge whether adding support to `wasmtime-wasi` would be difficult.

**Comment by bjorn3** [comment]
Wasi preview2 will use the wasm component model.

**Comment by eliabieri** [comment]
Any idea on when preview2 will land in `wasmtime` and `wasmtime-wasi`?
I'm currently investigating using the component model + WASI for a new project, but I might be a bit too early here.

**Comment by eliabieri** [comment]
I've found discussions about this topic here:

- https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/.E2.9C.94.20Guest.20missing.20imports
- https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/WASI.2C.20wit-component.2C.20and.20wasmtime

**Comment by adwhit** [comment]
Pretty confused by the current state of `wasi` and `wasm-components`. Does anyone know the current state-of-the-art? Are they compatible now?

**Comment by alexcrichton** [comment]
Ah this is a pretty old issue and actually now fixed now. The `wasmtime-wasi` should have suitable documentation on the `main` and `release-20.0.0` branches. Note that the docs.rs 19.0.0 version wasn't fully documented at the time of the release.
