### ISSUE TITLE
Cranelift: Wrong result for `fcvt_from_sint.f32` on RISCV

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5952]
👋 Hey,

I re-ran the fuzzer today with the issues that were fixed in the past weeks, and it reported some new cases.

### `.clif` Test Case

```
test interpret
test run
target riscv64gc

function %a(i16 uext) -> f32 {
block0(v0: i16):
    v1 = fcvt_from_sint.f32 v0
    return v1
}

; run: %a(-12800) == -0x1.900000p13
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

The test to pass!

### Actual Results

```
 ERROR cranelift_filetests::concurrent > FAIL: run
FAIL ./lmao.clif: run

Caused by:
    Failed test: run: %a(-12800) == -0x1.900000p13, actual: 0x1.9c0000p15
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: main (e2dcb19099606f161c6d6145ba71130579b452e2)

Operating system: Linux

Architecture: RISCV64GC

### Extra Info

CC: @yuyang-ok

**Comment by yuyang-ok** [comment]
@afonso360 👍

**Comment by yuyang-ok** [comment]
@afonso360   Looking at the `ISLE` lowering rules.I think we should extend value first.

**Comment by yuyang-ok** [comment]
@afonso360 Maybe a review. [#5964 ](https://github.com/bytecodealliance/wasmtime/pull/5964)
