### ISSUE TITLE
`Clone` for `wasmtime::component::PreInstance` ?

### ISSUE THREAD

**Issue by Fristi** [bytecodealliance/wasmtime#5965]
Would `Clone` be possible for `wasmtime::component::PreInstance` as well? There is a `Clone` for `wasmtime::PreInstance`.

Use case: I would like use `tokio::spawn` or other concurrent consumers of my WASM module to work, it seems you need `Clone` for that right ? (quite new to Rust)

**Comment by alexcrichton** [comment]
Yep! I've added it in https://github.com/bytecodealliance/wasmtime/pull/5966

**Comment by alexcrichton** [comment]
Ah the 6.0.1 release was not for this issue, and this will get released with 8.0.0 that gets published on April 20
