### ISSUE TITLE
Cranelift: AArch64 `attempt to add with overflow` panic on `shuffle.i8x16` 

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#5989]
👋 Hey,

### `.clif` Test Case

```
test compile
target aarch64

function %a() -> i8x16 system_v {
    const0 = 0x00000000000000000000000000000000

block0:
    v8 = vconst.i8x16 const0
    v17 = shuffle v8, v8, 0x00f2009e32ddd6465503ffffffffffff  ; v8 = const0, v8 = const0
    return v17
}
```

### Steps to Reproduce

* `clif-util test ./the-above.clif`

### Expected Results

The test to pass.

### Actual Results

```
     Running `/home/afonso/git/qemu/qemu-7.2.0/build/qemu-aarch64 -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib /home/afonso/git/wasmtime/target/aarch64-unknown-linux-gnu/debug/clif-util test ./lmao.clif`
thread 'worker #0' panicked at 'attempt to add with overflow', cranelift/codegen/src/isa/aarch64/lower/isle.rs:749:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ERROR cranelift_filetests::concurrent > FAIL: panicked in worker #0: attempt to add with overflow
FAIL ./lmao.clif: panicked in worker #0: attempt to add with overflow
1 tests
Error: 1 failure
```

### Versions and Environment

Cranelift version or commit: `main`

Operating system: Linux

Architecture: AArch64

### Extra Info

The panic happens [here](https://github.com/bytecodealliance/wasmtime/blob/af7ef8df9adb48204c4caedc7bd4f9ba8f3f7113/cranelift/codegen/src/isa/aarch64/lower/isle.rs#L749) and seems to have been introduced in #5977. (cc @alexcrichton)

**Comment by alexcrichton** [comment]
Thanks! I'll propose https://github.com/bytecodealliance/wasmtime/pull/5995 to solve this which doesn't involve changing the backend but instead the semantics of the instruction, but if that's not desired I can additionally got add a `.wrapping_add` in there.

**Comment by afonso360** [comment]
I don't mind either way, It should be fairly easy to update the fuzzer to follow the instruction semantics!
