### ISSUE TITLE
Allow to easily disable clocks in WasiCtx

### ISSUE THREAD

**Issue by RReverser** [bytecodealliance/wasmtime#6004]
#### Feature

Allow to easily disable clocks when constructing a `WasiCtx`.

#### Benefit

This is useful for execution in deterministic environments where modules aren't allowed access to any non-deterministic sources, such as random data generation or system time.

Disabling random data generation (or, rather, substituting with pre-seeded source) is already easy in wasmtime, but it seems that the only ways to disable clocks is to either return a `0` time from clocks, which is not ideal compared to an explicit capability error, or to reimplement the entire `WasiSnapshotPreview1` myself by forwarding everything except clock functions to the inner implementation, which is also pretty cumbersome.

#### Implementation

I'd probably wrap `system` and `monotonic` fields in [`WasiClocks`](https://docs.rs/wasi-common/6.0.1/wasi_common/clocks/struct.WasiClocks.html) into `Option<...>`.

**Comment by pchickey** [comment]
The requirements and implementation step sound good to me. I don't think any of our team has spare bandwidth to work on this right now but we'd be be happy to accept a PR.

**Comment by RReverser** [comment]
Thanks for the quick feedback. Sounds good, working on it.
