### ISSUE TITLE
error <wasi/core.h> is only supported on WASI platforms.

### ISSUE THREAD

**Issue by zababurinsv** [bytecodealliance/wasmtime#603]
Hi
I download wasi-sdk-8.0
create demo.c from example

create dir 
/wasi-sdk-8.0/
/demo.c
specied the sysroot directory like so

clang demo.c --sysroot /home/sergey/Desktop/wasmtime-demos/c/wasi-sdk-8.0/share/wasi-sysroot  -o demo.wasm

And getting this error

(base) sergey@node:~/Desktop/wasmtime-demos/c$ clang demo.c --sysroot /home/sergey/Desktop/wasmtime-demos/c/wasi-sdk-8.0/share/wasi-sysroot  -o demo.wasm
In file included from demo.c:1:
In file included from /home/sergey/Desktop/wasmtime-demos/c/wasi-sdk-8.0/share/wasi-sysroot/include/stdio.h:52:
In file included from /home/sergey/Desktop/wasmtime-demos/c/wasi-sdk-8.0/share/wasi-sysroot/include/__seek.h:4:
/home/sergey/Desktop/wasmtime-demos/c/wasi-sdk-8.0/share/wasi-sysroot/include/wasi/core.h:15:2: error: <wasi/core.h> is only supported on WASI platforms.
#error <wasi/core.h> is only supported on WASI platforms.
 ^
1 error generated.

Please tell me,
What's wrong ?

**Comment by rutvora** [comment]
Hey, I'm facing a similar issue. Please comment the solution if you remember. Would be helpful.
Thanks

**Comment by bjorn3** [comment]
You must use the clang that is part of wasi-sdk, not your system clang.

**Comment by rutvora** [comment]
I am using the wasi-sdk one
Here's my call 
`CC check-credentials/src/MD5.cpp -o MD5.wasm -nostartfiles -Wl,--no-entry,--export=GetMD5String -fno-exceptions --target=wasm32 -I ./wasi-sdk-11.0/share/wasi-sysroot/include/` where CC is `[WASI_SDK_PATH]/bin/clang --sysroot=[WASI_SDK_PATH]/share/wasi-sysroot/`

**Comment by bjorn3** [comment]
Does it work without the `--target` argument?

**Comment by rutvora** [comment]
No, it gave a bunch of errors and a lot more warnings. All associated with wasi/api.h with the first error still being the same, that it is only available on WASI platforms.

**Comment by rutvora** [comment]
it crashes on #ifndef __wasi__
Am I supposed to add an additional header somewhere in my code?

**Comment by sunfishcode** [comment]
`__wasi__` is predefined by clang when the target is wasm32-wasi. If `--target=wasm32-wasi` says no targets found compatible, is it possible you're accidentally using some other clang, rather than the clang from the wasi-sdk package?

**Comment by rutvora** [comment]
@sunfishcode I'm sure I'm calling the clang from WASI SDK. For reference, I have mentioned the command I used in a comment above. And I'm sure the env variable there points to the correct WASI_SDK directory.
I'm on MacOS Catalina, if that has some special conditions which I might have missed out on.

**Comment by rutvora** [comment]
@sunfishcode I rechecked, turns out I wasn't. I was calling "[WASI_SDK_PATH]/bin/clang" (as a literal) and it defaulted to xCode Clang somehow :/

Thanks for the help though @bjorn3 and @sunfishcode
