### ISSUE TITLE
How to embed in C++? How to store secret state?

### ISSUE THREAD

**Issue by codefishd** [bytecodealliance/wasmtime#610]
Greetings

I want to use wasmtime or another runtime in a C++ app to secure calls to complicated functions.
Is there an example for that?

In particular ----> how can a webassembly function call functions from the main app with secret state only stored in the app (-- not visible from webassembly for security --)? How to implement wrappers like https://github.com/wasmerio/wasmer/pull/925 with wasmtime? Is it possible?

**Comment by yurydelendik** [comment]
@codefishd The wasmtime implements [wasm-c-api](https://github.com/WebAssembly/wasm-c-api/) , see e.g. https://github.com/WebAssembly/wasm-c-api/blob/master/example/callback.c . AFAIK the wasm-c-api is (being) implemented for V8, wasmtime, wabt interpreter.

> to secure calls to complicated functions

Can you explain what do you mean under "complicated functions"?

>  how can a webassembly function call functions from the main app with secret state only stored in the app 

Is it similar to host into attached to the embedded object?

**Comment by jedisct1** [comment]
If I understand correctly, and if you don't specifically need to run code compiled to WebAssembly, the [Google Sandboxed API](https://github.com/google/sandboxed-api) may do what you are looking for.

**Comment by tschneidereit** [comment]
I think @yurydelendik's answer about callbacks should address this, so I'll close this issue. @codefishd, feel free to reopen if you disagree and can further clarify your use case and why it's not addressed by closure callbacks.
