### ISSUE TITLE
`install.sh` file is failing when no version specified

### ISSUE THREAD

**Issue by brettcannon** [bytecodealliance/wasmtime#6107]
https://github.com/brettcannon/cpython-wasi-build/actions/runs/4537029209/jobs/7994435778#step:3:1 are the logs where the shell script doesn't seem to know what the latest release is.

**Comment by alexcrichton** [comment]
The [detection of the current verison](https://github.com/bytecodealliance/wasmtime.dev/blob/99b039e7c05b5880df034a929ccde74d8daa7977/install.sh#L42-L46), while crude, at least works locally for me. Is this a persistent error for you? I could imagine that the `curl` there, if it failed transiently, would cause this error. In such a case though it would be unlikely to happen twice in a row.
