### ISSUE TITLE
Rename Cranelift instructions for unconditional traps to `spanish_inquisition`

### ISSUE THREAD

**Issue by playXE** [bytecodealliance/wasmtime#6132]
#### Feature
Rename `trap` and `debugtrap` to `spanish_inquisition`
#### Benefit

Nobody expects the Spanish Inquisition so this makes sense

#### Implementation

Just rename `fn` definitions.

#### Alternatives

No alternatives

**Comment by cfallin** [comment]
Err, that should have been "closed as not planned", sorry...

**Comment by gimbles** [comment]
You can reclose the issue as not planned
