### ISSUE TITLE
CI should deny warnings for wasi-tests

### ISSUE THREAD

**Issue by marmistrz** [bytecodealliance/wasmtime#614]
Currently both `dangling_fd.rs` and `path_link.rs` have warnings about dead code.
cc @kubkon

**Comment by kubkon** [comment]
I'm not sure we can do that on a per crate basis in the CI. @alexcrichton would you be OK with denying warnings by the CI, or do you feel it's somewhat of an overkill?

FWIW, in `wasi-common` repo, we've had the initial build stage in the CI configured with

```
RUSTFLAGS: "-D warnings"
```

**Comment by alexcrichton** [comment]
Yeah I think doing this via `RUSTFLAGS` on CI is the way to go, and seems reasonable to me at least!

**Comment by kubkon** [comment]
Since #616 landed, I'm going to close this.
