### ISSUE TITLE
Inline Assembly Error in helpers.c

### ISSUE THREAD

**Issue by mainini** [bytecodealliance/wasmtime#6177]
Hi!

When building a Rust project which uses wasmtime::Engine to run WASM binaries, linking fails. Project is built as usual with cargo. The following error occurs in [runtime/src/helpers.c:78](https://github.com/bytecodealliance/wasmtime/blob/main/crates/runtime/src/helpers.c#L78): _undefined reference to `asm'_

To me, it looks like this should be an empty inline assembly statement, and effectively, replacing it with `__asm("");` solves the issue. 

I am unaware of the build process for helpers.c but happy to provide more details if required. OS: Linux 6.2.9, CC: GCC 12.2.1 20230201

**Comment by alexcrichton** [comment]
Thanks for the report! Does https://github.com/bytecodealliance/wasmtime/pull/6188 fix compilation for you? Or is `__asm` required instead of `__asm__`?

**Comment by mainini** [comment]
Thanks for the quick action! Indeed, this fixes it.
As a sidenote, I've now understood why it failed in the first place: I forgot having CFLAGS="-std=c17 -Wall -Wextra -Wpedantic" in my environment by default...
Sorry for the noise - in any case it's standards compliant now ;-)
