### ISSUE TITLE
WASI strace feature request

### ISSUE THREAD

**Issue by TerrorJack** [bytecodealliance/wasmtime#6191]
Thanks for filing a feature request! Please fill out the TODOs below.

#### Feature

It would be very nice if `wasmtime` has a WASI strace feature, which logs all WASI syscalls.

#### Benefit

This feature improves observability of wasm modules being executed, and it's quite useful to debug the wasm module when things go wrong.

#### Implementation

Likely a CLI option, and some modification to the `wasmtime-wasi` crate.

#### Alternatives

Some third-party rust program that uses the `wasmtime` crate and implements the strace middleware there.

**Comment by abrown** [comment]
I've used the `RUST_LOG` environment variable for this in the past.

**Comment by TerrorJack** [comment]
Ah I didn't read the documentation clearly! There's already `RUST_LOG=wasi_common=trace`. Thanks a lot for reminding me @abrown!
