### ISSUE TITLE
How to dump the machine code after AOT compilation?

### ISSUE THREAD

**Issue by hungryzzz** [bytecodealliance/wasmtime#6213]
Hi, I want to dump the compiled machine code but I don't find the related option.
How could I do it? Thank you!

**Comment by alexcrichton** [comment]
There's no "official" way to do this but for debugging what you can do is call `Module::serialize` (or `wasmtime compile`) and then run `objdump -S` on the output. While not "officially supported" we're unlikely to change that since Wasmtime developers themselves frequently use it for debugging.

**Comment by jameysharp** [comment]
Depending on what you need it for, you might also find `wasmtime explore` helpful; it'll produce an HTML-format dump correlating wasm instructions with the machine code that they were compiled into.

**Comment by alexcrichton** [comment]
Oh thank you @jameysharp I keep forgetting to mention that as well! And it's probably a lot more useful than `objdump` to bood!
