### ISSUE TITLE
Quesiton: How to use wasmtime to compile wasm to aarch64 (arm) assembly on x86 machine?

### ISSUE THREAD

**Issue by fritzrehde** [bytecodealliance/wasmtime#6223]
Is it possible to use an x86 machine to compile wasm files to aarch64 assembly? Maybe by supplying `wasmtime` with the `--target aarch64-unknown-linux` option? I can also compile `wasmtime` itself on x86, and I found the `all-arch` feature flag at https://docs.rs/crate/wasmtime/latest/features, is that a recommended solution my to question?

**Comment by alexcrichton** [comment]
Indeed this is supported! As you've found the `--target` CLI flag which maps to [`Config::target`](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.target) is how to cross compile. Additionally as you've found cross-compilation is currently disabled by default but can be enabled at compile time with the `--features all-arch` flag.
