### ISSUE TITLE
Sync/Send modules and instances?

### ISSUE THREAD

**Issue by sfackler** [bytecodealliance/wasmtime#626]
`CompiledModule` and `InstanceHandle` are currently `!Sync` and `!Send`. This makes it awkward or impossible to use in some contexts. For example, I'm looking to run user-provided WASM in a web server, but some of the interfaces I'm working with require `Send` state.

It'd be great if these types could at least be `Send`. Ideally they'd be `Sync` as well, but you can always stick them in a `Mutex` to work around that.

**Comment by alexcrichton** [comment]
I think we've got a number of issues to handle with the API of the `wasmtime` crate, but I've gone ahead and folded this into https://github.com/bytecodealliance/wasmtime/issues/708 which is focused on the `wasmtime` API crate rather than the core types, which I think should handle this.
