### ISSUE TITLE
Caches are not working on GitHub Actions

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#6285]
One thing I forgot about when enabling the Merge Queue feature for this repository is that the existing usages of `actions/cache` are all broken now. The problem appears to be that caches are associated with a branch and while caches can pull from the "base branch" the base branch in our case is `main` which never runs CI. This means that all branches are always separate and have no shared base to pull from.

I posted about this [here](https://github.com/orgs/community/discussions/46757#discussioncomment-5723142) on the github merge queue discussion feedback but wanted to open up something here to track this. I was about to make a PR to remove all the caches but that didn't feel quite right, so I went this route instead.

**Comment by tschneidereit** [comment]
Could we do a daily cron-triggered CI run on main to prime the caches?

**Comment by alexcrichton** [comment]
Oh yes indeed, that's a great idea!
