### ISSUE TITLE
Installation: winget keeps reporting Wasmtime update available

### ISSUE THREAD

**Issue by henrikrxn** [bytecodealliance/wasmtime#6309]
This relates to installing the wasmtime CLI on Windows using the Windows package manager winget

*Environment*
Windows 11 Pro
Powershell 7.3.4
winget v1.5.1081-preview

I query winget for a list of my packages where an upgrade is available

```
PS> winget upgrade
Name                                    Id                                  Version    Available  Source
--------------------------------------------------------------------------------------------------------
Wasmtime                                BytecodeAlliance.Wasmtime           8.0.0      8.0.1      winget
```

I then update Wasmtime (winget ID BytecodeAlliance.Wasmtime) from 8.0.0 to 8.0.1 using the command

`PS> winget upgrade BytecodeAlliance.Wasmtime`

The installation went perfectly and I open a new Powershell prompt and check the version number:

```
PS> wasmtime -V 
wasmtime-cli 8.0.1
```

When run `winget upgrade` again Wasmtime is still there
```
PS> winget upgrade
Name                                    Id                                  Version    Available  Source
--------------------------------------------------------------------------------------------------------
Wasmtime                                BytecodeAlliance.Wasmtime           8.0.0      8.0.1      winget
```

I have seen this type of problem before for other packages and for many the root cause was the manifest file.

**Comment by bjorn3** [comment]
AFAIK the winget package is not maintained by the bytecodealliance.

**Comment by henrikrxn** [comment]
@bjorn3 Seems you are right

I did some digging in the [Winget package Github repository](https://github.com/microsoft/winget-pkgs) and the maintainer of the wasmtime entry has neither contributed to the wasmtime repository nor is a member of the bytecodealliance Github "org".

Therefore I am closing the issue
