### ISSUE TITLE
CI Failures when compiling wasi-common

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#633]
On several recent pull requests there appear to be CI failures unrelated to the change ... namely https://github.com/bytecodealliance/wasmtime/pull/625, https://github.com/bytecodealliance/wasmtime/pull/360, https://github.com/bytecodealliance/wasmtime/pull/627.

are a few that I've noticed. I have not been able to reproduce locally. Failure usually occurs on nightly though I believe I've seen similar error reported with a different configuration.

![image](https://user-images.githubusercontent.com/45402135/69572563-3dc4f980-0f79-11ea-83a3-bd2ec527ea91.png)

Will see if I can determine something more but anyone have an idea?

**Comment by alexcrichton** [comment]
I believe this is a [regression in rustc itself](https://github.com/rust-lang/rust/issues/66757)

**Comment by jlb6740** [comment]
I see. Thanks! Looks like https://github.com/bytecodealliance/wasmtime/pull/635 has been merged to address this. 

@alexcrichton @kubkon BTW is there a way to re-trigger CI without doing a force push?

Thanks.

**Comment by kubkon** [comment]
@jlb6740 you should be able to do that from the “checks” tab in your PR. There, you should see the summary of all Github Actions jobs, and in the top right corner, there should be a “Re-run all checks” button that should do what you’re after.
