### ISSUE TITLE
wasm_functype_new_1_1 & similar faulting

### ISSUE THREAD

**Issue by adv-sw** [bytecodealliance/wasmtime#6347]
### Test Case

#include <stdio.h>
#include <stdlib.h>
#include <wasm.h>
#include <wasmtime.h>
 
int main() 
{ 
  wasm_config_t* wasm_config = wasm_config_new();
  wasmtime_config_debug_info_set(wasm_config, true);
  wasm_engine_t *engine = wasm_engine_new_with_config(wasm_config);
 
  printf("A");
  wasm_valtype_t* val_i32 =  wasm_valtype_new(WASM_I32);
  wasm_functype_t *__ft_i32_out_i32  = wasm_functype_new_1_1(val_i32, val_i32);
  printf("B");
  printf("\n");
 
  return 0;
}

### Steps to Reproduce

Compile the above, Windows (might also fault other platforms, but untested). Run it.

### Expected Results

Completes - Output: AB

### Actual Results

Faults in: wasm_functype_new_1_1 

### Versions and Environment

Tip as of 5/5/2023 at 13:00 GMT

Windows 11 Home, X64

### Extra Info

Reverting the following resolves the regression.

https://pastebin.com/2Yt3FG9E

... though the spec apparently states that function should reassign owner rather than clone, rework of regressed functionality.

**Comment by bjorn3** [comment]
`wasm_functype_new_1_1` consumes both arguments according to the header declaration: https://github.com/WebAssembly/wasm-c-api/blob/c9d31284651b975f05ac27cee0bab1377560b87e/include/wasm.h#L607 This means that you can't pass the exact same argument twice without causing a crash. You have to call ` wasm_valtype_new(WASM_I32)` once for each use and never reuse it after passing it to `wasm_functype_new_1_1`.

**Comment by adv-sw** [comment]
ahhhh :)

what an odd api.

**Comment by adv-sw** [comment]
The following faults on wasm_valtype_delete so it seems we should never call wasm_valtype_delete as the value has been sucked internal to wasm_valtype_new.

Hence wondering why wasm_valtype_delete API entrypoint even exists.


int main() 
{ 
  wasm_config_t* wasm_config = wasm_config_new();
  wasmtime_config_debug_info_set(wasm_config, true);
  wasm_engine_t *engine = wasm_engine_new_with_config(wasm_config);

  printf("wasm_functype_new_1_1[before].\n");
  wasm_valtype_t* val_i32_1 =  wasm_valtype_new(WASM_I32);
  wasm_valtype_t* val_i32_2 =  wasm_valtype_new(WASM_I32);
  wasm_functype_t *__ft_i32_out_i32  = wasm_functype_new_1_1(val_i32_1, val_i32_2);
  printf("wasm_functype_new_1_1[after].\n");

  wasm_functype_delete(__ft_i32_out_i32);

  wasm_valtype_delete(val_i32_1);
  wasm_valtype_delete(val_i32_2);

  return 0;
}
