### ISSUE TITLE
Use `GITHUB_TOKEN` in install script

### ISSUE THREAD

**Issue by gbryant-arm** [bytecodealliance/wasmtime#6438]
#### Feature
Improve support for Github workflows by using [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) in the install script (`https://wasmtime.dev/install.sh`) to increase the [REST API's rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting)

#### Benefit
To get the latest version, the install script sends an unauthenticated request to Github's REST API, which is subject to a [rate limit of 60 requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting).
Using [`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) in Github workflows would push that limit to 1000 requests per hour

#### Implementation
See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api

**Comment by rikhuijzer** [comment]
I think this is fixed if you use `bytecodealliance/actions/wasmtime/setup` from https://github.com/bytecodealliance/actions. That project uses the default GitHub Action token: https://github.com/bytecodealliance/actions/commit/d0325fe0b8ce57a326793bb0ea98695a2ef20db7.

**Comment by alexcrichton** [comment]
Ah yes good point! I'd recommend the same nowadays to install wasmtime in CI, so I'll close this.
