### ISSUE TITLE
Winch Core Wasm Opcode Support

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/wasmtime#6528]
During the [debugging meeting on June 1, 2023](https://github.com/bytecodealliance/meetings/blob/main/SIG-Debugging/2023/debugging-06-01.md), we discussed opening an issue to track the missing Core Wasm opcodes in Winch. The objective of this issue is to make it easier for potential contributors to know where to start. 

This list is intended to be a comprehensive compilation of the missing opcodes required to achieve parity with Core Wasm(*). Each entry also includes an owner, indicating that work on a particular opcode is currently in progress.

(*) Excluding SIMD and Reference Types to start, as drafted in the initial RFC. We can open dedicated issues as we get to those and other proposals.

cc/ @fitzgen @itsrainy 

- [x]     Unreachable (@saulecabrera)
- [x]     Block (@saulecabrera)
- [x]     Loop (@saulecabrera)
- [x]     If (@saulecabrera)
- [x]     Else, (@saulecabrera)
- [x]     Br (@saulecabrera)
- [x]     BrIf (@saulecabrera)
- [x]     Return (@saulecabrera)
- [x]     CallIndirect (@saulecabrera)
- [x]     BrTable (@saulecabrera)
- [x]     Drop (@saulecabrera)
- [x]     Select (@saulecabrera)
- [x]     LocalTee (@saulecabrera)
- [x]     GlobalGet (@saulecabrera)
- [x]     GlobalSet (@saulecabrera)
- [x]     I32Load (@saulecabrera)
- [x]     I64Load (@saulecabrera)
- [x]     F32Load (@saulecabrera)
- [x]     F64Load (@saulecabrera)
- [x]     I32Load8S (@saulecabrera)
- [x]     I32Load8U (@saulecabrera)
- [x]     I32Load16S (@saulecabrera)
- [x]     I32Load16U (@saulecabrera)
- [x]     I64Load8S (@saulecabrera)
- [x]     I64Load8U (@saulecabrera)
- [x]     I64Load16S (@saulecabrera)
- [x]     I64Load16U (@saulecabrera)
- [x]     I64Load32S (@saulecabrera)
- [x]     I64Load32U (@saulecabrera)
- [x]     I32Store (@saulecabrera)
- [x]     I64Store (@saulecabrera)
- [x]     F32Store (@saulecabrera)
- [x]     F64Store (@saulecabrera)
- [x]     I32Store8 (@saulecabrera)
- [x]     I32Store16 (@saulecabrera)
- [x]     I64Store8 (@saulecabrera)
- [x]     I64Store16 (@saulecabrera)
- [x]     I64Store32 (@saulecabrera)
- [x]     MemorySize (@saulecabrera)
- [x]     MemoryGrow (@saulecabrera)
- [x]     F32Const (@saulecabrera)
- [x]     F64Const (@saulecabrera) 
- [x]     F32Eq (@jeffcharles)
- [x]     F32Ne(@jeffcharles)
- [x]     F32Lt(@jeffcharles)
- [x]     F32Gt(@jeffcharles)
- [x]     F32Le(@jeffcharles)
- [x]     F32Ge(@jeffcharles)
- [x]     F64Eq(@jeffcharles)
- [x]     F64Ne(@jeffcharles)
- [x]     F64Lt(@jeffcharles)
- [x]     F64Gt(@jeffcharles)
- [x]     F64Le(@jeffcharles)
- [x]     F64Ge(@jeffcharles)
- [x]     I32Clz (@jeffcharles)
- [x]     I32Ctz (@jeffcharles)
- [x]     I32Popcnt (@itsrainy)
- [x]     I32And (@jeffcharles)
- [x]     I32Or (@jeffcharles)
- [x]     I32Xor (@jeffcharles)
- [x]     I32Shl (@jeffcharles)
- [x]     I32ShrS (@jeffcharles)
- [x]     I32ShrU (@jeffcharles)
- [x]     I32Rotl (@jeffcharles)
- [x]     I32Rotr (@jeffcharles)
- [x]     I64Clz (@jeffcharles)
- [x]     I64Ctz (@jeffcharles)
- [x]     I64Popcnt (@itsrainy)
- [x]     I64And (@jeffcharles)
- [x]     I64Or (@jeffcharles)
- [x]     I64Xor (@jeffcharles)
- [x]     I64Shl (@jeffcharles)
- [x]     I64ShrS (@jeffcharles)
- [x]     I64ShrU (@jeffcharles)
- [x]     I64Rotl (@jeffcharles)
- [x]     I64Rotr (@jeffcharles)
- [x]     F32Abs (@elliottt)
- [x]     F32Neg (@elliottt)
- [x]     F32Ceil (@elliottt)
- [x]     F32Floor (@elliottt)
- [x]     F32Trunc (@elliottt)
- [x]     F32Nearest (@elliottt)
- [x]     F32Sqrt (@jeffcharles)
- [x]     F32Add (@jeffcharles)
- [x]     F32Sub (@jeffcharles)
- [x]     F32Mul (@jeffcharles)
- [x]     F32Div (@jeffcharles)
- [x]     F32Min (@jeffcharles)
- [x]     F32Max (@jeffcharles )
- [x]     F32Copysign (@jeffcharles)
- [x]     F64Abs (@elliottt)
- [x]     F64Neg (@elliottt)
- [x]     F64Ceil (@elliottt)
- [x]     F64Floor (@elliottt)
- [x]     F64Trunc (@elliottt)
- [x]     F64Nearest (@elliottt)
- [x]     F64Sqrt (@jeffcharles)
- [x]     F64Add (@jeffcharles)
- [x]     F64Sub (@jeffcharles)
- [x]     F64Mul (@jeffcharles)
- [x]     F64Div (@jeffcharles)
- [x]     F64Min (@jeffcharles)
- [x]     F64Max (@jeffcharles)
- [x]     F64Copysign (@jeffcharles)
- [x]     I32WrapI64 (@jeffcharles)
- [x]     I32TruncF32S (@jeffcharles)
- [x]     I32TruncF32U (@jeffcharles)
- [x]     I32TruncF64S (@jeffcharles)
- [x]     I32TruncF64U (@jeffcharles)
- [x]     I64ExtendI32S(@jeffcharles)
- [x]     I64ExtendI32U(@jeffcharles)
- [x]     I64TruncF32S (@jeffcharles)
- [x]     I64TruncF32U (@jeffcharles)
- [x]     I64TruncF64S (@jeffcharles)
- [x]     I64TruncF64U (@jeffcharles)
- [x]     F32ConvertI32S (@jeffcharles)
- [x]     F32ConvertI32U (@jeffcharles)
- [x]     F32ConvertI64S (@jeffcharles)
- [x]     F32ConvertI64U (@jeffcharles)
- [x]     F32DemoteF64 (@jeffcharles)
- [x]     F64ConvertI32S (@jeffcharles)
- [x]     F64ConvertI32U (@jeffcharles)
- [x]     F64ConvertI64S (@jeffcharles)
- [x]     F64ConvertI64U (@jeffcharles)
- [x]     F64PromoteF32 (@jeffcharles)
- [x]     I32ReinterpretF32 (@jeffcharles)
- [x]     I64ReinterpretF64 (@jeffcharles)
- [x]     F32ReinterpretI32 (@jeffcharles)
- [x]     F64ReinterpretI64 (@jeffcharles)
- [x]     I32Extend8S(@jeffcharles)
- [x]     I32Extend16S (@jeffcharles)
- [x]     I64Extend8S(@jeffcharles)
- [x]     I64Extend16S(@jeffcharles)
- [x]     I64Extend32S(@jeffcharles)
- [x]     MemoryInit (@saulecabrera)
- [x]     DataDrop (@saulecabrera)
- [x]     MemoryCopy (@saulecabrera)
- [x]     MemoryFill (@saulecabrera)
- [x]     TableInit (@saulecabrera)
- [x]     ElemDrop (@saulecabrera)
- [x]     TableFill (@saulecabrera)
- [x]     TableCopy (@saulecabrera)
- [x]     TableGet (@saulecabrera)
- [x]     TableSet (@saulecabrera)
- [x]     TableGrow (@saulecabrera)
- [x]     TableSize (@saulecabrera)

## Proposals

- [x] Multi-Value (@saulecabrera)
  - [x] Functions
  - [x] Blocks

**Comment by jeffcharles** [comment]
All good, I haven't started on either of those yet. I'm trying to debug an issue as part of implementing `clz` and `ctz` and I think your PR will be very helpful in resolving that issue.
