### ISSUE TITLE
Disable trace logs by default to optimize module compilation

### ISSUE THREAD

**Issue by TimonPost** [bytecodealliance/wasmtime#6548]
There has been a performance regression for module compilation. The PR #5382 added the `trace-log` feature by default ([this line]( https://github.com/bytecodealliance/wasmtime/pull/5382/files#diff-3a16b8de8e683460bef7c9ef4c6b2d0ec0e15efb8b404eef3a848742ce8625f4L45))

Historically high-frequent trace logs have been a performance bottleneck. Some efforts were made to revert that (#4481, #4484, #2758). In #4484 @bnjbvr added this feature flag, claiming perf increment of 32%, whereafter this flag was enabled by default in #5382.

The following numbers are from sampling the app once before and after with the macos instruments profiler.

The module compilation code takes in total 29.5 sec, of that three log functions here take up ~13 secs in total (43% of total). 

![image](https://github.com/bytecodealliance/wasmtime/assets/19969910/55794c87-7315-4f33-9b07-2bb05aa5e015)

Disabling trace logs results in total 10.3s, which is roughly ~65% faster.

<img width="1332" alt="image" src="https://github.com/bytecodealliance/wasmtime/assets/19969910/4636be43-e9c7-4013-84a8-242f9f17ab22">

Branch for this instrumentation can be found here: https://github.com/bytecodealliance/wasmtime/compare/main...TimonPost:wasmtime:timon/make-trace-logs-not-default?expand=1

#### Feature

We probably want to disable 'trace-log' by default as shown this takes ~60% of the total module compilation. Also we likely want to expose upstream control over this feature.

#### Benefit

Speeds up compilation by 60% :). 

#### Implementation

- Remove the `trace-log` feature from the default features array in `codegen`.
- Add `trace-log` feature to various crates that depend on `codegen`, and from those crates expose the ability to 'enable' trace logs as opt in.
-  Also expose this feature for `wasmtime` crate so that we can decide on enabling/disabling logs. 
 
#### Details

- Macos 13.0.1, Apple M1 Max
- Precompiled Wasm module is roughly 400MB

**Comment by repi** [comment]
Thanks that minimal fix improves compilation speed for our big model on my machine from 7.0 s -> 5.55s :tada: which is very significant and about what we saw last time when we implemented the feature flag for excluding the heavy trace log statements.
