### ISSUE TITLE
(docs) Component Fn Call syntax

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/wasmtime#6558]
https://github.com/bytecodealliance/wasmtime/blob/e105aa385e8bb1b2fa4c86d4a0a0522edc71ee5f/crates/wasmtime/src/component/mod.rs#L212

Is this syntax still valid? The only syntax I can find that works is always prepended with `call_`

Wondering if I'm missing something or if these docs are just out of date?

**Comment by pchickey** [comment]
The bindings generator prefixes export function names with `call_` in order to avoid collisions with the `new()` constructor, as well as Rust keywords. The docs are out of date. Would you mind sending a PR to correct that error?

**Comment by DougAnderson444** [comment]
No problem! Done :)
