### ISSUE TITLE
Current `preview2::WasiCtx::builder()` doesn't set `random`, so it can't be used

### ISSUE THREAD

**Issue by Hpmason** [bytecodealliance/wasmtime#6576]
`wasmtime_wasi::preview2::WasiCtx::builder` returns the default `WasiCtxBuilder`, but there's no way to set `random`, which is a required field to builder `WasiCtx`. The derived Default impl sets `random` to None, so there is no way to successfully build `WasiCtx` from `WasiCtx::builder`. 

`WasiCtx::builder`:
https://github.com/bytecodealliance/wasmtime/blob/aef1f57d130e359565dbc50090d031b398bac1c2/crates/wasi/src/preview2/ctx.rs#L203-L205

`random` required here:
https://github.com/bytecodealliance/wasmtime/blob/aef1f57d130e359565dbc50090d031b398bac1c2/crates/wasi/src/preview2/ctx.rs#L162-L177

## Version
This seems to affect version 10.0.0 up to the current main branch

**Comment by sunfishcode** [comment]
Thanks for the report! I've now submitted https://github.com/bytecodealliance/wasmtime/pull/6596 to add a `set_random` function for initializing the random state.

A workaround for this is to call `WasiCtxBuilder::new()` instead of `WasiCtx::builder()`.

**Comment by pchickey** [comment]
Sorry, `WasiCtx::builder()` and `WasiCtxBuilder::new()` should be identical, but since I only used one of them in tests, the other one diverged.
