### ISSUE TITLE
Using wasmtime from within WASM

### ISSUE THREAD

**Issue by Masterchef365** [bytecodealliance/wasmtime#6611]
#### Feature

To make it possible to compile Wasmtime itself to WebAssembly.

#### Benefit

1. To enable applications which support plugins via Wasmtime to be easily ported to WebAssembly themselves. 
2. Deeply nested WASM, for shenanigans
3. To be able to gloat about being "self-hosting"

#### Implementation

Because the host environment would be WASM, the easiest way to do this might be to create a mockup interface that behaves as Wasmtime does, but really does not do any work to e.g. JIT compile the WASM because we're already running in it.

#### Alternatives

The alternative to this is to not do it, because it is silly.

**Comment by pchickey** [comment]
We just had this thread the other day but I don't know where it went. This is not something we see much value in pursuing.

**Comment by jameysharp** [comment]
I think you're thinking of #6504, Pat, where we had more discussion about alternatives.
