### ISSUE TITLE
wasmtime C API failed to execute a .wat file

### ISSUE THREAD

**Issue by lyuxiaosu** [bytecodealliance/wasmtime#6626]
I have a C code using WASI and was compiled to .wasm. I can use **wasmtime** to execute it successfully. I then used **wasm2wat** tool to convert .wasm to .wat. Then I replaced the .wat file in `wasmtime/examples
/hello.c` with my converted .wat file to build and have a test (I also replaced _run_ function with __start_). However, when I executed it, it gave the following error:

```
$ ./wasmtime_test
Initializing...
Compiling module...
Creating callback...
Instantiating module...
error: failed to instantiate
expected 8 imports, found 1
```
Any suggestions for me about this? Is it possible that **wasm2wat** did something wrong? Thanks very much.

**Comment by bjorn3** [comment]
I believe the `hello.c` example doesn't work with WASI modules. The `linking.c` example should work though. As written it links two wasm modules together and additionally links the wasi implementation. You will probably want to change it to only link a single wasm module and the wasi implementation. I think removing https://github.com/bytecodealliance/wasmtime/blob/d24282c1fffa6773dca855919985a0a92fc1ee34/examples/linking.c#L81-L90 would work for that.

**Comment by lyuxiaosu** [comment]
@bjorn3 thanks a lot, it works. I made little change for linking.c and it works. This is really help. wasmtime's documentation and examples are really excellent.

**Comment by lyuxiaosu** [comment]
This issue was solved.
