### ISSUE TITLE
Provide wasmtime_config_with_host_memory in the C API

### ISSUE THREAD

**Issue by basvandijk** [bytecodealliance/wasmtime#6636]
#### Feature

We're working on a Haskell binding to wasmtime called [wasmtime-hs](https://github.com/dfinity/wasmtime-hs).

In our project we would like to have access to the [Config::with_host_memory(...)](https://docs.rs/wasmtime/10.0.1/wasmtime/struct.Config.html#method.with_host_memory) functionality. 
Could this function be provided in the [C API](https://docs.wasmtime.dev/c-api/config_8h.html)? 

#### Benefit

At the moment this functionality is only available in the Rust library. It would be nice if other languages have access to the same functionality.

#### Implementation

> Do you have an implementation plan, and/or ideas for data structures or
algorithms to use?

Not yet, it probably has to look something like this but I haven't thought about it too much yet:

```Rust
#[no_mangle]
pub unsafe extern "C" fn wasmtime_config_with_host_memory(
    c: &mut wasm_config_t,
    mem_creator_callback: wasmtime_new_memory_callback_t,
) {
    c.config.with_host_memory(...);
}

pub type wasmtime_new_memory_callback_t = extern "C" fn(
    ty: &wasm_memorytype_t,
    minimum: u64,
    maximum_specified: bool,
    maximum: u64,
    reserved_size_in_bytes_specified: bool,
    reserved_size_in_bytes: u64,
    guard_size_in_bytes: bool,
) -> Box<dyn LinearMemory>
```

**Comment by jameysharp** [comment]
This sounds reasonable to me but I'm not sure what design principles we're following for Wasmtime's C API, so I'd like to get opinions from @alexcrichton or @fitzgen on what this should look like.

Huh, maybe I shouldn't have used the `wasmtime:config` label. I wasn't expecting that particular auto-reply.

**Comment by alexcrichton** [comment]
This was [discussed a bit on Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/MemoryCreator.20C.20API) as well and my strawman there was:


```c
typedef wasmtime_error_t *(*wasmtime_new_memory_t)(
    wasm_memorytype_t *ty,
    size_t minimum,
    size_t maximum,
    size_t reserved_size_in_bytes,
    size_t guard_size_in_bytes,
    void **ret);

typedef void *(*wasmtime_memory_get_t)(
    void *ptr,
    size_t *byte_size,
    size_t *maximum_byte_size);

typedef wasmtime_error_t *(*wasmtime_memory_grow_t)(
    void *ptr,
    size_t new_size);

typedef struct {
  wasmtime_new_memory_t new_memory;
  wasmtime_memory_get_t get_memory;
  wasmtime_memory_grow_t grow_memory;
} wasmtime_memory_creator_t;

void wasmtime_config_memory_creator_set(wasmtime_config_t *config, wasmtime_memory_creator_t *creator);
```

Personally I don't think the details matter too too much so long as it all works for your use case, we can always iterate over time as necessary.

Note though that in the original suggestion an `extern "C" fn` can't return `Box<dyn LinearMemory>` because that's a Rust-defined structure which C can't mirror, so you'll need to package up those callbacks in addition to the `wasmtime_new_memory_callback_t` type

**Comment by basvandijk** [comment]
@alexcrichton thanks, I wasn't aware of that chat by my colleague :). But your strawman looks like a great start!
