### ISSUE TITLE
Debugging compiled wasm code

### ISSUE THREAD

**Issue by sirgl** [bytecodealliance/wasmtime#664]
I'm trying to create system of plugins with embedded wasmtime.
How is it supposed to debug (like breakpoint, step-by-step, condition evaluation and so on) jit-compiled wasm code?
Is some kind of debugging protocol planned (like JVMTI) or am I missed something and it is already implemented?

**Comment by tschneidereit** [comment]
Wasmtime has support for debugging with LLDB, as described in [this blog post from September](https://hacks.mozilla.org/2019/09/debugging-webassembly-outside-of-the-browser/).

Out of the box this only works on Linux for now: the version of LLDB that Apple ships with XCode has a bug in in that prevents this from working, and the Windows version of LLDB is just very different and much harder to support.

**Comment by bjorn3** [comment]
I think this can be closed.

**Comment by peterhuene** [comment]
Agreed, I think this should be closed.
