### ISSUE TITLE
Thoughts on Winter (extra-browser web API standardization)

### ISSUE THREAD

**Issue by trusktr** [bytecodealliance/wasmtime#6656]
I wasn't sure where to post this, as I didn't see some sort of public forum for Bytecode Alliance, so posting here for now.

This project is interesting:

https://wintercg.org/

However it is currently focused only on bringing web APIs to JavaScript engines outside of browsers, and WebAssembly is not part of the picture yet.

I wonder if there's some sort of potential to get WebAssembly into the picture, so that APIs like the File System API can be standardized in a way such that it is usable in both JS engines and Wasm engines. 

This would be an alternative to WASI. It would be different, and perhaps not useful for compiling existing and legacy C/C++ apps to WebAssembly, but useful in defining a new generation of applications built on common standards that don't leave the "web" in WebAssembly out of the picture for the new breed of apps that can build on these specs.

**Comment by philpax** [comment]
Hi! No opinion on the issue itself, but regarding the public forum for the Bytecode Alliance - check out their Zulip: https://bytecodealliance.zulipchat.com

You might be able to get more feedback there :)

**Comment by jameysharp** [comment]
Thanks for that thoughtful explanation, @linclark! I'm going to go ahead and close this particular issue as out of scope for Wasmtime.

**Comment by trusktr** [comment]
I suppose a more important question is, would it be good too officially support the spec, regardless of how it is implemented? (if it is on top of WASI, but people are directly using Winter, it still seems like an alternative).

Leaving it to library land won't be ideal, won't really make it a standard (I think it could be a good standard!) but *would* be a way to test it out.
