### ISSUE TITLE
`cranelift-filetest`: Allow `run` directives with functions that have a `vmctx`

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#6659]
And allow passing in arbitrary values as `vmctx` as well, basically treating it like any other argument.

While this wouldn't allow complex global values based on the `vmctx`, it would allow simple ones like `gv0 = vmctx`.

We would also want the CLIF interpreter to support this as well, since basically all of our runtests are also interpreter tests.

**Comment by fitzgen** [comment]
I guess I could have got that working with another trampoline function to init the vmctx, that's a good trick. Still a bit of a workaround though compared to just passing in a value.

**Comment by afonso360** [comment]
Oh, weird that it doesn't work when we call the vmctx function directly. That should be a somewhat easy fix, I don't mind working on it.

I think we don't support stack_limit in the interpreter yet though.
