### ISSUE TITLE
32-bit build of wasmtime is broken?

### ISSUE THREAD

**Issue by arvid-norlander** [bytecodealliance/wasmtime#6675]
I'm trying to build wasmtime for 32-bit x86 (and ARM in extension) as I want to embed it in a C program running on some industrial controllers, with very long service life. Unfortunately this seems broken. I can build a native x86-64 build with no issues. But the 32-bit build fails as follows:

```console
$ cargo build --target i686-unknown-linux-gnu                                                                                                                   9s
    Blocking waiting for file lock on build directory
[... lots of sucessfully built crates ...]
error[E0432]: unresolved import `wasmtime_asm_macros::asm_sym`
  --> crates/fiber/src/unix/x86.rs:13:37
   |
13 | use wasmtime_asm_macros::{asm_func, asm_sym};
   |                                     ^^^^^^^ no `asm_sym` in the root

   Compiling socket2 v0.4.7
For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmtime-fiber` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

Are 32-bit builds not supported? If so, do you know of any wasm runtime that works on 32-bit x86 and 32-bit ARM?

**Comment by bjorn3** [comment]
Cranelift doesn't support compiling for any 32bit architecture right now. Only x86_64, aarch64, s390x and riscv64 are currently supported.

cc https://github.com/bytecodealliance/wasmtime/issues/1980 and https://github.com/bytecodealliance/wasmtime/issues/1173

**Comment by bjorn3** [comment]
Maybe [WebAssembly Micro Runtime](https://github.com/bytecodealliance/wasm-micro-runtime) would work for your use case? According to it's readme it supports:

* X86-64, X86-32
* ARM, THUMB (ARMV7 Cortex-M7 and Cortex-A15 are tested)
* AArch64 (Cortex-A57 and Cortex-A53 are tested)
* RISCV64, RISCV32 (RISC-V LP64 and RISC-V LP64D are tested)
* XTENSA, MIPS, ARC
