### ISSUE TITLE
ResourceLimiter live within the lifecycle of "data" in Store, which is hard to implement.

### ISSUE THREAD

**Issue by abel-von** [bytecodealliance/wasmtime#6712]
As if we want to use WASI, we will make the "data" as WasiCtx, and if we want to limit the resources, we have to call `limiter` with a function of Type `impl FnMut(&mut T) -> &mut (dyn crate::ResourceLimiter) + Send + Sync + 'static`.  To satisfy this lifecycle requirement, we have to initialize an object of type that implements ResourceLimiter, and add it into the `data` of Store, but as the `data` is almost often to be a `WasiCtx`, we have no way to store this ResourceLimiter into it. That makes it no way to define a ResourceLimiter for those run wasm with wasi supported.

**Comment by alexcrichton** [comment]
When using WASI the `T` in `Store<T>` doesn't have to be `WasiCtx`, it only needs to contain `WasiCtx`. This means you can do something like:

```rust
struct MyData {
    wasi: WasiCtx,
    max_memory: usize,
}

impl ResourceLImiter for MyData {
    // ...
}
```

and then when you call `wasmtime_wasi::add_to_linker` the closure would be `|data| &mut data.wasi` (or something along these lines).

Does that work for your use case?

**Comment by abel-von** [comment]
Thank you for reply ,  I think it works for me.
