### ISSUE TITLE
please document community support for perl

### ISSUE THREAD

**Issue by jonassmedegaard** [bytecodealliance/wasmtime#6748]
Hi,

I notice you have a section in the README for community supported languages.
You might want to add perl to that list, referencing https://metacpan.org/pod/Wasm::Wasmtime

**Comment by alexcrichton** [comment]
Thanks for the heads up! Would you be up for sending a PR to update the README?

**Comment by jonassmedegaard** [comment]
Thanks for the encouragement but no: Due to Github questionable terms of service I only ever use their issue trackers, never push code.

I am happy to setup a git clone with a commit that you can pull, but I suspect that's more work for your (don't mind my investment in my odd principles) than simply writing that one-liner edit yourself. :-)

**Comment by alexcrichton** [comment]
This was done in https://github.com/bytecodealliance/wasmtime/pull/6880, so closing.
