### ISSUE TITLE
More sockopt Flexibility in the socket spec

### ISSUE THREAD

**Issue by keithmattix** [bytecodealliance/wasmtime#6803]
#### Feature
👋🏾 Hello! For the purposes of building something service mesh-esque using wasm, more flexible SOCK_OPT functionality in the socket interface would be extremely beneficial. The big one we use in mesh world is `SO_ORIGINAL_DST`, but there are others. How would I go about passing ~arbitrary socket options to the underlying host?

#### Benefit
Service mesh and other networking applications can have access to more complex socket functionality on the host.

#### Implementation
TBD

**Comment by pchickey** [comment]
I'm not sure the context of this request. We have a rudimentary sockets implementation as part of WASI preview 1, but it doesn't have any spec written down nor any tests in our tree, and we aren't looking to spend any additional effort on that spec or implementation (and in fact may delete it - see https://github.com/bytecodealliance/wasmtime/issues/6370 - are you a user? if so, can you help contribute compatibility support?). We are planning to implement https://github.com/WebAssembly/wasi-sockets very soon, which we feel is a much better spec for both users and implementors.

**Comment by keithmattix** [comment]
Ah I wasn't aware of that other repo; I still don't see the options there, so I'll create an issue in that repo

**Comment by pchickey** [comment]
Ok. Just to confirm, you're not using any existing sockets functionality in the wasi-common preview 1 implementation, so you won't be affected if it gets deleted without a direct replacement, and instead have to adopt wasi-sockets in preview 2 instead?

**Comment by keithmattix** [comment]
Yes! I explained more in webassembly/wasi-sockets#45
