### ISSUE TITLE
Docs: Possibly outdated memory64 support status in `contributing-architecture.md`

### ISSUE THREAD

**Issue by gibbz00** [bytecodealliance/wasmtime#6865]
I'm new to everything WASM, but I suspect this part of the documentation is outdated 😊:

https://github.com/bytecodealliance/wasmtime/blob/367bdc8c66df62d6854966a90564b42692a3f023/docs/contributing-architecture.md?plain=1#L391-L393

https://github.com/bytecodealliance/wasmtime/blob/367bdc8c66df62d6854966a90564b42692a3f023/docs/stability-wasm-proposals-support.md?plain=1#L26

**Comment by alexcrichton** [comment]
Thanks! memory64 is indeed supported so I've opened https://github.com/bytecodealliance/wasmtime/pull/6868 to update the docs.
