### ISSUE TITLE
Is it possible to release a patch 12.0.1

### ISSUE THREAD

**Issue by TimonPost** [bytecodealliance/wasmtime#6889]
On the 7th of August https://github.com/bytecodealliance/wasmtime/pull/6804 was merged which gives us quite some improvement in module compilation times. We hoped to get this feature in 0.12 but as it was merged with main 2 days after the 12.0 branch was created (the 5th) it hasn't been released. Is it possible to release a patch 12.0.1 with this commit? Also, this means the RELEASES https://github.com/bytecodealliance/wasmtime/pull/6838 is not correct as this change was not included in 12.0

**Comment by alexcrichton** [comment]
Personally I think this is fine to do at this time. Would you be up for sending a PR to backport that change to the 12.0.0 release branch?

**Comment by alexcrichton** [comment]
Done now via https://github.com/bytecodealliance/wasmtime/pull/6897 and https://github.com/bytecodealliance/wasmtime/pull/6901, so closing.
