### ISSUE TITLE
Wasmtime and ruby

### ISSUE THREAD

**Issue by anshul** [bytecodealliance/wasmtime#691]
I could not find the equivalent of the python wasmtime module for ruby.  Is there one?  Is an official one planned?

**Comment by sunfishcode** [comment]
Hello! There is not yet a Wasmtime module for ruby. I know some folks are thinking about it, but there aren't yet any plans I can link to here.

**Comment by sandstrom** [comment]
Just wanted to follow up on this one.

Anyone on the core team that know if there are plans for an official ruby module?

I know Shopify is using lucet (or wasmtime) internally, which is a known ruby shop. Anyone know if they are planning to open-source anything?

There is also this open source project (https://github.com/dtcristo/wasmtime-ruby) but it doesn't seem to have too much activity currently. Don't know which state it currently is in.

**Comment by sunfishcode** [comment]
I myself don't know anyone offhand, but I've sent out some messages to various places to see if I can find anyone.

**Comment by sandstrom** [comment]
@sunfishcode Many thanks Dan!

**Comment by tschneidereit** [comment]
@sandstrom sorry this took a while, but we now heard back and might have someone interested, but would need more details. If you're still interested on your end, please email me at till @ [this gh org].org

**Comment by sandstrom** [comment]
@tschneidereit Just wanted to ask if you got my email? (sent last week)

**Comment by sandstrom** [comment]
friendly ping @tschneidereit 😄

**Comment by sandstrom** [comment]
@tschneidereit Hello, just wanted to ask if you got my email? (I sent it to the address you quoted above)
