### ISSUE TITLE
Wasmtime wasi-sockets implementation: Finish tweaks to spec

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasmtime#7013]
@badeend has outlined these tasks remaining before we declare the wasi-sockets spec stable and ready for Preview 2:

1. [x] Remove `(set-)no-delay`
1. [x] Remove the non-essential `ip-name-lookup::resolve-addresses` parameters.
1. [x] Lift the `ip-name-lookup::resolve-addresses` hostname restriction against parsing IP addresses. Implementations will still have to parse IP addresses to decide whether or not to return an error

**Comment by alexcrichton** [comment]
I believe this is now all done on `main`
