### ISSUE TITLE
Wasmtime wasi-http: Tests demonstrate portability criteria met

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wasmtime#7026]

**Comment by pchickey** [comment]
Our plan to wrap this up is:
* @dicej is going to contribute a test from spin that exercises streaming behavior
* @tschneidereit is going to port web platform tests (#7062)

**Comment by elliottt** [comment]
We need a test that asserts that the timeouts specified in `request-options` will raise an error when any of the provided timeouts expire.

**Comment by elliottt** [comment]
In service of making it easier to tell when this issue is resolve, I've split it into #7357 and #7356.
