### ISSUE TITLE
Provide release details in GitHub Releases

### ISSUE THREAD

**Issue by brettcannon** [bytecodealliance/wasmtime#7068]
When you look at https://github.com/bytecodealliance/wasmtime/releases/tag/v13.0.0 there's no information about what is in the release (and subscribing to GitHub release notifications means releases are, at least for me, the primary way to find out about new releases). You have to navigate to https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#1300 in order to find out what's contained in the release.

Any way to either inline the release notes into the GitHub release or at least provide a link to the document?

**Comment by alexcrichton** [comment]
I agree! The best thing to do here would probably be to copy the release notes that you've linked to the release itself, ideally automatically. Fiddling with the release process is pretty difficult though since it's difficult to test, and I suspect this'll require some well-crafted shell commands and such to get right which I'm not myself 100% sure of.

**Comment by rockwotj** [comment]
Maybe in the meantime having a single link to release file is a good middle ground?

**Comment by bjorn3** [comment]
Rust has a bot which copies the release notes from RELEASES.md into github releases I believe. Maybe the same could be done for Wasmtime?

**Comment by alexcrichton** [comment]
You wouldn't happen to have a link on-hand to how this is integrated in to rust-lang/rust, would you? I'm not sure how to configure this all myself.

**Comment by bjorn3** [comment]
Seems to be part of triagebot: https://github.com/rust-lang/triagebot/tree/master/src/changelogs Should be possible to port it to github actions though.

**Comment by alexcrichton** [comment]
Ok I think this will be fixed by https://github.com/bytecodealliance/wasmtime/pull/7405
