### ISSUE TITLE
wit-bindgen: Only emit error type impls in one place

### ISSUE THREAD

**Issue by elliottt** [bytecodealliance/wasmtime#7074]
#### Feature

When a type is used in an error position in a `result` in multiple interfaces, it gets an `impl std::error::Error` definition in each module that it's used in. It should only get a single impl in the module that defines it instead.

#### Benefit

Error type reuse would be easier between wit interfaces.

**Comment by alexcrichton** [comment]
Ah ok I don't think that duplicate impls are generated, just a confusing rustc error message -- this should be fixed by https://github.com/bytecodealliance/wasmtime/pull/7075
