### ISSUE TITLE
"dev" release URL no longer present

### ISSUE THREAD

**Issue by kripken** [bytecodealliance/wasmtime#714]
Emscripten CI has been downloading https://github.com/CraneStation/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz (which I see github redirects to https://github.com/bytecodealliance/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz) for testing, but that seems to have been removed in the latest release from an hour ago. And looking in https://github.com/bytecodealliance/wasmtime/releases there don't seem to be binary builds in the assets for "dev" anymore.

Was that intentional? (If so I guess we'll switch to a pinned release.)

**Comment by tschneidereit** [comment]
Oh huh, that was definitely not intentional, thank you for reporting it!
We'll look into what's going on and restore the release

>

**Comment by alexcrichton** [comment]
I think this likely may have been a hiccup in automation, looks like it's back!
