### ISSUE TITLE
[wasmtime-wasi] StdinStream and StdoutStream are not publicly accessible

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/wasmtime#7149]
I'm updating some code from Wasmtime 13 to the `main` branch, and noticed that it does not appear to be possible to implement `StdinStream` or `StdoutStream` outside of `wasmtime-wasi` given that the `stdio` module is private and those traits are not re-exported anywhere.  Is this intentional?  If so, is there some other way to e.g. connect stdin to an arbitrary `AsyncReadStream`?

If it's not intentional, I'd be happy to open a PR to make those traits public.

**Comment by alexcrichton** [comment]
Oops indeed that's a bug, a PR sounds good!
