### ISSUE TITLE
Optionally print backtraces after error

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#716]
When I run `cargo run --package wasmtime-cli --bin wast -- --enable-simd -d tests/spec_testsuite/proposals/simd/simd_conversions.wast` I see the following error (as I expect):
```
for directive on tests/spec_testsuite/proposals/simd/simd_conversions.wast:3:1

Caused by:
    0: Failed to setup a module
    1: Validation error: module did not validate: Unknown 0xfd opcode (at offset 629)
```

The error chain printing is great but I thought I would be able to add the actual backtrace to this output by setting `RUST_BACKTRACE=1` in the environment. Unfortunately, I am either doing this wrong or we need to add some code to `src/wast.rs`, `src/wasmtime.rs`, and `src/wasm2obj.rs`. @alexcrichton, @joshtriplett: any thoughts on this?

**Comment by alexcrichton** [comment]
I believe that if you use the nightly toolchain and `RUST_BACKTRACE=1` this should work? Can you try testing that out and see if it produces a good enough backtrace for your use case?

**Comment by abrown** [comment]
Cool, that worked!

```
cargo +nightly run --package wasmtime-cli --bin wast -- --enable-simd -d tests/spec_testsuite/proposals/simd/simd_conversions.wast
```
