### ISSUE TITLE
riscv64: Improve `scalar_to_vector` codegen for constants

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#7189]
👋 Hey,

This is a fairly simple improvement. Cranelift's [`scalar_to_vector` instruction](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/trait.InstBuilder.html#method.scalar_to_vector) grabs a scalar value and places it at the bottom of a vector register.

We translate this into the [`vmerge.vxm` instruction](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#1115-vector-integer-merge-instructions) in the RISC-V backend.

This is all fairly ok, but we don't have a rule to match the `vmerge.vim` instruction that can place an immediate value instead of a register.

Implementing this should be fairly simple, we can create a rule similar to the [existing ones](https://github.com/bytecodealliance/wasmtime/blob/fef8a90f258483ac6c2e470d3de277a743d5d392/cranelift/codegen/src/isa/riscv64/lower.isle#L2340-L2353) but using a `imm5_from_value` extractror:
```
(rule 2 (lower (has_type (ty_vec_fits_in_register ty) (scalar_to_vector (imm5_from_value x))))
```

This `imm5_from_value` extractor doesn't exist yet, but we already have an [equivalent in the `replicated_imm5` extractor](https://github.com/bytecodealliance/wasmtime/blob/fef8a90f258483ac6c2e470d3de277a743d5d392/cranelift/codegen/src/isa/riscv64/inst.isle#L1837C33-L1837C33). It should be fairly easy to extract that into it's own separate extractor for use in this new rule.

See the existing `uimm5_from_value` extractor for help.

If anyone needs help working on this issue let me know!

**Comment by BieVic** [comment]
Hey! I'm fairly new to Cranelift but would like to give it a try.

**Comment by afonso360** [comment]
Awesome 🎉 Let me know if you need any help getting started!
