### ISSUE TITLE
Don't run full fuzz corpora in CI

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#728]
Our fuzz corpora have grown too big to run the whole thing in CI. It's taking too long.

Instead, we should sample N files from each corpus and run those over our target. This will require some small tweaks to `cargo fuzz`: https://github.com/rust-fuzz/cargo-fuzz/issues/196

**Comment by alexcrichton** [comment]
@fitzgen I think this is done now, right?

**Comment by fitzgen** [comment]
Yes
