### ISSUE TITLE
Cannot (apparently) supply import callbacks with a namespace prefix

### ISSUE THREAD

**Issue by autodidaddict** [bytecodealliance/wasmtime#729]
The WebAssembly modules that I'm working with all import their imported functions from a specific namespace. After a lengthy search trying to find `Callback` implementation examples, I found the [multi](https://github.com/bytecodealliance/wasmtime/blob/master/crates/api/examples/multi.rs) sample. This shows that the wat is _not_ utilizing a namespace for the import:

```
(func $f (import "" "f") (param i32 i64) (result i64 i32))
```

When I look at the definitions for `FuncType`, `Func`, and `Extern`, there's no apparent way to specify the namespace definition for the function that resides on the `Callback` trait object.

Further, it doesn't even appear as though the function _name_ is being matched. In the wat file, the import is named `f`, but there's nothing visible in the API that is doing a match on this name. The only thing the uninformed reader (e.g. me) is left to assume is that imports are being satisfied _by index alone_ and that the runtime must specify the imports in the extern list in the exact same order in which they are specified in the wasm module... which is error-prone and brittle.

I'm hoping that I'm missing some kind of implicit magic that is doing this function mapping, and would appreciate a link to the relevant parts of the API that I need in order to specify these mappings.

**Comment by autodidaddict** [comment]
It looks like this is what's happening ("magic" via assuming the extern list is provided in the same order in which the imports appear in the wasm module):

https://github.com/bytecodealliance/wasmtime/blob/39e57e3e9ac9c15bef45eb77a2544a7c0b76501a/crates/api/src/instance.rs#L72

The `zip` is going to run through the list of module imports and pair them index-wise with the list of externs the developer supplied. Using this approach, it won't even validate if the externs are in the same namespace as the ones the module is expecting.

**Comment by alexcrichton** [comment]
Thanks for the report! We're definitely missing lots of documentation on the API, and we're working on that! https://github.com/bytecodealliance/wasmtime/issues/708 is a summary of high-level changes planned and https://github.com/bytecodealliance/wasmtime/issues/727 is a proposal to improve the experience with `Instance::new`

Currently this is actually supported today, albeit in a bit of wonky fashion. The list of `Extern` items passed to `Instance::new` is expected to match up 1:1 with the list of imports from `module.imports()`. Name resolution isn't performed by `Instance::new` as a result since the imports are just lined up as they're listed in the original file.

**Comment by autodidaddict** [comment]
Ok, so I'm hoping that it'll get easier with the ergonomic changes. Somewhat related is how does one give the callback the ability to read/write the memory of an instance? There's no sample for that as well, and `HostRef` and `Instance` and `Memory` are all `!Sync` and `!Send`, and since the `Instance` constructor moves the extern trait objects inside, I wouldn't even know how to set the instance as a field on the callback struct even if it were thread-safe.

**Comment by alexcrichton** [comment]
That's a good question! Currently I don't think there's a great answer, you'll need to `Rc`/`RefCell` your way to success, but it's deifnitely somethign we should improve!

**Comment by yurydelendik** [comment]
> Name resolution isn't performed by Instance::new as a result since the imports are just lined up as they're listed in the original file

minor correction: as they are defined by the Module::imports()
