### ISSUE TITLE
wasmtime 14.0.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [bytecodealliance/wasmtime#7323]
With 14.0.0 release, the `wasmtime xx.wasm --invoke xx` seems not working

relates to https://github.com/Homebrew/homebrew-core/pull/151945

**Comment by chenrui333** [comment]
looks like the error status also has some issue as well

```
  ==> /usr/bin/clang hello.c -I/opt/homebrew/Cellar/wasmtime/14.0.0/include -L/opt/homebrew/Cellar/wasmtime/14.0.0/lib -lwasmtime -o hello
  ==> ./hello
  Assertion failed: (file != NULL), function main, file hello.c, line 33.
  Initializing...
  Error: wasmtime: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: nil
```

**Comment by alexcrichton** [comment]
Thanks for the report! This was a feature that was changed [in the 14.0.0 release](https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#1400), specifically the way CLI arguments are parsed.

Previously where `wasmtime xx.wasm --invoke xx` worked you'll now need to do `wasmtime --invoke xx xx.wasm`. If you change to placing the Wasmtime-related arguments before the wasm module itself, does it work for you?

**Comment by chenrui333** [comment]
@alexcrichton that is not work for me

```
==> /opt/homebrew/Cellar/wasmtime/14.0.0/bin/wasmtime --invoke sum 1 2 /private/tmp/wasmtime-test-20231022-20896-1uab29w/sum.wasm
Error: failed to read file: 1

Caused by:
    No such file or directory (os error 2)
```

this used to work `==> /opt/homebrew/Cellar/wasmtime/14.0.0/bin/wasmtime /private/tmp/wasmtime-test-20231022-20896-1uab29w/sum.wasm --invoke sum 1 2`

**Comment by chenrui333** [comment]
and what about this issue?

```
    Minitest::Assertion: Expected: 0
    Actual: nil
```

**Comment by alexcrichton** [comment]
I believe you'll change that to `wasmtime --invoke sum foo.wasm 1 2` to work correctly. Arguments to the wasm come after the wasm, not before. Arguments to Wasmtime must come before the wasm.

I don't know what minitest is or what that assertion is about, so sorry I can't help you there.

**Comment by chenrui333** [comment]
> I believe you'll change that to `wasmtime --invoke sum foo.wasm 1 2` to work correctly. Arguments to the wasm come after the wasm, not before. Arguments to Wasmtime must come before the wasm.

thanks, this helps my test. appreciate it.
