### ISSUE TITLE
No release notes for 14.0.1

### ISSUE THREAD

**Issue by brettcannon** [bytecodealliance/wasmtime#7342]
https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md only refers to 14.0.0 and https://github.com/bytecodealliance/wasmtime/releases/tag/v14.0.1 has the typical boilerplate that just says who triggered the release.

**Comment by bjorn3** [comment]
Looks like adding a changelog entry was forgotten. The only change was https://github.com/bytecodealliance/wasmtime/pull/7333 which is a bugfix to Cranelift that doesn't get hit by Wasmtime. We don't have a way to release Cranelift and Wasmtime independently so a Wasmtime release was made too.

**Comment by alexcrichton** [comment]
Oops, thanks for the reminder though!
