### ISSUE TITLE
curl install broken

### ISSUE THREAD

**Issue by monperrus** [bytecodealliance/wasmtime#7377]
Hi all,

FYI curl-based installation is broken with 404
```
± curl https://wasmtime.dev/install.sh -sSf | bash
  Installing latest version of Wasmtime (https://api.github.com/repos/bytecodealliance/wasmtime/releases/126307703)
    Checking for existing Wasmtime installation
    Fetching archive for Linux, version https://api.github.com/repos/bytecodealliance/wasmtime/releases/126307703
https://github.com/bytecodealliance/wasmtime/releases/download/https://api.github.com/repos/bytecodealliance/wasmtime/releases/126307703/wasmtime-https://api.github.com/repos/bytecodealliance/wasmtime/releases/126307703-x86_64-linux.tar.xz 
curl: (22) The requested URL returned error: 404                              

Error: Could not download Wasmtime version 'https://api.github.com/repos/bytecodealliance/wasmtime/releases/126307703'. See https://github.com/bytecodealliance/wasmtime/releases for a list of available releases
```

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report, can you detail what system you're using? It may be that your system utilities such as `curl` or `cut` aren't behaving as the script is expecting.

**Comment by monperrus** [comment]
I'm running Ubuntu 22.04.3 LTS.
Thanks!

**Comment by alexcrichton** [comment]
Can you execute [these lines manually](https://github.com/bytecodealliance/wasmtime.dev/blob/fa746b4c20126744a892277819f800cbd14255fa/install.sh#L43-L45) and paste their output? Ubuntu 22.04 is pretty standard so I'm not sure why they'd be going wrong.

**Comment by monperrus** [comment]
```
  curl --silent "https://api.github.com/repos/bytecodealliance/wasmtime/releases/latest" | \
    grep tag_name | \
    cut -d '"' -f 4
https://api.github.com/repos/bytecodealliance/wasmtime/releases/126802444
```

seems pretty OK

**Comment by alexcrichton** [comment]
Hm so that should print `v14.0.2` at this time on the terminal, not a URL, so that's the issue. Can you paste the output of the `curl` command alone perhaps?

**Comment by alexcrichton** [comment]
Ah I'm not sure why but your `curl` is printing compact JSON where the script is expecting "pretty" JSON. I'm not sure why that's happening, but that's why the script is failing.

**Comment by monperrus** [comment]
Github sends compact JSON.
As far as I know, curl has no capability for pretty-printing json.
If we want to have pretty JSON, we need to send it through json_pp or jq.

**Comment by cfallin** [comment]
Weirdly, exactly that `curl` command returns formatted JSON for me; I wonder if we're hitting some sort of A/B test, or if there's some middlebox (compressing proxy or similar) somewhere in your network path, or...?

IIRC, one of the considerations against using `jq` was that it would have to be installed on the user's machine, and `install.sh` is meant to work in as many places as possible without unnecessary dependencies. 

I wonder, though, if we can craft a sed regex or similar that grabs the tag name out of a single line or multiline JSON?

**Comment by monperrus** [comment]
> IIRC, one of the considerations against using jq was that it would have to be installed on the user's machine

I see.

> Weirdly, exactly that curl command returns formatted JSON for me

What! This is very surprising. I really don't see which component in the stack does that.

> I wonder, though, if we can craft a sed regex or similar that grabs the tag name out of a single line or multiline JSON?

brittle. honestly, `jq` would be much better. The target users of wasmtime are probably tech-savvy enough to install jq by themselves if need be.

**Comment by monperrus** [comment]
I confirm that changing `install.sh` to ` | json_pp` works!

```
  curl --silent "https://api.github.com/repos/bytecodealliance/wasmtime/releases/latest" | json_pp | \
    grep tag_name | \
    cut -d '"' -f 4
```

With this fix I have wasmtime on my machine, thanks!

**Comment by cfallin** [comment]
> brittle. honestly, `jq` would be much better. The target users of wasmtime are probably tech-savvy enough to install jq by themselves if need be.

A consideration when developing infrastructure like this is that the machines we may run on might not look like our own developer machines: for example, we want it to be easy to install `wasmtime` on a fresh virtual machine, server, CI environment, minimal Docker container, etc. The requirement to install JSON-munging tools would be a bit of a speedbump causing folks to trip; the use of a shell script and core Unix utilities only (plus curl) is pretty intentional here.

It's too bad there's no API endpoint that gives us exactly the latest release tag and nothing else. I wonder if some automation could e.g. put some file in place that helps with this -- @alexcrichton, what would you think about something in the release process that updates a `latest-release.txt` in the static site so one could do `curl https://wasmtime.dev/latest-release.txt`?

**Comment by bjorn3** [comment]
Using `| sed 's/.*tag_name": *"//' | sed 's/".*//'` instead of `| grep tag_name | cut -d '"' -f 4` should work for both pretty and unpretty json.

**Comment by alexcrichton** [comment]
I like the idea of `latest-release.txt` but I don't know how to do that easily off the top of my head. I'd be tempted to go with @bjorn3's suggestion first if we can, but that should be confirmed to work on macOS since I know that they've got a BSD version of sed (or something like that) and it's different from the GNU version sometimes.

**Comment by cfallin** [comment]
Unfortunately the sed command lines above don't work on macOS -- with pretty JSON, the line containing the tag is edited to just the tag, but a bunch of other lines remain:

```
cfallin@fastly2:~% curl --silent "https://api.github.com/repos/bytecodealliance/wasmtime/releases/latest" | sed 's/.*tag_name": *"//' | sed 's/".*//' | head -n 30
{
  [ lots of blank lines ]
  },

v14.0.4
```

It appears that BSD sed doesn't do multiline edits -- the man-page says "Normally, sed cyclically copies a line of input, not including its terminating newline character, ..." (and I can't find another flag that would override that).

So it appears we're back to
* Figure out why the JSON is compacted when some folks fetch it and not others, or
* Craft a grep+sed invocation that works on all platforms with both kinds of inputs, or
* Create an endpoint like `latest-release.txt` (or find one somewhere in the GitHub API)

**Comment by cfallin** [comment]
That worked for me -- just sent a PR for this, thanks!
