### ISSUE TITLE
Command Order Issue: Lack of Output with 'wasmtime file.wasm --invoke main'

### ISSUE THREAD

**Issue by XinyuShe** [bytecodealliance/wasmtime#7382]
### Steps to Reproduce

1. Execute the following command: `wasmtime a-test.wasm --invoke main`
2. Observe the lack of output.

### Expected Results

I expect the command `wasmtime a-test.wasm --invoke main` to execute the WebAssembly file and produce the correct output.

### Actual Results

The command `wasmtime a-test.wasm --invoke main` does not produce any output, while  `wasmtime a-test.wasm --invoke main` does.

### Versions and Environment

- Wasmtime version: 14.0.1
- Operating system: Ubuntu 22.04.3 LTS(GNU/Linux 5.15.0-79-generic x86_64)

### Extra Info

Explain that you noticed a difference in behavior when changing the order of the arguments. Mention that the issue is specific to the command order and that `wasmtime --invoke main a-test.wasm` works as expected.
![E}POCVS_S4L%E_0NN0L0MOO](https://github.com/bytecodealliance/wasmtime/assets/60457190/3c578187-5972-467b-ba26-df23d082d076)

**Comment by bjorn3** [comment]
If the `--invoke` is after `a-test.wat`, it will be passed as argument to the wasm module rather than interpreted by Wasmtime.

**Comment by tschneidereit** [comment]
We're working on a fix for this. See [here](https://github.com/bytecodealliance/wasmtime/issues/7336#issuecomment-1781511239) for details.

**Comment by alexcrichton** [comment]
As mentioned by @bjorn3 this is an intended change in Wasmtime 14 relative to prior verisons. More information about this is available at https://github.com/bytecodealliance/wasmtime/issues/7384 and that is going to track further developments here so I'm going to close this in favor of that. Thanks for the report though!
