### ISSUE TITLE
There is a bug in "invoke_func" function.

### ISSUE THREAD

**Issue by liutao-liu** [bytecodealliance/wasmtime#7401]
### Test Case
Na
### Steps to Reproduce

When I input "target/debug/wasmtime run my.wasm --invoke my_func_name 1.1" in the command line, i got an error "invalid digit found in string".

### Expected Results

The entered parameter "1.1" can be parsed successfully.

### Actual Results

Got an error："invalid digit found in string"。

### Versions and Environment

Wasmtime version or commit: wasmtime-cli 13.0.0

Operating system: Ubuntu 20.04

Architecture: Na

### Extra Info

**【Root Cause】**
https://github.com/bytecodealliance/wasmtime/blob/519808fc5c2565f11f9b6a7f5fe3d2385f9f95e8/src/commands/run.rs#L507

The function `invoke_func`  attempted to cast a floating-point string to F32/F64,which is actually a u32/u64 type.

**【Solution】**
I think this conversion should be written like this：
``` rust
let val: f32 = val.parse()?;
let val = val.to_bits();

**Comment by bjorn3** [comment]
You can use .to_bits() on f32 to avoid unsafe code.

**Comment by liutao-liu** [comment]
> You can use .to_bits() on f32 to avoid unsafe code.

You're right, I've revised it as you suggested.

**Comment by alexcrichton** [comment]
Can you share the WebAssembly module that is being run? If the argument is of type `i32` in wasm then it doesn't accept a floating point number as an argument (e.g. it won't call `to_bits()`).

**Comment by liutao-liu** [comment]
> Can you share the WebAssembly module that is being run? If the argument is of type `i32` in wasm then it doesn't accept a floating point number as an argument (e.g. it won't call `to_bits()`).

(module  (type $f_t (func (param f32) (result f32)))  (func $f_f (type $f_t) (param $a f32) (result f32)    local.get $a)  (export "ret_f32" (func $f_f)))

**Comment by alexcrichton** [comment]
Can you paste the full wasm module? Or upload it? The input you have provided does not have a function export called `my_func_name` which you're trying to invoke from the command line

**Comment by liutao-liu** [comment]
> Can you paste the full wasm module? Or upload it? The input you have provided does not have a function export called `my_func_name` which you're trying to invoke from the command line

(module (type $f_t (func (param f32) (result f32))) (func $f_f (type $f_t) (param $a f32) (result f32) local.get $a) (export "my_func_name" (func $f_f)))

**Comment by alexcrichton** [comment]
Thanks for the clarification, this should be fixed in https://github.com/bytecodealliance/wasmtime/pull/7440
