### ISSUE TITLE
mpk: some GitHub CI runners have MPK enabled but fail to run MPK code

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#7445]
GitHub CI runners are showing some strange behavior: on certain runners (unknown which ones), the CPUID bits claim that MPK is supported, but running any MPK code (e.g., `RDPKRU`) causes a `SIGILL` crash. #7446 disables MPK until this is resolved.

Some instances of this failure:
- https://github.com/bytecodealliance/wasmtime/actions/runs/6721387888/job/18267026371#step:15:3283
- https://github.com/bytecodealliance/wasmtime/actions/runs/6714337681/job/18247418366?pr=7335#step:15:3280

**Comment by alexcrichton** [comment]
Nice! Seems like this should be easy enough to manage by updating the supported check to require Intel CPUs and filter out AMD ones then?

**Comment by abrown** [comment]
Yeah, it appears that Intel and AMD differ on what is presented in that `CPUID` leaf:
- https://github.com/torvalds/linux/blob/8bc9e6515183935fa0cccaf67455c439afe4982b/arch/x86/include/asm/cpufeatures.h#L380-L383
- https://github.com/torvalds/linux/blob/8bc9e6515183935fa0cccaf67455c439afe4982b/tools/testing/selftests/mm/pkey-x86.h#L65C1-L66
- https://github.com/torvalds/linux/blob/8bc9e6515183935fa0cccaf67455c439afe4982b/tools/testing/selftests/kvm/include/x86_64/processor.h#L122-L155

**Comment by nagisa** [comment]
I can reproduce this issue locally reliably on my 2nd generation EPYC and can test things out it helps anyway.
