### ISSUE TITLE
There is another bug in "invoke_func" function

### ISSUE THREAD

**Issue by liutao-liu** [bytecodealliance/wasmtime#7467]
Similar to this [issue](https://github.com/bytecodealliance/wasmtime/issues/7401), ```nan:0x200000``` and ```-nan:0x200000``` cannot be parsed, and the same error message "invalid float literal" is reported.

In addition, ```-nan``` is parsed into ```nan```, which is incorrect. ```nan``` and```-nan``` represent different meanings, and their bits are different.

**Comment by alexcrichton** [comment]
Yes this is expected as the CLI uses the Rust standard libray to parse floats right now, which is not the same as the text format of WebAssembly.

**Comment by liutao-liu** [comment]
> Yes this is expected as the CLI uses the Rust standard libray to parse floats right now, which is not the same as the text format of WebAssembly.

Is that going to fix the problem?

**Comment by alexcrichton** [comment]
Sorry I'm not sure if I understand your question? 

To clarify what I'm saying, the parsing of f32/f64 in the CLI isn't specified right now in Wasmtime and it's "whatever rust libstd happens to implement". The syntax you're describing here I think is probably coming from the text format of WebAssembly, however, which isn't plumbed into this part of Wasmtime right now. Assuming you want the same text format of WebAssembly then yes I believe that will resolve this issue.

**Comment by liutao-liu** [comment]
Yes brother, I shouldn't describe it as a problem, this format is from webAssembly. It would be great if wasmtime should support this format in the future.
