### ISSUE TITLE
wasmtime 15.0.0 - how to build a static library?

### ISSUE THREAD

**Issue by osokin** [bytecodealliance/wasmtime#7567]
Hi,

I'm using `libwasmtime`, C API of `wasmtime`, to build a `wasm` module for NGINX Unit.
Previously it worked well by specifying `crates/c-api/Cargo.toml` configuration for `cargo`.
Since 15.0.0 that doesn't work anymore.  Could you guide me how can I build a static library
for the recent version?

Thank you.

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/pull/7341 changed the layout. Looks like you now have to specify `crates/c-api/artifact/Cargo.toml` instead.

**Comment by osokin** [comment]
Thanks for the quick reply, @bjorn3!   That works!

**Comment by pchickey** [comment]
Instead of using `--manifest-path whatever/Cargo.toml`, use `-p wasmtime-c-api` for your build scripts to be resilient against these sorts of changes.

**Comment by osokin** [comment]
> Instead of using `--manifest-path whatever/Cargo.toml`, use `-p wasmtime-c-api` for your build scripts to be resilient against these sorts of changes.

Thanks for the update, @pchickey!  I'm going to update the build procedure according your recommendations.
