### ISSUE TITLE
How can I capture stdout and stderr from a WebAssembly module generated by Emscripten or WASI  in Python?

### ISSUE THREAD

**Issue by skhaz** [bytecodealliance/wasmtime#7581]
I'd like to know if it's possible to have hooks/handlers for stdout and stderr using Python (or Go, or JavaScript), so that I can execute a `.wasm` and save the stdout/err in a variable.

**Comment by yfaming** [comment]
[`WasiConfig`](https://bytecodealliance.github.io/wasmtime-py/#wasmtime.WasiConfig) in [wasmtime-py](https://github.com/bytecodealliance/wasmtime-py) might be helpful. We can assign a path to `stdin_file/stdout_file/stderr_file`. It seems we can only redirect stdio into separate file(s).

Here is a simple example:

```python
# pip install wasmtime

from wasmtime import *

def main():
    config = WasiConfig()
    config.stdout_file = "stdout.txt"

    linker = Linker(Engine())
    linker.define_wasi()
    store = Store(linker.engine)
    store.set_wasi(config)

    module = Module.from_file(linker.engine, "wasi_hello.wasm")
    instance = linker.instantiate(store, module)
    instance.exports(store)["_start"](store)

if __name__ == "__main__":
    main()
```

**Comment by skhaz** [comment]
Thank you so much.

I was using file to do this, I thought that was another way though.

**Comment by yfaming** [comment]
wasmtime itself (in Rust) supports setting stdin/stdout via [WasiCtxBuilder](https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/sync/struct.WasiCtxBuilder.html). We can pass any struct implemented [WasiFile](https://docs.rs/wasi-common/latest/wasi_common/file/trait.WasiFile.html). Unfortunately, wasmtime-py does not support it ye.
