### ISSUE TITLE
wasmtime compile support for components

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/wasmtime#7605]
#### Feature

`wasmtime compile` does not currently support component binaries.

#### Benefit

The main use case I wanted to test here was component performance benchmarking, but this would of course be useful to component startup time and performance in general.

#### Implementation

I do not.

#### Alternatives

Suggestions with regards to alternatives for benchmarking workflows specifically would be very welcome.

**Comment by alexcrichton** [comment]
Could you gist the error you're seeing? This should be supported already and locally I'm running:

```
wasmtime compile -Wcomponent-model <(echo "(component)")
```

which generates 11.cwasm locally in my current directory
