### ISSUE TITLE
aarch64: `WasmFault` calculated with incorrect Wasm address

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#7624]
### Test Case

See `wasm_fault_address_reported_from_mpk_protected_memory` in #7622

### Steps to Reproduce

* Checkout the PR (e.g., `gh pr checkout 7622`)
* On an aarch64 machine, run `cargo test -- traps::wasm_fault_address_reported_from_mpk_protected_memory`

### Expected Results

The test to pass.

### Actual Results

The test fails because the error message contains `0xdeadbee8` instead of the expected `0xdeadbeef`. This likely is an endianness issue causing the calculation of `WasmFault` (see `Store::wasm_fault`, e.g.) to be slightly off.

### Versions and Environment

Wasmtime version or commit: #7622

Operating system: Reproduced in the "Linux arm64" CI runner ([here](https://github.com/bytecodealliance/wasmtime/actions/runs/7062145323/job/19225342835#step:18:2446))

Architecture: aarch64

**Comment by alexcrichton** [comment]
Ah this is expected platform-specific behavior (I think we raced with my [comment](https://github.com/bytecodealliance/wasmtime/pull/7622#issuecomment-1836545056)), so I'm going to close this.
