### ISSUE TITLE
A difference between windows and linux?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [bytecodealliance/wasmtime#7633]
### Test Case
The test.c file is uploaded as 
[test-c.txt](https://github.com/bytecodealliance/wasmtime/files/13560062/test-c.txt)

The test.wasm file is uploaded as 
[test-wasm.txt](https://github.com/bytecodealliance/wasmtime/files/13560063/test-wasm.txt)

### Steps to Reproduce
We create a normal file Data/hello.txt and write some initial content into the file.
using command `wasmtime run --dir=./Data test.wasm` to execute the wasm file.

### Actual Results
In linux, wasmtime do not write any bytes into the file and prints:
```
Successfully get the file fd.
Current offset: 0
Wrote 0 bytes to the file.
File Size: 30 bytes
Leave snapshot.
```

In windows, wasmtime writes null characters (\u0000) into the file and prints:
```
Successfully get the file fd.
Current offset: 0
Wrote 0 bytes to the file.
File Size: 50 bytes
Leave snapshot.
```

There is a difference between executing the wasm file in windows and linux.
Maybe in linux, this could be a bug?

### Versions and Environment
Ubuntu 20.04 (amd64)
Windows 10 (x86_64)
wasmtime 13.0.0

**Comment by pchickey** [comment]
Thanks for the report. In the future, can you add to your reports the traces given when WASMTIME_LOG=wasmtime_wasi=trace is set in your host environment?
