### ISSUE TITLE
component-model: unknown binary version and encoding combination: 0xd and 0x1

### ISSUE THREAD

**Issue by JMLX42** [bytecodealliance/wasmtime#7653]
### Test Case

`add.wasm`: [add.zip](https://github.com/bytecodealliance/wasmtime/files/13602970/add.zip)

### Steps to Reproduce

```rust
    let engine = Engine::default();
    let module = Module::from_binary(&engine, &data).expect("Failed to load module");
    let mut store = Store::new(&engine, ());
    let instance = Instance::new(&mut store, &module, &[])?;
    let answer = instance
        .get_func(&mut store, "add")
        .expect("`add` was not an exported function");
```

### Expected Results

`Module::from_binary()` returns a `Ok(Module)`.

### Actual Results

Panic!

```
thread 'main' panicked at crates/wasm2openapi/src/main.rs:186:54:
Failed to load module: failed to parse WebAssembly module

Caused by:
    Invalid input WebAssembly code at offset 0: unknown binary version and encoding combination: 0xd and 0x1, note: encoded as a component but the WebAssembly component model feature is not enabled - enable the feature to allow component validation
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Versions and Environment

For the `add.wasm` component:

```toml
cargo-component-bindings = "0.5.0"
```

For the host app:

```toml
wasmtime = { version = "15.0.1", features = ["component-model"] }
```

Operating system: Ubuntu 22.04

Architecture: 64bit

### Extra Info

Trying to dynamically call WASM Component exported functions via HTTP: https://github.com/JMLX42/wasm2openapi

**Comment by pchickey** [comment]
Set https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.wasm_component_model

**Comment by JMLX42** [comment]
> Set https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.wasm_component_model

Thank you @pchickey !

Yet as a Rust developer, when I read the "the WebAssembly component model feature is not enabled" part of the error message, I thought of a Cargo feature. May I suggest to make the error message more specific?

**Comment by JMLX42** [comment]
Ah... lots of plumbing that might not be very future-proof. Still people will now find this issue at least I guess!

**Comment by pchickey** [comment]
Its also worth noting that we will be turning all of these features on by default when we ship a completed WASI Preview 2 in the Wasmtime 17 release. So hopefully you are one of the last to run into this.
