### ISSUE TITLE
JIT compiler support with `#[no_std]` for embedded devices ?

### ISSUE THREAD

**Issue by LordCasser** [bytecodealliance/wasmtime#7700]
There is just a use case, I'd like to make the wasm JIT compiler a part of VM-OS.

**Comment by alexcrichton** [comment]
You'll find some more discussion about this [here](https://github.com/bytecodealliance/wasmtime/issues/7311), but I'll also want to point out [this section](https://docs.wasmtime.dev/stability-platform-support.html#what-about-no_std) of our documentation. If you have a target you're interested in supporting we'd love to discuss more, but `#![no_std]` won't work "out of the box" today.

In terms of bare-bones requirements Wasmtime at this time requires virtual memory (e.g. an MMU). I've got a branch I haven't upstreamed which distills Wasmtime's base runtime requirements to [this C API](https://github.com/alexcrichton/wasmtime/blob/470ed8ef8505d190d88620362c7e71c697a3427a/crates/runtime/src/sys/custom/capi.rs) which would need to be supported by the system.

**Comment by alexcrichton** [comment]
Wasmtime now supports no_std itself and otherwise having Cranelift support it is tracked at https://github.com/bytecodealliance/wasmtime/issues/1158, so I'm going to close this.
