### ISSUE TITLE
Can't use LLDB to attach to wasmtime 16 anymore

### ISSUE THREAD

**Issue by CryZe** [bytecodealliance/wasmtime#7720]
Attaching to wasmtime with LLDB to step through Rust code in the WebAssembly module stopped working after switching to wasmtime 16. It still worked perfectly fine on wasmtime 15.0.1. These are all the changes on my side (i.e. only version bumps): 
https://github.com/LiveSplit/livesplit-core/commit/23e31b3b7edb2badaa01050e9e946404e2e98610

I don't see anything in the changelog indicating that something changed regarding the DWARF support.

**Comment by alexcrichton** [comment]
Do you perhaps depend on Wasmtime with `default-features = false`? If that's the case the support for this was moved behind a `debug-builtins` feature which will need to be enabled.

**Comment by CryZe** [comment]
Yeah that seems to fix it. However it seems like that this is not documented at all:
1. The changelog doesn't mention it.
2. The crate features section doesn't mention it: https://docs.rs/wasmtime/16.0.0/wasmtime/index.html#crate-features
3. The `debug_info` function on the `Config` isn't feature gated by it, nor mentions it: https://docs.rs/wasmtime/16.0.0/wasmtime/struct.Config.html#method.debug_info

**Comment by alexcrichton** [comment]
Good point! I've pushed https://github.com/bytecodealliance/wasmtime/pull/7736 to add some docs.
