### ISSUE TITLE
Global sharable memory/store/engine support?

### ISSUE THREAD

**Issue by stevefan1999-personal** [bytecodealliance/wasmtime#7724]
I'm trying to implement the JS interface to WebAssembly using wasmtime with my own little JS engine project but I came across this

> A [Memory](https://webassembly.github.io/spec/js-api/#memory) object represents a single [memory instance](https://webassembly.github.io/spec/core/exec/runtime.html#memory-instances) which can be simultaneously referenced by multiple [Instance](https://webassembly.github.io/spec/js-api/#instance) objects. Each [Memory](https://webassembly.github.io/spec/js-api/#memory) object has the following internal slots:
> 
> [[Memory]] : a [memory address](https://webassembly.github.io/spec/core/exec/runtime.html#syntax-memaddr)
> 
> [[BufferObject]] : an [ArrayBuffer](https://tc39.github.io/ecma262/#sec-arraybuffer-objects) whose [Data Block](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-data-blocks) is [identified with](https://webassembly.github.io/spec/js-api/#identified-with) the above memory address
> 

(https://webassembly.github.io/spec/js-api/#memories)

But if you look closely at https://docs.wasmtime.dev/api/wasmtime/struct.Memory.html#impl-Memory, you can see that the only way to create a `Memory` is by handing it a `Store`, but to get a `Store` you must first create it from an `Engine` and so I think there is currently no way to implement the required semantics the WebAssembly Spec needed me to do.

**Comment by bjorn3** [comment]
An `Engine` is meant to be created once at startup and then used on all threads. (You can still create multiple `Engine`s if you need different settings in different places.) The way to model the JS behavior would be to create a single `Store` for every thread running javascript. Be aware however that all things that are part of a `Store` can't get deallocated without deallocating the entire `Store`. As such you can easily run out of memory if you keep a `Store` around for the entire JS execution.

**Comment by alexcrichton** [comment]
I don't have much more to add over what @bjorn3 already mentioned (thanks!) other than the Rust API for `wasmtime` is intentionally different from the JS API to better suit Rust idioms and cater to Wasmtime's use cases. 

Otherwise though given that a `Store`-per-JS-thread should suffice I'm otherwise going to close this. Let us know though if you've got other questions!
