### ISSUE TITLE
how to build with source?

### ISSUE THREAD

**Issue by 0xfocu5** [bytecodealliance/wasmtime#7753]
I learned how to build from https://docs.wasmtime.dev/contributing-building.html
but i got error:
-> % cargo build                  
error: failed to load manifest for workspace member `~/wasmtime/crates/c-api/artifact`

Caused by:
  failed to load manifest for dependency `wasmtime-c-api-impl`

Caused by:
  failed to load manifest for dependency `wasi-cap-std-sync`

Caused by:
  failed to load manifest for dependency `wasi-common`

Caused by:
  failed to parse manifest at `~/cache/wasmtime/crates/wasi-common/Cargo.toml`

Caused by:
  error inheriting `wiggle` from workspace root manifest's `workspace.dependencies.wiggle`

Caused by:
  `dependency.wiggle` was not found in `workspace.dependencies`

**Comment by bjorn3** [comment]
Try `git submodule update --init`.

**Comment by 0xfocu5** [comment]
> Try `git submodule update --init`.

i tried it，but got the same error.

**Comment by 0xfocu5** [comment]
> > Try `git submodule update --init`.
> 
> i tried it，but got the same error.

It might be due to the cache issue, and it's working now. Thank you very much.
