### ISSUE TITLE
The `wasmtime::Store` type should be thread-safe

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#777]
As proposed in #708 the `Store` type in the wasmtime API should be thread-safe, meaning it should implement both `Send` and `Sync`. Currently, however, it has a few items that are not thread safe and/or need audits:

* ~~The [`global_exports`](https://github.com/bytecodealliance/wasmtime/blob/06be4b14956061a4231771912f85a98904b70cec/crates/api/src/runtime.rs#L340) field is an `Rc`-protected data structure used by wasmtime internals. I don't know myself what it would take to remove this, but @sunfishcode looks like he does in https://github.com/bytecodealliance/wasmtime/pull/390~~
* The [`signature_cache` field](https://github.com/bytecodealliance/wasmtime/blob/06be4b14956061a4231771912f85a98904b70cec/crates/api/src/runtime.rs#L341) requires interior mutability and currently uses a `RefCell`. While this could be switched to a `Mutex` I think it would be best to avoid this altogether. I don't personally know why this field exists, @yurydelendik do you know why it's here?
* The `context` field has a contained [`compiler` field](https://github.com/bytecodealliance/wasmtime/blob/06be4b14956061a4231771912f85a98904b70cec/crates/api/src/context.rs#L10) which has a number of issues. Namely `Rc` and `RefCell` are not thread safe (but can be swapped for `Arc`/`Mutex` if necessary), but the [underlying `Compiler` type](https://github.com/bytecodealliance/wasmtime/blob/06be4b14956061a4231771912f85a98904b70cec/crates/jit/src/compiler.rs#L41-L60) has a number of trait objects, raw pointers, etc, which would need auditing. I think the solution here is going to be making `Compiler` itself threadsafe by redesigning it's internals.

**Comment by yurydelendik** [comment]
`signature_cache` shall be a common storage across all imports/exports/module that are interact between each other to maintain common database of SignatureId -> Signature. The `Compiler` type contains `signatures` field to do the reverse operation, which is needed for codegen.

**Comment by DemiMarie-parity** [comment]
@alexcrichton why is this impossible?

**Comment by alexcrichton** [comment]
@DemiMarie-parity the way things are set up right now you instantiate `Instance` structures into a `Store`. The `Store` keeps a handle on each `Instance`, so effectively a `Store` stores each `Instance`. This is done to keep each `Instance` alive since we don't have a GC right now to otherwise understand when there are no references to an `Instance`.

`Instance`s themselves are fundamentally not `Sync` because operations like global get/set aren't atomic. They're ideally `Send`, however, but with the `Rc` that we're using for memory management that forces them to not be `Send`.

The current state of affairs is that basically `Store` stores enough instance-local information that it can't be shared across threads because instances can't be shared across threads. There may still be internal refactorings or possible designs to fix this, but overall our threading story isn't great right now unfortunately.

**Comment by DemiMarie-parity** [comment]
@alexcrichton what if we used `Arc` instead?  I imagine that reference count operations are not in hot paths.

**Comment by alexcrichton** [comment]
Unfortunatey it's not quite as easy as that. In Rust there's no way to statically have a reference counted type that's `Send` but not `Sync`, which is morally what we'd want here. The only static solution for that is to entirely remove the reference counting, but that doesn't jive well with the memory management that we have in wasmtime today.

Failing that we'd have to invent our own solution in wasmtime which is much more invasive than just using an `Arc` instead of an `Rc`, and I'm not really sure if that's even possible much less workable.

**Comment by DemiMarie-parity** [comment]
What would need to change to allow JIT-compiled code to be used by multiple threads simultaneously?

**Comment by DemiMarie-parity** [comment]
The first idea that comes to mind is to separate the JIT-compiled code (which is immutable) from the data (which is mutable).  So to execute some code, one would first need to compile it, which would return an immutable `CompiledBlob` object.  One would then need to create an `Instance` from the `CompiledBlob`.  Since a `CompiledBlob` is immutable, making it `Send + Sync` is trivial.

**Comment by alexcrichton** [comment]
Ah yes so sharing `Store` is its own issue but sharing compiled code is definitely something that we want to enable. Making `Module` both `Send` and `Sync` should be easier than making `Store` either `Send` or `Sync`, and that's largely just a matter of internal refactorings.

**Comment by yurydelendik** [comment]
FWIW wasm-c-api planed to shared a module between two stores via wasm_module_share/wasm_module_obtain , see https://github.com/WebAssembly/wasm-c-api/blob/master/example/threads.c#L34
