### ISSUE TITLE
How to access the instance's memory in a shared host function?

### ISSUE THREAD

**Issue by eigenein** [bytecodealliance/wasmtime#7786]
👋 Hi team,

I'm instantiating a long-lived `Engine` and `Linker`, and then I'm adding some host functions to the linker (Rust API). Some of these functions should receive a string as a parameter, so an offset and a length in a guest's memory, for example:

```rust
let mut linker = wasmtime::Linker::new(&engine);
linker.func_wrap("logging", "info",
    |mut caller: Caller<'_, ()>, (offset, size): (u32, u32)| {
        // How do I access instance's memory here and read from it?
    },
)?;
```

I could use a closure as suggested in https://github.com/bytecodealliance/wasmtime/issues/2491#issuecomment-742352722, but I'm going to support a plugin system, and a shared host function may be called from any plugin. Also, `Store` is short-lived, and I wouldn't like to re-instantiate a `Linker` together with the closures for every host-to-guest call

Should I put a reference to `Instance` or to the instance's `Memory` into the instance's `Store`? That smells a little, since `Caller` already contains `Store` and all the memories are already owned by `Store` – so that would effectively be making a loop of references. Am I missing something?

**Comment by alexcrichton** [comment]
There's an example for this [on the documentation of `Func::wrap`](https://docs.rs/wasmtime/latest/wasmtime/struct.Func.html#method.wrap) where the gist of it is:

```rust
    let mem = match caller.get_export("memory") {
        Some(Extern::Memory(mem)) => mem,
        _ => anyhow::bail!("failed to find host memory"),
    };
```

One option is to store a `Memory` in the `T` of `Store<T>` (i.e. replace the `()` you're using currently), but the easiest option is probably to call `caller.get_export(...)`

**Comment by eigenein** [comment]
@alexcrichton Thank you, just exactly what I needed and completely overlooked!
