### ISSUE TITLE
`utime()` does not accept a file descriptor under preview 2 (as found by Python)

### ISSUE THREAD

**Issue by brettcannon** [bytecodealliance/wasmtime#7829]
### Test Case

TODO: upload Wasm file here

### Steps to Reproduce

* https://github.com/python/cpython/blob/07236f5b39a2e534cf190cd4f7c73300d209520b/Lib/test/test_posix.py#L452-L454

### Expected Results

Test should pass (it does under preview 1).

### Actual Results

Raises errno 63: [`ENOSR`](https://docs.python.org/3/library/errno.html#errno.ENOSR) (out of stream resources).

### Versions and Environment

Wasmtime version or commit: 17.0.0

Operating system: Linux/WSL

Architecture: x64

### Extra Info

Anything else you'd like to add?

Success logs under preview 1: 
[success-utime-fd.txt](https://github.com/bytecodealliance/wasmtime/files/14069110/success-utime-fd.txt)

Failure logs under preview 2:
[failure-utime-fd.txt](https://github.com/bytecodealliance/wasmtime/files/14069114/failure-utime-fd.txt)

**Comment by alexcrichton** [comment]
Could you perhaps reupload the failure logs? It currently seems to be empty and/or says success with no extra logs

**Comment by brettcannon** [comment]
[failure-utime-fd.txt](https://github.com/bytecodealliance/wasmtime/files/14070134/failure-utime-fd.txt)


Sorry about that!

**Comment by pchickey** [comment]
@elliottt and I investigated this and will be posting a fix shortly.

**Comment by brettcannon** [comment]
> I don't know how to run your tests locally to verify that this fixed it

FYI I'm working on better docs for this, but https://github.com/python/cpython/tree/main/Tools/wasm#wasi-wasm32-wasi are the current docs if you're interested.



> Please verify for us whether this is a fix when you have time

Will do! I'll plan to give it a try this week.



> if it changes the status of any other of your posix tests, which exercise a lot more than our test suite.

Yeah, Python's test suite is old and extensive for this sort of thing: we're great at exercising C compilers and OSs. 😁 If you're ever interested in trying to get the Python test suite set up as a 3rd-party test suite to run, just let me know.

**Comment by brettcannon** [comment]
Commented at https://github.com/bytecodealliance/wasmtime/pull/7876#issuecomment-1936792352 about the PR passing CPython's test suite.

**Comment by pchickey** [comment]
This landed in `main` and in `release-18.0.0` so I'm going to close it now. We chose not to release this fix as a patch release on `release-17.0.0` but if someone really needs it before 18 goes out in 7 days, we still could.
