### ISSUE TITLE
Could bump version of zstd in wasmtime-cache?

### ISSUE THREAD

**Issue by chenhdc** [bytecodealliance/wasmtime#7869]
Hi, we found libzstd_sys.rlib varies from filesystem readdir order with zstd in the 0.11.1 version.  And https://github.com/gyscos/zstd-rs/pull/162 had resolved this problem.  could bump ztsd version for resolving this problem?

**Comment by alexcrichton** [comment]
Thanks for the report, I've submitted https://github.com/bytecodealliance/wasmtime/pull/7870 to do an update.
