### ISSUE TITLE
Error during building from source

### ISSUE THREAD

**Issue by kermitdafrog8** [bytecodealliance/wasmtime#7893]
error: Package `wasmtime-cli v17.0.1 (/tmp/SBo/wasmtime-v17.0.1-src)` does not have feature `wasmtime-wast`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

Not sure if this has already been reported.  Trying to build the source package.

**Comment by alexcrichton** [comment]
Thanks for the report! The feature is currently called `wast`, so does that work for you rather than a `wasmtime-wast` feature?

**Comment by kermitdafrog8** [comment]
All I do is extract the archive and then run cargo build --release. Is there something I'm missing?

**Comment by alexcrichton** [comment]
Ah in that case I think your version of the Rust compiler rustc might be too old. The `main` branch of Wasmtime currently requires Rust 1.73.0. What version do you have locally? (you can find out with `rustc -vV`)

**Comment by kermitdafrog8** [comment]
rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2

**Comment by alexcrichton** [comment]
Ah yes as you can see you're using 1.70.0. Are you able to update to Rust 1.73.0 or later?

**Comment by kermitdafrog8** [comment]
I'll close this issues knowing now that this version requires a newer version of rust.
