### ISSUE TITLE
How does the debug work?

### ISSUE THREAD

**Issue by TerryGuo** [bytecodealliance/wasmtime#791]
Hi there,
I just came across this amazing video about debugging webassembly code outside browser with command like "lldb -- wasmtime -g hello.wasm". I am interesting in the mechanism under the hood. When we are debugging the code, how the original wasm code is actually executed by wasmtime vm, in native code way (as via JIT) or in interpreter way? If I want to learn how the wasmtime supports JIT debugger, where should I start from? Thanks for any help in advance.

BR,
Terry

**Comment by yurydelendik** [comment]
> When we are debugging the code, how the original wasm code is actually executed by wasmtime vm, in native code way (as via JIT) or in interpreter way?

There is no interpreter in wasmtime yet. The code produced by JIT. We are using cranelift to generate native code and execute that, also the cranelift provides information on how wasm instructions and variables mapped to generated/native code.

> If I want to learn how the wasmtime supports JIT debugger, where should I start from?

The [debug](https://github.com/bytecodealliance/wasmtime/tree/master/crates/debug) crate reads "wasm" DWARF information (generated by rustc or clang) from .wasm file and converts it to "native" DWARF, based of the above information from the cranelift. (The WebAssembly DWARF extension still in the works, so what you see can be changed)

**Comment by yurydelendik** [comment]
Closing as answered. Please provide additional information to re-open the issue.
