### ISSUE TITLE
wasi-cap-std-sync 18.x.x not published

### ISSUE THREAD

**Issue by glebpom** [bytecodealliance/wasmtime#8042]
wasi-cap-std-sync version in crates.io is 17.0.2, and it depends on wasi-common 17.0.2, but wasi-common 18.0.2 is already released

**Comment by alexcrichton** [comment]
Thanks for the report! This changed in https://github.com/bytecodealliance/wasmtime/pull/7881 which first landed as part of the 18.0.x release, so it's expected that these are no longer being published as the crates have been removed in-tree. I believe [this is the function you're looking for](https://docs.rs/wasi-common/latest/wasi_common/sync/fn.add_to_linker.html) from the old wasi-cap-std-sync crate.
