### ISSUE TITLE
wasmtime CLI settings command panic

### ISSUE THREAD

**Issue by Escapingbug** [bytecodealliance/wasmtime#8058]
Thanks for filing a bug report! Please fill out the TODOs below.

**Note: if you want to report a security issue, please read our [security policy](https://bytecodealliance.org/security)!**

### Test Case

No wasmfile needed

### Steps to Reproduce

On a windows machine, run cli: `wasmtime settings`

### Expected Results

Normal settings help message.

### Actual Results

```
wasmtime settings
thread 'main' panicked at crates\cranelift\src\builder.rs:94:18:
set_tunables not called
```

### Versions and Environment

Wasmtime version or commit: `wasmtime-cli 18.0.2 (90db6e99f 2024-02-28)`

Operating system: Windows 10

Architecture: x86_64

### Extra Info

Anything else you'd like to add?

**Comment by peterhuene** [comment]
This reproduces on non-Windows platforms as well and was apparently regressed with #7844.
