### ISSUE TITLE
Switch from setuptools-rust to maturin?

### ISSUE THREAD

**Issue by gilescope** [bytecodealliance/wasmtime#807]
If you build with https://github.com/PyO3/maturin rather than setuptools-rust I hear it's less picky about which python version the result binds to. Might help simplify your build a bit maybe?

**Comment by alexcrichton** [comment]
Our CI stuff is all set up now at this point and it seems to be working so we're not too too pressed to change things up and/or clean up. This looks like it's something good to look into if we ever refactor though! Additionally PRs are of course always welcome to update this :)

**Comment by bjorn3** [comment]
I think this should be moved to https://github.com/bytecodealliance/wasmtime-py.

**Comment by alexcrichton** [comment]
Indeed. @gilescope if you're still interested in pursuing this and if it's still applicable to wasmtime-py, feel free to reopen!
