### ISSUE TITLE
winch: Component Model Support

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/wasmtime#8087]
In order for Winch to reach feature parity with Cranelift, we want to ensure that it can compile WebAssembly Components.

One approach is to implement the component trampolines from scratch, however, this will likely be a considerable amount of work and a lot of very similar work will be duplicated across both compilers. An alternative is to using Cranelift to compile all the trampolines, including the component ones. This approach will require making Winch match Cranelift's ABI. At that time of writing, this mostly involves adding callee-saved registers to Winch's ABI.

Switching to using Cranelift's trampolines has the added benefit that Winch will receive support for all trampolines types for "free".

**Comment by elliottt** [comment]
Fixed in #8082
