### ISSUE TITLE
winch: Use cranelift as the trampoline compiler

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/wasmtime#8098]
https://github.com/bytecodealliance/wasmtime/pull/8082 introduces Cranelift as the trampoline compiler for components in Winch. This allows reducing code duplication and allowing for better maintainability. 

In order to have uniform trampoline compilation across the board, we want to migrate the rest of Winch's trampolines to use Cranelift.

**Comment by elliottt** [comment]
Fixed in #8082

**Comment by elliottt** [comment]
I confused this with #8087 when closing old issues.
