### ISSUE TITLE
Compilation stage is too early?

### ISSUE THREAD

**Issue by pepyakin** [bytecodealliance/wasmtime#816]
I tried to migrate to use `wasmtime-api` instead of `wasmtime-runtime`. The experience is way better!

However, one problem that I've bumped into is that compilation is happening in `Instance`, rather than in `Module`, which basically destroys the performance for our case.

A few words about the use case: we use wasm to perform singular calls on a same module but with a fresh instance a lot of times. Therefore the latency is really important for us. One possible option how to work around this is to reuse a single `Instance` and after each call try to reset the state, specifically globals and memories. This, however, is not possible to do with `wasmtime-api` either since those items are not necessary exported. (As an aside, I think at some point we might would like to have an ability to change underlying memory mapping that is used for linear memory, that trick worked in case of wasmi).

What would be the best way forward here? Can we move compilation into module's constructor, or make it customizable? Or would it be better to keep staying on `wasmtime-runtime`?

cc @alexcrichton @sunfishcode

**Comment by alexcrichton** [comment]
Yes the implementation of the `wasmtime` crate is still relatively in its infancy, and rejiggering things around is most welcome! This was a TODO item on https://github.com/bytecodealliance/wasmtime/issues/708 that I didn't actually get around to doing myself, and figured we could tackle it once it arose, and now it has arisen :)

I think this will likely take some internal refactoring of how the bits and pieces work, but the API should all be in place to have this "just work"

**Comment by yurydelendik** [comment]
#811 split instantiate() into two parts: compilation and instantiation -- it is possible to move the CompiledModule part into `Module` and cache it there.

**Comment by pepyakin** [comment]
> there is dependency on imports.

But it is still doable, right? From a brief look it seems we roughly need to split `link_module`, do the relocation part at the compilation stage. The second part, i.e. creation of `Imports` object we move to `CompiledModule::instantiate`. Am I missing something?

In any case, I can help with this one given I have a description what exactly we want here

**Comment by alexcrichton** [comment]
Yes this will require some refactoring in `wasmtime-jit`, and yeah we basically need to be able to create a compiled module and then later repeatedly invoke instantiate on it with a new resolver each time, so the resolver will need to be refactored out of the constructor of a `RawCompiledModule`
