### ISSUE TITLE
Wasmtime bindgen macro does not support derives, unlike wit_bindgen generate

### ISSUE THREAD

**Issue by AaronFriel** [bytecodealliance/wasmtime#8254]
[wasmtime::component::bindgen](https://docs.rs/wasmtime/latest/wasmtime/component/macro.bindgen.html) does not support derives. Guests are able to add `serde` derives, and hosts are not.

**Comment by alec-deason** [comment]
This would be very nice to have.

**Comment by alexcrichton** [comment]
I think this'd be great to add, and the guest support in `wit-bindgen-rust` is probably a good way to model a change such as this.

**Comment by sehz** [comment]
This is really needed as sharing WIT between guest and host
