### ISSUE TITLE
Bad relocation type generated

### ISSUE THREAD

**Issue by Wang-Zhongqi** [bytecodealliance/wasmtime#8255]
### Test Case
~~~ wat
(module
  (func (export "ceil") (param $x f32) (result f32) (f32.ceil (local.get $x)))
  (func (export "floor") (param $x f32) (result f32) (f32.floor (local.get $x)))
  (func (export "trunc") (param $x f32) (result f32) (f32.trunc (local.get $x)))
  (func (export "nearest") (param $x f32) (result f32) (f32.nearest (local.get $x)))
)
~~~

### Steps to Reproduce

* TODO: first, disable sse support
* TODO: second, wasmtime compile -Ccache=n -o test.cwasm test.wasm
* TODO: objdump -r test.cwasm

### Expected Results

The expected relocation type is R_X86_64_64, indicating a 64-bit absolute relocation. 
![image](https://github.com/bytecodealliance/wasmtime/assets/56493493/1e3118be-161e-4812-ad37-6ad5d318f033)

### Actual Results

The actual relocation type is 8-bit.
![image](https://github.com/bytecodealliance/wasmtime/assets/56493493/5076d4d4-15e8-4886-8f0d-8aa33a959699)

### Versions and Environment

Wasmtime version or commit: 16.0

Operating system: ubuntu 20.04

Architecture: X86_64

### Extra Info

This could be 64, not 8.
![image](https://github.com/bytecodealliance/wasmtime/assets/56493493/f7b3af91-2d40-4678-8850-020aa0e8dca3)

**Comment by alexcrichton** [comment]
Yeah looks like a bug, thanks! Would you be up for sending a PR to update that constant? I believe an update will be required [here](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasmtime/src/runtime/code_memory.rs#L105) as well.
