### ISSUE TITLE
FileOutputStream::write() modify the position repeatedly

### ISSUE THREAD

**Issue by liutao-liu** [bytecodealliance/wasmtime#8257]
Two modifications to the ```p``` code：
https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/filesystem.rs#L359

https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1705

The former is an invalid modification, because ```self.mode``` is not a reference of postion in [fd_write](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1670) , which is passed by value in [write_via_stream](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1690).

Please help confirm if this is a bug. If it is, I'll submit a pr with my local changes.

**Comment by alexcrichton** [comment]
Could you clarify with a test case what the expected behavior is? Reviewing these mutations I don't see anything amiss myself, but a test case could help understand if there's a bug here

**Comment by liutao-liu** [comment]
> Could you clarify with a test case what the expected behavior is? Reviewing these mutations I don't see anything amiss myself, but a test case could help understand if there's a bug here

Delete the modification in [here](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/filesystem.rs#L359) All test case can run success. The reason is what I said before:```self.mode``` is not a reference of postion in [fd_write](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1670) , which is passed by value in [write_via_stream](https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1690).

![image](https://github.com/bytecodealliance/wasmtime/assets/10509166/b2d5fd02-8e3c-4273-8333-c1fe88432862)

**Comment by alexcrichton** [comment]
Sorry yeah our test suite for preview2 is not overly comprehensive. I've added a test in https://github.com/bytecodealliance/wasmtime/pull/8271 which fails if the code you're linking to fails.

It's a bit subtle and it needs a few different things in play, but I believe that this code is still necessary. Can you elaborate more on why you're looking to see this deleted?

**Comment by liutao-liu** [comment]
The postion has been modified in ```fd_write```(```fd_read``` is the same):
https://github.com/bytecodealliance/wasmtime/blob/9c92881d3b936b5d2e593ded370609a6e31717d8/crates/wasi/src/preview1.rs#L1705
The implementation of ```fd_write``` is as follows: first call ```write_via_stream```, then call ```blocking_write_and_flush```, and finally modify the ```position```.
The test case you added in #8271: call ```write_via_stream``` **once**, then call ```blocking_write_and_flush``` **twice**.

**Comment by alexcrichton** [comment]
You'll need to remember that there's a few layers here. The test I added in #8271 specifically uses preview2-based APIs and does not use preview1. You're correct that in a world where preview2 does not exist removing the write is ok, but in a world where preview2 exists removing the write is not correct.

I've asked a few times already, but can you clarify why you'd like this write removed? Is it causing performance problems or something like that? Or are you instead trying to understand why it's needed? (whatever's fine, I'm just curious!)

**Comment by liutao-liu** [comment]
> You'll need to remember that there's a few layers here. The test I added in #8271 specifically uses preview2-based APIs and does not use preview1. You're correct that in a world where preview2 does not exist removing the write is ok, but in a world where preview2 exists removing the write is not correct.
> 
> I've asked a few times already, but can you clarify why you'd like this write removed? Is it causing performance problems or something like that? Or are you instead trying to understand why it's needed? (whatever's fine, I'm just curious!)

Sorry, I wasn't thinking from preview2's perspective. I see what you mean, thanks for your reply.
