### ISSUE TITLE
Memory Input Pipe Write from outside

### ISSUE THREAD

**Issue by MinusGix** [bytecodealliance/wasmtime#8274]
#### Feature

When supplying a custom`MemoryInputPipe` to `WasiCtxBuilder` as `stdin` it would be useful to have the ability to write to it in order to communicate with the program.  
  
(The specific use-case here is spawning WASM programs that essentially act like LSPs, communicating over a simple text interface rather than directly calling functions)

#### Benefit
Allows sending data through stdin, along with reading data from stdout/stderr.

#### Implementation

Probably have to change `MemoryInputPipe` to use a `BytesMut`.  
Could add standard `std::io::Read`/`std::io::Write` implementations to `MemoryInputPipe` (and `MemoryOutputPipe`, though that's readable though `.content()`) like the old `ReadPipe`/`WritePipe` from wasi-common?

#### Alternatives

Reimplement a version locally.  
(Could be I've missed some alternative solution?)

**Comment by bjorn3** [comment]
Would `wasmtime_wasi::pipe::AsyncReadStream` work for you? It allows the guest to read from an `AsyncRead` you supply.

**Comment by MinusGix** [comment]
I am using the Rust API, updating a project that was last on 14.0.0.
  
I have not directly used async/tokio much in any past projects, which makes it unclear what type to use that implements `AsyncRead` + can be shared so that we can write to it from elsewhere. If there's some obvious choice here, I was unable to find it after some searching on the net/tokio docs.  

If I'm needing a custom implementation, then it seems simpler to reuse a modified `MemoryInputStream` to implement `Write` (and if provided in wasmtime would make it simpler as a user).

**Comment by alexcrichton** [comment]
I think what you probably want is a [`DuplexStream`](https://docs.rs/tokio/latest/tokio/io/struct.DuplexStream.html)

**Comment by MinusGix** [comment]
That'll probably work.  
Looking back, the primary issue is seemingly that I was confused about `MemoryInputPipe`/`MemoryOutputPipe`: I was interpreting them as "buffers to read/write from which are just missing utility functions", but they're actually for having some fixed data that you want to pass in or having a fixed size buffer to write data into.
