### ISSUE TITLE
Trap handling may segfault due to being out-of-stack

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#829]
On [master for me currently](https://github.com/bytecodealliance/wasmtime/tree/b2bfb98f1ffbd10209aa2510ce5e5a2dbdafdd25) I get:

```
$ cargo test --test wast_testsuites misc_traps
    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running target/debug/deps/wast_testsuites-073f46d5a7733a1a

running 1 test
error: test failed, to rerun pass '--test wast_testsuites'

Caused by:
  process didn't exit successfully: `/home/alex/code/wasmtime/target/debug/deps/wast_testsuites-073f46d5a7733a1a misc_traps` (signal: 11, SIGSEGV: invalid memory reference)
```

The stack trace of the segfault looks like this:

<details>

```
Thread 1 "wast_testsuites" received signal SIGSEGV, Segmentation fault.
do_lookup_x (undef_name=undef_name@entry=0x7ffff7593c7b "_Unwind_Find_FDE", new_hash=new_hash@entry=997813959, old_hash=old_hash@entry=0x7ffff7ff50c0, ref=0x7ffff7592f70, result=result@entry=0x7ffff7ff50d0, scope=0x7ffff7ffe428, i=0, version=0x7ffff7fd5680, flags=5, skip=0x0, type_class=1, undef_map=0x7ffff7fd7f00) at dl-lookup.c:338
338     dl-lookup.c: No such file or directory.
(gdb) bt
#0  do_lookup_x (undef_name=undef_name@entry=0x7ffff7593c7b "_Unwind_Find_FDE", new_hash=new_hash@entry=997813959, old_hash=old_hash@entry=0x7ffff7ff50c0, ref=0x7ffff7592f70, result=result@entry=0x7ffff7ff50d0, scope=0x7ffff7ffe428, i=0, version=0x7ffff7fd5680, flags=5, skip=0x0, type_class=1, undef_map=0x7ffff7fd7f00) at dl-lookup.c:338
#1  0x00007ffff7de01ef in _dl_lookup_symbol_x (undef_name=0x7ffff7593c7b "_Unwind_Find_FDE", undef_map=0x7ffff7fd7f00, ref=ref@entry=0x7ffff7ff5168, symbol_scope=0x7ffff7fd8258, version=0x7ffff7fd5680, type_class=type_class@entry=1, flags=5, skip_map=<optimized out>) at dl-lookup.c:813
#2  0x00007ffff7de4ec3 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>) at ../elf/dl-runtime.c:112
#3  0x00007ffff7dec7ca in _dl_runtime_resolve_xsavec () at ../sysdeps/x86_64/dl-trampoline.h:125
#4  0x00007ffff75a1223 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#5  0x00007ffff75a2400 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#6  0x00007ffff75a3108 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x0000555555bccf0d in backtrace::backtrace::libunwind::trace (cb=...) at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/backtrace/libunwind.rs:86
#8  backtrace::backtrace::trace_unsynchronized (cb=...) at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/backtrace/mod.rs:66
#9  0x0000555555bcce8e in backtrace::backtrace::trace (cb=...) at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/backtrace/mod.rs:53
#10 0x0000555555bc530d in backtrace::capture::Backtrace::create (ip=93824998986352) at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/capture.rs:164
#11 0x0000555555bc5284 in backtrace::capture::Backtrace::new_unresolved () at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.42/src/capture.rs:158
#12 0x0000555555b5a16c in RecordTrap (pc=0x7ffff7f29015 "@\213\001@", <incomplete sequence \303>, reset_guard_page=false) at crates/runtime/src/traphandlers.rs:55
#13 0x0000555555bb2cba in HandleTrap (context=0x7ffff7ff6380, reset_guard_page=false) at signalhandlers/SignalHandlers.cpp:415
#14 0x0000555555bb2d93 in WasmTrapHandler (signum=11, info=0x7ffff7ff64b0, context=0x7ffff7ff6380) at signalhandlers/SignalHandlers.cpp:645
#15 <signal handler called>
#16 0x00007ffff7f29015 in ?? ()
#17 0x00007fffffff99c0 in ?? ()
#18 0x00007ffff7f18012 in ?? ()
#19 0x00007fffffff9ad0 in ?? ()
#20 0x0000555555bb30b0 in WasmtimeCallTrampoline (vmctx=0x555555bb404e <std::thread::local::LocalKey<T>::try_with+286>, body=0x7ffff7fd2828, args=0x7fffffff99b8) at signalhandlers/Trampolines.cpp:14
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

</details>

where the faulting instruction looks like this:

<details>

```
Dump of assembler code for function do_lookup_x:
   0x00007ffff7ddf240 <+0>:     push   %r15
   0x00007ffff7ddf242 <+2>:     push   %r14
   0x00007ffff7ddf244 <+4>:     push   %r13
   0x00007ffff7ddf246 <+6>:     push   %r12
   0x00007ffff7ddf248 <+8>:     push   %rbp
   0x00007ffff7ddf249 <+9>:     push   %rbx
   0x00007ffff7ddf24a <+10>:    sub    $0x98,%rsp
   0x00007ffff7ddf251 <+17>:    mov    0x8(%r9),%eax
=> 0x00007ffff7ddf255 <+21>:    mov    %rdi,0x28(%rsp)
   0x00007ffff7ddf25a <+26>:    mov    %rsi,(%rsp)
   0x00007ffff7ddf25e <+30>:    mov    %rdx,0x60(%rsp)
   0x00007ffff7ddf263 <+35>:    mov    %rcx,0x30(%rsp)
```

</details>

where I can read `%rsp+0x28` in gdb, but I can't write to it.

I believe what's happening here looks like this:

* [Wasmtime registers signal handlers with `SA_ONSTACK`](https://github.com/bytecodealliance/wasmtime/blob/b2bfb98f1ffbd10209aa2510ce5e5a2dbdafdd25/crates/runtime/signalhandlers/SignalHandlers.cpp#L721-L738)
* The Rust standard library [configures an alternate stack](https://github.com/rust-lang/rust/blob/117ceeba400e69aa7b8ba5155acd1c8c0cdf7f7f/src/libstd/sys/unix/stack_overflow.rs#L154-L165) if one isn't already configured per-thread. The stack defaults to [`SIGSTKSZ`](https://github.com/rust-lang/rust/blob/117ceeba400e69aa7b8ba5155acd1c8c0cdf7f7f/src/libstd/sys/unix/stack_overflow.rs#L130) bytes, which [is 8192 bytes](https://docs.rs/libc/0.2.66/src/libc/unix/linux_like/linux/gnu/b64/x86_64/mod.rs.html#724) on x86_64 linux.
* When a wasm trap happens, [we call `Backtrace::new_unresolved`](https://github.com/bytecodealliance/wasmtime/blob/b2bfb98f1ffbd10209aa2510ce5e5a2dbdafdd25/crates/runtime/src/traphandlers.rs#L55). This ends up consuming enough stack space that we blow the stack, hitting presumably some sort of guard page.

This doesn't appear to be happening on CI, and from what I can guess it's relatively localized and dependent on stack sizes here and there. This may also be glibc related because the actual fault itself is in the dynamic loader (presumably since this was the first time I generated a backtrace). I believe, though, that 2 pages (at most) apparently isn't enough to generate a full stack trace (note that we're also hitting things like malloc which we "pray works"). 

I'm not really sure what best to do about this. I can actually "fix" this locally by calling `Backtrace::new_unresolved()` somewhere randomly in the program before it hits a fault, since that way the dynamic loader isn't triggered during the trap handler. Unfortunately it's not really easy for us to set our own stack to handle faults on since that would involve poking with `sigaltstack` on all threads wasmtime is called on, which may lead to excessive overhead. 

The stack pointer of the various frames are, for one trace in a debug build:

| function | `$rsp` | diff from previous |
|------------|-------|-------------------|
| `WasmTrapHandler` | 0x7ffff7ff6320 | |
| `HandleTrap` | 0x7ffff7ff62f0 | 48 |
| `RecordTrap` | 0x7ffff7ff61f0 | 256 |
| `backtrace::capture::Backtrace::new_unresolved` | 0x7ffff7ff61e0 | 16 |
| `backtrace::capture::Backtrace::create` | 0x7ffff7ff6140 | 160 |
| `backtrace::backtrace::trace` | 0x7ffff7ff60d0 | 112 |
| `backtrace::backtrace::trace_unsynchronized` | 0x7ffff7ff60a0 | 48 |
| `backtrace::backtrace::libunwind::trace` | 0x7ffff7ff60a0 | 0 |
| `_Unwind_Backtrace` | 0x7ffff7ff5df0 | 688 |
| `??` | 0x7ffff7ff5c30 | 448 |
| `??` | 0x7ffff7ff5bc0 | 112 |
| `_dl_runtime_resolve_xsavec` | 0x7ffff7ff5180 | 2624 |
| `_dl_fixup` | 0x7ffff7ff5150 | 48 |
| `_dl_lookup_symbol_x` | 0x7ffff7ff5050 | 256 |
| `do_lookup_x` | 0x7ffff7ff4f80 | 208 |

Since libstd allocates 2 pages for the stack handler, I'm assuming that the stack was from 0x7ffff7ff5000  to 0x7ffff7ff7000, which is why `do_lookup_x` faulted. I'm not sure why `WasmTrapHandler` started so low, but maybe there's a bunch of kernel data structures or signal information on the stack? Unsure.

In any case it looks like we definitely can't run the dynamic loader in SIGSTKSZ, but we presumably can run backtraces because that's what's already happening on CI. I wanted to get this all written down in an issue somewhere because I'm about to send a PR for a pretty bad hack which doesn't truly fix the issue but should patch over the problem for now (hopefully)

**Comment by pepyakin** [comment]
I've observed a similar problem running on a Linux machine using 448faed5ca0e38c3ee5cdbe703b9f89f1e76e8a0. The stack trace is a bit different though.

```
* thread #1, name = 'sc_executor-f4f', stop reason = signal SIGSEGV: invalid address (fault address: 0x8)
  * frame #0: 0x00007ffff72185df libgcc_s.so.1`___lldb_unnamed_symbol41$$libgcc_s.so.1 + 1055
    frame #1: 0x00007ffff721a138 libgcc_s.so.1`_Unwind_Backtrace + 104
    frame #2: 0x0000555555a68137 sc_executor-f4fe4729a78e1cc7`backtrace::backtrace::trace::h1adcaa00054f7e2c + 87
    frame #3: 0x0000555555a67a56 sc_executor-f4fe4729a78e1cc7`backtrace::capture::Backtrace::new_unresolved::hcc88b2186746cdd0 + 86
    frame #4: 0x0000555555710c9f sc_executor-f4fe4729a78e1cc7`RecordTrap + 239
    frame #5: 0x00005555557128ff sc_executor-f4fe4729a78e1cc7`WasmTrapHandler(int, siginfo_t*, void*) + 431
    frame #6: 0x00007ffff7433890 libpthread.so.0`___lldb_unnamed_symbol1$$libpthread.so.0 + 1
    frame #7: 0x00007ffff7fb3d84
    frame #8: 0x00007ffff7fb365a
    frame #9: 0x00007ffff7fb06a5
    frame #10: 0x00007ffff7fbe2f2
    frame #11: 0x00007ffff67f9031
    frame #12: 0x0000555555712b40 sc_executor-f4fe4729a78e1cc7`WasmtimeCallTrampoline + 128
    frame #13: 0x0000555555711517 sc_executor-f4fe4729a78e1cc7`wasmtime_call_trampoline + 23
```

the code around there looks like this

```
    0x7ffff72185d8 <+1048>: movq   0x98(%r13), %rax
->  0x7ffff72185df <+1055>: cmpb   $0x48, (%rax)
    0x7ffff72185e2 <+1058>: jne    0x7ffff7218580            ; <+960>
    0x7ffff72185e4 <+1060>: movabsq $0x50f0000000fc0c7, %rdx  ; imm = 0x50F0000000FC0C7 
    0x7ffff72185ee <+1070>: cmpq   %rdx, 0x1(%rax)
    0x7ffff72185f2 <+1074>: jne    0x7ffff7218580            ; <+960>
```

**Comment by alexcrichton** [comment]
@pepyakin a fault at 0x8 sounds like some sort of null pointer sneaking in somewhere, mind opening a dedicated issue for that?

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/bytecodealliance/wasmtime/issues/900 since I think that's going to solve this, and this is otherwise effectively mitigated for now.
