### ISSUE TITLE
Wasmtime reentrance

### ISSUE THREAD

**Issue by geloizi** [bytecodealliance/wasmtime#83]
When wasmtime engine is embedded into a user application would it be possible to call the same wasm module from multiple system threads? For simplicity let's assume the functions inside wasm module are stateless and don't need locking.

**Comment by sunfishcode** [comment]
Yes, if you're not accessing linear memory or globals, that should work. When Wasmtime adds support for shared memory, it'll work on shared memory too.

**Comment by joshtriplett** [comment]
@sunfishcode Is there a tracking issue somewhere for thread support and shared memory support in wasmtime?

**Comment by alexcrichton** [comment]
Looks like we have a few of these issues open in the issue tracker so I'm going to close this in favor of a dedicated tracking issue -- https://github.com/bytecodealliance/wasmtime/issues/888
