### ISSUE TITLE
[lightbeam] remainder overflow in debug mode (backend:rem_s:868)

### ISSUE THREAD

**Issue by pventuzelo** [bytecodealliance/wasmtime#837]
# Issue description

`lightbeam` will try to calculate the remainder even if an overflow occurs in the function `rem_s`. 

``` sh
$ ./debug_diff_compile panic_remainder_overflow_868_2.wasm 
thread 'main' panicked at 'attempt to calculate the remainder with overflow', XXX/wasmtime/crates/lightbeam/src/backend.rs:868:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This issue is related to the function `rem_s` when dealing with the `i32.rem_s` opcode:

https://github.com/bytecodealliance/wasmtime/blob/420dcd76fd0d684291901c7a6afeb481481dea7e/crates/lightbeam/src/backend.rs#L867-L869

I suspect this issue can also occurs in `rem_u`:

https://github.com/bytecodealliance/wasmtime/blob/420dcd76fd0d684291901c7a6afeb481481dea7e/crates/lightbeam/src/backend.rs#L826-L829

# Reproduction

Download 
[panic_remainder_overflow_868.zip](https://github.com/bytecodealliance/wasmtime/files/4077577/panic_remainder_overflow_868.zip)

``` wat
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const -2147483648
    i32.const -1
    i32.rem_s
    unreachable))
```

wasmtime commit: 7890fa670547578f549a5e4e5d0f69788bed96cf

**Comment by alexcrichton** [comment]
Lightbeam was removed in https://github.com/bytecodealliance/wasmtime/pull/3390 as explained in [RFC 14](https://github.com/bytecodealliance/rfcs/pull/14), so I'm going to close this.
