### ISSUE TITLE
WASI semver compatibility should apply to exports

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#8395]
In https://github.com/bytecodealliance/wasmtime/pull/7994 the `component::Linker` type in Wasmtime was made aware of semver by enabling loading a component that requires 0.2.0 of an interface with a supplied 0.2.1 of an interface. This enables us to update WASI in Wasmtime without breaking the ability to load older components.

This support, however, does not work for exports. If a component exports 0.2.0 and the runtime is generating bindings for 0.2.1 then loading the export will fail currently, there's no logic anywhere to probe for older verions.

This represents a snag in our story of WASI compatibility in Wasmtime and is something we should address before updating WASI to 0.2.1

**Comment by bjorn3** [comment]
Removing exports in a new interface version should be trivially fine? Adding non-optional exports shouldn't be allowed as the host may attempt to call them. Adding optional exports would be fine, but the component model doesn't have a way to represent them, right?
