### ISSUE TITLE
The outputs of Wasmtime are  inconsistent across different platforms

### ISSUE THREAD

**Issue by abc767234318** [bytecodealliance/wasmtime#8399]
I constructed a wasm binary with an exported function called "main". I compared the outputs of wasmtime and found they are inconsistent across different platforms.
[file86.zip](https://github.com/bytecodealliance/wasmtime/files/15024610/file86.zip)

Wasmtime  v18.0.2 Ubuntu22.04 x86_64:
```
wasmtime --invoke main file86.wasm
warning: using `--invoke` with a function that returns values is experimental and may break in the future
667210185897120983469013534608098645
667210185897120983469013534608098645
667210185897120983469013534608098645
667210185897120983469013534608098645
667210185897120983469013534608098645
667210185897120983469013534608098645
667210185897120983469013534608098645
```

Wasmtime  v18.0.2 MacOS arm64:
```
wasmtime --invoke main file86.wasm
warning: using `--invoke` with a function that returns values is experimental and may break in the future
667210185936411072606488982786049365
667210185936411072606488982786049365
667210185936411072606488982786049365
667210185936411072606488982786049365
667210185936411072606488982786049365
667210185936411072606488982786049365
667210185936411072606488982786049365
```

**Comment by bjorn3** [comment]
Does the wasm module look at the raw bits of floats? NaN values are allowed to be non-deterministic by the wasm specification. Different cpu architectures have different handling of NaN values. This may be the cause of the difference here if the answer to my question is true.
