### ISSUE TITLE
`wasmtime-wasi-http` shouldn't add the default port to outbound `host` header

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wasmtime#8430]
The outbound HTTP implementation will add a default port to the URI authority if not present:

https://github.com/bytecodealliance/wasmtime/blob/1fa8de140fce161ed5d77cf939558de79d3956c1/crates/wasi-http/src/http_impl.rs#L68-L69

As reported [on Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/217126-wasmtime/topic/wasmtime-wasi-http.20treatment.20of.20Host.20header.20breaks.20AWS.20SD.2E.2E.2E) and as [a Spin issue](https://github.com/fermyon/spin/issues/2325), this causes breakage with AWS signed requests, which [include the exact host header value in the signature payload](https://docs.aws.amazon.com/IAM/latest/UserGuide/signing-elements.html#endpoint-specification).

I believe the current behavior is incorrect. Per the [HTTP/1.1 spec](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#rfc.section.3.2.p.5):

> If the target URI includes an authority component, then a client MUST send a field value for Host that is identical to that authority component

**Comment by alexcrichton** [comment]
cc @elliottt
