### ISSUE TITLE
The additional_derives option on bindgen misses some types

### ISSUE THREAD

**Issue by alec-deason** [bytecodealliance/wasmtime#8477]
#8441  recently added support for additional_derives in `wasmtime::component::bindgen` but the new version appears not to apply the derives to all types. In particular it seems to miss variants which are only used as fields in records, as in this definition:

```
package test:bindgen-test;

interface types {
    variant inner-variant {
        a,
        b,
        c
    }
    record outer-record{
        inner: inner-variant
    }
}

world bindgen-test {
    use types.{outer-record};
    export test-failure: func() -> outer-record;
}
```

In my testing the derives will be applied to OuterRecord but not to InnerVariant.

Attached is a complete test case which fails to compile.
[bindgen_case.tgz](https://github.com/bytecodealliance/wasmtime/files/15120002/bindgen_case.tgz)

**Comment by fibonacci1729** [comment]
@alec-deason Sorry about that! I added the fix in #8482.
