### ISSUE TITLE
Panics are not caught within Callable

### ISSUE THREAD

**Issue by pepyakin** [bytecodealliance/wasmtime#848]
When anything panics inside of `wasmtime::Callable` the whole process gets aborted it seems.

```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    98746 abort      cargo run
```

I think `error 5` corresponds to the error when it cannot find the handler on the stack

**Comment by peterhuene** [comment]
Hi @pepyakin.

For my information, which platform did you run into this issue?  As far as I'm aware, we should now be able to unwind properly on Linux, macOS, and Windows.

If possible, what's the commit of your branch that you're reproducing it with?
