### ISSUE TITLE
Wasi Tutorial Error: Invalid digit found in string 

### ISSUE THREAD

**Issue by jlb6740** [bytecodealliance/wasmtime#855]
When following the tutorial here: 
https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-tutorial.md

An error is seen when attempting to run the demo.wasm example (created from demo.c) with filenames that are strings. Specifically the command:

target/debug/wasmtime --dir=. ~/wasmtime-wasi-tutorial/demo.wasm a.txt b.txt 
warning: using `--invoke` with a function that takes arguments is experimental and may break in the future
Error: failed to run main module `/home/jlbirch/wasmtime-wasi-tutorial/demo.wasm`

Caused by:
    invalid digit found in string

A backtrace is indicating that the error is thrown from wasmtime_cli::commands::run::RunCommand::invoke_export
where it seems there is an attempt to match against a LongLong argument type instead of a string.

**Comment by kubkon** [comment]
This is a bug introduced after changing global-exports mechanism with caller-mechanism in #789. I've now provided a fix for this in #867

**Comment by kubkon** [comment]
> This is a bug introduced after changing global-exports mechanism with caller-mechanism in #789. I've now provided a fix for this in #867

I've actually missed the fact that @yurydelendik has already provided a fix in #858, so when it lands, we should be good to go.

**Comment by jlb6740** [comment]
+1

**Comment by kubkon** [comment]
Given that #858 was merged into master, this should be fixed now. I'm gonna go ahead and close this issue. Feel free to reopen it @jlb6740 if you feel otherwise :-)

**Comment by huangjj27** [comment]
I encounter the exactly same bug with the rust version code, with wasmtime 4.0.0 on windows 11:

1. use the rust code from the [tutorial](https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-tutorial.md)
2. make the function `process` to be `pub`, and `#[no_mangle]`
3. compile the project with `cargo wasi build`
4. `echo hello world > test.txt`
5. run the command and its return error:
```
> wasmtime --dir=. target\wasm32-wasi\debug\demo.wasm --invoke process test.txt somewhere.txt
warning: using `--invoke` with a function that takes arguments is experimental and may break in the future
Error: failed to run main module `target\wasm32-wasi\debug\demo.wasm`

Caused by:
    invalid digit found in string
```

**Comment by huangjj27** [comment]
and I checked out that what #858 has fixed is another bug, and its added a test for a digit param when invoking, but not for a string param, which is the bug I'm encountering now.

**Comment by huangjj27** [comment]
I find out another problem with the same bug [on stackoverflow](https://stackoverflow.com/questions/58424072/failed-to-invoke-functions-when-running-wasm-file-with-wasmtime), just linking :-}
