### ISSUE TITLE
Changing a multiplication operation to a division one makes a big performance decreasing

### ISSUE THREAD

**Issue by hungryzzz** [bytecodealliance/wasmtime#8571]
### Test Case

[cases.zip](https://github.com/bytecodealliance/wasmtime/files/15236026/cases.zip)

### Steps to Reproduce

Hi, I run the attached two cases(`good.wasm`&`bad.wasm`) in `Wasmtime` and `WasmEdge`, and collect their execution time respectively.

### Expected Results & Actual Results

Actually the only difference between the attached two cases is as follow, i.e., a multiplication operation to a division one, but the execution time of `Wasmtime` increases by more than 5 times, while the execution time before and after the modification is nearly the same in `Wasmedge` and `Wasmer`.

![截屏2024-05-07 21 18 58](https://github.com/bytecodealliance/wasmtime/assets/32137313/a5c51594-b60f-466e-8517-48977fed9da3)

For `good.wasm`, the execution time in different runtimes are as follows:
<img width="1214" alt="截屏2024-05-07 21 32 15" src="https://github.com/bytecodealliance/wasmtime/assets/32137313/41a41f7d-72ab-4233-81eb-2600a6cb021f">

For `bad.wasm`, the execution time in different runtimes are as follows:
<img width="1191" alt="截屏2024-05-07 21 33 33" src="https://github.com/bytecodealliance/wasmtime/assets/32137313/2f281b67-4568-40d9-adba-240d069b6fdf">

### Versions and Environment

Wasmtime version or commit: d0cf46a098d97bab9c4cf54a2f3aeaddea7d3831

Operating system: Linux ringzzz-OptiPlex-7070 5.15.0-97-generic

Architecture: Intel(R) Core(TM) i5-9500T CPU @ 2.20GHz

**Comment by bjorn3** [comment]
Division is a lot more expensive than multiplication on pretty much every cpu. It may be that the other wasm engines are optimizing it away, or schedule the instructions slightly differently in a way that masks most of the latency on modern super scalar cpu's.

**Comment by hungryzzz** [comment]
Yes, you're right, but the default backend of `Wasmer` is also `Cranelift`,  the execution time before and after the modification in `Wasmer` is nearly the same. So I am wondering if it is possible that the subsequent commits introduce some bugs.

<img width="1366" alt="截屏2024-05-07 22 27 01" src="https://github.com/bytecodealliance/wasmtime/assets/32137313/650171d3-f6db-4e60-9ad1-0a0811c4d026">

**Comment by cfallin** [comment]
@hungryzzz our current version of the mid-end optimizer can't yet rewrite divs by constants into multiplies by magic constants; we have #6049 for this. I'm going to go ahead and close this issue in favor of that as it's a duplicate report.

**Comment by hungryzzz** [comment]
@cfallin Hi, I check the generated machine code of `bad.wasm` and `good.wasm`, and find that, in the wasm code, the result of `i32.div_u` or `i32.mul` will be dropped directly, and the machine code of `good.wasm` will eliminate the multiplication operation, however, the machine code of `bad.wasm` will still do the division operation.
Does this have anything to do with "rewrite divs by constants into multiplies by magic constants"? (In my view, this optimization aims to speed up the division operation under some magic contants?)
By the way, I also replace `i32.mul` to other operator, e.g., `i32.sub` and `i32.add`, all of this operator will be eliminated directly. But I don't understand why only the division operator will not be eliminated.

```wat
;; part of bad.wasm
i32.const 0
i32.const 1
i32.div_u ;; diff
drop

;; part of good.wasm
i32.const 0
i32.const 1
i32.mul ;; diff
drop
```
[report.zip](https://github.com/user-attachments/files/15856642/report.zip)

**Comment by cfallin** [comment]
Yes, divides also cannot be removed currently, even if dead: they may have side-effects in general (and Cranelift's predicate for "is this instruction side-effecting" doesn't know about constant input values, so it can't reason that a divide-by-constant-1 will never reach the divide-by-zero trap case). That's why a `drop`'d `i32.div_u` still appears in codegen while the `i32.mul` does not.
