### ISSUE TITLE
C API uses `Module::new_unchecked`

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#859]
Currently [the implementation of `wasm_module_new`](https://github.com/bytecodealliance/wasmtime/blob/3db1074c1539709b76e1b51dcda45390fe0a377f/crates/c-api/src/lib.rs#L790) in the C API uses `Module::new_unchecked`, but this isn't a safe API! We should move over to using `Module::new` and returning errors (probably as null pointers?).

I tried to initially do this in https://github.com/bytecodealliance/wasmtime/pull/813 but the C# tests look like they rely on `new_unchecked`. I think this is because the C# tests exercise features like wasm multi-value, and right now there's no way, via the C API, to enable wasm features like multi-value (or change configuration in general). 

To fix this issue I think we'll need to add wasmtime-specific C API calls to manage a `Config` which can then be used to create a `wasm_engine_t`. We'll then need to update the C# tests to explicitly enable multi-value (and other such features), and then we should be able to switch over to `new` instead of `new_unchecked`

**Comment by sunfishcode** [comment]
FWIW, in https://github.com/WebAssembly/wasm-c-api/issues/123, it was clarified that `wasm_memory_new` is indeed intended to perform validation.

**Comment by alexcrichton** [comment]
@peterhuene would you be willing to take this on to extend the C# API with the necessary support to explicitly enable wasm features for the tests it runs? Once we get that in place we should be able to switch over to `from_binary` instead of `from_binary_unchecked`

**Comment by peterhuene** [comment]
I'll take this on.
