### ISSUE TITLE
x64: Add support for `fmsub` and `fnmsub` instructions

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#8602]
👋 Hey,

#### Feature

Add support for the [`fmsub`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vfmsub&ig_expand=3421,3211) and [`fnmsub`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vfnmsub&ig_expand=3421,3211,3421) instructions in the x64 backend.

#### Benefit

This improves instruction selection quality for a few special fma cases.

#### Implementation

We already have support for the `fmadd` and `fnmadd` versions of these instructions [here](https://github.com/bytecodealliance/wasmtime/blob/e6f9ca5efa0c4bf59c9cf133d9abeaab63ec07bb/cranelift/codegen/src/isa/x64/lower.isle#L2840-L2864) and [here](https://github.com/bytecodealliance/wasmtime/blob/e6f9ca5efa0c4bf59c9cf133d9abeaab63ec07bb/cranelift/codegen/src/isa/x64/inst.isle#L4341-L4367). So we adding support for these instructions should be a matter of introducing the new opcodes and implementing lowering rules similar to what already exists today.

Something similar was done in #8588 for the RISC-V backend. If anyone needs help implementing this, let me know!

**Comment by UnlimitedHummus** [comment]
Hey, I would like to try to implement this. I might need some help, as this is my first contribution.

If I have questions, should I ask them here or in Zulip?

**Comment by afonso360** [comment]
Awesome! 🎉 

> If I have questions, should I ask them here or in Zulip?

Up to you, I'm available in both. I might be able to give you a faster reply on Zulip since that usually sends me a notification.

**Comment by aidenfoxivey** [comment]
@afonso360 Seems the same here - also complete.
