### ISSUE TITLE
aarch64: Add support for `fnmadd`/`fmsub`/`fnmsub`

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#8603]
👋 Hey,

#### Feature

Add support for the [`fnmadd`](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions/FNMADD--Floating-point-Negated-fused-Multiply-Add--scalar--) / [`fmsub`](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions/FMSUB--Floating-point-Fused-Multiply-Subtract--scalar--) / [`fnmsub`](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions/FNMSUB--Floating-point-Negated-fused-Multiply-Subtract--scalar--) instructions in the aarch64 backend.

#### Benefit

This improves instruction selection quality for a few special fma cases.

#### Implementation

We already have support for the scalar `fmadd` instruction [here](https://github.com/bytecodealliance/wasmtime/blob/e6f9ca5efa0c4bf59c9cf133d9abeaab63ec07bb/cranelift/codegen/src/isa/aarch64/lower.isle#L516-L517). So we adding support for these instructions should be a matter of introducing the new opcodes and implementing lowering rules similar to what already exists today.

Something similar was done in #8588 for the RISC-V backend. If anyone needs help implementing this, let me know!

**Comment by aidenfoxivey** [comment]
@afonso360 Seems like this issue is solved.

**Comment by afonso360** [comment]
That's right, thanks for letting me know!
