### ISSUE TITLE
pooling allocator should take virtual address space into account (on aarch64 and riscv64)

### ISSUE THREAD

**Issue by matsbror** [bytecodealliance/wasmtime#8607]
Thanks for filing a bug report! Please fill out the TODOs below.

### Test Case

Hello wasi http

### Steps to Reproduce

These steps fail on Ubuntu 24.04/riscv64 on VisionFive 2 and on Ubuntu 18.04/aarch64 on Nvidia Jetson Nano.

* Build the hello wasi http code as described [here](https://github.com/sunfishcode/hello-wasi-http)
* run `wasmtime serve target/wasm32-wasi/debug/hello_wasi_http.wasm` 

### Expected Results

I would have expected the tutorial to work as described. 

### Actual Results

```
jetson@360lab-nano2:~/docker/hello-wasi-http$ wasmtime serve -O pooling-allocator=y target/wasm32-wasi/debug/hello_wasi_http.wasm
Error: failed to create memory pool mapping                                                                                                                                                                                                     Caused by:
    0: mmap failed to reserve 0x5dc80000000 bytes
    1: Cannot allocate memory (os error 12)
```

When running without pooling allocator it works:

```
jetson@360lab-nano2:~/docker/hello-wasi-http$ wasmtime serve -O pooling-allocator=n target/wasm32-wasi/debug/hello_wasi_http.wasm
Serving HTTP on http://0.0.0.0:8080/
```

### Versions and Environment

Wasmtime version or commit: 21.0

Operating system: 
 - For RISCV64 Ubuntu 24.04 downloaded from [here](https://ubuntu.com/download/risc-v)
 - For Aarch64 Ubuntu 18.04 downloaded from [here](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write)

Architecture: 
 - Riscv64
 - Aarch64

### Extra Info

I guess there should be a way to detect the virtual address size as it seems to be around 39 bits in these architectures.

**Comment by alexcrichton** [comment]
In lieu of directly probing address space limitations I've opted to do something slightly different in https://github.com/bytecodealliance/wasmtime/pull/8610 which probes for a large reservation to succeed before attempting another one for the pooling allocator.

**Comment by matsbror** [comment]
Thanks. Will this also help spin, which uses wasmtime as library? The same error occurs there.

**Comment by alexcrichton** [comment]
Not directly, no, but I can propose the same change on Spin to have the same effect
