### ISSUE TITLE
Cranelift: `sret` argument without use causes bad SSA to be passed to regalloc

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/wasmtime#8659]
As reported by @bjorn3 just now, we get a compilation panic with the following:

```
test compile precise-output
target aarch64

function u0:11(i64 sret) system_v {
                                block0(v0: i64):
                                    nop
                                    jump block1

                                block1:
                                    nop
@0001                               return
}
```

This was bisected just now to #8438 (first failing in 3befbe52c9c50100300c3a00dac4c082ae5f36d9). @jameysharp, could you take a look? We should backport and do a point-release on the just-released Cranelift as well as @bjorn3 discovered this while trying to upgrade.

**Comment by alexcrichton** [comment]
I've killed the CI job doing today's release for now to help accomodate this.
