### ISSUE TITLE
Tests fail in WSL 2 (Pengwin Distribution)

### ISSUE THREAD

**Issue by sharpninja** [bytecodealliance/wasmtime#866]
# `crate test` fails on WSL2 on commit 16804673a2ce32d231cbf0d8954525adadcd00b9 in master

Getting latest from Github and performing `cargo test` fails on WSL2 (Pengwin).

## Environement

* Windows 10 20h1 (19551.1005) 
* pengwin-base:
  Installed: 0.1-309
  Candidate: 0.1-309
* rustc 1.40.0 (73528e339 2019-12-16)
* Intel Core i7 7700k
* 16GB RAM

## Steps Followed:

```bash
git clone --recursive https://github.com/bytecodealliance/wasmtime.git
git submodule update --remote
cargo test
```

The attached is a complete log of `cargo test`.
[wasm-failure.txt](https://github.com/bytecodealliance/wasmtime/files/4114295/wasm-failure.txt)

**Comment by alexcrichton** [comment]
Thanks for the report! I think though that the commands you're using to manage the git submodules may not be quite right? I followed them locally and it looks like they're checking out different revisions than we have pinned in this repository. 


I think you can drop the `git submodule update --remote` command, and you should be good to go!
