### ISSUE TITLE
Wasmtime-wasi fails to build on WASI itself

### ISSUE THREAD

**Issue by aruokhai** [bytecodealliance/wasmtime#8688]
### Test Case

Building  rust  crate `wasmtime-wasi = "21.0.1" in a project 
`
### Steps to Reproduce

- `rustup default stable `  
- `rustup target add wasm32-wasi`
- `cargo build --target wasm32-wasi`

### Expected Results

To build Without Error

### Actual Results

`error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/joshua/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-extras-0.18.2/src/lib.rs:21:41
   |
21 | #![cfg_attr(target_os = "wasi", feature(wasi_ext))]
   |                                         ^^^^^^^^`

### Versions and Environment

Wasmtime version or commit:  21.0.1

Operating system: Ubuntu 22.04.3 LTS

Architecture: amd64

cargo: 1.78.0

**Comment by sunfishcode** [comment]
The wasmtime-wasi crate contains a native-host implementation of WASI, and is not meant to be itself compiled to WASI. Could you say more about what you're looking to do here?

**Comment by aruokhai** [comment]
My understanding is that wasmtime-wasi library can be used to call wasi-0.2 api's in a project that is to be complied to WASI. Specifically I want to make use of the Socket api, which tokio doesn't seem to have implemented. If this is not the case, what options do I have .

**Comment by bjorn3** [comment]
You are probably looking for the wasi crate. The wasmtime-wasi crate contains the host implementation of wasi when using wasmtime. It is never used as part of your wasm module. The guest (wasm module) side bindings are provided by the wasi crate.

**Comment by aruokhai** [comment]
Oh ok, thanks a lot for clearing that up.
