### ISSUE TITLE
Cranelift: no_std builds fail.

### ISSUE THREAD

**Issue by Lucky4Luuk** [bytecodealliance/wasmtime#8696]
### Steps to Reproduce

* Add `cranelift-codegen = { version = "0.108.1", default-features = false, features = ["core"] }` to project dependencies.
* Attempt to compile for a no_std target.
* That's it.

### Expected Results

Library compiles and is usable.

### Actual Results

Long list of errors output while compiling, due to a dependency on arbitrary in cranelift-control. This library relies on the std.

### Versions and Environment

Cranelift version: 0.108.1

Operating system: Windows 10 x64.

Architecture: x86_64-unknown-none

**Comment by bjorn3** [comment]
Cranelift can't be compiled for no_std yet. Getting it working with no_std is tracked by https://github.com/bytecodealliance/wasmtime/issues/1158.

**Comment by Lucky4Luuk** [comment]
Then why is it marked as no_std on crates.io?

**Comment by bjorn3** [comment]
A couple of years ago it supported no_std, but as it wasn't being tested in CI, support for it broke. For a long while it wasn't fixed as the maintenance burden of no_std support was perceived to be too high. Only very recently has it been decided to add support for it back, but this hasn't been finished yet.

**Comment by Lucky4Luuk** [comment]
IMO it is worth taking off the tag from crates.io, just to avoid further questions like this in the future, until it actually supports no_std again. But thank you for the replies, I'll read through the thread and see if I can contribute.
