### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by pingiun** [bytecodealliance/wasmtime#8729]
The readme has a link to https://docs.wasmtime.dev/stability-wasm-proposals-support.html, which is 404 currently. 

This is from this part of the readme:
> [Standards Compliant](https://docs.wasmtime.dev/stability-wasm-proposals-support.html). Wasmtime passes...

**Comment by pingiun** [comment]
I wanted to read if wasmtime implements the webassembly 2.0 draft, but unfortunately that link doesn't have that info now

**Comment by pchickey** [comment]
Thanks for the bug report. The page you might be looking for might be this one: https://docs.wasmtime.dev/stability-tiers.html#current-tier-status describes which WebAssembly proposals are supported. I will fix the link in the readme to point there.

**Comment by pingiun** [comment]
Thank you, that's great!
