### ISSUE TITLE
Cranelift: failing assert during DWARF transform

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/wasmtime#8734]
### Steps to Reproduce

1. Download and unzip [this file](https://www.dropbox.com/scl/fi/2cq1fe6hio9i6dwl3y29n/runtime-eval.wasm.zip?rlkey=n8jfdr8jbjq49ook4s40uxrzt&dl=1).
2. With #8693 applied to current `main`, run the following:
```sh
wasmtime serve -S common -D debug-info runtime-eval.wasm
```

### Expected Results

Wasmtime serving the `runtime-eval.wasm` component as a `wasi:http/proxy` handler.

### Actual Results

A panic with the following output:
```
thread 'main' panicked at crates/cranelift/src/debug/transform/unit.rs:401:17:
assertion `left == right` failed
  left: StaticModuleIndex(1)
 right: StaticModuleIndex(0)
```

### Versions and Environment

Cranelift version or commit: See STR

Operating system: MacOS Version 14.5 (23F79)

Architecture: Aarch64

@alexcrichton this is the bug I mentioned that I encountered when trying #8693.

**Comment by alexcrichton** [comment]
Fixed now in the latest commits of https://github.com/bytecodealliance/wasmtime/pull/8693, thanks!
