### ISSUE TITLE
Wasmtime sets multiple `Host` header on `wasi-http` when guest specifies it. 

### ISSUE THREAD

**Issue by karthik2804** [bytecodealliance/wasmtime#8747]
It appears that wasmtime's implementation of outbound calls using `wasi-http` unconditionally set the `Host` header [here](https://github.com/bytecodealliance/wasmtime/blob/2fbc40ae3da0c1bad6f564c32eb240ec27632217/crates/wasi-http/src/http_impl.rs#L67). It then appears to iterate over the headers provided by the guest [here](https://github.com/bytecodealliance/wasmtime/blob/2fbc40ae3da0c1bad6f564c32eb240ec27632217/crates/wasi-http/src/http_impl.rs#L79-L81) leading to there being multiple host headers when the guest automatically sets a host header which is the case for apps built using [StarlingMonkey](https://github.com/bytecodealliance/starlingmonkey). 

This leads to certain servers rejecting the request because of duplicate headers. Should the guest not be setting a header or should wasmtime only set it conditionally?

**Comment by alexcrichton** [comment]
Wasmtime in theory should be stripping the host header [via functionality like this](https://github.com/bytecodealliance/wasmtime/blob/fa84dd83ba0f5c45bf0174bb5f988c215d848cfe/crates/wasi-http/src/types.rs#L115-L149). The issue of setting the host and port should be fixed through https://github.com/bytecodealliance/wasmtime/pull/8563 (which required a follow-up fix at https://github.com/bytecodealliance/wasmtime/pull/8671, but both should be in the 21.0.0 release).

Auditing a bit it looks like any guest-specified header goes through filtering before being inserted into `req.headers`, so now I'm also a bit confused how a second one could show up there.

Do you have an example guest which runs afoul of the double-host header?

**Comment by alexcrichton** [comment]
(and/or were y'all testing with 21.0.0? or an older version?)

**Comment by karthik2804** [comment]
We were testing with version `18.0.4`.

**Comment by alexcrichton** [comment]
Aha ok makes sense! The `Host` header was made "forbidden" in https://github.com/bytecodealliance/wasmtime/pull/7905 which was first landed in 19.0.x so I think this might be fixed with a wasmtime upgrade?

**Comment by karthik2804** [comment]
I can confirm that this issue has been fixed by upgrading to wasmtime 21.
