### ISSUE TITLE
Assertion failure generating debuginfo on a module with no functions

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#887]
Given this wasm file:

```wat
(module (memory 1))
```

This panics with:

```
$ wasmtime -g ./foo.wat
thread 'main' panicked at 'assertion failed: `(left > right)`
  left: `0`,
 right: `0`', crates/debug/src/lib.rs:72:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

cc @yurydelendik

**Comment by yurydelendik** [comment]
The assertion is right: we need to a) return early from the function keeping debug image empty, b) no invoke `emit_debugsections_image`.

Archeology discovered related #636, though it was not addressed properly. The proper way is to allow debug info with memory defined (or imported?) by reverting the #641, but disable the debug info when module has no functions.
