### ISSUE TITLE
What should the default behavior of `wasmtime serve` be with scheme/authority?

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#8878]
My changes in https://github.com/bytecodealliance/wasmtime/pull/8861 introduced a change in the default behavior of `wasmtime serve`. Notably this program:

```rust
use wasi::http::types::*;

struct T;

wasi::http::proxy::export!(T);

impl wasi::exports::wasi::http::incoming_handler::Guest for T {
    fn handle(request: IncomingRequest, outparam: ResponseOutparam) {
        println!("request.method = {:?}", request.method());
        println!("request.scheme = {:?}", request.scheme());
        println!("request.authority = {:?}", request.authority());

        let resp = OutgoingResponse::new(Fields::new());
        ResponseOutparam::set(outparam, Ok(resp));
    }
}
```

[(compiled component)](https://github.com/user-attachments/files/15995214/wat.wasm.gz)

When run with `wasmtime serve` and hit with `curl http://localhost:8080` it prints:

```
Serving HTTP on http://0.0.0.0:8080/
stdout [0] :: request.method = Method::Get
stdout [0] :: request.scheme = Some(Scheme::Http)
stdout [0] :: request.authority = Some("localhost:8080")
```

On `main`, however, it prints

```
Serving HTTP on http://0.0.0.0:8080/
stdout [0] :: request.method = Method::Get
stdout [0] :: request.scheme = None
stdout [0] :: request.authority = None
```

This regression is due to [these changes](https://github.com/bytecodealliance/wasmtime/pull/8861/files#diff-7da576f5c8e7ffe1f4d334844eec78ed27e092a9bacdad959a54468904d870b2L414) because I didn't understand what they were doing.

Now why wasn't this caught by the test suite? I tried writing a test for this and it passed, but apparently it's due to our usage of 
`hyper::Request::builder().uri("http://localhost/")` in the test suite. That creates an HTTP requests that looks like:

```
GET http://localhost/ HTTP/1.1
...
```

where using `curl` on the command line generates:

```
GET / HTTP/1.1
...
```

That leads me to this issue. What should `scheme` and `authority` report in these two cases for `wasmtime serve` by default? The previous behavior means that `GET /` could not be distinguished from `GET http://localhost/` which naively seems like what `scheme` and `authority` are trying to map to.

Is the previous behavior of `wasmtime serve` buggy? Is the current behavior buggy? Should the spec be clarified?

cc @elliottt @pchickey

**Comment by alexcrichton** [comment]
I'll note that the difference can be seen with:

```
$ curl -v --request-target http://localhost/ http://localhost:8080
```

vs 

```
$ curl -v http://localhost:8080
```

in terms of how the headers are set. The former is basically what our test suite does while the latter is what the `curl` command line does by default.

**Comment by lann** [comment]
The former (full URL in request) is incorrect; that form is only applicable to CONNECT methods.

**Comment by lann** [comment]
The former (full URL in request) is incorrect; that form is only applicable to CONNECT methods.

Edit: looks like I might be wrong about it being incorrect per se; it might just be very uncommon.

**Comment by alexcrichton** [comment]
That makes sense, and means we should probably update our tests, but I guess I'm also curious still what the behavior here should be. For example why do `scheme` and `authority` return an `Option` at the WIT level? Are they intended to map to this or is it expected that they're effectively always `Some`?

**Comment by lann** [comment]
`scheme` is derived from out of band info: whether the request came in over TLS or not

**Comment by tschneidereit** [comment]
my take is that we should have wasi:http either always provide an authority, or provide the `host` header. Otherwise there's no standard way for content to learn about the authority it's called under. I know that @lukewagner concluded that we must never provide the `host` header. If that stands, I conversely think that we must continue providing the authority for incoming requests.

In effect, that means that for incoming requests what content sees is always the `absoluteURI` form, which the RFC seems to indicate is the way forward, too:
> To allow for transition to absoluteURIs in all requests in future
   versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI
   form in requests, even though HTTP/1.1 clients will only generate
   them in requests to proxies.

**Comment by lann** [comment]
Don't pay too much attention to the 1.1 spec for future direction. HTTP/2 makes authority even more special by splitting it into a "pseudo-header".

**Comment by lukewagner** [comment]
Great question.  First of all, from asking some HTTP folks, I believe it is the case that we could tighten the spec wording to say that for methods other than CONNECT and OPTIONS, there must *always* be an `authority` (i.e., the return value is `some`).  Apparently, CONNECT and OPTIONS have an unfortunate `*` option that simply has no authority.

Next, my understanding from RFC 9110 is that the `authority` either comes from the `:authority` pseudo-header in H/2/3 or the `Host` header in H/1, and if both are present, they are not allowed to disagree (and this is Web-compatible).  Thus, I think what WASI HTTP should say is that:
* `Host` is in the definitely-forbidden headers list
* The `request.authority` field is derived in a transport-dependent manner (and required to be present for non-CONNECT/OPTIONS)

This allows the host implementation to do the transport-appropriate thing for requests coming in or out over the wire.

**Comment by alexcrichton** [comment]
Ok so for the use case of `wasmtime serve` specifically:

* `[method]incoming-request.scheme` is always `some(http)` because we don't implement https yet
* `[method]incoming-request.authority` uses the incoming URI's host if it's there (probably only for CONNECT and OPTIONS). Otherwise it uses `Host`, otherwise it returns .... None? `"127.0.0.1"`? The value of `--addr`?

This all indicates to me that [`new_incoming_request`](https://docs.rs/wasmtime-wasi-http/latest/wasmtime_wasi_http/trait.WasiHttpView.html#method.new_incoming_request) should take both a `scheme` and an `authority` argument rather than inferring these from the `Request` as well?

(sorry I'm really looking for guidance/second opinions here, I don't know why things were originally constructed the way they are or if they're just how things got shaken out)

**Comment by lann** [comment]
> otherwise it returns .... None?

Do we want/need to support HTTP/1.0? afaik `host` is mandatory for 1.1

**Comment by alexcrichton** [comment]
Ah ok I didn't realize that was a 1.0 thing. Sounds like it should search for `Host` as a header in the host-side `hyper::Request` for the authority if it's not present in the URI. I try to make a PR with these changes tomorrow.

**Comment by lukewagner** [comment]
The impression that I got talking to an HTTP server maintainer is that it's web-compatible to require the `Host` field (rejecting if it's absent in HTTP 1.0 or 1.1) and that allowing an empty `authority` in cases other than CONNECT/OPTIONS can transitively lead to security issues (random googling found [this](https://medium.com/the-volatile-triad/hacking-the-blank-host-header-trick-e280efbaf274) e.g.).  Similarly, RFC 9110 (which also intends to be Web-compatible) says that there [MUST](https://www.rfc-editor.org/rfc/rfc9110#name-host-and-authority) be a `Host` header (when there is no `:authority` pseudo-header) without making an exception for HTTP 1.0.  Thus, I'd suggest making it an error in `wasmtime serve` if there is no `Host` in HTTP 1.0, at least to start with, and see if anyone complains.
