### ISSUE TITLE
how can I access file system with k8s?

### ISSUE THREAD

**Issue by BhavinPrajapti** [bytecodealliance/wasmtime#8880]
I have installed wasmtime, wasmedge runtime in my k8s node. 

for the normal hello-world application, I created OCI image as per below file.

FROM scratch
ADD hello-wasm.wasm /
CMD ["/hello-wasm.wasm"]   

since wasmtime, wasmedge runtime is running on my node so this is working.  
but how can i access file system? anyone have some reference tutorial or github link for this type of implementation?

**Comment by alexcrichton** [comment]
Thanks for the report, but this might be an issue best reported to the k8s integration with Wasmtime. Such integration is not maintained here. The `wasmtime`-CLI answer to your question is the `--dir` flag, but I don't know how such a flag integrates with the k8s pieces.

**Comment by bacongobbler** [comment]
More specifically, WasmEdge's github repository can be found here: https://github.com/WasmEdge/WasmEdge

**Comment by tschneidereit** [comment]
I think the question has been answered as much as we can answer it here.
