### ISSUE TITLE
Cannot Compile "wasi-common" When Building

### ISSUE THREAD

**Issue by elithrar** [bytecodealliance/wasmtime#892]
Summary: Running `cargo build --release` on v0.8.0 and HEAD (ea4faa4a01bc268b418f6a574d4464b78aaa5793) fails to build with a macro panic.

Error:

```
elithrar@wasi-builder:~/wasmtime$ cargo build --release
   Compiling serde v1.0.104
warning: The spec testsuite is disabled. To enable, run `git submodule update --remote`.
   Compiling wasi-common v0.8.0 (/home/elithrar/wasmtime/crates/wasi-common)
error: proc macro panicked
  --> crates/wasi-common/src/host.rs:11:1
   |
11 | witx_host_types!("snapshot" "wasi_snapshot_preview1");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: error opening file /home/elithrar/wasmtime/crates/wasi-common/WASI/phases/snapshot/witx/wasi_snapshot_preview1.witx: with file "/home/elithrar/wasmtime/crates/wasi-common/WASI/phases/snapshot/witx/wasi_snapshot_preview1.witx": No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `wasi-common`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Rust versions:

* Both stable - `stable installed - rustc 1.41.0 (5e1a79984 2020-01-27)`
* And nightly - `1.42.0-nightly (cd1ef390e 2020-01-31)`

Note: I'm far from a Rust expert, but I'm attempting to build a WASI binary via the rust wasm32-wasi target (works) and then run it locally (Ubuntu 19.10) via wasmtime (fails).

**Comment by gatesn** [comment]
I believe you need to run:

`git submodule update —init —recursive`

**Comment by elithrar** [comment]
Works, thanks! Missed that with the cargo output.

Submitted #893 to document the from-source build process more fully as well
