### ISSUE TITLE
Error while building wasmtime

### ISSUE THREAD

**Issue by celinesantosh98** [bytecodealliance/wasmtime#8930]
Hi

I am celine, master student of saarIand university, Germany. I am currently working on my thesis and I use wasmtime as a part of it. I was trying to build wasmtime on macOS.
I have cloned the repo first and then ran cargo build.
I got the following error

error: failed to parse manifest at `/Users/celinesantosh/Desktop/sem_5/wasmtime/Cargo.toml`

Caused by:
  invalid type: map, expected SemVer version for key `package.version`
  
  Any help would be appreciated.
  
  Thanks in advance.

**Comment by bjorn3** [comment]
You likely have a too old rustc version installed. The latest Wasmtime version needs rustc 1.77.0 or later.

**Comment by alexcrichton** [comment]
Agreed that the issue is likely a too-old rustc. I'm going to close this since I believe that's the solution, but if there are still other issues feel free to comment here or open another issue

**Comment by celinesantosh98** [comment]
Thanks a lot . Compiled successfully now.
