### ISSUE TITLE
Overriding `argv[0]` for `wasmtime run`

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime#8955]
#### Feature

I would like it to be possible to override `argv[0]` for commands executed with `wasmtime run`. E.g.:

```
wasmtime run --argv0=clang++ bin/clang.wasm ...
```

#### Benefit

Certain applications use the value of `argv[0]` to:
- Dispatch between incompatible code paths (multi-call binaries), e.g. Clang;
- Discover location of data via executable-relative paths, e.g. also Clang in some cases (not the usual configuration though).

In general I think the path passed to `wasmtime run` is only meaningful on the host and will rarely if ever mean anything within the sandbox.

#### Implementation

A new option `--argv0=` would work for me, but really anything that gets the job done is fine.

#### Alternatives

I can't think of any besides not having the functionality.

**Comment by alexcrichton** [comment]
This sounds reasonable to me to implement as well, and I think `--argv0` is a fine name as well. We already infer it from the provided wasm module so providing the ability to customize that seems like a good idea.

**Comment by whitequark** [comment]
I was going to implement it originally, but unfortunately I lost the direct motivation for this as I've moved to shipping the combined LLVM compiler driver (the `llvm` command, if you've seen it, as it's a bit obscure... it's like `busybox`) which takes the command to invoke as `argv[1]`.

**Comment by whitequark** [comment]
Thank you!
