### ISSUE TITLE
Does Cranelift honour the requirement of WebAssembly that NaN results of most float ops must be arithmetic?

### ISSUE THREAD

**Issue by primoly** [bytecodealliance/wasmtime#8967]
NaNs in IEEE floats are encoded just like infinities, except that at least one of the mantissa bits is set to one. Wasm NaNs in results of float ops (_except_ `fabs`, `fneg` and `fcopysign`) have the additional requirement that the most significant bit of the mantissa must be one (arithmetic NaN). Is this actually honoured by Cranelift codegen? If NaNs are always canonicalised then this is guaranteed (as the canonical NaN is also an arithmetic one), but if NaNs are simply propagated then this could be an issue.

https://webassembly.github.io/spec/core/exec/numerics.html#nan-propagation
https://webassembly.github.io/spec/core/syntax/values.html#syntax-float
https://webassembly.github.io/spec/core/syntax/values.html#arithmetic-nan

**Comment by cfallin** [comment]
(As an additional note, I'd be surprised if Wasm were spec'd in such a way that e.g. a `f32.add` required more than a bare FP add instruction on common ISAs -- that would seem to go against the "predictable performance" design, and I haven't seen "ensure it's an arithmetic NaN" logic in other engines -- but this is good to double-check.)

**Comment by fitzgen** [comment]
> (As an additional note, I'd be surprised if Wasm were spec'd in such a way that e.g. a `f32.add` required more than a bare FP add instruction on common ISAs -- that would seem to go against the "predictable performance" design, and I haven't seen "ensure it's an arithmetic NaN" logic in other engines -- but this is good to double-check.)

+1 to this; I'd also be very surprised.

**Comment by afonso360** [comment]
For RISC-V the behavior is fairly straightforward. (See §21.3. "NaN Generation and Propagation" of the [ISA Unprivileged Manual](https://github.com/riscv/riscv-isa-manual/releases/tag/riscv-isa-release-982eac4-2024-07-16))

> Except when otherwise stated, if the result of a floating-point operation is NaN, it is the canonical
NaN. The canonical NaN has a positive sign and all significand bits clear except the MSB, a.k.a. the
quiet bit. For single-precision floating-point, this corresponds to the pattern 0x7fc00000

AFAIK the exceptions to this are `fmin`/`fmax` and the sign injection instructions.

So I think this is compliant with the WASM Spec directly, and for `fmin`/`fmax` we do some corrections.

**Comment by uweigand** [comment]
The s390x ISA does not use the term "arithmetic NaN".  However, the definition of this term in the WebAssembly spec (most significant payload bit is 1) corresponds exactly to what the s390x ISA calls "quiet NaN":

>There are two types of NaNs, signaling and quiet. A signaling NaN (SNaN) is distinguished from the corresponding quiet NaN (QNaN) by the leftmost fraction bit: zero for the SNaN and one for the QNaN. A special QNaN is supplied as the default result for an IEEE-invalid-operation exception; it has a plus sign and a leftmost fraction bit of one, with the remaining fraction bits being set to zeros.

The ISA guarantees that the result of any floating-point instruction (except those only manipulating the sign bit) will always be a quiet NaN (if it is a NaN).   More specifically if the output is a NaN, it is either a copy of one of the input operands (possibly transformed from a signaling NaN to a quiet NaN), or else the default NaN described in the quote above (which corresponds to what WebAssembly calls the "canonical NaN").

Given that behavior of the ISA, it seems unlikely that code generated by the wasmtime backend would ever be able to violate the WebAssembly NaN propagation rules on s390x (although I haven't explicitly verified all patterns).
