### ISSUE TITLE
Does wasmtime support interpreter?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [bytecodealliance/wasmtime#8984]
Does wasmtime support an interpreter for executing Wasm binaries, or does it only support Ahead-of-Time (AOT) compilation for executing Wasm binaries?

**Comment by bjorn3** [comment]
Currently Wasmtime can only compile wasm binaries to machine code, but a wasm interpreter is in the works: https://github.com/bytecodealliance/rfcs/pull/35

**Comment by Userzxcvbvnm** [comment]
Does that means wasmtime support JIT and AoT?

**Comment by bjorn3** [comment]
Wasmtime already supports JIT.

**Comment by alexcrichton** [comment]
I believe the question here was answered, so I'm going to close this.
