### ISSUE TITLE
Wasmtime support for AWS Graviton

### ISSUE THREAD

**Issue by chwanshu27** [bytecodealliance/wasmtime#8998]
Thanks for filing a feature request! Please fill out the TODOs below.

#### Feature

TODO: Does wasmtime has support for Graviton? If yes, can you please share some doc and if not, then is there any plan for supporting AWS Graviton.

#### Benefit

TODO: AWS Graviton is a new set of processors which is optimized for cloud workloads and many businesses are planning to move towards it.

#### Implementation

TODO: No

#### Alternatives

TODO: NA

**Comment by bjorn3** [comment]
Arm64 is supported by Wasmtime.

**Comment by chwanshu27** [comment]
Thanks for the confirmation!
