### ISSUE TITLE
unresolved import `wasmtime_asm_macros::asm_sym`

### ISSUE THREAD

**Issue by TheAwiteb** [bytecodealliance/wasmtime#9028]
In [asm-macros], there is no function named `asm_sym`. However, it is imported in [fiber/src/unix/x86.rs] but remains unused.

[asm-macros]: https://github.com/bytecodealliance/wasmtime/blob/d8f7c77f8f8dbeadfee0e6ab052e57f11800dfe9/crates/asm-macros/src/lib.rs
[fiber/src/unix/x86.rs]: https://github.com/bytecodealliance/wasmtime/blob/d8f7c77f8f8dbeadfee0e6ab052e57f11800dfe9/crates/fiber/src/unix/x86.rs

**Comment by bjorn3** [comment]
Wasmtime doesn't support 32bit x86, so when the x86_64 version was changed, the 32bit x86 versiob of this wasmtime-fiber likely wasn't changed, but due to the lack of 32bit x86 support of Wasmtime in general, this wasn't noticed in CI.

**Comment by TheAwiteb** [comment]
> Wasmtime doesn't support 32bit x86

Yes, I'm aware of that. However, by addressing this issue, wasmtime will be able to provide a clear error message indicating that this architecture is not supported.

```
error: Wasmtime is being compiled for an architecture that it does not support. If this architecture is one you would like to see supported you may file an issue on Wasmtime's issue tracker: https://github.com/bytecodealliance/wasmtime/issues/new
```

**Comment by alexcrichton** [comment]
I've submitted https://github.com/bytecodealliance/wasmtime/pull/9035 to add CI checks for wasmtime-fiber on i686/arm but yes Wasmtime doesn't support 32-bit. After that PR the error in the Wasmtime crate should show up.
