### ISSUE TITLE
Panic on modules containing an `anyref` local

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#905]
Given an input module such as:

```wat
(module (func (local anyref)))
```

this will fail with:

```
$ cargo run foo.wat
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/wasmtime ./foo.wat`
thread 'main' panicked at 'reference types were found but safepoints were not enabled.', /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.56.0/src/regalloc/context.rs:219:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

@yurydelendik is this perhaps a bug in `wasmparser` where an `anyref` local is accepted, despite validation not having reference types enabled?

**Comment by yurydelendik** [comment]
> is this perhaps a bug in wasmparser where an anyref local is accepted, despite validation not having reference types enabled?

"reference types were found but safepoints were not enabled" comes from cranelift -- the safepoints needs to be enabled for function with reference types. See also https://github.com/bytecodealliance/cranelift/pull/1073#issuecomment-534955132

**Comment by alexcrichton** [comment]
That's true yeah, but we shouldn't support reference types at all right now in theory. I would have expected that `wasmparser`'s validation of the module would fail since an `anyref` local was used, but we didn't enable reference types in the list of features
