### ISSUE TITLE
large enums slow down compilation

### ISSUE THREAD

**Issue by MatthiasGrandl** [bytecodealliance/wasmtime#9081]
Related to https://github.com/bytecodealliance/wit-bindgen/issues/1019

I have a large enum with 1424 cases. While it's completely broken on the client side, it works as expected on the host side, but compilation takes ages. On this Macbook Pro M3 Pro it takes 1 minute longer on a fresh compile than without the enum.

I attached the wit for testing.

[icons.wit.txt](https://github.com/user-attachments/files/16509148/icons.wit.txt)

**Comment by alexcrichton** [comment]
I've tested that with #9122 the enum in question goes from generating 80_000 lines of code to 8_000 lines of code, which should be a large improvement. When that lands though can you confirm that it improves things locally as well? If the compile time is still too long I'll look into this further and see what else is generating a lot of code.

**Comment by MatthiasGrandl** [comment]
@alexcrichton I would be happy to test it!

**Comment by MatthiasGrandl** [comment]
@alexcrichton tested the changes and they definitely solved my issue! thanks a lot!

**Comment by alexcrichton** [comment]
Great, thanks for testing!
