### ISSUE TITLE
export func authentication

### ISSUE THREAD

**Issue by itachaaa** [bytecodealliance/wasmtime#9095]
When the WASM plug-in calls back the host, is there a way to know which WASM plug-in is on the host side, so as to authenticate different WASM plug-ins, to ensure that the interface exposed by the host does not have the problem of permission leakage.

**Comment by alexcrichton** [comment]
For this it's recommended to store state in the `T` of `Store<T>`. Does that work for you?

**Comment by itachaaa** [comment]
> For this it's recommended to store state in the `T` of `Store<T>`. Does that work for you? 重试    错误原因

We've tried that too, and it probably won't solve the problem. Because T is shared in the store, different instances in the same store may tamper with this T to bypass our authentication rules.
I'm curious if there's a way to automatically bring up the module name interface or capability when calling back the host method.

**Comment by nerdachse** [comment]
> For this it's recommended to store state in the `T` of `Store<T>`. Does that work for you?

Could you elaborate a bit on this please?

I don't see right now how that data could be relied on and have a very, very similar "problem"/question to the Op
