### ISSUE TITLE
Option to turn off and clear automatic module caching to ~/.cache/wasmtime/modules/wasmtime-

### ISSUE THREAD

**Issue by guest271314** [bytecodealliance/wasmtime#9103]
Thanks for filing a feature request! Please fill out the TODOs below.

#### Feature

Option to turn off and clear automatic module caching to `~/.cache/wasmtime/modules/wasmtime-`.

#### Benefit

When testing the contents of `~/.cache/wasmtime/modules/wasmtime-` can continue to grow exponentially.

#### Implementation

Add an option to 

1. Run the `.wasm` file directly without caching
2. Option to automatically remove the cached folders and files after the `.wasm` file is run
3. Option to remove the contents of `wasmtime` cached modules, e.g., with Bun we can do `bun pm cache rm`

#### Alternatives

Unknown.

**Comment by bjorn3** [comment]
You can disable the cache globally by writing

```toml
[cache]
enabled = false
```

to `~/.config/wasmtime/config.toml`.

To disable the cache for a single invocation use `-C cache=n`. To remove the cache you can remove the `~/.cache/wasmtime` directory.

**Comment by guest271314** [comment]
@bjorn3 That works. I had to create the `~/.config/wasmtime` directory and `config.toml` file. Is this documented somewhere here?

**Comment by bjorn3** [comment]
The `wasmtime config new` command creates this file with the default configs filled in. It also prints the path to the config file it created.

**Comment by guest271314** [comment]
Thanks.

Would help if the content of the wasmtime "guide" was conspicuously in the README. 

I still don't know what `wasmtime-min` does and how to use that executable.

**Comment by bjorn3** [comment]
> I still don't know what wasmtime-min does and how to use that executable.

It is the wasmtime executable, except with every optional feature (like wasi support) disabled and optimized for size. You should ignore it unless you actually need a tiny wasmtime binary for some reason.

**Comment by guest271314** [comment]
> You should ignore it unless you actually need a tiny wasmtime binary for some reason.

Testing.

> except with every optional feature (like wasi support) disabled

I guess that explains why `wasmtime-min` doesn't execute code compiled with `javy`.
