### ISSUE TITLE
Small wasm modules taking excessive amounts of time to compile

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#911]
In reviewing some fuzz bugs we've got a good number of test cases that end up timing out unfortunately. I believe that cranelift has a number of known issues about the speed of its compilation, particularly around register allocation. I figure it'd be good to collect a few concrete wasm files (discovered from fuzzing) which take an abnormally long amount of time to compile compared to the size of the input.

It's worth noting that the timeout on the fuzzers is relatively high, I think something like 30 or 60 seconds. When fuzzing though [binaries can be up to 50x slower](https://github.com/rust-fuzz/cargo-fuzz/issues/216) which means our time budget for passing the fuzzers is pretty small, generally less than 3 seconds I think (ish). It's also worth noting that fuzzers are compiled with debug assertions enabled, which enables, well, debug assertions, but also the cranelift verifier pass. I've seen the verifier pass be quite expensive on some of these modules below, but in general the modules without the verifier pass still take an abnormally long amount of time to compile.

For the files below I'm testing with:

```
$ cargo build --release && time ./target/release/wasmtime --disable-cache ./foo2.wasm 
```

most of them fail to instantiate or run, but it's the compilation which largely matters here which all happens as part of `time`. Which is to say you can ignore the errors of the CLI generally

* [file1.wasm[1].gz](https://github.com/bytecodealliance/wasmtime/files/4166418/file1.wasm.1.gz) - takes 1s locally. Profiling shows lots of time in the register allocator.
* [file2.wasm[1].gz](https://github.com/bytecodealliance/wasmtime/files/4166471/file2.wasm.1.gz) - this takes 300ms locally, but with the verifier and debug assertions enabled takes about 1s. The time looks to be largely in the verifier/register allocator like before.
* [file3.wasm[1].gz](https://github.com/bytecodealliance/wasmtime/files/4166505/file3.wasm.1.gz) - same as previous
* [file4.wasm[1].gz](https://github.com/bytecodealliance/wasmtime/files/4166506/file4.wasm.1.gz) - same as previous

I'm assuming that there's generally not a huge amount we can do about this. When cranelift is looking to benchmark new register allocator implementations, however, we can perhaps use the files here as test beds to see how things are improving?

In any case I figure it's good to start tracking files as we come across them if we can.

**Comment by fitzgen** [comment]
cc @bnjbvr -- making sure you see this ;)

**Comment by alexcrichton** [comment]
[testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4232245/testcase0.wasm.gz)

Another test case found from fuzzing, this one takes 1.5s to compile locally

**Comment by alexcrichton** [comment]
[testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4232296/testcase0.wasm.gz)

And one more which takes ~1.2s for me, also found through fuzzing

**Comment by fitzgen** [comment]
> [testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4232245/testcase0.wasm.gz)
> 
> Another test case found from fuzzing, this one takes 1.5s to compile locally

From `wasm-objdump`, it looks like this has a relatively large number of elements:

```
 - segment[0] table=0 count=175617 - init i32=0
```

Everything else about it seems reasonably sized.

**Comment by alexcrichton** [comment]
Ah yeah FWIW I'm testing these and they're all still taking a long amount of time in the register allocator in cranelift, so this is basically just a collection of cases to "see if the new cranelift register allocator is fast" as opposed to new and novel bugs

**Comment by alexcrichton** [comment]
Here's another case which takes about a half second locally, although this one is pretty different from the previous ones. This one is just one function with about 20k instructions, a huge number of which are just constants with some `trunc` instructions thrown in for flavor. All results of the function are basically thrown away, but it looks like a disproportionately large time is spent compiling it, mostly in `cranelift_codegen::ir::layout::Layout::split_block` according to `perf` (as well as `cranelift_codegen::flowgraph::ControlFlowGraph::compute_block` to a lesser extent)

[foo.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4276234/foo.wasm.gz)

**Comment by bnjbvr** [comment]
Noted, thanks for the pings! I'll make sure to revisit these test cases once we have isel and regalloc in a position where we can test useful benchmarks.

**Comment by fitzgen** [comment]
Here is another test case that hangs in register allocation: [slow-regalloc.wat.gz](https://github.com/bytecodealliance/wasmtime/files/4308387/slow-regalloc.wat.gz)

**Comment by fitzgen** [comment]
Here is another that hangs in register allocation: [testcase1.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4339762/testcase1.wasm.gz)

Wondering if some of these might be the same as https://github.com/bytecodealliance/wasmtime/issues/1306...

**Comment by alexcrichton** [comment]
[foo.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/4403805/foo.wasm.gz)

Another fuzz bug that came up over the weekend, again looks like it's largely register allocation.

**Comment by julian-seward1** [comment]
Note that https://github.com/bytecodealliance/regalloc.rs/pull/89 fixes extreme slowness in the new regalloc's coalescing analysis, that was reported for some of the examples listed here.

**Comment by julian-seward1** [comment]
With the abovementioned fix (regalloc.rs PR89) in place, having looked at the profiles on one of these cases, I reckon we could probably chop another 10% off the allocation costs by rewriting the allocator's `avl_tree.rs` `fn insert_wrk` to be non-recursive.  Not sure if this is really worth it though; these test cases are pretty artificial -- a function with 2 basic blocks containing in total 400000+ instructions, including several tens of thousands of calls.

**Comment by alexcrichton** [comment]
FWIW these are all fuzz bugs so it's not like they're representative of actual code. If they're generating ridiculously large functions it may be that we just need to tweak the fuzzer limits, so once your patch lands seems reasonable to basically close this out!

**Comment by alexcrichton** [comment]
Another fuzz bug: 
[foo.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/5449653/foo.wasm.gz)

**Comment by alexcrichton** [comment]
Another fuzz bug that cropped up today - https://gist.github.com/alexcrichton/fc234498ac40b718ed2d1b0aead6bc79

**Comment by alexcrichton** [comment]
Another fuzz bug today - [testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/7847535/testcase0.wasm.gz)

**Comment by alexcrichton** [comment]
[testcase70.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8198784/testcase70.wasm.gz)

Here's another test case:

```
$ time RAYON_NUM_THREADS=1 cargo run --release -- compile --wasm-features multi-memory,memory64 testcase70.wasm --fuel 0 --epoch-interruption --interruptable
RAYON_NUM_THREADS=1 cargo run --release -- compile --wasm-features   --fuel 0  3.45s user 0.10s system 99% cpu 3.553 total
```

This one is a fuzz bug where lots of instrumentation was enabled (three separate ways of interrupting a module), which blows up compile time by quite a lot. Simply adding fuel is enough to make the compile time somewhat excessive at 2 seconds, though, so there may be other cranelift things here. `perf` still shows everything in register allocation right now

**Comment by alexcrichton** [comment]
Another fuzz bug [foo.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8198900/foo.wasm.gz)

```
$ time RAYON_NUM_THREADS=1 perf record ./target/release/wasmtime compile foo.wasm --wasm-features memory64,multi-memory
RAYON_NUM_THREADS=1 perf record ./target/release/wasmtime compile foo.wasm    2.05s user 0.15s system 70% cpu 3.121 total
```

(all in regalloc again)

**Comment by alexcrichton** [comment]
Another fuzz bug: [testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8216545/testcase0.wasm.gz)

```
$ time RAYON_NUM_THREADS=1 ./target/release/wasmtime compile --wasm-features multi-memory,memory64 testcase0.wasm
RAYON_NUM_THREADS=1 ./target/release/wasmtime compile --wasm-features    0.63s user 0.00s system 99% cpu 0.634 total
```

**Comment by alexcrichton** [comment]
Another: [testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8216572/testcase0.wasm.gz)
 
```
$ time RAYON_NUM_THREADS=1 ./target/release/wasmtime compile testcase0.wasm
RAYON_NUM_THREADS=1 ./target/release/wasmtime compile testcase0.wasm  1.91s user 0.00s system 99% cpu 1.911 total
```

**Comment by alexcrichton** [comment]
Another: [testcase3.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8225781/testcase3.wasm.gz)

```
$ time ./target/release/wasmtime compile testcase3.wasm
./target/release/wasmtime compile testcase3.wasm  3.21s user 0.02s system 100% cpu 3.207 total
```

**Comment by alexcrichton** [comment]
Another: [testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8246482/testcase0.wasm.gz)
 
```
$ time RAYON_NUM_THREADS=1 wasmtime compile testcase0.wasm --wasm-features multi-memory,memory64
RAYON_NUM_THREADS=1 wasmtime compile testcase0.wasm --wasm-features   5.13s user 0.22s system 99% cpu 5.355 total
```

**Comment by alexcrichton** [comment]
[foo.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8264977/foo.wasm.gz)


```
$ time RAYON_NUM_THREADS=1 cargo run -q --release compile foo.wasm
RAYON_NUM_THREADS=1 cargo run --release compile foo.wasm  1.58s user 0.04s system 99% cpu 1.629 total
```

**Comment by alexcrichton** [comment]
⚠️⚠️⚠️⚠️⚠️ 

[testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8326206/testcase0.wasm.gz)

```
$ time wasmtime compile testcase0.wasm
wasmtime compile testcase0.wasm  100.89s user 0.02s system 100% cpu 1:40.89 total
```

**Comment by alexcrichton** [comment]
[testcase0.wasm.gz](https://github.com/bytecodealliance/wasmtime/files/8382110/testcase0.wasm.gz)


```
$ time wasmtime compile testcase0.wasm
wasmtime compile testcase0.wasm  4.84s user 0.00s system 100% cpu 4.829 total
```

**Comment by alexcrichton** [comment]
I'm going to close this given the discussion on https://github.com/bytecodealliance/wasmtime/issues/4060, these sorts of outliers are expected and eventually we'll want to tweak fuzzers to not generate these patterns of code.
