### ISSUE TITLE
Add Tail Call Optimization

### ISSUE THREAD

**Issue by ValorZard** [bytecodealliance/wasmtime#9142]
#### Feature
Add [Tail Call Optimization](https://v8.dev/blog/wasm-tail-call)

#### Benefit

I'm mostly interested in this so I could use [Guile Hoot](https://gitlab.com/spritely/guile-hoot) with wasmtime. Guile Hoot is an implementation of Scheme that compiles down to WebAssembly and requires the features WasmGC and Tail Call Optimization. The former is already being worked on, but I can't find anything relating to the latter.

#### Implementation
No idea! Look at how Firefox and Chrome implemented it I guess?

#### Alternatives
No idea, this is a core WASM feature I'm pretty sure.

**Comment by cfallin** [comment]
Wasmtime actually supports the Wasm tail call instructions today! Let us know if you have any issues with them.

**Comment by cfallin** [comment]
And to cross-link this a bit: #1065 tracked tail-call implementation (completed last May); #6530 added the feature on the last platform (s390x) that came a bit after the rest.

**Comment by ValorZard** [comment]
Ah okay! I guess i didnt see it since i was specifically looking for "tail call optimization." Guess I just gotta wait for the GC!
