### ISSUE TITLE
Add WASI apis to async component

### ISSUE THREAD

**Issue by seogrady** [bytecodealliance/wasmtime#9205]
Hello 👋 I'm new to wasmtime and have some questions after going through the examples. It looks like wasi-common is being deprecated in favor of wasmtime-wasi. There's a few different options such as wasmtime_wasi, wasmtime_wasi::preview0 and wasmtime_wasi::preview1. You can build a wasi_ctx with WasiCtxBuilder::new().build() or WasiCtxBuilder::new().build_p1(). Is there an example component using the latest preview?

I've managed to convert the provided component example from wasi-common to use wasmtime_wasi with async enabled.
```
bindgen!({
    world: "convert",
    path: "../wasi-component/wit",
    // tracing: true,
    async: {
        only_imports: [],
    },
    trappable_imports: true,
    require_store_data_send: true,
});
```

What do I need to do in order to get basic APIs working like stdio? I've tried adding inherit_stdio `WasiCtxBuilder::new().inherit_stdio().build()` to WasiCtxBuilder. Do I need to specify in the WIT file as well? 🙏

**Comment by alexcrichton** [comment]
There are some examples in [the documentation](https://docs.rs/wasmtime-wasi) of the `wasmtime-wasi` crate throughout various functions such as [`add_to_linker_async`](https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/fn.add_to_linker_async.html). Does that satisfy what you need? Or is there something else you're curious about?
