### ISSUE TITLE
Help wanted: How to pass a string from wasm to rust?

### ISSUE THREAD

**Issue by LeviLovie** [bytecodealliance/wasmtime#9212]
I'm sorry to disturb, if that is written somewhere. I'm having problem with passing strings from wasm to rust. Thank you

**Comment by alexcrichton** [comment]
Does the [fourth example here](https://docs.rs/wasmtime/latest/wasmtime/struct.Func.html#examples-2) help?

**Comment by LeviLovie** [comment]
Yes, thank you!
