### ISSUE TITLE
Dropping a `Module` doesn't free its JIT memory

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#925]
Running this code for example:

```rust
use wasmtime::*;

fn main() {
    let store = Store::default();
    loop {
        drop(Module::new(&store, "(module (func i32.const 0 drop))").unwrap());
    }
}
```

will cause the program to infinitely consume memory.

I believe the issue here is that compiled code is always appended to a new `CodeMemory` instance inside of the shared data within a `Store`, and that's never cleaned up.

**Comment by alexcrichton** [comment]
I should note that if you do indeed drop `Store` then everything does appear to get cleaned up.

**Comment by sunfishcode** [comment]
The origin for this is a design that anticipates handing out plain Rust function pointers to JIT'd functions, and since Rust's lifetime system doesn't cover code, it can't safely prevent these references from outliving the underlying memory.

**Comment by alexcrichton** [comment]
Ah yeah that makes sense, but to clarify do you think we should change the behavior of the code above to not leak memory until the `Store` is dropped? We would indeed have to be particularly careful about the lifetime of data involved, and I can see a few hazards already, but I think it's all surmountable.

**Comment by sunfishcode** [comment]
Yes, it does make sense to drop the memory when the `Module` is dropped (unless we want to cache JIT code in memory, but that's a separate feature), provided we can make it safe.

**Comment by joshtriplett** [comment]
@sunfishcode By "doesn't cover code", do you mean that a normal Rust function pointer doesn't have a lifetime? That's true, but we could potentially create a function pointer type that does, and still keep it conveniently callable. Seems potentially worth doing, so that we can delegate "when can we drop this" to rustc.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/bytecodealliance/wasmtime/issues/960 since it's highly related to that sort of memory management, and it sort of sounds like this will be a *feature* of the API rather than a bug.
