### ISSUE TITLE
Expose remaining pooling allocator options as CLI flags

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#9256]
Wasmtime's pooling instance allocator has a [number of configuration options](https://github.com/bytecodealliance/wasmtime/blob/a659b5a9c64c7d3cb74fc5d03446cd46d74e614b/crates/wasmtime/src/config.rs#L2510) not all of which are reflected onto the CLI at this time [around here](https://github.com/bytecodealliance/wasmtime/blob/a659b5a9c64c7d3cb74fc5d03446cd46d74e614b/crates/cli-flags/src/lib.rs#L603-L653). Ideally all of the pooling alloctator configuration options should be reflected on the CLI with a various `-O pooling-...` flag.

**Comment by alexcrichton** [comment]
I'm tagging this as a "good first issue" and the basic task would be:

1. Write down a list of all configuration options on `PoolingAllocationConfig`
2. Write down a list of configuration options that the `wasmtime` CLI supports configuring
3. Figure out what's in list (1) and not in list (2)
4. Add new options for these missing configuration flags along the lines of the items already in list (2)

We don't have exhaustive tests for Wasmtime's CLI options at this time so it's ok to skip the tests for this at this time and just rely on code review to catch issues.

**Comment by vHugoObject** [comment]
Can I take this?

**Comment by alexcrichton** [comment]
Feel free!

**Comment by omarjatoi** [comment]
🤦 sorry @vHugoObject! I totally missed your comment before opening the PR.

**Comment by vHugoObject** [comment]
No problem at all, I have been too busy for this anyways.

**Comment by alexcrichton** [comment]
Landed in https://github.com/bytecodealliance/wasmtime/pull/9447, so I'm going to close this. Thkas @omarjatoi!
