### ISSUE TITLE
Error: max_wasm_stack size cannot exceed the async_stack_size

### ISSUE THREAD

**Issue by pavelsavara** [bytecodealliance/wasmtime#9298]
### Test Case

Testing dotnet AOT with the new wasmtime v 25 in the dotnet CI.
The [full log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-108179-merge-a238d0a9053e45129a/System.Collections.Specialized.Tests.Attempt.3/1/console.c5dc63d9.log?helixlogtype=result)

### Steps to Reproduce

`wasmtime --dir=. --wasm max-wasm-stack=134217728 --wasi http --wasi inherit-network --wasi allow-ip-name-lookup dotnet.wasm`

### Expected Results

probably we need a way how to specify `--wasm async-stack-size=134217728` on cli.
But I'm not sure I understand the feature well enough.

### Actual Results

`Error: max_wasm_stack size cannot exceed the async_stack_size`

### Versions and Environment

Wasmtime version or commit: wasmtime 25.0.0 (0b195ef5d 2024-09-20)

Operating system: ubuntu-22.04

Architecture: x64

### Extra Info

Anything else you'd like to add?

**Comment by alexcrichton** [comment]
Thanks for the report! This was an oversight when turning on async on the CLI and should be fixed in https://github.com/bytecodealliance/wasmtime/pull/9302
