### ISSUE TITLE
`wasmtime::runtime::vm::const_expr::ConstEvalContext` doesn't need its `module` field

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#9311]
The `instance` field already provides access to that module via `instance.env_module()`. We should remove the `module` field, remove the `module` parameter from `ContEvalContext::new`, and replace old uses of `self.module` with `self.instance.env_module()`.

**Comment by Tirthnp** [comment]
Hey I would like to take an attempt at this. I am trying to learn about compiler and Rust. I have created this Draft PR: https://github.com/bytecodealliance/wasmtime/pull/9314, I am really sorry if I should ask for the issue to be assigned to me.

**Comment by fitzgen** [comment]
Cool! Excited to take a look. Just a heads up that I am pretty busy with the Bytecode Alliance's plumbers summit through the rest of the week, so I probably won't take a look until next week. Someone else might beat me to it though.

**Comment by evanmcc** [comment]
looks like this should be closed.

**Comment by alexcrichton** [comment]
Thanks!
