### ISSUE TITLE
DWARF-5 support

### ISSUE THREAD

**Issue by ggreif** [bytecodealliance/wasmtime#932]
Current Goal
------------

The upcoming milestone is `Exprloc` support for the [Wasm-style locations](https://yurydelendik.github.io/webassembly-dwarf/#DWARF-expressions-and-location-descriptions). I'll try to put together a PR next.

So far I see following problems (possibly related to https://github.com/bytecodealliance/wasmtime/issues/1613):
- no operand stack locations yet (middle-term)
- index needs (seems) to begin at `1` (I'd expect `0`) to obtain valid ranges
- [x] (potentially resolved by https://github.com/bytecodealliance/wasmtime/pull/1572) ranges get discarded [because not being sufficiently populated with labels](https://github.com/bytecodealliance/wasmtime/pull/1410#issuecomment-620025367).

Next Goal
------------

- accept `.debug_types` (middle-term)

OUTDATED info below
------------

I gather that the [Wasm DWARF spec](https://yurydelendik.github.io/webassembly-dwarf/) defines DWARF-5 as the baseline debug format.

However several sections from Version 5 are rejected by `wasmtime` with panics. E.g.
https://github.com/bytecodealliance/wasmtime/blob/master/crates/debug/src/read_debuginfo.rs#L63

For my purposes `".debug_rnglists"` is the most important.

Is there any ETA for supporting these?

Note: The `clang-10` compiler (currently in `rc1`) [doesn't reliably emit DWARF-5](https://bugs.llvm.org/show_bug.cgi?id=44728) yet.

`clang-11` (pre-release) seems to generate DWARF-5 without crashing. As per #1410 the DWARF example Wasm files are compiled with this `clang`.

**Comment by yurydelendik** [comment]
> I gather that the Wasm DWARF spec defines DWARF-5 as the baseline debug format.
> For my purposes ".debug_rnglists" is the most important.
> Note: The clang-10 compiler (currently in rc1) doesn't reliably emit DWARF-5 yet.

The wasmtime currently consumes LLVM output. As you noticed, that older clang supports DWARF-4, and we are using it as input at the moment.

@ggreif which Wasm code generators you are using that output DWARF 5 sections?

> Is there any ETA for supporting these?

I'll keep this issue opened to start tracking missing DWARF 5 features.

**Comment by ggreif** [comment]
> 
> @ggreif which Wasm code generators you are using that output DWARF 5 sections?
> 

It is an in-house compiler. Please p/m me if you need details. I am happy to send generated code to check your ingesters (when you're ready).

**Comment by yurydelendik** [comment]
@ggreif is anything else left to close this particular issue? I see `.debug_types` and "operand stack locations". I would suggest to open a separate issue for the latter to track it with https://reviews.llvm.org/D78818.

**Comment by ggreif** [comment]
I have my own heap of problems, with my compiler. Happy to close this one.
