### ISSUE TITLE
Why are you not supporting windows??? ):

### ISSUE THREAD

**Issue by orihal1** [bytecodealliance/wasmtime#9329]

**Comment by bjorn3** [comment]
Wasmtime does support Windows just fine and precompiled Windows executables are provided for each release. Why do you think it doesn't.

**Comment by alexcrichton** [comment]
I'm going to close this because Windows is indeed supported (as @bjorn3 points out). @orihal1 if there's perhaps outdated documentation saying otherwise please let us know and we can go through and update it. Otherwise though since support is already here, I'm going to close.
