### ISSUE TITLE
Is the C API to embed wasmtime usable?

### ISSUE THREAD

**Issue by newbee1920** [bytecodealliance/wasmtime#933]
"Wasmtime exposes an API for embedding as a library through the wasmtime subcrate, which contains both a high-level and safe Rust API, as well as a C-compatible API compatible with the proposed WebAssembly C API."

Where can we find this "C-compatible API compatible with the proposed WebAssembly C API"?

**Comment by yurydelendik** [comment]
CI has [tests](https://github.com/bytecodealliance/wasmtime/blob/master/crates/c-api/tests/wasm-c-examples.rs) that run C [examples](https://github.com/WebAssembly/wasm-c-api/tree/master/example) from WebAssembly C API. See also custom [Makefile](https://github.com/bytecodealliance/wasmtime/blob/master/crates/c-api/examples/Makefile)

> Where can we find this "C-compatible API compatible with the proposed WebAssembly C API"? 

The [releases](https://github.com/bytecodealliance/wasmtime/releases) have archives with "-c-api" suffix -- the built libraries with C API interface can be found there. Closing the issue as answered.
