### ISSUE TITLE
Broken link to JS polyfill source in intro

### ISSUE THREAD

**Issue by fivedots** [bytecodealliance/wasmtime#937]
The link to the Javascripte polyfill source code in https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-intro.md#the-browser-polyfill seems to be broken. I got to the document via wasi.dev.

**Comment by kubkon** [comment]
Hey @fivedots! Thanks for the issue. Yeah, we're currently in the middle of a transition from C-based implementation to Rust-based implementation of the polyfill, and the link is indeed incorrectly referencing the former which has been removed from the tree. The tracking issue for the polyfill based on Rust impl of WASI can be found in this PR #720, while the link to the original, C-based source can be found here: [wasmtime/tree/polyfill/wasmtime-wasi/js-polyfill](https://github.com/bytecodealliance/wasmtime/tree/polyfill/wasmtime-wasi/js-polyfill).

**Comment by ChristianWeyer** [comment]
Is there any projected ETA for the new Rust-based implementation @kubkon?
Thanks.

**Comment by kubkon** [comment]
Hi @ChristianWeyer! It's been a while since I looked into this but this very functionality now come back around at work for me so I'll be revisiting it in the coming days and hopefully will get something functional soon-ish. I'll report back when a working PR is submitted.

**Comment by ChristianWeyer** [comment]
Did you already find some minutes... @kubkon ? ;-)

**Comment by bjorn3** [comment]
The link has since been replaced with a link to https://github.com/bjorn3/browser_wasi_shim.
