### ISSUE TITLE
Trap handlers assertion failed: !p.is_null()

### ISSUE THREAD

**Issue by gatesn** [bytecodealliance/wasmtime#940]
I'm working on building Java bindings to Wasmtime using the C API and I keep running into Rust backtraces that look like this:

```
thread '<unnamed>' panicked at 'assertion failed: !p.is_null()', crates/runtime/src/traphandlers.rs:247:13
stack backtrace:
   0:        0x13698e3b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415ddd0ba88caaaf
   1:        0x1369ab960 - core::fmt::write::h3335552e2df81c1d
   2:        0x13698becb - std::io::Write::write_fmt::he6837371b9a45188
   3:        0x13698ff83 - std::panicking::default_hook::{{closure}}::h708e66cfeb0483ba
   4:        0x13698fc8a - std::panicking::default_hook::h39ea8ddf674c04ec
   5:        0x13699061b - std::panicking::rust_panic_with_hook::h9db77b22c2255a16
   6:        0x1369b9335 - std::panicking::begin_panic::h9061d5cb41adf9cd
   7:        0x13672f948 - wasmtime_runtime::traphandlers::tls::with::h61612510d5b35bc9
   8:        0x13673ab3d - RecordTrap
   9:        0x13673b8e5 - _ZL15WasmTrapHandleriP9__siginfoPv
  10:     0x7fff6ba2cb5d - _sigtramp
  11:        0x136680685 - wasm_instance_exports
  12:        0x106b9ef6d - call2
  13:        0x106b9f24b - invoke2
  14:        0x106b9f346 - Java_com_kenai_jffi_Foreign_invokeN2O1
fatal runtime error: failed to initiate panic, error 5
```

It seems that the error handling code in traphandlers is what's trapping, and it's not clear what originally caused the error. Am I doing something wrong here? Should I be configuring something such that `p` isn't null? Or do I just need to find my bug?

**Comment by alexcrichton** [comment]
Thanks for the report! 

This looks like a bug in the usage actually where a segfault is happening in the `wasm_instance_exports` function (maybe a null pointer passed in?).

Our segfault handler for wasm though is a bit too eager in catching segfaults and is failing here, causing the bug to look different than what it actually is. That's been fixed on master, though, and if you update your local `wasmtime` you should see the panic about `p.is_null()` go away and a segfault should show up.

If that doesn't happen though, please let us know and we can reopen!

**Comment by gatesn** [comment]
Ah, now it segfaults. Thanks!
