### ISSUE TITLE
Ability to both pause and resume a WASM instance

### ISSUE THREAD

**Issue by moonheart08** [bytecodealliance/wasmtime#950]
At the moment, as far as I can tell, there's no way to temporarily pause execution of WASM only to re-enter it later, which is vital for running multiple WASM instances on the same thread without one being able to stall all of the others. Is this even on WASMTime's radar, or would I be better suited finding a WASM interpreter (or designing my own) to use for this purpose instead?

**Comment by alexcrichton** [comment]
Thanks for the report! This is not yet possible but would be covered by https://github.com/bytecodealliance/wasmtime/issues/860, so I'm going to close in favor of that.
