### ISSUE TITLE
Can `RelocationTarget` be entirely removed?

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#951]
One of the neat use cases with caching is that we can mmap the cache from disk into memory and then simply start running code. Unfortunately though `RelocationTarget` means that we also may have to actually modify the code we map in, which in turn can cause a lot of it to get paged in unnecessarily quickly.

This issue is intended to track if we can get rid of `RelocationTarget` entirely, or if it's even desirable. The downsides to this would be that everything currently requiring a relocation would go through some form of indirection instead. The upside however is that we can possibly do zero work when loading code from a cache, making cached instantiation even faster than it is today.

**Comment by pchickey** [comment]
Additionally, this would give us a path for AOT codegen that doesn't rely on ELF or dlopen, which would simplify our trusted computing base and allow us to avoid some inefficient implementation details of dlopen (glibc performs a linear scan to check whether a library is already open, which starts to become a problem when you have >10k open in a process)

**Comment by bjorn3** [comment]
Is this still relevant?

**Comment by alexcrichton** [comment]
Yes I think enough has changed this is much less relevant. While not finished I think the major ideas behind this have been achieved.
