### ISSUE TITLE
Error when inspect

### ISSUE THREAD

**Issue by lianzhilu** [bytecodealliance/wasmtime#9586]
Hi, I meet this error when execute
`wasmtime  inspect sqlite3.wasm`
and the result is 

```
Error: failed to read file: inspect

Caused by:
    No such file or directory (os error 2)
```

The file does exist in the current path. How can I fix this problem?

**Comment by bjorn3** [comment]
You are probably looking for `wasmtime explore`, not `wasmtime inspect`.

**Comment by pchickey** [comment]
`wasmtime inspect` is not a subcommand. Try `wasmtime --help`
