### ISSUE TITLE
[Error] invalid result arity: func type returns multiple values (at offset 47)

### ISSUE THREAD

**Issue by ratnadeep007** [bytecodealliance/wasmtime#962]
Trying out tutorial in docs [rust tutorial](https://github.com/bytecodealliance/wasmtime/blob/master/docs/wasm-rust.md).

When using wasm-bindgen and running:

```bash
wasmtime --invoke greet ./target/wasm32-wasi/release/hello_world.wasm "wasmtime CLI"
```

getting following error:

```bash
Error: failed to run main module `./target/wasm32-wasi/release/hello_world.wasm`

Caused by:
    invalid result arity: func type returns multiple values (at offset 47)
```

**Comment by alexcrichton** [comment]
Thanks for the report! 

The support for interface types is pretty prototypical at this stage and is in a lot of flux. What you may need to do though is to pass `--enable-multi-value`, although even with that a lot of stars need to align to get everything working just right.

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!

**Comment by ratnadeep007** [comment]
Thanks for the update
