### ISSUE TITLE
Clearing console prints characters instead

### ISSUE THREAD

**Issue by Rochet2** [bytecodealliance/wasmtime#964]
The following code is suggested to be used to clear the console.
The code seems to print the characters to console instead of clearing the console.
Using ubuntu 18.04.4 tested with c94cdc7730bc2cf5e97c21678a0e393860dc092d and 9c6150b10312e2c4aec27b5885ceba8fb2fc6ce1
```C
#include <stdio.h>

int main (int argc, char *argv[]) {
	printf ("Hello world!\n");
	/* try clear console */
	puts ("\033[H\033[J");
	printf("\e[1;1H\e[2J"); 
	return 0;
}
```
![image](https://user-images.githubusercontent.com/468816/75098222-3afb9400-55bc-11ea-9fc0-e5021533543d.png)

Other wasm runtimes like wasm3, wasmer and wavm seemed to clear the console as expected with both codes.
Is this something that should be supported / is a bug?

**Comment by rene-fonseca** [comment]
wasmtime filters ansi escape codes that could be used to trick/mislead users.

You can check the topic at https://github.com/WebAssembly/WASI/issues/162

**Comment by Rochet2** [comment]
thanks
