### ISSUE TITLE
wasm_instance_new implementation C-API fails

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#969]
The **wasm_instance_new** C-API implementation fails due to buffer overrun for the imports buffer.

https://github.com/bytecodealliance/wasmtime/blob/2fd3a31c06adedd352eaf6fe9e814eb61e41ef9c/crates/c-api/src/lib.rs#L731-L732

The for-loop below should not check against the module import - but should just iterator over the items in the imports buffer argument. Since there is no size given as argument, it needs to be assumed that the imports buffer is NULL terminated. Note that all C-API examples need to be updated to add the NULL as the last item for the imports buffer.

```
   let mut externs: Vec<Extern> = Vec::with_capacity((*module).imports.len());
    for i in 0..(*module).imports.len() { // only check if imports is non-NULL and then do infinite loop starting from i == 0
        let import = *imports.add(i);
        // if import is NULL then break loop
        externs.push(match &(*import).which {
            ExternHost::Func(e) => Extern::Func(e.borrow().clone()),
            ExternHost::Table(e) => Extern::Table(e.borrow().clone()),
            ExternHost::Global(e) => Extern::Global(e.borrow().clone()),
            ExternHost::Memory(e) => Extern::Memory(e.borrow().clone()),
        });
    }
```

**Comment by yurydelendik** [comment]
@rene-fonseca can you open an issue at https://github.com/WebAssembly/wasm-c-api/ -- the wasmtime merely implements the proposed behavior.

**Comment by rene-fonseca** [comment]
Done.

https://github.com/WebAssembly/wasm-c-api/issues/129

**Comment by rene-fonseca** [comment]
@rossberg would like issue back to wasmtime.

**Comment by yurydelendik** [comment]
> Since there is no size given as argument, it needs to be assumed that the imports buffer is NULL terminated. Note that all C-API examples need to be updated to add the NULL as the last item for the imports buffer.

@rossberg @rene-fonseca The behavior mimics https://github.com/WebAssembly/wasm-c-api/blob/master/src/wasm-v8.cc#L2036-L2062 . It is not specific to wasmtime implementation

**Comment by rossberg** [comment]
In the C API it is the caller's responsibility to make sure that imports[] matches the expected import_types[], and it's undefined behaviour if it doesn't. That's the usual C way. You probably don't want to replicate that for Rust. (There is no NULL termination, the number of imports is known for each module.)

**Comment by yurydelendik** [comment]
> You probably don't want to replicate that for Rust.

Correct, the Rust API does not replicate the C way of doing things. The current C API implemented by wasmtime behaves as documented as in above comment. Closing as resolved.
