### ISSUE TITLE
winch(aarch64): Improve 32-bit {s,u}div

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/wasmtime#9766]
While reviewing https://github.com/bytecodealliance/wasmtime/pull/9762, I realized that in the case of 32-bit operands a sign-extension is required given that `cranelift-codegen`, only accepts 64-bit operands. 

The ARM64 documentation states [1], [2] that 32-bit operands for division are allowed.

[1]: https://developer.arm.com/documentation/ddi0596/2020-12/Base-Instructions/SDIV--Signed-Divide-
[2]: https://developer.arm.com/documentation/ddi0602/2024-09/Base-Instructions/UDIV--Unsigned-divide-

Introducing support for 32-bit operands means that in Winch we can skip the extension sequence when dealing with 32-bit operands.

As a side note, it seems that when migrating to ISLE [the intention was to add support for 32-bit operands](https://github.com/bytecodealliance/wasmtime/pull/3572/files#diff-bd652d5af8795961ba7456cf427fdae37bb82500e9f18fa6fc1621281bd1ab58L103). 

cc @alexcrichton / @cfallin I'm not entirely familiar with the development history of the Aarch64 backend, is there any other reason to be aware of when considering support for 32-bit operands?

**Comment by MarinPostma** [comment]
I'd like to take a stab at that after I'm done with winch. Any guidance on how I should tackle that?

**Comment by saulecabrera** [comment]
One approach could be to take a look at how similar instructions have been added in the past e.g., https://github.com/bytecodealliance/wasmtime/pull/8453
