### ISSUE TITLE
Cranelift optimizations aren't enabled by default for the API.

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime#981]
We've recently turned optimizations on by default in the CLI.

I think we should probably enable optimizations by default for both the Rust and C APIs. 

I propose we enable the cranelift optimization level to match the CLI for `Engine::default()` (thus [`Config::new`](https://github.com/bytecodealliance/wasmtime/blob/master/crates/api/src/runtime.rs#L35-L65) sets the optimization level).

**Comment by alexcrichton** [comment]
Agreed!

I don't think we necessarily want the CLI to match *everything* about the API, for example I think it's probably the way we want it to have the CLI have an on-by-default cache but the API has an off-by-default cache. For something like this though I think it's best to match the two.

**Comment by peterhuene** [comment]
> I don't think we necessarily want the CLI to match everything about the API,

Totally.  Off by default cache makes sense to me since the use pattern is so unknown.  With respect to optimization, I would imagine that embedders will want optimized codegen almost all of the time and so it makes sense to have it on by default for such an important performance feature.
