### ISSUE TITLE
Cranelift: should be implemented in ISLE (stack_load.i64)

### ISSUE THREAD

**Issue by stellaphax** [bytecodealliance/wasmtime#9835]
Creating something for a Capture the Flag (CTF) challenge, and came across this when attempting to compile my function.

### Full Backtrace:

thread 'main' panicked at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\machinst\lower.rs:685:21:
should be implemented in ISLE: inst = `v71 = stack_load.i64 ss0`, type = `Some(types::I64)`
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: cranelift_codegen::machinst::lower::impl$3::lower_clif_block::closure$0<enum2$<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst>,cranelift_codegen::isa::x64::X64Backend>
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\machinst\lower.rs:685
   3: enum2$<core::option::Option<smallvec::SmallVec<array$<cranelift_codegen::machinst::valueregs::ValueRegs<cranelift_codegen::machinst::reg::Reg>,2> > > >::unwrap_or_else<smallvec::SmallVec<array$<cranelift_codegen::machinst::valueregs::ValueRegs<cranelift_co
             at C:\Users\accord\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:1017
   4: cranelift_codegen::machinst::lower::Lower<enum2$<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst> >::lower_clif_block<enum2$<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst>,cranelift_codegen::isa::x64::X64Backend>
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\machinst\lower.rs:679
   5: cranelift_codegen::machinst::lower::Lower<enum2$<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst> >::lower<enum2$<cranelift_codegen::isa::x64::lower::isle::generated_code::MInst>,cranelift_codegen::isa::x64::X64Backend>
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\machinst\lower.rs:1017
   6: cranelift_codegen::machinst::compile::compile<cranelift_codegen::isa::x64::X64Backend>
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\machinst\compile.rs:41
   7: cranelift_codegen::isa::x64::X64Backend::compile_vcode
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\isa\x64\mod.rs:61
   8: cranelift_codegen::isa::x64::impl$1::compile_function
             at C:\Users\accord\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cranelift-codegen-0.114.0\src\isa\x64\mod.rs:73
   9: ctf::interpreter::generate
             at .\src\interpreter.rs:924
  10: REDACTED::main
             at .\src\bin\virtualizer.rs:6
  11: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at C:\Users\accord\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
  12: core::hint::black_box
             at C:\Users\accord\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:389
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `REDACTED.exe` (exit code: 101)

### My IR

`function u0:0(i64, i64) -> i64 windows_fastcall {
    ss0 = explicit_slot 8, align = 65536
    ss1 = explicit_slot 8, align = 65536

block0(v0: i64, v1: i64):
    stack_store v0, ss0
    stack_store v1, ss1
    jump block1

block1:
    v2 = stack_load.i64 ss0
    v3 = iconst.i64 128
    v4 = iadd v2, v3  ; v3 = 128
    v5 = load.i64 readonly little v4
    v6 = load.i64 readonly little v5
    v7 = bnot v6
    v8 = iconst.i64 0x489d_2061_0fc3_fb2a
    v9 = isub v7, v8  ; v8 = 0x489d_2061_0fc3_fb2a
    v10 = iconst.i64 -4461110450679002079
    v11 = bxor v9, v10  ; v10 = -4461110450679002079
    v12 = iconst.i64 0x1c14_4295_049e_9905
    v13 = bxor v11, v12  ; v12 = 0x1c14_4295_049e_9905
    v14 = ineg v13
    v15 = bnot v14
    v16 = iconst.i64 -8819557583384649525
    v17 = isub v15, v16  ; v16 = -8819557583384649525
    v18 = iconst.i64 -292475872589187261
    v19 = bxor v17, v18  ; v18 = -292475872589187261
    v20 = iconst.i64 -8660319366599639002
    v21 = isub v19, v20  ; v20 = -8660319366599639002
    v22 = iconst.i64 -7151449463209098624
    v23 = bxor v21, v22  ; v22 = -7151449463209098624
    v24 = iconst.i64 0x18c8_b9af_33b0_a405
    v25 = iadd v23, v24  ; v24 = 0x18c8_b9af_33b0_a405
    v26 = iconst.i64 0x40e7_0af5_6ce5_56dd
    v27 = bxor v25, v26  ; v26 = 0x40e7_0af5_6ce5_56dd
    v28 = iconst.i64 -6954426303843586127
    v29 = bxor v27, v28  ; v28 = -6954426303843586127
    v30 = iconst.i64 -6831553930069083890
    v31 = bxor v29, v30  ; v30 = -6831553930069083890
    v32 = iconst.i64 0x0bbe_eb37_ba28_a537
    v33 = bxor v31, v32  ; v32 = 0x0bbe_eb37_ba28_a537
    v34 = iconst.i64 0x6d27_b06f_df5c_9472
    v35 = bxor v33, v34  ; v34 = 0x6d27_b06f_df5c_9472
    v36 = iconst.i64 0x6e30_5d88_0555_9288
    v37 = bxor v35, v36  ; v36 = 0x6e30_5d88_0555_9288
    v38 = ineg v37
    v39 = iconst.i64 -2882484716177919502
    v40 = bxor v38, v39  ; v39 = -2882484716177919502
    v41 = iconst.i64 0x3af4_83c5_3db0_1d9d
    v42 = isub v40, v41  ; v41 = 0x3af4_83c5_3db0_1d9d
    v43 = iconst.i64 -5792733239001732165
    v44 = bxor v42, v43  ; v43 = -5792733239001732165
    v45 = bnot v44
    v46 = iconst.i64 8
    v47 = iadd v5, v46  ; v46 = 8
    store little v47, v4
    v48 = iconst.i64 -7783865175571007017
    v49 = icmp eq v45, v48  ; v48 = -7783865175571007017
    brif v49, block2, block13

block13:
    v50 = iconst.i64 0x7b5a_d962_d1b6_bc9e
    v51 = icmp.i64 eq v45, v50  ; v50 = 0x7b5a_d962_d1b6_bc9e
    brif v51, block3, block14

block14:
    v52 = iconst.i64 -6272791173886278192
    v53 = icmp.i64 eq v45, v52  ; v52 = -6272791173886278192
    brif v53, block4, block15

block15:
    v54 = iconst.i64 -2797489443462894109
    v55 = icmp.i64 eq v45, v54  ; v54 = -2797489443462894109
    brif v55, block5, block16

block16:
    v56 = iconst.i64 0x02c8_1cdd_21bd_b3c0
    v57 = icmp.i64 eq v45, v56  ; v56 = 0x02c8_1cdd_21bd_b3c0
    brif v57, block6, block17

block17:
    v58 = iconst.i64 0x6ee2_e465_36e8_77b5
    v59 = icmp.i64 eq v45, v58  ; v58 = 0x6ee2_e465_36e8_77b5
    brif v59, block7, block18

block18:
    v60 = iconst.i64 -8073358707478604768
    v61 = icmp.i64 eq v45, v60  ; v60 = -8073358707478604768
    brif v61, block8, block19

block19:
    v62 = iconst.i64 0x1057_b219_e4fa_5f10
    v63 = icmp.i64 eq v45, v62  ; v62 = 0x1057_b219_e4fa_5f10
    brif v63, block9, block20

block20:
    v64 = iconst.i64 -8726837251761108653
    v65 = icmp.i64 eq v45, v64  ; v64 = -8726837251761108653
    brif v65, block10, block21

block21:
    v66 = iconst.i64 -7230224490429434294
    v67 = icmp.i64 eq v45, v66  ; v66 = -7230224490429434294
    brif v67, block11, block22

block22:
    v68 = iconst.i64 0x6b23_5923_d009_c45c
    v69 = icmp.i64 eq v45, v68  ; v68 = 0x6b23_5923_d009_c45c
    brif v69, block12, block23

block23:
    jump block1

block2:
    v70 = stack_load.i64 ss0
    v71 = iconst.i64 128
    v72 = iadd v70, v71  ; v71 = 128
    v73 = load.i64 readonly little v72
    v74 = load.i64 readonly little v73
    v75 = iconst.i64 -2704559895804829619
    v76 = bxor v74, v75  ; v75 = -2704559895804829619
    v77 = bnot v76
    v78 = iconst.i64 0x7e5d_964e_adf2_ac49
    v79 = isub v77, v78  ; v78 = 0x7e5d_964e_adf2_ac49
    v80 = bnot v79
    v81 = ineg v80
    v82 = iconst.i64 0x5b93_de21_5f20_6444
    v83 = isub v81, v82  ; v82 = 0x5b93_de21_5f20_6444
    v84 = iconst.i64 0x2e8e_61ad_5854_eb18
    v85 = bxor v83, v84  ; v84 = 0x2e8e_61ad_5854_eb18
    v86 = bnot v85
    v87 = iconst.i64 0x5935_230f_2339_3e3e
    v88 = bxor v86, v87  ; v87 = 0x5935_230f_2339_3e3e
    v89 = ineg v88
    v90 = iconst.i64 -3750086189034530752
    v91 = bxor v89, v90  ; v90 = -3750086189034530752
    v92 = iconst.i64 0x66f2_7dd6_509a_7dd6
    v93 = bxor v91, v92  ; v92 = 0x66f2_7dd6_509a_7dd6
    v94 = iconst.i64 0x0feb_13a6_5b72_5ca9
    v95 = bxor v93, v94  ; v94 = 0x0feb_13a6_5b72_5ca9
    v96 = iconst.i64 0x4bae_b9b1_b37a_17d2
    v97 = isub v95, v96  ; v96 = 0x4bae_b9b1_b37a_17d2
    v98 = iconst.i64 0x4b39_bbbc_9294_7a09
    v99 = bxor v97, v98  ; v98 = 0x4b39_bbbc_9294_7a09
    v100 = iconst.i64 -5626529817850843395
    v101 = iadd v99, v100  ; v100 = -5626529817850843395
    v102 = iconst.i64 -6666738309278736411
    v103 = isub v101, v102  ; v102 = -6666738309278736411
    v104 = iconst.i64 -1757971160561802068
    v105 = bxor v103, v104  ; v104 = -1757971160561802068
    v106 = iconst.i64 8
    v107 = iadd v73, v106  ; v106 = 8
    store little v107, v72
    v108 = iconst.i64 8
    v109 = imul v105, v108  ; v108 = 8
    v110 = iadd v70, v109
    v111 = load.i64 readonly little v110
    v112 = iconst.i64 336
    v113 = iadd v70, v112  ; v112 = 336
    v114 = load.i64 readonly little v113
    v115 = iconst.i64 8
    v116 = isub v114, v115  ; v115 = 8
    store little v116, v113
    store little v111, v116
    jump block1

block3:
    v117 = stack_load.i64 ss0
    v118 = iconst.i64 128
    v119 = iadd v117, v118  ; v118 = 128
    v120 = load.i64 readonly little v119
    v121 = load.i64 readonly little v120
    v122 = iconst.i64 0x02f3_7043_5ac2_8a35
    v123 = bxor v121, v122  ; v122 = 0x02f3_7043_5ac2_8a35
    v124 = ineg v123
    v125 = iconst.i64 0x5b5c_416b_0348_d8b8
    v126 = bxor v124, v125  ; v125 = 0x5b5c_416b_0348_d8b8
    v127 = iconst.i64 -532105587687712844
    v128 = isub v126, v127  ; v127 = -532105587687712844
    v129 = iconst.i64 -2570165577146278076
    v130 = bxor v128, v129  ; v129 = -2570165577146278076
    v131 = iconst.i64 -1935725075630874489
    v132 = bxor v130, v131  ; v131 = -1935725075630874489
    v133 = iconst.i64 0x25a7_887d_c02d_9046
    v134 = isub v132, v133  ; v133 = 0x25a7_887d_c02d_9046
    v135 = iconst.i64 -1507838080575882525
    v136 = isub v134, v135  ; v135 = -1507838080575882525
    v137 = iconst.i64 0x1fa7_b9bd_371e_13e5
    v138 = bxor v136, v137  ; v137 = 0x1fa7_b9bd_371e_13e5
    v139 = iconst.i64 0x429f_b567_16ef_0c79
    v140 = bxor v138, v139  ; v139 = 0x429f_b567_16ef_0c79
    v141 = iconst.i64 0x4447_f036_bfd7_a725
    v142 = iadd v140, v141  ; v141 = 0x4447_f036_bfd7_a725
    v143 = iconst.i64 -8881785380371716220
    v144 = bxor v142, v143  ; v143 = -8881785380371716220
    v145 = iconst.i64 0x2692_f75c_d4a6_60c5
    v146 = bxor v144, v145  ; v145 = 0x2692_f75c_d4a6_60c5
    v147 = iconst.i64 -889400163786108327
    v148 = bxor v146, v147  ; v147 = -889400163786108327
    v149 = iconst.i64 0x0d40_b8c0_437e_5a44
    v150 = bxor v148, v149  ; v149 = 0x0d40_b8c0_437e_5a44
    v151 = iconst.i64 -744866226958587271
    v152 = bxor v150, v151  ; v151 = -744866226958587271
    v153 = ineg v152
    v154 = iconst.i64 0x60e6_4bc2_acb9_f190
    v155 = bxor v153, v154  ; v154 = 0x60e6_4bc2_acb9_f190
    v156 = iconst.i64 -7239240155899509169
    v157 = isub v155, v156  ; v156 = -7239240155899509169
    v158 = iconst.i64 0x608c_6025_8c88_d442
    v159 = bxor v157, v158  ; v158 = 0x608c_6025_8c88_d442
    v160 = iconst.i64 0x4d02_51c2_f0b5_a74c
    v161 = bxor v159, v160  ; v160 = 0x4d02_51c2_f0b5_a74c
    v162 = iconst.i64 8
    v163 = iadd v120, v162  ; v162 = 8
    store little v163, v119
    v164 = iconst.i64 336
    v165 = iadd v117, v164  ; v164 = 336
    v166 = load.i64 readonly little v165
    v167 = iconst.i64 8
    v168 = isub v166, v167  ; v167 = 8
    store little v168, v165
    store little v161, v168
    jump block1

block4:
    v169 = stack_load.i64 ss0
    v170 = iconst.i64 128
    v171 = iadd v169, v170  ; v170 = 128
    v172 = load.i64 readonly little v171
    v173 = load.i64 readonly little v172
    v174 = iconst.i64 0x78c1_0f22_4884_5ab5
    v175 = bxor v173, v174  ; v174 = 0x78c1_0f22_4884_5ab5
    v176 = iconst.i64 -481473301226030139
    v177 = bxor v175, v176  ; v176 = -481473301226030139
    v178 = iconst.i64 0x01da_a262_4505_8a19
    v179 = bxor v177, v178  ; v178 = 0x01da_a262_4505_8a19
    v180 = iconst.i64 0x6511_9123_9ee2_8caf
    v181 = bxor v179, v180  ; v180 = 0x6511_9123_9ee2_8caf
    v182 = iconst.i64 -5182374953491362535
    v183 = bxor v181, v182  ; v182 = -5182374953491362535
    v184 = iconst.i64 -471016823963830313
    v185 = bxor v183, v184  ; v184 = -471016823963830313
    v186 = iconst.i64 -973127001378486962
    v187 = bxor v185, v186  ; v186 = -973127001378486962
    v188 = bnot v187
    v189 = bnot v188
    v190 = ineg v189
    v191 = bnot v190
    v192 = bnot v191
    v193 = iconst.i64 -2957607114569826566
    v194 = isub v192, v193  ; v193 = -2957607114569826566
    v195 = iconst.i64 -3390650912100258663
    v196 = bxor v194, v195  ; v195 = -3390650912100258663
    v197 = iconst.i64 8
    v198 = iadd v172, v197  ; v197 = 8
    store little v198, v171
    v199 = iconst.i64 8
    v200 = imul v196, v199  ; v199 = 8
    v201 = iadd v169, v200
    v202 = iconst.i64 336
    v203 = iadd v169, v202  ; v202 = 336
    v204 = load.i64 readonly little v203
    v205 = load.i64 readonly little v204
    store little v205, v201
    v206 = iconst.i64 8
    v207 = iadd v204, v206  ; v206 = 8
    store little v207, v203
    jump block1

block5:
    v208 = stack_load.i64 ss0
    return v208

block6:
    v209 = stack_load.i64 ss0
    v210 = iconst.i64 128
    v211 = iadd v209, v210  ; v210 = 128
    v212 = load.i64 readonly little v211
    v213 = load.i64 readonly little v212
    v214 = bnot v213
    v215 = iconst.i64 0x3db1_938a_c5a3_0bf4
    v216 = bxor v214, v215  ; v215 = 0x3db1_938a_c5a3_0bf4
    v217 = iconst.i64 0x743c_32fd_9b5c_b9c4
    v218 = isub v216, v217  ; v217 = 0x743c_32fd_9b5c_b9c4
    v219 = bnot v218
    v220 = iconst.i64 -6314325928910406644
    v221 = bxor v219, v220  ; v220 = -6314325928910406644
    v222 = iconst.i64 0x422b_ff40_82f2_ad6c
    v223 = bxor v221, v222  ; v222 = 0x422b_ff40_82f2_ad6c
    v224 = iconst.i64 0x77b8_74ec_f207_b4f8
    v225 = iadd v223, v224  ; v224 = 0x77b8_74ec_f207_b4f8
    v226 = iconst.i64 -5404974257690580134
    v227 = iadd v225, v226  ; v226 = -5404974257690580134
    v228 = ineg v227
    v229 = iconst.i64 0x4966_e277_41b7_55fc
    v230 = isub v228, v229  ; v229 = 0x4966_e277_41b7_55fc
    v231 = iconst.i64 0x7db8_1ee0_8991_d879
    v232 = bxor v230, v231  ; v231 = 0x7db8_1ee0_8991_d879
    v233 = iconst.i64 -6648515627860166807
    v234 = bxor v232, v233  ; v233 = -6648515627860166807
    v235 = ineg v234
    v236 = iconst.i64 8
    v237 = iadd v212, v236  ; v236 = 8
    store little v237, v211
    v238 = iconst.i64 336
    v239 = iadd v209, v238  ; v238 = 336
    v240 = load.i64 readonly little v239
    v241 = stack_load.i64 ss1
    v242 = iadd v241, v235
    v243 = iconst.i64 8
    v244 = isub v240, v243  ; v243 = 8
    store little v244, v239
    store little v242, v244
    jump block1

block7:
    v245 = stack_load.i64 ss0
    v246 = iconst.i64 336
    v247 = iadd v245, v246  ; v246 = 336
    v248 = load.i64 readonly little v247
    v249 = iconst.i64 0
    v250 = iadd v248, v249  ; v249 = 0
    v251 = load.i64 readonly little v250
    v252 = iconst.i64 8
    v253 = iadd v248, v252  ; v252 = 8
    v254 = load.i64 readonly little v250
    v255 = iconst.i64 8
    v256 = iadd v248, v255  ; v255 = 8
    store little v256, v247
    v257 = band v251, v254
    store little v257, v256
    jump block1

block8:
    v258 = stack_load.i64 ss0
    v259 = iconst.i64 336
    v260 = iadd v258, v259  ; v259 = 336
    v261 = load.i64 readonly little v260
    v262 = iconst.i64 0
    v263 = iadd v261, v262  ; v262 = 0
    v264 = load.i64 readonly little v263
    v265 = iconst.i64 8
    v266 = iadd v261, v265  ; v265 = 8
    v267 = load.i64 readonly little v263
    v268 = iconst.i64 8
    v269 = iadd v261, v268  ; v268 = 8
    store little v269, v260
    v270 = bor v264, v267
    store little v270, v269
    jump block1

block9:
    v271 = stack_load.i64 ss0
    v272 = iconst.i64 336
    v273 = iadd v271, v272  ; v272 = 336
    v274 = load.i64 readonly little v273
    v275 = iconst.i64 0
    v276 = iadd v274, v275  ; v275 = 0
    v277 = load.i64 readonly little v276
    v278 = iconst.i64 8
    v279 = iadd v274, v278  ; v278 = 8
    v280 = load.i64 readonly little v276
    v281 = iconst.i64 16
    v282 = iadd v274, v281  ; v281 = 16
    store little v282, v273
    v283 = iconst.i64 0
    v284 = icmp eq v277, v283  ; v283 = 0
    brif v284, block24, block25

block24:
    v285 = stack_load.i64 ss0
    v286 = iconst.i64 128
    v287 = iadd v285, v286  ; v286 = 128
    v288 = iconst.i64 336
    v289 = iadd v285, v288  ; v288 = 336
    v290 = load.i64 readonly little v289
    v291 = iconst.i64 8
    v292 = iadd v290, v291  ; v291 = 8
    v293 = load.i64 readonly little v276
    store little v293, v287
    v294 = iconst.i64 16
    v295 = iadd v290, v294  ; v294 = 16
    store little v295, v289
    jump block1

block25:
    v296 = stack_load.i64 ss0
    v297 = iconst.i64 336
    v298 = iadd v296, v297  ; v297 = 336
    v299 = load.i64 readonly little v298
    v300 = iconst.i64 16
    v301 = iadd v299, v300  ; v300 = 16
    store little v301, v298
    jump block1

block10:
    v302 = stack_load.i64 ss0
    v303 = iconst.i64 336
    v304 = iadd v302, v303  ; v303 = 336
    v305 = load.i64 readonly little v304
    v306 = iconst.i64 128
    v307 = iadd v302, v306  ; v306 = 128
    v308 = iconst.i64 0
    v309 = iadd v305, v308  ; v308 = 0
    v310 = load.i64 readonly little v309
    store little v310, v307
    v311 = iconst.i64 8
    v312 = iadd v305, v311  ; v311 = 8
    store little v312, v304
    jump block1

block11:
    v313 = stack_load.i64 ss0
    v314 = iconst.i64 336
    v315 = iadd v313, v314  ; v314 = 336
    v316 = load.i64 readonly little v315
    v317 = iconst.i64 0
    v318 = iadd v316, v317  ; v317 = 0
    v319 = load.i64 readonly little v318
    v320 = iconst.i64 8
    v321 = iadd v316, v320  ; v320 = 8
    v322 = load.i64 readonly little v321
    v323 = iconst.i64 -3172171700287393760
    v324 = icmp eq v322, v323  ; v323 = -3172171700287393760
    brif v324, block27, block28

block27:
    v325 = stack_load.i64 ss0
    v326 = iconst.i64 336
    v327 = iadd v325, v326  ; v326 = 336
    v328 = load.i64 readonly little v327
    v329 = iconst.i64 0
    v330 = iadd v328, v329  ; v329 = 0
    v331 = load.i64 readonly little v330
    v332 = load.i8 readonly little v331
    v333 = sextend.i64 v332
    v334 = iconst.i64 255
    v335 = band v333, v334  ; v334 = 255
    v336 = iconst.i64 8
    v337 = iadd v328, v336  ; v336 = 8
    store little v337, v327
    store little v335, v337
    jump block26

block28:
    v338 = stack_load.i64 ss0
    v339 = iconst.i64 336
    v340 = iadd v338, v339  ; v339 = 336
    v341 = load.i64 readonly little v340
    v342 = iconst.i64 8
    v343 = iadd v341, v342  ; v342 = 8
    v344 = load.i64 readonly little v343
    v345 = iconst.i64 0x682d_0739_c329_8f2c
    v346 = icmp eq v344, v345  ; v345 = 0x682d_0739_c329_8f2c
    brif v346, block29, block30

block29:
    v347 = stack_load.i64 ss0
    v348 = iconst.i64 336
    v349 = iadd v347, v348  ; v348 = 336
    v350 = load.i64 readonly little v349
    v351 = iconst.i64 0
    v352 = iadd v350, v351  ; v351 = 0
    v353 = load.i64 readonly little v352
    v354 = load.i16 readonly little v353
    v355 = sextend.i64 v354
    v356 = iconst.i64 0xffff
    v357 = band v355, v356  ; v356 = 0xffff
    v358 = iconst.i64 8
    v359 = iadd v350, v358  ; v358 = 8
    store little v359, v349
    store little v357, v359
    jump block26

block30:
    v360 = stack_load.i64 ss0
    v361 = iconst.i64 336
    v362 = iadd v360, v361  ; v361 = 336
    v363 = load.i64 readonly little v362
    v364 = iconst.i64 8
    v365 = iadd v363, v364  ; v364 = 8
    v366 = load.i64 readonly little v365
    v367 = iconst.i64 -886636409264311685
    v368 = icmp eq v366, v367  ; v367 = -886636409264311685
    brif v368, block31, block32

block31:
    v369 = stack_load.i64 ss0
    v370 = iconst.i64 336
    v371 = iadd v369, v370  ; v370 = 336
    v372 = load.i64 readonly little v371
    v373 = iconst.i64 0
    v374 = iadd v372, v373  ; v373 = 0
    v375 = load.i64 readonly little v374
    v376 = load.i32 readonly little v375
    v377 = sextend.i64 v376
    v378 = iconst.i64 0xffff_ffff
    v379 = band v377, v378  ; v378 = 0xffff_ffff
    v380 = iconst.i64 8
    v381 = iadd v372, v380  ; v380 = 8
    store little v381, v371
    store little v379, v381
    jump block26

block32:
    v382 = stack_load.i64 ss0
    v383 = iconst.i64 336
    v384 = iadd v382, v383  ; v383 = 336
    v385 = load.i64 readonly little v384
    v386 = iconst.i64 8
    v387 = iadd v385, v386  ; v386 = 8
    v388 = load.i64 readonly little v387
    v389 = iconst.i64 0x3914_c7b4_8a02_ac9c
    v390 = icmp eq v388, v389  ; v389 = 0x3914_c7b4_8a02_ac9c
    brif v390, block33, block34

block33:
    v391 = stack_load.i64 ss0
    v392 = iconst.i64 336
    v393 = iadd v391, v392  ; v392 = 336
    v394 = load.i64 readonly little v393
    v395 = iconst.i64 0
    v396 = iadd v394, v395  ; v395 = 0
    v397 = load.i64 readonly little v396
    v398 = load.i64 readonly little v397
    v399 = iconst.i64 8
    v400 = iadd v394, v399  ; v399 = 8
    store little v400, v393
    store little v398, v400
    jump block26

block34:
    v401 = stack_load.i64 ss0
    v402 = iconst.i64 336
    v403 = iadd v401, v402  ; v402 = 336
    v404 = load.i64 readonly little v403
    v405 = iconst.i64 16
    v406 = iadd v404, v405  ; v405 = 16
    store little v406, v403
    jump block26

block26:
    jump block1

block12:
    jump block36

block35:
    v407 = stack_load.i64 ss0
    v408 = iconst.i64 336
    v409 = iadd v407, v408  ; v408 = 336
    v410 = load.i64 readonly little v409
    v411 = iconst.i64 24
    v412 = iadd v410, v411  ; v411 = 24
    store little v412, v409
    jump block1

block40:
    jump block35

block41:
    v413 = stack_load.i64 ss0
    v414 = iconst.i64 336
    v415 = iadd v413, v414  ; v414 = 336
    v416 = load.i64 readonly little v415
    v417 = iconst.i64 0
    v418 = iadd v416, v417  ; v417 = 0
    v419 = load.i64 readonly little v418
    v420 = iconst.i64 16
    v421 = iadd v416, v420  ; v420 = 16
    v422 = load.i64 readonly little v421
    v423 = bmask.i8 v422
    store little v423, v419
    jump block35

block42:
    v424 = stack_load.i64 ss0
    v425 = iconst.i64 336
    v426 = iadd v424, v425  ; v425 = 336
    v427 = load.i64 readonly little v426
    v428 = iconst.i64 0
    v429 = iadd v427, v428  ; v428 = 0
    v430 = load.i64 readonly little v429
    v431 = iconst.i64 16
    v432 = iadd v427, v431  ; v431 = 16
    v433 = load.i64 readonly little v432
    v434 = bmask.i16 v433
    store little v434, v430
    jump block35

block43:
    v435 = stack_load.i64 ss0
    v436 = iconst.i64 336
    v437 = iadd v435, v436  ; v436 = 336
    v438 = load.i64 readonly little v437
    v439 = iconst.i64 0
    v440 = iadd v438, v439  ; v439 = 0
    v441 = load.i64 readonly little v440
    v442 = iconst.i64 16
    v443 = iadd v438, v442  ; v442 = 16
    v444 = load.i64 readonly little v443
    v445 = bmask.i32 v444
    store little v445, v441
    jump block35

block44:
    v446 = stack_load.i64 ss0
    v447 = iconst.i64 336
    v448 = iadd v446, v447  ; v447 = 336
    v449 = load.i64 readonly little v448
    v450 = iconst.i64 0
    v451 = iadd v449, v450  ; v450 = 0
    v452 = load.i64 readonly little v451
    v453 = iconst.i64 16
    v454 = iadd v449, v453  ; v453 = 16
    v455 = load.i64 readonly little v454
    store little v455, v452
    jump block35

block36:
    v456 = stack_load.i64 ss0
    v457 = iconst.i64 336
    v458 = iadd v456, v457  ; v457 = 336
    v459 = load.i64 readonly little v458
    v460 = iconst.i64 0
    v461 = iadd v459, v460  ; v460 = 0
    v462 = load.i64 readonly little v461
    v463 = iconst.i64 0x4651_c83f_e245_a00a
    v464 = icmp eq v462, v463  ; v463 = 0x4651_c83f_e245_a00a
    brif v464, block41, block37

block37:
    v465 = stack_load.i64 ss0
    v466 = iconst.i64 336
    v467 = iadd v465, v466  ; v466 = 336
    v468 = load.i64 readonly little v467
    v469 = iconst.i64 0
    v470 = iadd v468, v469  ; v469 = 0
    v471 = load.i64 readonly little v470
    v472 = iconst.i64 0x260a_18d0_3030_833b
    v473 = icmp eq v471, v472  ; v472 = 0x260a_18d0_3030_833b
    brif v473, block42, block38

block38:
    v474 = stack_load.i64 ss0
    v475 = iconst.i64 336
    v476 = iadd v474, v475  ; v475 = 336
    v477 = load.i64 readonly little v476
    v478 = iconst.i64 0
    v479 = iadd v477, v478  ; v478 = 0
    v480 = load.i64 readonly little v479
    v481 = iconst.i64 -8009081386208279231
    v482 = icmp eq v480, v481  ; v481 = -8009081386208279231
    brif v482, block43, block39

block39:
    v483 = stack_load.i64 ss0
    v484 = iconst.i64 336
    v485 = iadd v483, v484  ; v484 = 336
    v486 = load.i64 readonly little v485
    v487 = iconst.i64 0
    v488 = iadd v486, v487  ; v487 = 0
    v489 = load.i64 readonly little v488
    v490 = iconst.i64 0x1998_4e84_e8d9_85b5
    v491 = icmp eq v489, v490  ; v490 = 0x1998_4e84_e8d9_85b5
    brif v491, block44, block40
}`

### Expected Results

For stack_load to be implemented and for the function to successfully compile.

### Actual Results

The panic as exemplified in the earlier presented backtrace.

### Versions and Environment

Cranelift version or commit: 0.114.0

Operating system: Windows 10

Architecture: x86_64

### Extra Info

Let me know an ETA I guess, or don't, that works too. You got enough on your hands.

**Comment by bjorn3** [comment]
How did you try to compile the function? Using `cranelift_codegen::Context::compile` or in sone other way?

**Comment by stellaphax** [comment]
> How did you try to compile the function? Using `cranelift_codegen::Context::compile` or in sone other way?

Ohh.... I did it through some other avenue. Thank you for letting me know! I switched to using that same API you just mentioned, and everything works fine now. Thank you!

**Comment by bjorn3** [comment]
Great to hear you managed to get it working! The reason it didn't work through the other method you tried is likely because that other method skipped the "legalization" from stack_load to stack_addr combined with a regular load.
