### ISSUE TITLE
macOS dylib has undesired dependency

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#984]
```shell
otool -L libwasmtime.0.8.dylib
```

```
libwasmtime.0.8.dylib:
	/Users/runner/runners/2.160.2/work/wasmtime/wasmtime/target/release/deps/libwasmtime.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

The /Users/runner entry shouldn't be there.

**Comment by alexcrichton** [comment]
Thanks for the report! Can you describe how you generated libwasmtime.0.8.dylib? Was that just a `cargo build` in the c-api directory?

**Comment by rene-fonseca** [comment]
I seen it for all the builds I do locally (0.8 - up to 0.11). But same issue for release on github:
carbon --build release

See wasmtime-v0.8.0-x86_64-linux-c-api.tar.xz
at https://github.com/bytecodealliance/wasmtime/releases

**Comment by alexcrichton** [comment]
Ok thanks for clarifying. It looks like this is an artifact of how `rustc` works by default, we're not exactly going out of our way to configure this.

I don't really know a lot myself about how dynamic libraries work well on OSX, do you? Do you know what we should be specifying here other than the full path? Would `libwasmtime.dylib` suffice or do we need something like `@rpath/libwasmtime.dylib`?

**Comment by rene-fonseca** [comment]
Look at it a bit more - it is actually the LC_ID_DYLIB entry here that is undesired - not a lib dependency:

If you can pass "install-name" argument to linker with name of lib it should work for consumers.

Consumers can do the overrides required using the install_tool_name tool. For now this is always requires to make the lib load.

```shell
install_name_tool -id libwasmtime.dylib libwasmtime.dylib
```

**Comment by rene-fonseca** [comment]
Maybe the rpath should be set to @executable_path for the distribution since the dylib is not commonly installed in the system lib folders. But note sure which rpath would give the least problems.

```shell
install_name_tool -add_rpath "@executable_path/" mylib.dylib
```
Consumer can still adjust rpath if required. Maybe add info in readme for distribution just to remind consumers.

**Comment by alexcrichton** [comment]
It's true yeah there's various ways we can configure this, but is there a conventional way do you know to ship dynamic libraires on OSX? For example for other projects producing `libfoo.dylib` as an artifact, is it expected to have a particular `LC_ID_DYLIB` directive?

(largely just wondering if there's existing convention we can adhere to, I'm not aware of one myself)

**Comment by rene-fonseca** [comment]
It is probably safe to pick the same as what CMake produces by default.

It sets LC_ID_DYLIB to the equivalent of `@rpath/libwasmtime.0.dylib` .

Where libwasmtime.0.dylib and libwasmtime.dylib would be symlinks to libwasmtime.0.12.dylib
Minor version is not included.

**Comment by alexcrichton** [comment]
Ok I've posted a PR to do this on our CI at: https://github.com/bytecodealliance/wasmtime/pull/1009
