### ISSUE TITLE
Merge defined and imported impls of memory-related instructions together

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#985]
We have two copies of all of our runtime functions that implement memory-related instructions (eg `memory.size`, `memory.grow`, `memory.init`, and `memory.copy`):

1. A version for locally defined memories
2. A version for imported memories

Having two different impls isn't a speed win because the tiny bit of specialization is definitely dwarfed by the cost of an indirect library function call.

We just don't currently have a nice way to get a memory regardless if it is imported or locally defined given a `MemoryIndex`. That is easy enough to do, we have `Instance::get_table` that does exactly this for tables rather than memories, and we can do a similar thing for memories.

**Comment by rgrmrts** [comment]
hi, I started working on https://github.com/bytecodealliance/wasmtime/issues/2561 and am wondering if this issue is a clone of that? seems like the end goal is the same - getting rid of the dichotomy between imported/local memory for these function calls

**Comment by alexcrichton** [comment]
Ah yes looks like this is indeed accidentally a duplicate!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/bytecodealliance/wasmtime/pull/3023
