### ISSUE TITLE
impl Debug and/or Default for SparseMap

### ISSUE THREAD

**Issue by wtachau** [bytecodealliance/wasmtime#9856]
Hello, is there a reason that [SparseMap](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/entity/src/sparse.rs) doesn't impl `std::fmt::Debug` and/or `Default`? I would like to use it inside my own data structures that derive those impls.

(I read [these contribution guidelines](https://docs.wasmtime.dev/contributing.html) which encouraged me to open an issue, please let me know if there's a more appropriate place to ask, thanks!)

**Comment by cfallin** [comment]
This seems like a reasonable contribution to make -- I'd be happy to review a PR if you'd like to do this! The only thing I'd note right away is that we don't want to constrain `K: Debug` and `V: Debug` unconditionally -- let's have a trait impl that provides `Debug` if they both have that impl.

**Comment by wtachau** [comment]
thanks @cfallin! opened a PR [here](https://github.com/bytecodealliance/wasmtime/pull/9860).
