### ISSUE TITLE
Consider introducing wasmtime specific header for the library distribution

### ISSUE THREAD

**Issue by rene-fonseca** [bytecodealliance/wasmtime#986]
It would be nice to have version/compatibility info available via a header when consuming the wasmtime library. I use such version defines to automatically tag the the binaries built (e.g. allows future security issues to be detected automatically).

E.g. look at ZLIB library header for useful info.

#define ZLIB_VERSION "1.2.11"
#define ZLIB_VERNUM 0x12b0
#define ZLIB_VER_MAJOR 1
#define ZLIB_VER_MINOR 2
#define ZLIB_VER_REVISION 11
#define ZLIB_VER_SUBREVISION 0

I then consume info at compile time like this:
https://github.com/rene-fonseca/base/blob/9d478d34a6ac3b1661b781a97dd8c90610ae5428/base/compression/ZLibInflater.cpp#L65-L67

**Comment by yurydelendik** [comment]
Is this issue limited only to C API packages?

**Comment by rene-fonseca** [comment]
Not sure how non-C environments work. Maybe info could be available to C#/Rust too.

But I was thinking about C-API. But not specific to WASI C-API - since it is really the runtime info I'm looking for here - ie. the wasmtime implementation.

**Comment by plicease** [comment]
For FFI it would be helpful to have a `wasmtime_version()` function for diagnostics that returned a string with the wasmtime version for taged releases, and the git commit id for dev releases.

Adding this information as `#define`s to the header is useful for C/C++, but not for languages that use FFI based on libffi or similar.

**Comment by bjorn3** [comment]
I think this is a duplicate of https://github.com/bytecodealliance/wasmtime/issues/5635 which was fixed in https://github.com/bytecodealliance/wasmtime/pull/5651.
