### ISSUE TITLE
Cannot install python wasmtime on Alpine OS docker container

### ISSUE THREAD

**Issue by sharksforarms** [bytecodealliance/wasmtime#995]
Cannot install python wasmtime on Alpine OS docker container

I think this has something to do with this: https://github.com/docker-library/docs/issues/904

Getting
```
ERROR: Could not find a version that satisfies the requirement wasmtime (from versions: none)
ERROR: No matching distributions found for wasmtime
```

**Comment by alexcrichton** [comment]
Thanks for the report! At this time we only support glibc binary releases, and to install on Alpine you'll need to compile from source against musl.

**Comment by alexcrichton** [comment]
If it helps as well, here's an example of how to build it in alpine:

```dockerfile
FROM alpine

# Install build tools
RUN apk add musl-dev g++ curl git

# Install nightly Rust
ENV CARGO_HOME=/cargo RUSTUP_HOME=/rustup PATH=$PATH:/cargo/bin
RUN curl https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly

# Download and build wasmtime, note that we configure the musl target for
# dynamic linkage here instead of the default static.
RUN git clone https://github.com/bytecodealliance/wasmtime --recursive
WORKDIR /wasmtime
ENV RUSTFLAGS=-Ctarget-feature=-crt-static
RUN cargo fetch
RUN cargo build --release

# Download python and such to build the python extension
RUN apk add python3
RUN pip3 install setuptools wheel setuptools-rust
RUN cd crates/misc/py && python3 setup.py bdist_wheel
```

**Comment by sharksforarms** [comment]
Thanks for the tip!

**Comment by bjorn3** [comment]
I think this can be closed. If not at least it should be moved to https://github.com/bytecodealliance/wasmtime-py.

**Comment by alexcrichton** [comment]
Indeed yes I think the wasmtime-py bits have changed enough that this is no longer relevant as-is.

**Comment by willhausman** [comment]
@alexcrichton is this answer still true?  I had opened https://github.com/bytecodealliance/wasmtime-dotnet/issues/82 this morning, but further investigation revealed it was not an issue specific to the dotnet build as I can reproduce the same behavior with python.

**Comment by bjorn3** [comment]
That is probably the same kind of error. However it is something that needs to be separately fixed for both. For example by adding a new build for musl based systems.

**Comment by alexcrichton** [comment]
Yes the `wasmtime-py` extension and the Wasmtime repository do not have precompiled artifacts for musl, only for glibc.
